### ISSUE TITLE
NPE occurs when some db-stored application property has null value

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#1016]
See https://www.cuba-platform.com/discuss/t/nullpointerexception-in-create-new-command-of-custom-filter-conditions

### Environment

- Platform version: 6.9.2

### Description of the bug or enhancement

- Minimal reproducible example

1) Start the application
2) Open entity manager
3) Chose the sys$Config entity
4) Define some db-stored (_type = SourceType.DATABASE_) property with "null" value
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/df8c6161-76a3-4680-a74b-912c6026777c)
5) Restart the server 
6) Open some screen woth filter
7) Try to create a custom filter condition

- Actual behavior

![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/8c640e70-ae1b-49d5-bb54-37e2f413f610)

```code
Caused by: java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[na:1.8.0_172]
	at java.util.concurrent.ConcurrentHashMap.putAll(ConcurrentHashMap.java:1084) ~[na:1.8.0_172]
	at com.haulmont.cuba.client.sys.config.ConfigPersisterClientImpl.loadCache(ConfigPersisterClientImpl.java:79) ~[cuba-client-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.client.sys.config.ConfigPersisterClientImpl.getProperty(ConfigPersisterClientImpl.java:60) ~[cuba-client-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.core.config.ConfigGetter.getProperty(ConfigGetter.java:110) ~[cuba-global-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.core.config.ConfigGetter.getProperty(ConfigGetter.java:95) ~[cuba-global-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.core.config.ConfigGetter.invoke(ConfigGetter.java:67) ~[cuba-global-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.core.config.ConfigHandler.invoke(ConfigHandler.java:79) ~[cuba-global-6.9.2.jar:6.9.2]
	at com.sun.proxy.$Proxy67.getGenericFilterColumnsCount(Unknown Source) ~[na:na]
	at com.haulmont.cuba.gui.components.filter.edit.ConditionFrame.initComponents(ConditionFrame.java:69) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.gui.components.filter.edit.CustomConditionFrame.initComponents(CustomConditionFrame.java:111) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.gui.components.filter.edit.ConditionFrame.init(ConditionFrame.java:55) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.gui.components.filter.edit.CustomConditionFrame.init(CustomConditionFrame.java:105) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.gui.xml.layout.loaders.FrameLoader$FrameLoaderInitTask.execute(FrameLoader.java:271) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.gui.xml.layout.loaders.ComponentLoaderContext$InitTaskExecutor.run(ComponentLoaderContext.java:266) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.gui.xml.layout.loaders.ComponentLoaderContext.executeInitTasks(ComponentLoaderContext.java:160) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.gui.WindowManager.initWrapperFrame(WindowManager.java:1238) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.gui.WindowManager.createWindow(WindowManager.java:581) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.gui.WindowManager.openWindow(WindowManager.java:750) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.web.WebWindowManager.openWindow(WebWindowManager.java:158) ~[cuba-web-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.gui.components.filter.AddConditionHelper._addCondition(AddConditionHelper.java:114) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.gui.components.filter.AddConditionHelper.lambda$addCondition$0(AddConditionHelper.java:99) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.web.gui.WebWindow.fireWindowClosed(WebWindow.java:910) ~[cuba-web-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.web.gui.WebWindow.onClose(WebWindow.java:902) ~[cuba-web-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.web.gui.WebWindow.close(WebWindow.java:1199) ~[cuba-web-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.gui.components.AbstractWindow.close(AbstractWindow.java:283) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.gui.components.filter.addcondition.AddConditionWindow.select(AddConditionWindow.java:132) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.gui.components.filter.addcondition.AddConditionWindow$1.actionPerform(AddConditionWindow.java:78) ~[cuba-gui-6.9.2.jar:6.9.2]
	at com.haulmont.cuba.web.gui.components.WebTree.lambda$setItemClickAction$1cd57308$1(WebTree.java:254) ~[cuba-web-6.9.2.jar:6.9.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	... 47 common frames omitted

```

**Comment by alexbudarov** [comment]
I've met this several times.
The problem is that sys_config does not have notnull constraint. While the code does not support null values.

**Comment by jreznot** [comment]
We have changed create SQL scripts for 6.9+ and added update scripts for 6.10+. Now SYS_CONFIG has not null constraints for `VALUE_` and `NAME`.
