### ISSUE TITLE
REST API: accessing non-existent path after rest/v2 results in internal server error

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/cuba#1023]
### Environment

- Platform version: 6.9.2

### Description of the bug or enhancement
Run app based on CUBA 6.9
http://localhost:8080/app/rest/v2/someurl
*AR* Server responds with 500 (internal error)
*ER* Server responds with 404 (not found)

<details><summary>Exception log</summary><p>
 com.haulmont.restapi.auth.CubaRestLastSecurityFilter - Error during REST API call
java.lang.IllegalArgumentException: null source
at java.util.EventObject.(EventObject.java:56) ~[na:1.8.0_171]
at org.springframework.context.ApplicationEvent.(ApplicationEvent.java:42) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at com.haulmont.restapi.events.BeforeRestInvocationEvent.(BeforeRestInvocationEvent.java:37) ~[cuba-rest-api-6.9.2.jar:6.9.2]
at com.haulmont.restapi.auth.CubaRestLastSecurityFilter.doFilter(CubaRestLastSecurityFilter.java:80) ~[cuba-rest-api-6.9.2.jar:6.9.2]
</p></details>

**Comment by jreznot** [comment]
Caused by https://youtrack.haulmont.com/issue/PL-9551
