### ISSUE TITLE
Errors occuring when loading more than 500 entities with complex view

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#1032]
### Environment
- Platform version: 6.8.13

### Description of the bug or enhancement
EclipseLink fails to properly load large dataset when there are 501 or more entities A with the following view:
A -> (one-to-many) B
B -> (embedded) C
C -> (many-to-one) D
C -> (many-to-one) E

Most of times EclipseLink just silently does not load D and E for A entities starting from 501th and further.
But sometimes it fails with exceptions.

### How to reproduce
1)
Patch no.1 for refapp 6.8. It does not require to change data model, but reproduces only one case: when data loading is successful, but D is not loaded.
[batch-501-simple.patch.txt](https://github.com/cuba-platform/cuba/files/2595004/batch-501-simple.patch.txt)
DriverGroup -> (one-to-many) Driver
Driver -> (embedded) Address
Address -> (many-to-one) Place

Misbehavior: Place is not loaded for 501th DriverGroup.
```
13:27:30.243 [main] INFO com.haulmont.refapp.core.EclipseLinkBatchTest1 - Checking Driver #498
13:27:30.243 [main] INFO com.haulmont.refapp.core.EclipseLinkBatchTest1 - Checking Driver #499
13:27:30.243 [main] INFO com.haulmont.refapp.core.EclipseLinkBatchTest1 - Checking Driver #500
13:27:30.243 [main] INFO com.haulmont.refapp.core.EclipseLinkBatchTest1 - Checking Driver #501
java.lang.AssertionError
	at com.haulmont.refapp.core.EclipseLinkBatchTest1.notAllDataIsLoadedCase(EclipseLinkBatchTest1.java:87)
```

2)
Patch no.2 for refapp 6.8.
[batch-3-different-errors.patch.txt](https://github.com/cuba-platform/cuba/files/2595010/batch-3-different-errors.patch.txt)
It has changes for data model (new link Address -> Colour).
DriverGroup -> (one-to-many) Driver
Driver -> (embedded) Address
Address -> (many-to-one) Colour
Address -> (many-to-one) Place

But this patch reproduces the same problem with 3 different kinds of errors, depending on data set which we save to DB:
1 - the same as above (Colour is not loaded for 501th DriverGroup)

2 - ArrayIndexOutOfBoundsException:
<details>
 <summary>Click to expand java.lang.ArrayIndexOutOfBoundsException</summary>
 
```
javax.persistence.PersistenceException: java.lang.ArrayIndexOutOfBoundsException: -1

	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:484)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultFromCache(QueryImpl.java:647)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultList(QueryImpl.java:341)
	at com.haulmont.cuba.core.app.RdbmsStore.executeQuery(RdbmsStore.java:699)
	at com.haulmont.cuba.core.app.RdbmsStore.getResultList(RdbmsStore.java:607)
	at com.haulmont.cuba.core.app.RdbmsStore.loadList(RdbmsStore.java:210)
	at com.haulmont.cuba.core.app.DataManagerBean.loadList(DataManagerBean.java:84)
	at com.haulmont.refapp.core.EclipseLinkBatchTest2.testIndexOutOfBoundsException(EclipseLinkBatchTest2.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.Vector.elementData(Vector.java:737)
	at java.util.Vector.get(Vector.java:753)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.extractResultFromBatchQuery(ForeignReferenceMapping.java:592)
	at org.eclipse.persistence.internal.indirection.NoIndirectionPolicy.valueFromBatchQuery(NoIndirectionPolicy.java:297)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.batchedValueFromRow(ForeignReferenceMapping.java:275)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.valueFromRow(ForeignReferenceMapping.java:2176)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.buildCloneFromRow(ForeignReferenceMapping.java:336)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.buildCloneFromRow(ForeignReferenceMapping.java:359)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildAttributesIntoWorkingCopyClone(ObjectBuilder.java:1997)
	at org.eclipse.persistence.mappings.AggregateObjectMapping.buildAggregateFromRow(AggregateObjectMapping.java:437)
	at org.eclipse.persistence.mappings.AggregateObjectMapping.buildCloneFromRow(AggregateObjectMapping.java:767)
	at org.eclipse.persistence.mappings.AggregateObjectMapping.buildCloneFromRow(AggregateObjectMapping.java:779)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildAttributesIntoWorkingCopyClone(ObjectBuilder.java:1997)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildWorkingCopyCloneFromRow(ObjectBuilder.java:2258)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObjectInUnitOfWork(ObjectBuilder.java:848)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObject(ObjectBuilder.java:735)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObject(ObjectBuilder.java:689)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.buildObject(ObjectLevelReadQuery.java:802)
	at org.eclipse.persistence.queries.ReadAllQuery.registerResultInUnitOfWork(ReadAllQuery.java:962)
	at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:573)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1172)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1131)
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:460)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1219)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2944)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1854)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1836)
	at org.eclipse.persistence.mappings.CollectionMapping.executeBatchQuery(CollectionMapping.java:974)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.extractResultFromBatchQuery(ForeignReferenceMapping.java:647)
	at org.eclipse.persistence.mappings.CollectionMapping.extractResultFromBatchQuery(CollectionMapping.java:955)
	at org.eclipse.persistence.internal.indirection.BatchValueHolder.instantiate(BatchValueHolder.java:58)
	at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:121)
	at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:101)
	at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiateImpl(UnitOfWorkValueHolder.java:174)
	at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiate(UnitOfWorkValueHolder.java:235)
	at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:101)
	at org.eclipse.persistence.indirection.IndirectList.buildDelegate(IndirectList.java:271)
	at org.eclipse.persistence.indirection.IndirectList.getDelegate(IndirectList.java:455)
	at org.eclipse.persistence.indirection.IndirectList.size(IndirectList.java:829)
	at org.eclipse.persistence.internal.queries.CollectionContainerPolicy.sizeFor(CollectionContainerPolicy.java:198)
	at org.eclipse.persistence.internal.indirection.TransparentIndirectionPolicy.instantiateObject(TransparentIndirectionPolicy.java:390)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.instantiateAttribute(ForeignReferenceMapping.java:1135)
	at org.eclipse.persistence.mappings.CollectionMapping.load(CollectionMapping.java:1399)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.load(ObjectBuilder.java:803)
	at org.eclipse.persistence.internal.sessions.AbstractSession.load(AbstractSession.java:5185)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.load(UnitOfWorkImpl.java:2555)
	at org.eclipse.persistence.internal.sessions.AbstractSession.load(AbstractSession.java:5177)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.load(UnitOfWorkImpl.java:2561)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1189)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1131)
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:460)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1219)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2944)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1854)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1836)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1801)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:473)
	... 13 more
```
</details>

3 - PSQLException (malformed SQL query):
<details>
 <summary>Click to expand PSQLException</summary>
 
```
javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.2.cuba23): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 145
Error Code: 0
Call: SELECT ID, DTYPE, CREATE_TS, CREATED_BY, DELETE_TS, DELETED_BY, NAME, UPDATE_TS, UPDATED_BY, VERSION, DESCRIPTION FROM REF_PLACE WHERE ((ID IN ()) AND ((0=0) AND (DTYPE = ?)))
	bind => [ext$Place]
Query: ReadAllQuery(name="place" referenceClass=ExtPlace sql="SELECT ID, DTYPE, CREATE_TS, CREATED_BY, DELETE_TS, DELETED_BY, NAME, UPDATE_TS, UPDATED_BY, VERSION, DESCRIPTION FROM REF_PLACE WHERE ((ID IN ?) AND ((0=0) AND (DTYPE = ?)))")

	at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:382)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:260)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:473)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultFromCache(QueryImpl.java:647)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultList(QueryImpl.java:341)
	at com.haulmont.cuba.core.app.RdbmsStore.executeQuery(RdbmsStore.java:699)
	at com.haulmont.cuba.core.app.RdbmsStore.getResultList(RdbmsStore.java:607)
	at com.haulmont.cuba.core.app.RdbmsStore.loadList(RdbmsStore.java:210)
	at com.haulmont.cuba.core.app.DataManagerBean.loadList(DataManagerBean.java:84)
	at com.haulmont.refapp.core.EclipseLinkBatchTest2.testSqlException(EclipseLinkBatchTest2.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.2.cuba23): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 145
Error Code: 0
Call: SELECT ID, DTYPE, CREATE_TS, CREATED_BY, DELETE_TS, DELETED_BY, NAME, UPDATE_TS, UPDATED_BY, VERSION, DESCRIPTION FROM REF_PLACE WHERE ((ID IN ()) AND ((0=0) AND (DTYPE = ?)))
	bind => [ext$Place]
Query: ReadAllQuery(name="place" referenceClass=ExtPlace sql="SELECT ID, DTYPE, CREATE_TS, CREATED_BY, DELETE_TS, DELETED_BY, NAME, UPDATE_TS, UPDATED_BY, VERSION, DESCRIPTION FROM REF_PLACE WHERE ((ID IN ?) AND ((0=0) AND (DTYPE = ?)))")
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:702)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:544)
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2052)
	at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570)
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:258)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.executeCall(ExpressionQueryMechanism.java:2863)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:299)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:694)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2751)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2704)
	at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:559)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1172)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1131)
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:460)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1219)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2944)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1854)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1836)
	at org.eclipse.persistence.mappings.OneToOneMapping.executeBatchQuery(OneToOneMapping.java:812)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.extractResultFromBatchQuery(ForeignReferenceMapping.java:647)
	at org.eclipse.persistence.internal.indirection.NoIndirectionPolicy.valueFromBatchQuery(NoIndirectionPolicy.java:297)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.batchedValueFromRow(ForeignReferenceMapping.java:275)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.valueFromRow(ForeignReferenceMapping.java:2176)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.buildCloneFromRow(ForeignReferenceMapping.java:336)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.buildCloneFromRow(ForeignReferenceMapping.java:359)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildAttributesIntoWorkingCopyClone(ObjectBuilder.java:1997)
	at org.eclipse.persistence.mappings.AggregateObjectMapping.buildAggregateFromRow(AggregateObjectMapping.java:437)
	at org.eclipse.persistence.mappings.AggregateObjectMapping.buildCloneFromRow(AggregateObjectMapping.java:767)
	at org.eclipse.persistence.mappings.AggregateObjectMapping.buildCloneFromRow(AggregateObjectMapping.java:779)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildAttributesIntoWorkingCopyClone(ObjectBuilder.java:1997)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildWorkingCopyCloneFromRow(ObjectBuilder.java:2258)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObjectInUnitOfWork(ObjectBuilder.java:848)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObject(ObjectBuilder.java:735)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObject(ObjectBuilder.java:689)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.buildObject(ObjectLevelReadQuery.java:802)
	at org.eclipse.persistence.queries.ReadAllQuery.registerResultInUnitOfWork(ReadAllQuery.java:962)
	at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:573)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1172)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1131)
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:460)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1219)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2944)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1854)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1836)
	at org.eclipse.persistence.mappings.CollectionMapping.executeBatchQuery(CollectionMapping.java:974)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.extractResultFromBatchQuery(ForeignReferenceMapping.java:647)
	at org.eclipse.persistence.mappings.CollectionMapping.extractResultFromBatchQuery(CollectionMapping.java:955)
	at org.eclipse.persistence.internal.indirection.BatchValueHolder.instantiate(BatchValueHolder.java:58)
	at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:121)
	at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:101)
	at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiateImpl(UnitOfWorkValueHolder.java:174)
	at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiate(UnitOfWorkValueHolder.java:235)
	at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:101)
	at org.eclipse.persistence.indirection.IndirectList.buildDelegate(IndirectList.java:271)
	at org.eclipse.persistence.indirection.IndirectList.getDelegate(IndirectList.java:455)
	at org.eclipse.persistence.indirection.IndirectList.size(IndirectList.java:829)
	at org.eclipse.persistence.internal.queries.CollectionContainerPolicy.sizeFor(CollectionContainerPolicy.java:198)
	at org.eclipse.persistence.internal.indirection.TransparentIndirectionPolicy.instantiateObject(TransparentIndirectionPolicy.java:390)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.instantiateAttribute(ForeignReferenceMapping.java:1135)
	at org.eclipse.persistence.mappings.CollectionMapping.load(CollectionMapping.java:1399)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.load(ObjectBuilder.java:803)
	at org.eclipse.persistence.internal.sessions.AbstractSession.load(AbstractSession.java:5185)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.load(UnitOfWorkImpl.java:2555)
	at org.eclipse.persistence.internal.sessions.AbstractSession.load(AbstractSession.java:5177)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.load(UnitOfWorkImpl.java:2561)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1189)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1131)
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:460)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1219)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2944)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1854)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1836)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1801)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258)
	... 14 more
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 145
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:305)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
	at com.haulmont.cuba.core.sys.jdbc.ProxyPreparedStatement.lambda$executeQuery$0(ProxyPreparedStatement.java:34)
	at com.haulmont.cuba.core.sys.jdbc.ProxyStatement.executeSqlStatement(ProxyStatement.java:257)
	at com.haulmont.cuba.core.sys.jdbc.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:34)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1040)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:659)
	... 92 more
```
</details>

### Short analysis
The problem is related to EclipseLink batch loading - it loads sub-graph by batches of 500 IDs.
Places which I have investigated are org.eclipse.persistence.mappings.ForeignReferenceMapping#extractResultFromBatchQuery
and org.eclipse.persistence.queries.BatchFetchPolicy#dataResults map.
When D and E entities for second batch are loaded, BatchFetchPolicy#dataResults map appears to contain wrong list of parent records (B entities).

**Comment by alexbudarov** [comment]
@andreysubbotin reliable test case is ready

**Comment by andreysubbotin** [comment]
EclipseLink changes: https://github.com/cuba-platform/eclipselink/commit/c06759c543f882eb1edd6a5e6d2dc803d5b58c67
