### ISSUE TITLE
Incorrect SQL is built when COALESCE arguments order differs from tables order in JOIN-clause

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#1068]
See https://www.cuba-platform.com/discuss/t/joining-the-same-entity-twice-results-in-wrong-final-query/5771

### Environment

- Platform version: 6.9.3

### Description of the bug or enhancement

- Steps to reproduce

1) Create three entities with some integer fields
2) On some screen specify collectionDtasource with the following query
```code
select e from test$Country e where e.intFld in 
(
select coalesce(bar.intFld, foo.intFld) from test$Foo foo
left join test$Bar bar on foo.intFld = bar.intFld
)
```

3) Add a Table on the screen and assign the datasource to this Table

- Expected behavior
When *coalesce* Foo and Bar have the same order as in *join* it works
```code
select e from test$Country e where e.intFld in 
(
select coalesce(foo.intFld, bar.intFld) from test$Foo foo
left join test$Bar bar on foo.intFld = bar.intFld
)
```
- Actual behavior

```code
com.haulmont.cuba.core.global.RemoteException:
---
javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.2.cuba23): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "t2"
  Position: 134
Error Code: 0
Call: SELECT t0.ID AS a1, t0.COUNTRY_FLD AS a2, t0.INT_FLD AS a3 FROM TRASHTEST_COUNTRY t0 WHERE t0.INT_FLD IN (SELECT COALESCE(t1.INT_FLD,t2.INT_FLD ) FROM TRASHTEST_FOO t1) LIMIT ? OFFSET ?
	bind => [10000, 0]
Query: ReadAllQuery(referenceClass=Country sql="SELECT t0.ID AS a1, t0.COUNTRY_FLD AS a2, t0.INT_FLD AS a3 FROM TRASHTEST_COUNTRY t0 WHERE t0.INT_FLD IN (SELECT COALESCE(t1.INT_FLD,t2.INT_FLD ) FROM TRASHTEST_FOO t1) LIMIT ? OFFSET ?")
FetchGroup(){countryFld, id, intFld}
---
org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "t2"
 Position: 134
Error Code: 0
Call: SELECT t0.ID AS a1, t0.COUNTRY_FLD AS a2, t0.INT_FLD AS a3 FROM TRASHTEST_COUNTRY t0 WHERE t0.INT_FLD IN (SELECT COALESCE(t1.INT_FLD,t2.INT_FLD ) FROM TRASHTEST_FOO t1) LIMIT ? OFFSET ?
	bind => [10000, 0]
Query: ReadAllQuery(referenceClass=Country sql="SELECT t0.ID AS a1, t0.COUNTRY_FLD AS a2, t0.INT_FLD AS a3 FROM TRASHTEST_COUNTRY t0 WHERE t0.INT_FLD IN (SELECT COALESCE(t1.INT_FLD,t2.INT_FLD ) FROM TRASHTEST_FOO t1) LIMIT ? OFFSET ?")
FetchGroup(){countryFld, id, intFld}
---
org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "t2"
  Position: 134
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:129)
	at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ...

```

**Comment by andreysubbotin** [comment]
EclipseLink bug
