### ISSUE TITLE
Excel action which only supports a maximum of 65536 rows

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#107]
При попытке распечатать excel из списка c большим количеством записей - ошибка:
```
11:02:35,162 ERROR [AppLog] [app] [admin] Exception in com.vaadin.ui.Button:
com.vaadin.event.ListenerMethod$MethodException
Cause: java.lang.IllegalArgumentException: Invalid row number (65536) outside allowable range (0..65535)
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:164)
        at com.vaadin.ui.AbstractComponent.fireEvent(AbstractComponent.java:1220)
        at com.vaadin.ui.Button.fireClick(Button.java:479)
        at com.vaadin.ui.Button.changeVariables(Button.java:198)
        at com.haulmont.cuba.web.sys.CubaCommunicationManager.handleVariableBurst(CubaCommunicationManager.java:180)
        at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.handleVariables(AbstractCommunicationManager.java:1233)
        at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.doHandleUidlRequest(AbstractCommunicationManager.java:733)
        at com.vaadin.terminal.gwt.server.CommunicationManager.handleUidlRequest(CommunicationManager.java:296)
        at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:500)
        at com.haulmont.cuba.web.sys.CubaApplicationServlet.doService(CubaApplicationServlet.java:230)
        at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:120)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:92)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at com.haulmont.thesis.web.sys.DeviceFilter.doFilter(DeviceFilter.java:63)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.IllegalArgumentException: Invalid row number (65536) outside allowable range (0..65535)
        at org.apache.poi.hssf.usermodel.HSSFRow.setRowNum(HSSFRow.java:239)
        at org.apache.poi.hssf.usermodel.HSSFRow.<init>(HSSFRow.java:87)
        at org.apache.poi.hssf.usermodel.HSSFRow.<init>(HSSFRow.java:71)
        at org.apache.poi.hssf.usermodel.HSSFSheet.createRow(HSSFSheet.java:232)
        at com.haulmont.cuba.gui.export.ExcelExporter.createRow(ExcelExporter.java:258)
        at com.haulmont.cuba.gui.export.ExcelExporter.exportTable(ExcelExporter.java:183)
        at com.haulmont.thesis.web.actions.ThesisExcelAction.actionPerform(ThesisExcelAction.java:117)
        at com.haulmont.cuba.web.gui.components.WebButton$1.buttonClick(WebButton.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:490)
        ... 34 more
```

---
Original issue: https://youtrack.haulmont.com/issue/PL-4619
---
**For QA**

Test: Table, GroupTable, TreeTable, DataGrid;

**Comment by jreznot** [comment]
Let's show only part of the data in this case and show notification on that
