### ISSUE TITLE
Reimplement SearchField and SearchPickerField 

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1085]
Reimplement SearchField and SearchPickerField  components with Vaadin 8

**Comment by glebfox** [comment]
Relates to #444

**Comment by natfirst** [comment]
# refapp > test samples
# open SearchPickerField screen
# also check SuggestionField
```
java.lang.ClassCastException: java.lang.String cannot be cast to com.haulmont.cuba.core.entity.Entity
	at com.haulmont.cuba.web.gui.components.WebSearchPickerField.setNullOption(WebSearchPickerField.java:49)
	at com.haulmont.cuba.gui.xml.layout.loaders.LookupFieldLoader.loadComponent(LookupFieldLoader.java:59)
	at com.haulmont.cuba.gui.xml.layout.loaders.SearchFieldLoader.loadComponent(SearchFieldLoader.java:34)
	at com.haulmont.cuba.gui.xml.layout.loaders.SearchPickerFieldLoader.loadComponent(SearchPickerFieldLoader.java:37)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:39)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:91)
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractBoxLoader.loadComponent(AbstractBoxLoader.java:51)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:39)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:91)
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractBoxLoader.loadComponent(AbstractBoxLoader.java:51)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:39)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:91)
	at com.haulmont.cuba.gui.xml.layout.loaders.WindowLoader.loadComponent(WindowLoader.java:80)
	at com.haulmont.cuba.gui.WindowManager.createWindow(WindowManager.java:572)
	at com.haulmont.cuba.gui.WindowManager.openWindow(WindowManager.java:747)
	at com.haulmont.cuba.gui.WindowManager.openWindow(WindowManager.java:781)
	at com.haulmont.cuba.gui.components.WindowDelegate.openWindow(WindowDelegate.java:240)
	at com.haulmont.cuba.web.gui.WebWindow.openWindow(WebWindow.java:470)
	at com.haulmont.cuba.gui.components.AbstractFrame.openWindow(AbstractFrame.java:469)
	at com.haulmont.refapp.gui.app.sample.SamplesMenu.openSampleScreen(SamplesMenu.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.cuba.gui.xml.DeclarativeAction.actionPerform(DeclarativeAction.java:85)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:47)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:71)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```
