### ISSUE TITLE
 Exception in log with query results

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#1123]
```
2018-08-06 15:25:08.296 DEBUG [cuba_core_scheduler-2] com.haulmont.cuba.core.app.queryresults.QueryResultsManager - Delete query results for inactive user sessions
2018-08-06 15:25:08.298 DEBUG [cuba_core_scheduler-2] com.haulmont.cuba.core.app.queryresults.QueryResultsManager - Deleting 0 records
2018-08-06 15:25:08.356 ERROR [cuba_core_scheduler-2] org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.RuntimeException: Error deleting query result records
    at com.haulmont.cuba.core.app.queryresults.QueryResultsManager.delete(QueryResultsManager.java:280) ~[cuba-core-6.9.3.jar:6.9.3]
    at com.haulmont.cuba.core.app.queryresults.QueryResultsManager.internalDeleteForInactiveSessions(QueryResultsManager.java:265) ~[cuba-core-6.9.3.jar:6.9.3]
    at com.haulmont.cuba.core.app.queryresults.QueryResultsManager.deleteForInactiveSessions(QueryResultsManager.java:238) ~[cuba-core-6.9.3.jar:6.9.3]
    at sun.reflect.GeneratedMethodAccessor1159.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_151]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_151]
    at com.haulmont.cuba.core.sys.CubaThreadPoolTaskScheduler$TaskDecorator.run(CubaThreadPoolTaskScheduler.java:120) [cuba-global-6.9.3.jar:6.9.3]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
    at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: java.sql.SQLException: ERROR: syntax error at or near ")"
  Position: 43 Query: delete from SYS_QUERY_RESULT where ID in () Parameters: []
    at com.haulmont.bali.db.QueryRunner.rethrow(QueryRunner.java:462) ~[cuba-global-6.9.3.jar:6.9.3]
    at com.haulmont.bali.db.QueryRunner.update(QueryRunner.java:550) ~[cuba-global-6.9.3.jar:6.9.3]
    at com.haulmont.bali.db.QueryRunner.update(QueryRunner.java:521) ~[cuba-global-6.9.3.jar:6.9.3]
    at com.haulmont.bali.db.QueryRunner.update(QueryRunner.java:606) ~[cuba-global-6.9.3.jar:6.9.3]
    at com.haulmont.bali.db.QueryRunner.update(QueryRunner.java:571) ~[cuba-global-6.9.3.jar:6.9.3]
    at com.haulmont.cuba.core.app.queryresults.QueryResultsManager.delete(QueryResultsManager.java:278) ~[cuba-core-6.9.3.jar:6.9.3]
    ... 15 common frames omitted
```

**Comment by andreysubbotin** [comment]
Test case:
* Set property `cuba.deleteOldQueryResultsInterval = 10 000` in the core application properties
* Run application, open browser screen. Apply filter and pin results and apply filter again
* Wait for 10 or more seconds
* Check logs haven't exceptions
