### ISSUE TITLE
String nullOption value for the LookupPickerField causes the exception

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1132]
#### Environment

- Platform version: 7.0

#### Description of the bug or enhancement

1. Create a LookupPickerField
2. Specify the MetaClass or the Datasource
3. Set the nullName option with the string value:
```
<lookupPickerField nullName="(empty)"/>
```
or
```
 lookupPickerField .setNullOption("<null>");
```

4 Run the application and open the screen

Another way to reproduce the problem is to open the LookupPickerFieldSamlple screen in refapp.

**E.R.** Screen will be opened without exception
**A.R.** Exception will appear

```
java.lang.ClassCastException: java.lang.String cannot be cast to com.haulmont.cuba.core.entity.Entity
	at com.haulmont.cuba.web.gui.components.WebLookupPickerField.setNullOption(WebLookupPickerField.java:46)
	at com.haulmont.cuba.gui.xml.layout.loaders.LookupFieldLoader.loadComponent(LookupFieldLoader.java:59)
	at com.haulmont.cuba.gui.xml.layout.loaders.LookupPickerFieldLoader.loadComponent(LookupPickerFieldLoader.java:39)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:39)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:91)
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractBoxLoader.loadComponent(AbstractBoxLoader.java:51)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:39)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:91)
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractBoxLoader.loadComponent(AbstractBoxLoader.java:51)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:39)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:91)
	at com.haulmont.cuba.gui.xml.layout.loaders.WindowLoader.loadComponent(WindowLoader.java:80)
```

**Comment by glebfox** [comment]
New methods were added:
* `String getNullSelectionCaption();`
* `void setNullSelectionCaption(String nullOption);`

Old ones were deprecated
