### ISSUE TITLE
NPE occurs while trying to create an entity if KRYO serialization is enabled in the project

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1149]
#### Environment

- Platform version: 6.10

#### Description of the bug or enhancement
1. Use sample-sales project #742 
2. Enable KRYO serialization by setting: `cuba.serialization.impl = com.haulmont.cuba.core.sys.serialization.KryoSerialization` in the core and web properties
3. Run the app
4. Try to create any entity, for example, Customer
```
java.lang.NullPointerException
	at com.google.common.collect.ForwardingCollection.add(ForwardingCollection.java:84)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at com.haulmont.cuba.core.sys.serialization.KryoSerialization.deserialize(KryoSerialization.java:153)
	at com.haulmont.cuba.core.sys.serialization.KryoSerialization.deserialize(KryoSerialization.java:170)
	at com.haulmont.cuba.core.sys.serialization.SerializationSupport.deserialize(SerializationSupport.java:65)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:169)
	at com.sun.proxy.$Proxy29.commit(Unknown Source)
	at com.haulmont.cuba.client.sys.DataManagerClientImpl.commit(DataManagerClientImpl.java:96)
	at com.haulmont.cuba.gui.data.impl.GenericDataSupplier.commit(GenericDataSupplier.java:94)
	at com.haulmont.cuba.gui.data.impl.DsContextImpl.commit(DsContextImpl.java:166)
	at com.haulmont.cuba.gui.components.EditorWindowDelegate.commit(EditorWindowDelegate.java:271)
	at com.haulmont.cuba.web.gui.WebWindow$Editor.commitAndClose(WebWindow.java:1755)
```

**Comment by andreysubbotin** [comment]
https://github.com/cuba-platform/cuba/commit/08a9ac663689d6f60223ff2132af60f54c2a6421
