### ISSUE TITLE
Shortcut support for Button

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1198]
At the moment we can specify shortcut only on Action.

We should support it in API and XML markup.

## Updates
The button has shortcut support. 
You can set the attribute value either in XML descriptor or using methods:
- `void setShortcutCombination(KeyCombination shortcut)` - sets shortcut key combination
- `void setShortcut(String shortcut)` - sets shortcut from the string representation

And you can get the shortcut key combination for the button using `KeyCombination getShortcutCombination()`

You can subscribe to shortcut using the method `onButtonClick`

## QA
Checklist
- [ ] Sets a shortcut combination using API
- [ ] Sets a shortcut combination using XML descriptor
- [ ] Sets a shortcut combination using API or XML descriptor and then reset it by setting `null`. The shortcut key combination should reset.

**Comment by sukhova** [comment]
1) Create a screen
2) Create a button
3) Define the **shortcut** attribute by selecting a value from a list of possible values, for example:
```
<button id="button1" caption="Button" shortcut="${CLOSE_SHORTCUT}"/>
```
4) Launch the application
5) Try to open the created screen

**AR**:
```
IllegalArgumentException: No enum constant com.haulmont.cuba.gui.components.KeyCombination.Key.${CLOSE_SHORTCUT}
```

Stacktrace:

```
java.lang.IllegalArgumentException: No enum constant com.haulmont.cuba.gui.components.KeyCombination.Key.${CLOSE_SHORTCUT}
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.haulmont.cuba.gui.components.KeyCombination$Key.valueOf(KeyCombination.java:105)
	at com.haulmont.cuba.gui.components.KeyCombination.create(KeyCombination.java:65)
	at com.haulmont.cuba.web.gui.components.WebButton.setShortcut(WebButton.java:247)
	at com.haulmont.cuba.gui.xml.layout.loaders.ButtonLoader.loadShortcut(ButtonLoader.java:98)
	at com.haulmont.cuba.gui.xml.layout.loaders.ButtonLoader.loadComponent(ButtonLoader.java:79)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:37)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:75)
	at com.haulmont.cuba.gui.xml.layout.loaders.WindowLoader.loadComponent(WindowLoader.java:93)
	at com.haulmont.cuba.web.sys.WebScreens.loadWindowFromXml(WebScreens.java:365)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:232)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:175)
	at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:319)
	at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:264)
	at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:249)
	at com.haulmont.cuba.web.gui.components.mainwindow.WebSideMenu$MenuItemImpl.menuSelected(WebSideMenu.java:573)
	at com.haulmont.cuba.web.widgets.CubaSideMenu$1.menuItemTriggered(CubaSideMenu.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by Mihail063** [comment]
1. Create a new screen
2. Create a new button
3. Open the screen controller and inject the button
4. Define the shortcut attribute by selecting a value from a list of possible values, for example: `button.setShortcut("${FILTER_APPLY_SHORTCUT}");`
5. Launch the application
6. Try to open the created screen

**AR:**
Exception occurs 
```
IllegalArgumentException: No enum constant com.haulmont.cuba.gui.components.KeyCombination.Key.${FILTER_APPLY_SHORTCUT}
```
Stacktrace:
```

java.lang.IllegalArgumentException: No enum constant com.haulmont.cuba.gui.components.KeyCombination.Key.${FILTER_APPLY_SHORTCUT}
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.haulmont.cuba.gui.components.KeyCombination$Key.valueOf(KeyCombination.java:105)
	at com.haulmont.cuba.gui.components.KeyCombination.create(KeyCombination.java:65)
	at com.haulmont.cuba.web.gui.components.WebButton.setShortcut(WebButton.java:255)
	at com.company.untitled3.web.screens.NewScreen.onInit(NewScreen.java:46)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:128)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:60)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:253)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:175)
	at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:319)
	at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:264)
	at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:249)
	at com.haulmont.cuba.web.gui.components.mainwindow.WebSideMenu$MenuItemImpl.menuSelected(WebSideMenu.java:573)
	at com.haulmont.cuba.web.widgets.CubaSideMenu$1.menuItemTriggered(CubaSideMenu.java:90)
	at sun.reflect.GeneratedMethodAccessor158.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
```

Also, the same error occurs after trying to set `button.setShortcut("${com.haulmont.cuba.client.ClientConfig#getTableRemoveShortcut}");`

**Comment by GlebDurygin** [comment]
The user can use predefined shortcut aliases only in the XML descriptor. In the screen controller, a string of the form: `"${FILTER_APPLY_SHORTCUT}"`, will be considered as a key combination.
