### ISSUE TITLE
Atmosphere initialization failed for SingleWAR deployment

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#1219]
### Environment

- Platform version: 7.0
- Tomcat 8.5

### Description of the bug or enhancement

- Minimal reproducible example

1) Checkout RefApp 7.0
2) Build SingleWAR
3) Run assembled WAR in Tomcat

- Expected behavior

Everything is ok

- Actual behavior
Web client doesn't work. 
```
12:41:28.708 INFO  com.vaadin.server.VaadinServlet - Requested resource [/VAADIN/widgetsets/com.haulmont.charts.web.widgets.ChartsWidgetSet/com.haulmont.charts.web.widgets.ChartsWidgetSet.nocache.js] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
12:41:29.160 INFO  c.h.cuba.gui.config.WindowConfig - WindowConfig initialized in 26 ms
12:41:35.831 INFO  com.vaadin.server.VaadinServlet - Requested resource [/VAADIN/widgetsets/com.haulmont.charts.web.widgets.ChartsWidgetSet/com.haulmont.charts.web.widgets.ChartsWidgetSet.nocache.js] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
12:41:37.166 INFO  com.vaadin.server.VaadinServlet - Requested resource [/VAADIN/widgetsets/com.haulmont.charts.web.widgets.ChartsWidgetSet/com.haulmont.charts.web.widgets.ChartsWidgetSet.nocache.js] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
```

Huge error output related to JSR356 and Atmoshpere for web app:

```
java.lang.IllegalStateException: Unable to configure jsr356 at that stage. No Servlet associated with app_servlet
        at org.atmosphere.util.IOUtils.guestRawServletPath(IOUtils.java:275) [atmosphere-runtime-2.4.24-1-cuba.jar:2.4.24-1-cuba]
        at org.atmosphere.util.IOUtils.guestServletPath(IOUtils.java:248) [atmosphere-runtime-2.4.24-1-cuba.jar:2.4.24-1-cuba]
        at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:65) [atmosphere-runtime-2.4.24-1-cuba.jar:2.4.24-1-cuba]
        at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:42) [atmosphere-runtime-2.4.24-1-cuba.jar:2.4.24-1-cuba]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_181]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_181]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_181]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [na:1.8.0_181]
        at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:237) [atmosphere-runtime-2.4.24-1-cuba.jar:2.4.24-1-cuba]
        at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:308) [atmosphere-runtime-2.4.24-1-cuba.jar:2.4.24-1-cuba]
        at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:294) [atmosphere-runtime-2.4.24-1-cuba.jar:2.4.24-1-cuba]
        at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2085) [atmosphere-runtime-2.4.24-1-cuba.jar:2.4.24-1-cuba]
        at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914) [atmosphere-runtime-2.4.24-1-cuba.jar:2.4.24-1-cuba]
        at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838) [atmosphere-runtime-2.4.24-1-cuba.jar:2.4.24-1-cuba]
        at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:194) [vaadin-server-8.5.1-6-cuba.jar:8.5.1-6-cuba]
        at com.vaadin.server.communication.PushRequestHandler.<init>(PushRequestHandler.java:64) [vaadin-server-8.5.1-6-cuba.jar:8.5.1-6-cuba]
        at com.vaadin.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:68) [vaadin-server-8.5.1-6-cuba.jar:8.5.1-6-cuba]
        at com.haulmont.cuba.web.sys.CubaVaadinServletService.createRequestHandlers(CubaVaadinServletService.java:173) [cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
        at com.vaadin.server.VaadinService.init(VaadinService.java:194) [vaadin-server-8.5.1-6-cuba.jar:8.5.1-6-cuba]
        at com.haulmont.cuba.web.sys.CubaApplicationServlet.createServletService(CubaApplicationServlet.java:85) [cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
        at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:357) [vaadin-server-8.5.1-6-cuba.jar:8.5.1-6-cuba]
        at com.vaadin.server.VaadinServlet.init(VaadinServlet.java:187) [vaadin-server-8.5.1-6-cuba.jar:8.5.1-6-cuba]
        at com.haulmont.cuba.web.sys.CubaApplicationServlet.init(CubaApplicationServlet.java:101) [cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
        at com.haulmont.cuba.web.sys.singleapp.SingleAppWebContextLoader.registerAppServlet(SingleAppWebContextLoader.java:112) [cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
        at com.haulmont.cuba.web.sys.singleapp.SingleAppWebContextLoader.contextInitialized(SingleAppWebContextLoader.java:83) [cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
```

**Comment by jreznot** [comment]
We need to update to Vaadin 8.5.2 and Atmosphere 2.4.30

**Comment by jreznot** [comment]
For QA: Check  with Jetty 9.3 and Tomcat 8 and 9
