### ISSUE TITLE
NPE in Loggers window when select empty level

### ISSUE THREAD

**Issue by sergkarv** [cuba-platform/cuba#1246]
1. Open Administration-Monitoring-Server Log.
1. Open tab Options.
1. Press the button "Control".
1. Select an empty level.
1. Press the button "Apply".

```
java.lang.NullPointerException
    at com.haulmont.cuba.web.app.ui.serverlogviewer.ServerLogWindow$9.windowClosed(ServerLogWindow.java:467) 
    at com.haulmont.cuba.web.gui.WebWindow.fireWindowClosed(WebWindow.java:711) 
    at com.haulmont.cuba.web.gui.WebWindow.onClose(WebWindow.java:703) 
    at com.haulmont.cuba.web.gui.WebWindow.close(WebWindow.java:1006) 
    at com.haulmont.cuba.gui.components.AbstractWindow.close(AbstractWindow.java:212) 
    at com.haulmont.cuba.web.app.ui.serverlogviewer.ControlLoggerWindow.apply(ControlLoggerWindow.java:74) 
```

**Comment by Flaurite** [comment]
Hi!
Issue template was created especially to simplify investigation of a bug or enhancement.
Why do you just removed it? Could you clarify which platform version do you use?

**Comment by sergkarv** [comment]
Hi!
I use  Release 5.9.
But this exception i saw in the latest version.

**Comment by sergkarv** [comment]
The latest versions do not reproduced. my mistake.

**Comment by Flaurite** [comment]
Release 5.9 fixed in: https://youtrack.cuba-platform.com/issue/PL-10764
