### ISSUE TITLE
Unobvious API to dynamically add column to table

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#1255]
### Environment

- Platform version: 6.8.12
- Client type: Web

### Description of the bug or enhancement
This code produces internal exception:
```
driversTable.addColumn(new Table.Column("createTs"));
```
```
2018-09-12 13:16:36.937 ERROR [http-nio-8080-exec-8/app/admin] com.haulmont.cuba.web.log.AppLog - Exception in com.haulmont.cuba.web.toolkit.ui.CubaMenuBar: 
java.lang.UnsupportedOperationException: null
	at com.haulmont.cuba.web.gui.data.CollectionDsWrapper.addContainerProperty(CollectionDsWrapper.java:194) ~[cuba-web-6.8-SNAPSHOT.jar:6.8-SNAPSHOT]
	at com.vaadin.ui.AbstractSelect.addContainerProperty(AbstractSelect.java:844) ~[vaadin-server-7.7.13.cuba.11.jar:7.7.13.cuba.11]
	at com.vaadin.ui.Table.addContainerProperty(Table.java:4411) ~[vaadin-server-7.7.13.cuba.11.jar:7.7.13.cuba.11]
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.addColumn(WebAbstractTable.java:180) ~[cuba-web-6.8-SNAPSHOT.jar:6.8-SNAPSHOT]
	at com.haulmont.refapp.gui.app.driver.DriverBrowser.init(DriverBrowser.java:47) ~[refapp-gui-6.8-SNAPSHOT.jar:na]
...
```

This code works but is clumsy and unobvious (btw MetaProperty doesn't work, only MetaPropertyPath):
```
driversTable.addColumn(new Table.Column(driversTable.getDatasource().getMetaClass().getPropertyPath("createTs")));
```

Table.addColumn() method is not documented: no javadocs, not mentioned in developer's manual.

### Updates
* Added JavaDocs for `Table#addColumn` methods.
* User cannot use follow code: 
```
driversTable.addColumn(new Table.Column("createTs"));
```
An exception will be thrown:
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/06292e97-40ca-4723-a10d-f8fcfedeef5f)
* To add a column to the table, use the `MetaPropertyPath` as an column id:
```
driversTable.addColumn(new Table.Column(driversTable.getDatasource().getMetaClass().getPropertyPath("createTs")));
```

### QA
Check the above cases.

**Comment by GlebDurygin** [comment]
This exception (`IllegalArgumentException: Column id should be an instance of MetaPropertyPath`) is always thrown if the column is generated.

**Comment by natfirst** [comment]
For the more universal way (for both legacy and new screens) use the `getItems()` method:
```
customersTable.addColumn(new Table.Column(((EntityTableItems) customersTable.getItems()).getEntityMetaClass().getPropertyPath("createTs")));
```
