### ISSUE TITLE
SingleWar does not work on JVM 8

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#1270]
### Environment

- Platform version: 7.0-SNAPSHOT
Java 1.8.0_172
Tomcat 8.5

### Description of the bug or enhancement

- Minimal reproducible example
1) Open the Refapp project in IDE
2) launch _gradlew buildSingleWar_
3) put the generated app.wat to webapps 
4) star the tomcat 

- Actual behavior
It seems *jaxb* is not compatible with JAVA 8
But when the same application is deployed by multi-WAR it works ok 

```code
4-Sep-2018 14:14:27.283 SEVERE [localhost-startStop-1] org.apache.catalina.startup.ContextConfig.processAnnotationsJar Unable to process Jar entry [module-info.class] from Jar [file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.5/webapps/app/WEB-INF/lib/jaxb-api-2.3.0.jar] for annotations
 org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:97)
	at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:54)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:174)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:83)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2053)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2000)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1970)
	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1923)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1163)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:775)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5087)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by myatlevEvg** [comment]
1) Checkout RefApp 7.0
2) Build SingleWAR
3) Run that single war in jetty 9.3

```
2018-11-08 12:09:16.062:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@5cc7c2a6{/app,[file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/, jar:file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/jquery-ui-touch-punch-0.2.3-2.jar!/META-INF/resources, jar:file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/jquery-1.12.4.jar!/META-INF/resources, jar:file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/jquery-ui-1.12.1.jar!/META-INF/resources, jar:file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/ace-builds-1.1.9-1-cuba.jar!/META-INF/resources, jar:file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/jquery-file-upload-9.22.0.cuba.0.jar!/META-INF/resources, jar:file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/amcharts-3.21.12.cuba.1.jar!/META-INF/resources, jar:file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/pivottable-2.21.0.cuba.0.jar!/META-INF/resources, jar:file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/diff-match-patch-0.1.cuba.1.jar!/META-INF/resources, jar:file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/object-fit-images-3.2.3.jar!/META-INF/resources],STARTING}{C:\Users\myatlev\Documents\jetty-distribution-9.3.6.v20151106\webapps\app.war}
MultiException[java.lang.RuntimeException: Error scanning entry module-info.class from jar file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/FastInfoset-1.2.15.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/istack-commons-runtime-3.0.7.jar, java.lang.RuntimeException: Error scanning entry META-INF/versions/9/javax/xml/bind/ModuleUtil.class from jar file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/jaxb-api-2.3.1.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/jaxb-api-2.3.1.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/jaxb-runtime-2.3.1.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/stax-ex-1.8.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:///C:/Users/myatlev/AppData/Local/Temp/jetty-0.0.0.0-8080-app.war-_app-any-123967412099750744.dir/webapp/WEB-INF/lib/txw2-2.3.1.jar]
        at org.eclipse.jetty.annotations.AnnotationConfiguration.scanForAnnotations(AnnotationConfiguration.java:536)
        at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:447)
        at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:491)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1336)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)
        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:453)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:561)
        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:405)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:372)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1510)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1435)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:214)
        at org.eclipse.jetty.start.Main.start(Main.java:457)
        at org.eclipse.jetty.start.Main.main(Main.java:75)
```

**Comment by andreysubbotin** [comment]
Remove dependencies to JAXB from CUBA. For building and execution on JAVA 10 specify dependencies in the `global` of build.gradle.

**Comment by andreysubbotin** [comment]
Documentation: cuba-platform/documentation#253
