### ISSUE TITLE
Reimplement the Tree component

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1277]

**Comment by glebfox** [comment]
**Currently, there are several differences:**

* No border and padding
* Selection doesn't move by arrows keys

**New API:**

* setSelectionMode
* getSelectionMode
* expand(E item)
* collapse(E item)

**Deprecated API:**

* setMultiSelect
* expand(Object itemId)
* collapse(Object itemId)

**Comment by sukhova** [comment]
1) Do not define attribute _captionProperty_
2) Set _CaptionMode.PROPERTY_ programmatically
3) Open the app
4) See NPE:

```
java.lang.NullPointerException
	at com.haulmont.chile.core.model.impl.MetaClassImpl.getPropertyPath(MetaClassImpl.java:114)
	at com.haulmont.cuba.core.global.MetadataTools.resolveMetaPropertyPath(MetadataTools.java:905)
	at com.haulmont.cuba.core.global.MetadataTools.resolveMetaPropertyPathNN(MetadataTools.java:921)
	at com.haulmont.cuba.web.gui.components.WebTree.generateItemCaption(WebTree.java:225)
	at com.vaadin.ui.Tree.lambda$new$1170f939$1(Tree.java:275)
	at com.vaadin.ui.Grid$Column.generateRendererValue(Grid.java:1055)
	at com.vaadin.ui.Grid$Column.access$1100(Grid.java:844)
	at com.vaadin.ui.Grid$Column$1.generateData(Grid.java:875)
	at com.vaadin.data.provider.DataCommunicator.getDataObject(DataCommunicator.java:454)
	at com.vaadin.data.provider.DataCommunicator.pushData(DataCommunicator.java:434)
	at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:347)
	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:316)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:114)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:115)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:84)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:317)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:208)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:412)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1385)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```
