### ISSUE TITLE
Using RowsCount with KeyValueCollectionLoader

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#1301]
Now it leads to a number of issues:

When clicking to ? or to >>:
```
java.lang.RuntimeException: Unable to find selected entity name [null]
	at com.haulmont.cuba.core.sys.jpql.QueryTreeAnalyzer.getMainSelectedEntityName(QueryTreeAnalyzer.java:82)
	at com.haulmont.cuba.core.sys.jpql.transform.QueryTransformerAstBased.createMainSelectedPathNodeReference(QueryTransformerAstBased.java:309)
	at com.haulmont.cuba.core.sys.jpql.transform.QueryTransformerAstBased.replaceWithCount(QueryTransformerAstBased.java:209)
	at com.haulmont.cuba.web.gui.components.WebRowsCount$LoaderAdapter.getCount(WebRowsCount.java:499)
	at com.haulmont.cuba.web.gui.components.WebRowsCount.onLastClick(WebRowsCount.java:265)
```

When sorting a partially loaded collection:
```
java.lang.IllegalArgumentException: Property login is invalid
	at com.haulmont.cuba.core.app.RdbmsQueryBuilder.processSort(RdbmsQueryBuilder.java:189)
	at com.haulmont.cuba.core.app.RdbmsQueryBuilder.init(RdbmsQueryBuilder.java:97)
	at com.haulmont.cuba.core.app.RdbmsStore.loadValues(RdbmsStore.java:540)
	at com.haulmont.cuba.core.app.DataManagerBean.loadValues(DataManagerBean.java:239)
	at com.haulmont.cuba.core.app.DataServiceBean.loadValues(DataServiceBean.java:66)
```

**Comment by knstvk** [comment]
Duplicates #2054 and #2087.
