### ISSUE TITLE
NPE when creating report using wizard

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#1302]
Platform 7.0

1) Open refapp 7.0
2) Open reports screen
3) Click Create -> Using Wizard

**AR**

```java.lang.NullPointerException
	at com.haulmont.cuba.web.gui.components.WebDialogWindow$WebDialogOptions.setWidth(WebDialogWindow.java:332)
	at com.haulmont.cuba.gui.DialogOptions.setWidth(DialogOptions.java:225)
	at com.haulmont.cuba.gui.DialogOptions.setWidth(DialogOptions.java:214)
	at com.haulmont.reports.gui.report.wizard.ReportWizardCreator.init(ReportWizardCreator.java:147)
	at com.haulmont.cuba.gui.components.AbstractWindow.init(AbstractWindow.java:91)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:124)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:54)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:221)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:156)
	at com.haulmont.cuba.web.sys.WebScreens.openWindow(WebScreens.java:562)
	at com.haulmont.cuba.gui.screen.compatibility.LegacyFrame.openWindow(LegacyFrame.java:113)
	at com.haulmont.reports.gui.report.browse.ReportBrowser$7.actionPerform(ReportBrowser.java:179)
	at com.haulmont.cuba.web.gui.components.WebPopupButton$PopupActionWrapper.actionPerform(WebPopupButton.java:395)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:60)

**Comment by myatlevEvg** [comment]
Check the next issue before close this one:
https://app.zenhub.com/workspace/o/cuba-platform/reports/issues/103
