### ISSUE TITLE
Saved filter using wrong value selector for the unary condition

### ISSUE THREAD

**Issue by Ilya-c** [cuba-platform/cuba#1310]
### Environment

- Platform version: 6.10-SNAPSHOT 

- Client type: Web

### Description of the bug

1 ) Create a filter using "is set" condition.
For example: Application - Cars - Add search condition - VIN - "is set"
Value selector will be a lookup field with YES/NO options.
![filter](https://user-images.githubusercontent.com/6366861/46202793-d4236e00-c328-11e8-8173-537177a9d42a.jpg)
2) Save this filter, reopen the screen and select it.
Instead of lookup will be a checkbox - ![filter after open](https://user-images.githubusercontent.com/6366861/46202806-d980b880-c328-11e8-8581-0a38fceb5ed1.jpg)
In this case filter isn't working for "is not set" condition (checkbox isn't checked)

Code in PropertyCondition#setOperator should also be executed during the creation of the condition from filter xml.

**Comment by soraksh** [comment]
Problem remains for previously saved filters, but fixed for newly created and saved (and for updated and re-saved old ones).

**Comment by Mihail063** [comment]
Environment
Platform version: 7.0.7, 7.1.0, 7.2.0

1. Create a filter using "is set" condition.
2. Set the option "Yes" or "No"
3. Save the filter with the attribute
4. Reopen the screen
5. Select the filter from the previous step

A.R.
NPE error occurred. 
```
java.lang.NullPointerException
	at com.haulmont.cuba.gui.components.filter.condition.PropertyCondition.updateText(PropertyCondition.java:124)
	at com.haulmont.cuba.gui.components.filter.condition.AbstractCondition.getText(AbstractCondition.java:250)
	at com.haulmont.cuba.gui.components.filter.condition.AbstractCondition.toXml(AbstractCondition.java:311)
	at com.haulmont.cuba.gui.components.filter.condition.PropertyCondition.toXml(PropertyCondition.java:176)
	at com.haulmont.cuba.gui.components.filter.FilterParserImpl.recursiveToXml(FilterParserImpl.java:145)
	at com.haulmont.cuba.gui.components.filter.FilterParserImpl.getXml(FilterParserImpl.java:125)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.isFilterModified(FilterDelegateImpl.java:1098)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.setFilterActionsEnabled(FilterDelegateImpl.java:690)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.setFilterEntity(FilterDelegateImpl.java:615)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl$5.actionPerform(FilterDelegateImpl.java:1217)
	at com.haulmont.cuba.web.gui.components.WebPopupButton.lambda$setPopupButtonAction$1(WebPopupButton.java:328)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
...
```

**Comment by soraksh** [comment]
For QA: can't reproduce NPE on 7.0.7, 7.1.0 and 7.2.0 versions, but reproduced on 7.0.6. Check once more with filters created on 7.0.7, 7.1.0 and 7.2.0 versions (NPE may occur for filters created on older versions).
