### ISSUE TITLE
CurrencyField value type must extend Number

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1311]
Currently, any type can be assigned, but if we set a value to the ValueSource:

```
userDs.getItem().setName("Test");
```

we get an exception:

```
java.lang.IllegalArgumentException: Cannot format given Object as a Number
	at java.text.DecimalFormat.format(DecimalFormat.java:507)
	at java.text.Format.format(Format.java:157)
	at com.haulmont.chile.core.datatypes.impl.BigDecimalDatatype.format(BigDecimalDatatype.java:69)
	at com.haulmont.cuba.web.gui.components.WebCurrencyField.convertToPresentation(WebCurrencyField.java:76)
	at com.haulmont.cuba.web.gui.components.WebCurrencyField.convertToPresentation(WebCurrencyField.java:41)
	at com.haulmont.cuba.web.gui.components.WebAbstractValueComponent.setValue(WebAbstractValueComponent.java:88)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.sourceValueChanged(ValueBinder.java:256)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.data.value.DatasourceValueSource.datasourceItemPropertyChanged(DatasourceValueSource.java:188)
	at com.haulmont.bali.events.EventRouter.fireEvent(EventRouter.java:45)
	at com.haulmont.cuba.gui.data.impl.AbstractDatasource$ItemListener.propertyChanged(AbstractDatasource.java:285)
	at com.haulmont.chile.core.model.impl.AbstractInstance.propertyChanged(AbstractInstance.java:52)
	at com.haulmont.cuba.security.entity.User.setName(User.java:135)
```

## QA

Check the following cases:
1. Field has `datatype` and `datasource` - value should be formatted according to `datatype`
2. Field has only `datatype` - value should be formatted according to `datatype`
3. Field has only `datasource` - value should be formatted according to `datatype` corresponding to `datasource` property
4. Field has no `datatype` or `datasource` - value should be formatted according to `BigDecimal` datatype.

Check also `datatype` switching / resetting.

**Comment by jreznot** [comment]
It seems that we have to add `<T extends Number>` to typing

**Comment by glebfox** [comment]
Exception, if the datatype differs from `BigDecimal`:
```
<currencyField id="component"
               datatype="int"
               buffered="false"
               datasource="dataTypesDs"
               property="integerField"/>
```
```
java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.chile.core.model.utils.MethodsCache.invokeSetter(MethodsCache.java:58)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:138)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:115)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:122)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:172)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:151)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValueEx(AbstractInstance.java:149)
	at com.haulmont.cuba.gui.components.data.value.DatasourceValueSource.setValue(DatasourceValueSource.java:114)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.setValueToSource(ValueBinder.java:250)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.componentValueChanged(ValueBinder.java:243)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.web.gui.components.WebAbstractComponent.publish(WebAbstractComponent.java:84)
	at com.haulmont.cuba.web.gui.components.WebAbstractValueComponent.componentValueChanged(WebAbstractValueComponent.java:142)
	at com.haulmont.cuba.web.gui.components.WebCurrencyField.lambda$attachValueChangeListener$1ebec749$1(WebCurrencyField.java:63)
```

**Comment by dtsaryov** [comment]
> Exception, if the datatype differs from BigDecimal:

This case is related not only to the `CurrencyField` component and will be handled in #1508.
