### ISSUE TITLE
IllegalArgumentException occurs when open the screen which contains DataGrid with two or more columns

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#1317]
Platform 7.0

1) Add DataGrid at any screen
2) Define CollectionDatasource in dsContext
3) Add two or more columns for DataGrid
4) Open the screen

See the attached refapp patch and exported UserSettings to JSON in zip file from attachments.

[dataGridExc.zip](https://github.com/cuba-platform/cuba/files/2436943/dataGridExc.zip)

**AR**
```
java.lang.IllegalArgumentException: Duplicate ID for columns
	at com.vaadin.ui.Grid.setColumnId(Grid.java:4683)
	at com.vaadin.ui.Grid$Column.setId(Grid.java:1177)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.createStubsForGeneratedColumns(WebAbstractDataGrid.java:974)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.setDataSource(WebAbstractDataGrid.java:821)
	at com.haulmont.cuba.web.gui.components.WebTreeDataGrid.setDataSource(WebTreeDataGrid.java:51)
	at com.haulmont.cuba.gui.components.TreeDataGrid.setDatasource(TreeDataGrid.java:56)
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractDataGridLoader.loadComponent(AbstractDataGridLoader.java:178)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:38)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:90)
	at com.haulmont.cuba.gui.xml.layout.loaders.WindowLoader.loadComponent(WindowLoader.java:101)
	at com.haulmont.cuba.web.sys.WebScreens.loadScreenXml(WebScreens.java:254)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:201)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:154)

**Comment by glebfox** [comment]
Can't reproduce, the following configuration works as intended:
```
<dsContext>
    <hierarchicalDatasource
            id="groupsDs"
            class="com.haulmont.cuba.security.entity.Group"
            view="group.browse"
            hierarchyProperty="parent">
        <query>
            <![CDATA[select g from sec$Group g order by g.name]]>
        </query>
    </hierarchicalDatasource>
</dsContext>
<layout>
    <treeDataGrid
            datasource="groupsDs"
            height="100%"
            width="100%">
        <columns>
            <column property="name"/>
            <column property="parent"/>
        </columns>
    </treeDataGrid>
</layout>
```

**Comment by glebfox** [comment]
The following configuration works as expected:

```
<dsContext>
    <hierarchicalDatasource
            id="groupsDs"
            class="com.haulmont.cuba.security.entity.Group"
            view="group.browse"
            hierarchyProperty="parent">
        <query>
            <![CDATA[select g from sec$Group g order by g.name]]>
        </query>
    </hierarchicalDatasource>
</dsContext>

<layout>
    <treeDataGrid datasource="groupsDs"
                  height="100%"
                  width="100%">
        <columns>
            <column property="name"/>
            <column property="parent"/>
        </columns>
    </treeDataGrid>
</layout>
```
