### ISSUE TITLE
NPE during application start if an application component does not have any properties in descriptor

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/cuba#1322]
### Environment

- Platform version: 6.10.0
- Client type: Web

### Description of the bug or enhancement

If an application component does not have properties in descriptor:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<app-component xmlns="http://schemas.haulmont.com/cuba/app-component.xsd"
               dependsOn="com.haulmont.cuba">
    <module blocks="*"
            name="global">
        <artifact appJar="true"
                  name="cuba-jpa-repositories-global"/>
    </module>
</app-component>
```
Then on application startup it fails with an error:
```
22:31:20.151 ERROR c.h.c.c.s.AbstractWebAppContextLoader   - Error initializing application
java.lang.NullPointerException: null
        at com.haulmont.cuba.core.sys.AppComponent.getPropertyNames(AppComponent.java:110) ~[cuba-global-6.10.0.jar:6.10.0]
        at com.haulmont.cuba.core.sys.AppProperties.getPropertyNames(AppProperties.java:86) ~[cuba-global-6.10.0.jar:6.10.0]
        at com.haulmont.cuba.core.sys.AppContext.getPropertyNames(AppContext.java:107) ~[cuba-global-6.10.0.jar:6.10.0]
        at com.haulmont.cuba.core.sys.persistence.PersistenceConfigProcessor.create(PersistenceConfigProcessor.java:91) ~[cuba-core-6.10.0.jar:6.10.0]
        at com.haulmont.cuba.core.sys.AppContextLoader.createPersistenceXml(AppContextLoader.java:69) ~[cuba-core-6.10.0.jar:6.10.0]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_172]
        at com.haulmont.cuba.core.sys.AppContextLoader.beforeInitAppContext(AppContextLoader.java:84) ~[cuba-core-6.10.0.jar:6.10.0]
        at com.haulmont.cuba.core.sys.AbstractWebAppContextLoader.contextInitialized(AbstractWebAppContextLoader.java:76) ~[cuba-global-6.10.0.jar:6.10.0]
```

In AppComponent.java:110
```java
    public List<String> getPropertyNames() {
        //We should check properties for null here I guess.
        List<String> list = new ArrayList<>(properties.stringPropertyNames());
        list.sort(Comparator.naturalOrder());
        return list;
    }
```

**Comment by belyaev-andrey** [comment]
BTW why don't we init properties in lazy manner? Can't we init field with the empty properties during declaration? 

```java
    public void setProperty(String name, String value, boolean additive) {
        if (properties == null)
            properties = new Properties();

        if (additive) {
            if (additiveProperties == null) {
                additiveProperties = new HashSet<>();
            }
            additiveProperties.add(name);
        } else if (additiveProperties != null) {
            additiveProperties.remove(name);
        }

        properties.setProperty(name, value);
    }
```
