### ISSUE TITLE
ClassCastException when trying to set up a query for the report

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1331]
#### Environment

- Platform version: 7.0

#### Description of the bug or enhancement

1. Open the reports screen
2. Create a new one using wizard
3. Fill the necessary fields
4. Select  *Report for the list of entities, selected by query*
5. Click **Set query**

```
java.lang.ClassCastException: Cannot cast com.haulmont.cuba.web.widgets.CubaTree to com.vaadin.v7.ui.Tree
	at java.lang.Class.cast(Class.java:3369)
	at com.haulmont.cuba.web.gui.components.WebAbstractComponent.unwrap(WebAbstractComponent.java:415)
	at com.haulmont.cuba.web.gui.components.WebFilterHelper.initConditionsDragAndDrop(WebFilterHelper.java:104)
	at com.haulmont.cuba.gui.components.filter.edit.FilterEditor.init(FilterEditor.java:302)
	at com.haulmont.cuba.gui.components.AbstractWindow.init(AbstractWindow.java:93)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:133)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:54)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:220)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:155)
	at com.haulmont.cuba.web.sys.WebScreens.openWindow(WebScreens.java:550)
	at com.haulmont.cuba.gui.screen.compatibility.LegacyFrame.openWindow(LegacyFrame.java:100)
	at com.haulmont.reports.gui.report.wizard.DetailsStepFrame$SetQueryAction.actionPerform(DetailsStepFrame.java:221)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:60)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by glebfox** [comment]
Moved to cuba-platform/reports#110
