### ISSUE TITLE
IllegalArgumentException when trying to copy settings for user

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#1344]
### Environment

- Platform version: 7.0
- Client type: Web
- Operating system: Windows

### Description of the bug or enhancement

1) Open **Administration->Users**
2) Right-click of the mouse on any user
3) Select **Copy settings**
4) Select any user from the list and click on the **Copy** button
5) In the **Confirmation** dialog click **Yes** button

**AR:**

![70.JPG](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/dc58b5fa-2875-46eb-ae7c-40d89801f637)

Log:

```
java.lang.IllegalArgumentException: You have attempted to set a value of type class com.haulmont.cuba.security.entity.User for parameter 1 with expected type of class java.util.UUID from query string delete from sec$Presentation p where p.user.id=?1.
	at org.eclipse.persistence.internal.jpa.QueryImpl.setParameterInternal(QueryImpl.java:944)
	at org.eclipse.persistence.internal.jpa.QueryImpl.setParameterInternal(QueryImpl.java:918)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setParameter(EJBQueryImpl.java:479)
	at com.haulmont.cuba.core.sys.QueryImpl$Param.apply(QueryImpl.java:744)
	at com.haulmont.cuba.core.sys.QueryImpl.getQuery(QueryImpl.java:153)
	at com.haulmont.cuba.core.sys.QueryImpl.executeUpdate(QueryImpl.java:425)
	at com.haulmont.cuba.security.app.UserSettingServiceBean.copyPresentations(UserSettingServiceBean.java:211)
	at com.haulmont.cuba.security.app.UserSettingServiceBean.copySettings(UserSettingServiceBean.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:117)
	at sun.reflect.GeneratedMethodAccessor217.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy240.copySettings(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154)
	at com.sun.proxy.$Proxy36.copySettings(Unknown Source)
	at com.haulmont.cuba.gui.app.security.user.copysettings.CopySettings.copySettings(CopySettings.java:86)
	at com.haulmont.cuba.gui.app.security.user.copysettings.CopySettings.lambda$null$0(CopySettings.java:66)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.actions.BaseAction.actionPerform(BaseAction.java:236)
	at com.haulmont.cuba.web.sys.WebDialogs$OptionDialogImpl.lambda$show$0(WebDialogs.java:305)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
```

**Comment by knstvk** [comment]
Fixed by 4a585cd863f071df0e4baac066cba517280afffe
