### ISSUE TITLE
Problem in audimex-dashboardscomponent after switching to 6.10.0 

### ISSUE THREAD

**Issue by antmarr** [cuba-platform/cuba#1346]
- Platform version: 6.10.0
1)Create dashboard
2)Add any widget to layout. Fill all required fields, press Ok.
3)Widget will display in dasboard. Press edit button in widget (details in attached picture)
4)Error during editor opening

```
Caused by: com.haulmont.cuba.core.global.EntityAccessException: Unable to load entity dashboard$Widget-880baba6-4050-1b54-a27e-86e58865e2d2 because it has been deleted or access denied
	at com.haulmont.cuba.client.sys.DataManagerClientImpl.reload(DataManagerClientImpl.java:93) ~[cuba-client-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.gui.data.impl.GenericDataSupplier.reload(GenericDataSupplier.java:55) ~[cuba-gui-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.gui.components.EditorWindowDelegate.setItem(EditorWindowDelegate.java:155) ~[cuba-gui-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.web.gui.WebWindow$Editor.setItem(WebWindow.java:1701) ~[cuba-web-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.gui.components.AbstractEditor.setItem(AbstractEditor.java:71) ~[cuba-gui-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.gui.WindowManager.openEditor(WindowManager.java:893) ~[cuba-gui-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.web.WebWindowManager.openEditor(WebWindowManager.java:178) ~[cuba-web-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.gui.WindowManager.openEditor(WindowManager.java:842) ~[cuba-gui-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.gui.components.WindowDelegate.openEditor(WindowDelegate.java:265) ~[cuba-gui-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.web.gui.WebWindow.openEditor(WebWindow.java:502) ~[cuba-web-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.gui.components.AbstractFrame.openEditor(AbstractFrame.java:519) ~[cuba-gui-6.10.0.jar:6.10.0]
	at com.haulmont.addon.dashboard.web.dashboard.frames.editor.DashboardEdit.onOpenWidgetEditor(DashboardEdit.java:276) ~[dashboard-web-2.0-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
	at com.haulmont.cuba.gui.events.sys.UiEventListenerMethodAdapter.doInvoke(UiEventListenerMethodAdapter.java:211) ~[cuba-gui-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.gui.events.sys.UiEventListenerMethodAdapter.processEvent(UiEventListenerMethodAdapter.java:137) ~[cuba-gui-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.gui.events.sys.UiEventListenerMethodAdapter.onApplicationEvent(UiEventListenerMethodAdapter.java:96) ~[cuba-gui-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.gui.events.sys.UiEventsMulticasterImpl.invokeListener(UiEventsMulticasterImpl.java:73) ~[cuba-gui-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.gui.events.sys.UiEventsMulticasterImpl.multicastEvent(UiEventsMulticasterImpl.java:66) ~[cuba-gui-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.web.sys.WebEvents.publish(WebEvents.java:31) ~[cuba-web-6.10.0.jar:6.10.0]
	at com.haulmont.addon.dashboard.web.dashboard.tools.componentfactory.CanvasDropComponentsFactory.lambda$createEditButton$19(CanvasDropComponentsFactory.java:148) ~[dashboard-web-2.0-SNAPSHOT.jar:na]
	at com.haulmont.addon.dashboard.web.dashboard.tools.componentfactory.CanvasDropComponentsFactory$$Lambda$266/908838512.accept(Unknown Source) ~[na:na]
	at com.haulmont.cuba.gui.components.actions.BaseAction.actionPerform(BaseAction.java:228) ~[cuba-gui-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.web.gui.components.WebButton.performAction(WebButton.java:46) ~[cuba-web-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.web.gui.components.WebButton.lambda$new$61446b05$1(WebButton.java:38) ~[cuba-web-6.10.0.jar:6.10.0]
	at com.haulmont.cuba.web.gui.components.WebButton$$Lambda$86/1740668852.buttonClick(Unknown Source) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510) ~[vaadin-server-7.7.14.cuba.0.jar:7.7.14.cuba.0]
```

**Comment by antmarr** [comment]
![dash_bug](https://user-images.githubusercontent.com/31250459/46585473-e5cbea80-ca79-11e8-8c64-4831b444db20.png)

**Comment by jreznot** [comment]
Probably, relates to  #1341

**Comment by natfirst** [comment]
In order to use standard browser-editor screens with non-persistent entities, create a special DataSupplier and register it in the editor screen, for example:

```
package com.company.untitled.web.testentity;

import com.haulmont.chile.core.model.MetaClass;
import com.haulmont.cuba.core.entity.Entity;
import com.haulmont.cuba.core.global.View;
import com.haulmont.cuba.gui.data.impl.GenericDataSupplier;

import javax.annotation.Nullable;

public class NonPersistentDataSupplier extends GenericDataSupplier {

    @Override
    public <E extends Entity> E reload(E entity, View view, @Nullable MetaClass metaClass, boolean loadDynamicAttributes) {
        return entity;
    }
}
```

```
<window xmlns="http://schemas.haulmont.com/cuba/window.xsd"
        class="com.company.untitled.web.testentity.TestEntityEdit"
        ...
        dataSupplier="com.company.untitled.web.testentity.NonPersistentDataSupplier">
    <dsContext>
...
```

**Comment by antmarr** [comment]
@jreznot Does I need to fix my code as @natfirst wrote in last comment or it will be fixed on CUBA platform side?

**Comment by knstvk** [comment]
@antmarr You need to add this DataSupplier to all editors loading non-persistent entities.
