### ISSUE TITLE
NPE while opening a hot deployed screen

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1362]
### Environment

- Platform version: 7.0-SNAPSHOT

### Description of the bug or enhancement

1. Make some changes in a screen controller that is inherited from `Screen`.
2. Hot Deploy changes
3. Restart the app using `gradlew restart`
4. Try to open the screen

AR:
```
java.lang.NullPointerException
	at com.haulmont.cuba.gui.config.WindowConfig.extractWindowTemplate(WindowConfig.java:210)
	at com.haulmont.cuba.gui.config.WindowConfig$1.getTemplate(WindowConfig.java:110)
	at com.haulmont.cuba.gui.config.WindowInfo.getTemplate(WindowInfo.java:128)
	at com.haulmont.cuba.web.sys.WebScreens.loadScreenXml(WebScreens.java:233)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:202)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:155)
```

Another case:
Old window in refapp: `StockChartSampleScreen`
1. Start refapp;
2. Add the following code to a controller:
```
@Subscribe("stockChart3")
public void onRollOver(StockChart.StockGraphRollOverEvent stockGraphRollOverEvent){
    showNotification("StockGraphRollOverEvent");
}
```
3. Do hot deploy;
4. Try to open screen.

```
java.lang.NullPointerException
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.createMessageBundle(UiControllerDependencyInjector.java:644)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.getInjectedInstance(UiControllerDependencyInjector.java:608)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.doInjection(UiControllerDependencyInjector.java:495)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.injectValues(UiControllerDependencyInjector.java:288)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.inject(UiControllerDependencyInjector.java:104)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:235)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:157)
```
Interesting fact. If we open a screen and then do the above steps exception will not be invoked.

**Comment by jreznot** [comment]
Relates to https://bugs.openjdk.java.net/browse/JDK-8189231
