### ISSUE TITLE
Studio throws java.util.zip.ZipException when try to unpack cuba-portal-6.7.13-sources.jar

### ISSUE THREAD

**Issue by rgalimov** [cuba-platform/cuba#1369]
### Environment

- Platform version: 6.7.13
- Client type: Portal

### Description of the bug or enhancement

When I open project on cuba-platform 6.7.13 in studio 6.10.0 it show the following error:
```
2018-10-10 12:33:56,298 INFO [com.haulmont.studio.backend.maven.RemoteMavenRepository] [external_req] Load file content https://dl.bintray.com/cuba-platform/main/com/haulmont/cuba/cuba-portal/6.7.13/cuba-portal-6.7.13-sources.jar
2018-10-10 12:33:56,676 ERROR [com.haulmont.studio.ui.app.App] Exception occured
java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
 at com.haulmont.studio.common.StudioFiles.unjar(StudioFiles.java:160)
 at com.haulmont.studio.backend.BaseSources.loadArtifact(BaseSources.java:240)
 at com.haulmont.studio.backend.BaseSources.loadModule(BaseSources.java:190)
 at com.haulmont.studio.backend.BaseSources.access$200(BaseSources.java:47)
 at com.haulmont.studio.backend.BaseSources$1.run(BaseSources.java:99)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at com.haulmont.studio.common.StudioExecutors$StudioWrappingExecutorService.lambda$wrapTask$0(StudioExecutors.java:54)
 at com.haulmont.studio.common.StudioExecutors$StudioWrappingExecutorService.lambda$wrapTask$1(StudioExecutors.java:72)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.zip.ZipException: error in opening zip file
 at java.util.zip.ZipFile.open(Native Method)
 at java.util.zip.ZipFile.(ZipFile.java:225)
 at java.util.zip.ZipFile.(ZipFile.java:155)
 at java.util.jar.JarFile.(JarFile.java:166)
 at java.util.jar.JarFile.(JarFile.java:130)
 at com.haulmont.studio.common.StudioFiles.unjar(StudioFiles.java:135)
 ... 12 more
```
Looks like this artifact is broken https://dl.bintray.com/cuba-platform/main/com/haulmont/cuba/cuba-portal/6.7.13/cuba-portal-6.7.13-sources.jar

**Comment by jreznot** [comment]
We have replaced JAR
