### ISSUE TITLE
Internal Server Error if backward slash is put to URL

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1377]
Case:

1. Open a **new** tab in a browser
2. Type the following http://cubadev:9061/app/#!\ and press enter
3. The  backward slash will be removed from the URL but nothing is displayed
4. Refresh the page a couple of times

AR:

```
Internal Server Error. 
Please contact system administrator.
Try again later. Click here to continue. 

Development information: 

[!] You can disable development information using: cuba.web.productionMode application property. 
Exception Name: javax.servlet.ServletException 
Exception Message: com.vaadin.server.ServiceException: java.lang.NullPointerException 
Exception stack trace: 
    javax.servlet.ServletException: com.vaadin.server.ServiceException: java.lang.NullPointerException
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:363)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:312)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:203)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:107)
	...
Caused by: com.vaadin.server.ServiceException: java.lang.NullPointerException
	at com.vaadin.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1487)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1447)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:361)
	... 30 more
Caused by: java.lang.NullPointerException
	at com.haulmont.cuba.web.AppUI.refresh(AppUI.java:310)
	at com.vaadin.ui.UI.doRefresh(UI.java:742)
	at com.vaadin.server.communication.UIInitHandler.reinitUI(UIInitHandler.java:273)
	at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:175)
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:74)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435)
	... 31 more
```

**Comment by jreznot** [comment]
Relates to https://github.com/vaadin/framework/issues/6306
