### ISSUE TITLE
Could not save Association when referenced entity is inherited with the JOINED strategy

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/cuba#1379]
Test project: 
[demo.zip](https://github.com/cuba-platform/cuba/files/2468587/demo.zip)
Source issue: 
https://www.cuba-platform.ru/discuss/t/ispolzovanie-kompozitnyh-atributov-v-sushhnostyah-s-ierarhiej/2214

### Environment

- Platform version: 6.10.0 (not tested on 6.9)

### Description of the bug

- Minimal reproducible example
1. Create a new record for the EntityA.
2. Create a new record for the EntityB.
3. Create new record for the EntityD, open EntityA lookup screen from the pickerField and select the EntityA created in the step 1. => OK
4. 3. Create new record for the EntityD, open EntityA lookup screen from the pickerField and select the EntityA created in the step 2. 

Actual result:
```
java.lang.IllegalStateException: Cannot get unfetched attribute [nameB] from detached object com.company.demo.entity.EntityB-5e9dee54-3d47-3d99-3c33-4859d5117312 [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:98)
	at com.haulmont.cuba.core.sys.persistence.CubaEntityFetchGroup.onUnfetchedAttribute(CubaEntityFetchGroup.java:74)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:2846)
	at com.haulmont.chile.core.model.impl.AbstractInstance._persistence_checkFetched(AbstractInstance.java)
	at com.company.demo.entity.EntityB._persistence_get_nameB(EntityB.java)
	at com.company.demo.entity.EntityB.getNameB(EntityB.java:32)
	at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.chile.core.model.utils.MethodsCache.invokeGetter(MethodsCache.java:71)
	at com.haulmont.chile.core.model.impl.AbstractInstance.getValue(AbstractInstance.java:102)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.getValue(BaseGenericIdEntity.java:139)
	at com.haulmont.chile.core.model.utils.InstanceUtils.getInstanceName(InstanceUtils.java:235)
	at com.haulmont.cuba.web.toolkit.ui.converters.StringToEntityConverter.convertToPresentation(StringToEntityConverter.java:45)
	at com.haulmont.cuba.web.gui.components.WebPickerField$1.convertToPresentation(WebPickerField.java:90)
	at com.haulmont.cuba.web.gui.components.WebPickerField$1.convertToPresentation(WebPickerField.java:75)
	at com.haulmont.cuba.web.toolkit.ui.CubaPickerField.getStringRepresentation(CubaPickerField.java:223)
	at com.haulmont.cuba.web.toolkit.ui.CubaPickerField.updateTextRepresentation(CubaPickerField.java:215)
	at com.haulmont.cuba.web.toolkit.ui.CubaPickerField.lambda$initTextField$d8f8193f$1(CubaPickerField.java:124)
	at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1037)
	at com.vaadin.ui.AbstractField.fireValueChange(AbstractField.java:1199)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:600)
	at com.vaadin.ui.AbstractField.setValueIgnoreReadOnly(AbstractField.java:479)
	at com.haulmont.cuba.web.gui.components.WebAbstractField.setValue(WebAbstractField.java:244)
	at com.haulmont.cuba.web.gui.components.WebPickerField.setValue(WebPickerField.java:143)
	at com.haulmont.cuba.gui.components.PickerField$LookupAction.handleLookupWindowSelection(PickerField.java:413)
	at com.haulmont.cuba.gui.components.SelectAction.actionPerform(SelectAction.java:55)
	at com.haulmont.cuba.web.gui.WebWindow$Lookup.lambda$setLookupComponent$0(WebWindow.java:1851)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable$5.actionPerform(WebAbstractTable.java:889)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.handleClickAction(WebAbstractTable.java:871)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.lambda$initComponent$90fa93c2$1(WebAbstractTable.java:749)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1037)
	at com.vaadin.ui.Table.handleClickEvent(Table.java:3175)
	at com.vaadin.ui.Table.changeVariables(Table.java:2952)
	at com.haulmont.cuba.web.toolkit.ui.CubaTable.changeVariables(CubaTable.java:252)
	at com.haulmont.cuba.web.toolkit.ui.CubaGroupTable.changeVariables(CubaGroupTable.java:169)
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:623)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:470)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:413)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:361)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:312)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:203)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

Expected result:
When referenced, the master EntityA is loaded separately, without EntityB. It should be loaded with the _minimal view, as set in views.xml:
```
<view class="com.company.demo.entity.EntityD"
      extends="_local"
      name="entityD-view">
    <property name="refA"
              view="_minimal"/>
</view>
```

**Comment by andreysubbotin** [comment]
Related issue: #2155
