### ISSUE TITLE
UnsupportedOperationException when open EntityLog

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#1404]
platform 7.0

1) Open Administration - Entity Log

**AR**
```
java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableMap.put(ImmutableMap.java:529)
	at com.haulmont.cuba.gui.WindowParams.set(WindowParams.java:151)
	at com.haulmont.cuba.gui.app.core.entitylog.EntityLogBrowser.init(EntityLogBrowser.java:154)
	at com.haulmont.cuba.gui.components.AbstractWindow.init(AbstractWindow.java:93)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:133)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:54)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:245)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:157)
	at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:192)
	at com.haulmont.cuba.web.sys.MenuBuilder$MenuCommandExecutor.accept(MenuBuilder.java:249)
	at com.haulmont.cuba.web.sys.MenuBuilder$MenuCommandExecutor.accept(MenuBuilder.java:237)
	at com.haulmont.cuba.web.gui.components.mainwindow.WebAppMenu$MenuItemImpl.menuSelected(WebAppMenu.java:433)
```

**Comment by myatlevEvg** [comment]
Check #1279 on 7.0 platform when this issue will be fixed
