### ISSUE TITLE
NPE occured if the screen controller has injection

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1406]
#### Environment

- Platform version: 7.0
#### Description of the bug 

See the [issue](https://app.zenhub.com/workspace/o/cuba-platform/cuba/issues/1393)

1. Apply patch to refapp
2. Open Demo screen
```
java.lang.NullPointerException
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.createMessageBundle(UiControllerDependencyInjector.java:644)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.getInjectedInstance(UiControllerDependencyInjector.java:608)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.doInjection(UiControllerDependencyInjector.java:495)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.injectValues(UiControllerDependencyInjector.java:288)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.inject(UiControllerDependencyInjector.java:104)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:235)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:157)
	at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:192)
```

**Comment by jreznot** [comment]
Works as expected 

Use patch: [https://app.zenhub.com/files/54624511/80902716-9797-4b57-96d5-73a84e033a38/download](https://app.zenhub.com/files/54624511/80902716-9797-4b57-96d5-73a84e033a38/download)
