### ISSUE TITLE
Concurrent problem with desktop LookupField.NewOptionHandler

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#142]
На лукап фиелде висит newOptionHandler, который при определенном условии показывает модально сообщение об ошибке и стирает введенное значение. В брейкпоинте логгируется выражение Long.toString(System.currentTimeMillis()) и Thread.currentThread().getStackTrace().

Похоже, что с разницей в 150 миллисекунд от контрола приходят 2 разных события - focusLost и keyReleased. Это приводит к тому, что окно с сообщением показывается 2 раза, причем второй раз - немодально.

1) Breakpoint reached at com.haulmont.taxi.client.ui.booking.common.panels.reference.JobReferencePanel$NewReferenceInstanceProcessor.processNewInstance(JobReferencePanel.java:505)
1438872391792
```
[java.lang.Thread.getStackTrace(Thread.java:1589),
com.haulmont.taxi.client.ui.booking.common.panels.reference.JobReferencePanel$NewReferenceInstanceProcessor.processNewInstance(JobReferencePanel.java:505),
com.haulmont.taxi.client.ui.booking.common.panels.reference.JobReferencePanel$NewReferenceInstanceProcessor.searchOnServer(JobReferencePanel.java:491),
com.haulmont.taxi.client.ui.booking.common.panels.reference.JobReferencePanel$NewReferenceInstanceProcessor.processNewValue(JobReferencePanel.java:472),
com.haulmont.taxi.client.ui.booking.common.panels.reference.JobReferencePanel$ReferenceInstanceNewOptionHandler.addNewOption(JobReferencePanel.java:549),
com.haulmont.cuba.desktop.gui.components.DesktopLookupField$3.actionPerformed(DesktopLookupField.java:142),
javax.swing.JComboBox.fireActionEvent(JComboBox.java:1260),
javax.swing.JComboBox.actionPerformed(JComboBox.java:1317),
ca.odell.glazedlists.swing.AutoCompleteSupport$AutoCompleteKeyHandler.keyReleased(AutoCompleteSupport.java:1969),
java.awt.Component.processKeyEvent(Component.java:6477),
javax.swing.JComponent.processKeyEvent(JComponent.java:2829),
java.awt.Component.processEvent(Component.java:6293),
java.awt.Container.processEvent(Container.java:2229),
java.awt.Component.dispatchEventImpl(Component.java:4872),
java.awt.Container.dispatchEventImpl(Container.java:2287),
java.awt.Component.dispatchEvent(Component.java:4698),
java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1887),
java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:762),
java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027),
java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899),
java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727),
java.awt.Component.dispatchEventImpl(Component.java:4742),
java.awt.Container.dispatchEventImpl(Container.java:2287),
java.awt.Window.dispatchEventImpl(Window.java:2719),
java.awt.Component.dispatchEvent(Component.java:4698),
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747),
java.awt.EventQueue.access$300(EventQueue.java:103),
java.awt.EventQueue$3.run(EventQueue.java:706),
java.awt.EventQueue$3.run(EventQueue.java:704),
java.security.AccessController.doPrivileged(Native Method),
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76),
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87),
java.awt.EventQueue$4.run(EventQueue.java:720),
java.awt.EventQueue$4.run(EventQueue.java:718),
java.security.AccessController.doPrivileged(Native Method),
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76),
java.awt.EventQueue.dispatchEvent(EventQueue.java:717),
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242),
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161),
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150),
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146),
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138),
java.awt.EventDispatchThread.run(EventDispatchThread.java:91)])]
```
2) Breakpoint reached at com.haulmont.taxi.client.ui.booking.common.panels.reference.JobReferencePanel$NewReferenceInstanceProcessor.processNewInstance(JobReferencePanel.java:505)
1438872391941
```
[java.lang.Thread.getStackTrace(Thread.java:1589),
com.haulmont.taxi.client.ui.booking.common.panels.reference.JobReferencePanel$NewReferenceInstanceProcessor.processNewInstance(JobReferencePanel.java:505),
com.haulmont.taxi.client.ui.booking.common.panels.reference.JobReferencePanel$NewReferenceInstanceProcessor.searchOnServer(JobReferencePanel.java:491),
com.haulmont.taxi.client.ui.booking.common.panels.reference.JobReferencePanel$NewReferenceInstanceProcessor.processNewValue(JobReferencePanel.java:472),
com.haulmont.taxi.client.ui.booking.common.panels.reference.JobReferencePanel$ReferenceInstanceNewOptionHandler.addNewOption(JobReferencePanel.java:549),
com.haulmont.cuba.desktop.gui.components.DesktopLookupField$3.actionPerformed(DesktopLookupField.java:142),
javax.swing.JComboBox.fireActionEvent(JComboBox.java:1260),
javax.swing.JComboBox.actionPerformed(JComboBox.java:1317),
javax.swing.plaf.basic.BasicComboBoxUI$Handler.focusLost(BasicComboBoxUI.java:1836),
java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:230),
java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:229),
java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:229),
java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:229),
java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:229),
java.awt.Component.processFocusEvent(Component.java:6408),
java.awt.Component.processEvent(Component.java:6272),
java.awt.Container.processEvent(Container.java:2229),
java.awt.Component.dispatchEventImpl(Component.java:4872),
java.awt.Container.dispatchEventImpl(Container.java:2287),
java.awt.Component.dispatchEvent(Component.java:4698),
java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1887),
java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:947),
java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:621),
java.awt.Component.dispatchEventImpl(Component.java:4742),
java.awt.Container.dispatchEventImpl(Container.java:2287),
java.awt.Component.dispatchEvent(Component.java:4698),
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747),
java.awt.EventQueue.access$300(EventQueue.java:103),
java.awt.EventQueue$3.run(EventQueue.java:706),
java.awt.EventQueue$3.run(EventQueue.java:704),
java.security.AccessController.doPrivileged(Native Method),
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76),
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87),
java.awt.EventQueue$4.run(EventQueue.java:720),
java.awt.EventQueue$4.run(EventQueue.java:718),
java.security.AccessController.doPrivileged(Native Method),
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76),
java.awt.EventQueue.dispatchEvent(EventQueue.java:717),
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242),
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161),
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150),
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146),
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138),
java.awt.EventDispatchThread.run(EventDispatchThread.java:91)]
```

---
Original issue: https://youtrack.haulmont.com/issue/PL-5787

**Comment by jreznot** [comment]
Obsolete
