### ISSUE TITLE
Exception in log after long request has been completed

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#144]
```
2015-08-24 13:14:03,270 WARN  [com.haulmont.cuba.web.sys.CubaApplicationServlet] [app] Too long request processing [1977203 ms]: ip=127.0.0.1, url=/app/HEARTBEAT/
2015-08-24 13:14:03,325 ERROR [com.haulmont.cuba.web.log.AppLog] [app] [alexander.budarov] Exception: 
java.lang.NullPointerException
	at com.vaadin.ui.ConnectorTracker.removeUnregisteredConnectors(ConnectorTracker.java:340)
	at com.vaadin.ui.ConnectorTracker.cleanConnectorMap(ConnectorTracker.java:284)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:305)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:151)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:99)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1406)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:155)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

2015-08-24 13:14:03,326 WARN  [com.haulmont.cuba.web.sys.CubaApplicationServlet] [app] Too long request processing [2113772 ms]: ip=127.0.0.1, url=/app/UIDL/
```

Выполнение jmx-операции выполнялось больше получаса, видимо за это время протухла http-сессия.

---
Original issue: https://youtrack.haulmont.com/issue/PL-5854

**Comment by jreznot** [comment]
Obsolete
