### ISSUE TITLE
UnsupportedOperationException is invoked when you try to create Car entity from EI

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#1446]
### Environment
- Platform version: 7.0.0
- Client type: Web
### Description of the bug or enhancement
Steps to reproduce:
1. Open _Entity Inspector_
2. Select _Car (ref_Car)_
3. Try to create new instance
  
**AR**
```
java.lang.UnsupportedOperationException: Datasource must support paging
	at com.haulmont.cuba.web.gui.components.WebRowsCount.createDatasourceAdapter(WebRowsCount.java:185)
	at com.haulmont.cuba.web.gui.components.WebRowsCount.setDatasource(WebRowsCount.java:115)
	at com.haulmont.cuba.gui.app.core.entityinspector.EntityInspectorEditor.addTable(EntityInspectorEditor.java:814)
	at com.haulmont.cuba.gui.app.core.entityinspector.EntityInspectorEditor.createDataComponents(EntityInspectorEditor.java:381)
	at com.haulmont.cuba.gui.app.core.entityinspector.EntityInspectorEditor.init(EntityInspectorEditor.java:192)
	at com.haulmont.cuba.gui.components.AbstractWindow.init(AbstractWindow.java:93)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:132)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:54)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:227)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:161)
	at com.haulmont.cuba.web.sys.WebScreens.openWindow(WebScreens.java:876)
	at com.haulmont.cuba.gui.screen.compatibility.LegacyFrame.openWindow(LegacyFrame.java:88)
	at com.haulmont.cuba.gui.app.core.entityinspector.EntityInspectorBrowse$CreateAction.actionPerform(EntityInspectorBrowse.java:472)
```

**Comment by jreznot** [comment]
Duplicates https://github.com/cuba-platform/cuba/issues/1497
