### ISSUE TITLE
UnsupportedOperationException if either Future or Past annotations are defined for an entity attribute with TemporalType.DATE

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1474]
### Description of the bug or enhancement

**Actual behavior**

```
java.lang.UnsupportedOperationException
	at java.sql.Date.toInstant(Date.java:304)
	at org.hibernate.validator.internal.constraintvalidators.bv.time.future.FutureValidatorForDate.getInstant(FutureValidatorForDate.java:23)
	at org.hibernate.validator.internal.constraintvalidators.bv.time.future.FutureValidatorForDate.getInstant(FutureValidatorForDate.java:19)
	at org.hibernate.validator.internal.constraintvalidators.bv.time.AbstractInstantBasedTimeValidator.isValid(AbstractInstantBasedTimeValidator.java:55)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:171)
	at org.hibernate.validator.internal.engine.constraintvalidation.SimpleConstraintTree.validateConstraints(SimpleConstraintTree.java:68)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:73)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.doValidateConstraint(MetaConstraint.java:127)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:120)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:533)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForSingleDefaultGroupElement(ValidatorImpl.java:496)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:465)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:430)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateValueInContext(ValidatorImpl.java:781)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateValue(ValidatorImpl.java:210)
	at com.haulmont.cuba.gui.components.validators.BeanValidator.validate(BeanValidator.java:100)
	at com.haulmont.cuba.gui.components.Field$Validator.accept(Field.java:72)
	at com.haulmont.cuba.web.gui.components.WebDateField.triggerValidators(WebDateField.java:664)
	at com.haulmont.cuba.web.gui.components.WebDateField.validate(WebDateField.java:657)
	at com.haulmont.cuba.gui.ComponentsHelper.validateUiComponents(ComponentsHelper.java:617)
	at com.haulmont.cuba.gui.screen.Screen.validateUiComponents(Screen.java:486)
	at com.haulmont.cuba.gui.screen.Screen.validateScreen(Screen.java:481)
	at com.haulmont.cuba.gui.screen.StandardEditor.validateScreen(StandardEditor.java:315)
	at com.haulmont.cuba.gui.screen.StandardEditor.commitChanges(StandardEditor.java:286)
	at com.haulmont.cuba.gui.screen.Screen.closeWithCommit(Screen.java:378)
	at com.haulmont.cuba.gui.screen.StandardEditor.commitAndClose(StandardEditor.java:346)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
```

**Comment by pribavkindenis** [comment]
The issue is also reproduced if FutureOrPresent or PastOrPresent annotations are defined for an entity attribute. #1538
