### ISSUE TITLE
NPE while removing an item from GroupTable

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1478]
### Description of the bug or enhancement

**Minimal reproducible example**

1. Open the **Users** screen
2. **Group** by any column
3. Try to remove a non-default user

**Actual behavior**

```
java.lang.NullPointerException
	at com.haulmont.cuba.gui.app.security.user.browse.UserBrowser.lambda$initTimeZoneColumn$2(UserBrowser.java:145)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable$2.generateCell(WebAbstractTable.java:2104)
	at com.vaadin.v7.ui.Table.parseItemIdToCells(Table.java:2333)
	at com.vaadin.v7.ui.Table.getVisibleCellsNoCache(Table.java:2203)
	at com.vaadin.v7.ui.Table.refreshRenderedCells(Table.java:1746)
	at com.vaadin.v7.ui.Table.refreshRowCache(Table.java:2654)
	at com.vaadin.v7.ui.Table.containerItemSetChange(Table.java:4556)
	at com.haulmont.cuba.web.gui.components.table.TableDataContainer.fireItemSetChanged(TableDataContainer.java:164)
	at com.haulmont.cuba.web.gui.components.table.TableDataContainer.datasourceItemSetChanged(TableDataContainer.java:272)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.data.table.DatasourceTableItems.datasourceCollectionChanged(DatasourceTableItems.java:63)
	at com.haulmont.bali.events.EventRouter.fireEvent(EventRouter.java:45)
	at com.haulmont.cuba.gui.data.impl.AbstractCollectionDatasource.fireCollectionChanged(AbstractCollectionDatasource.java:373)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.removeItem(CollectionDatasourceImpl.java:404)
	at com.haulmont.cuba.gui.components.actions.RemoveAction.doRemove(RemoveAction.java:335)
	at com.haulmont.cuba.gui.components.actions.RemoveAction.remove(RemoveAction.java:251)
	at com.haulmont.cuba.gui.components.actions.RemoveAction.lambda$confirmAndRemove$0(RemoveAction.java:229)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.actions.BaseAction.actionPerform(BaseAction.java:221)
	at com.haulmont.cuba.web.sys.WebDialogs$OptionDialogImpl.lambda$show$0(WebDialogs.java:306)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

It seems that a column generator is called for the removed entity, so the null value is passed to a column generator.

**Comment by jreznot** [comment]
Relates to #1479
