### ISSUE TITLE
Unable to open EntityInspector editor

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1497]
### Description of the bug or enhancement

1. Open entity inspector for Users
2. Click on Create / Edit

- Actual result:

Entity Inspector editor throws exception:
```
java.lang.UnsupportedOperationException: Datasource must support paging
	at com.haulmont.cuba.web.gui.components.WebRowsCount.createDatasourceAdapter(WebRowsCount.java:185)
	at com.haulmont.cuba.web.gui.components.WebRowsCount.setDatasource(WebRowsCount.java:115)
	at com.haulmont.cuba.gui.app.core.entityinspector.EntityInspectorEditor.addTable(EntityInspectorEditor.java:814)
	at com.haulmont.cuba.gui.app.core.entityinspector.EntityInspectorEditor.createDataComponents(EntityInspectorEditor.java:381)
	at com.haulmont.cuba.gui.app.core.entityinspector.EntityInspectorEditor.init(EntityInspectorEditor.java:192)
	at com.haulmont.cuba.gui.components.AbstractWindow.init(AbstractWindow.java:94)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:124)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:53)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:223)
	at com.haulmont.cuba.web.sys.WebScreens.openWindow(WebScreens.java:963)
	at com.haulmont.cuba.gui.components.HasWindowManager.openWindow(HasWindowManager.jav
```

**Comment by jreznot** [comment]
For QA: check basic CRUD operations with User
