### ISSUE TITLE
Unable to lookup from legacy screen

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#1522]
## Environment

- Platform version: 7.0-SNAPSHOT

### Description of the bug or enhancement

- Create an entity having `user` attribute - an association with security User
- Create a screen with PickerField for this attribute and lookup action
- Run the app, create an entity, try to lookup a user. On "Select" click, error happens:
```
java.lang.ClassCastException: com.haulmont.cuba.gui.LookupScreens$$Lambda$520/991173896 cannot be cast to com.haulmont.cuba.gui.components.compatibility.SelectHandlerAdapter
	at com.haulmont.cuba.gui.components.Window$Lookup.getLookupHandler(Window.java:464)
	at com.haulmont.cuba.gui.components.SelectAction.actionPerform(SelectAction.java:51)
	at com.haulmont.cuba.gui.components.AbstractLookup.selectItemsOnClick(AbstractLookup.java:129)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.lambda$setLookupSelectHandler$4(WebAbstractTable.java:1164)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.actions.BaseAction.actionPerform(BaseAction.java:221)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.handleClickAction(WebAbstractTable.java:1147)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.lambda$initComponent$db766529$1(WebAbstractTable.java:959)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041)
	at com.vaadin.v7.ui.Table.handleClickEvent(Table.java:3126)
```

**Comment by jreznot** [comment]
Fixed in https://github.com/cuba-platform/cuba/issues/1518
