### ISSUE TITLE
NPE when trying to delete the report

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1532]
#### Environment

- Platform version: 7.0

#### Description of the bug or enhancement

1. Create any report
2. Try to delete it

```
java.lang.NullPointerException
	at com.haulmont.cuba.web.gui.components.table.AbbreviatedColumnGenerator.generateCell(AbbreviatedColumnGenerator.java:43)
	at com.vaadin.v7.ui.Table.parseItemIdToCells(Table.java:2333)
	at com.vaadin.v7.ui.Table.getVisibleCellsNoCache(Table.java:2203)
	at com.vaadin.v7.ui.Table.refreshRenderedCells(Table.java:1746)
	at com.haulmont.cuba.web.widgets.CubaGroupTable.refreshRenderedCells(CubaGroupTable.java:717)
	at com.vaadin.v7.ui.Table.refreshRowCache(Table.java:2654)
	at com.vaadin.v7.ui.Table.containerItemSetChange(Table.java:4556)
	at com.haulmont.cuba.web.gui.components.table.TableDataContainer.fireItemSetChanged(TableDataContainer.java:164)
	at com.haulmont.cuba.web.gui.components.table.TableDataContainer.datasourceItemSetChanged(TableDataContainer.java:272)
	at com.haulmont.cuba.web.gui.components.table.GroupTableDataContainer.datasourceItemSetChanged(GroupTableDataContainer.java:321)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.data.table.DatasourceTableItems.datasourceCollectionChanged(DatasourceTableItems.java:67)
	at com.haulmont.bali.events.EventRouter.fireEvent(EventRouter.java:45)
	at com.haulmont.cuba.gui.data.impl.AbstractCollectionDatasource.fireCollectionChanged(AbstractCollectionDatasource.java:373)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.removeItem(CollectionDatasourceImpl.java:404)
	at com.haulmont.cuba.gui.components.actions.RemoveAction.doRemove(RemoveAction.java:335)
	at com.haulmont.cuba.gui.components.actions.RemoveAction.remove(RemoveAction.java:251)
	at com.haulmont.cuba.gui.components.actions.RemoveAction.lambda$confirmAndRemove$0(RemoveAction.java:229)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.actions.BaseAction.actionPerform(BaseAction.java:221)
	at com.haulmont.cuba.web.sys.WebDialogs$OptionDialogImpl.lambda$show$0(WebDialogs.java:304)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by jreznot** [comment]
Fixed in #1478
