### ISSUE TITLE
LookupField setOptionCaptionProvider leads to NPE when receives null

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#1543]
### Environment
- Platform version: 7.0.0
- Client type: Web

1. Create LookupField
2. Try to pass `null` to `setOptionCaptionProvider` programmatically

StackTrace
```
java.lang.NullPointerException
	at com.haulmont.cuba.web.gui.components.WebLookupField.setOptionCaptionProvider(WebLookupField.java:284)
	at com.haulmont.cuba.gui.components.listeditor.ListEditorPopupWindow.createComponentForEntity(ListEditorPopupWindow.java:301)
	at com.haulmont.cuba.gui.components.listeditor.ListEditorPopupWindow.initAddComponentLayout(ListEditorPopupWindow.java:174)
	at com.haulmont.cuba.gui.components.listeditor.ListEditorPopupWindow.init(ListEditorPopupWindow.java:132)
```

**Comment by natfirst** [comment]
NPE with another text is occured
```
java.lang.NullPointerException: Item caption generators must not be null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.vaadin.ui.AbstractListing.setItemCaptionGenerator(AbstractListing.java:199)
	at com.vaadin.ui.ComboBox.setItemCaptionGenerator(ComboBox.java:688)
	at com.haulmont.cuba.web.gui.components.WebLookupField.setOptionCaptionProvider(WebLookupField.java:284)
	at com.company.forumcheck.web.Screen.onInit(Screen.java:20)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:125)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:53)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:220)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:155)
	at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:199)
	at com.haulmont.cuba.web.sys.MenuBuilder$MenuCommandExecutor.accept(MenuBuilder.java:256)
	at com.haulmont.cuba.web.sys.MenuBuilder$MenuCommandExecutor.accept(MenuBuilder.java:241)
	at com.haulmont.cuba.web.gui.components.mainwindow.WebAppMenu$MenuItemImpl.menuSelected(WebAppMenu.java:433)
	at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:225)
```
