### ISSUE TITLE
Aggregation doesn't work on treeTable

### ISSUE THREAD

**Issue by alexander-shustanov** [cuba-platform/cuba#1555]
### Environment
- Platform version: 7.0-SNAPSHOT

### Steps

1. Download and launch attached project.
2. Open screen Application -> Person
3. Application fails.

Exception from logs:
```
Caused by: java.lang.NullPointerException: null
        at com.haulmont.cuba.web.widgets.CubaTreeTable.paintAggregationRow(CubaTreeTable.java:667) ~[cuba-web-widgets-7.0-SNAPSHOT.jar:na]
        at com.haulmont.cuba.web.widgets.CubaTreeTable.paintAdditionalData(CubaTreeTable.java:636) ~[cuba-web-widgets-7.0-SNAPSHOT.jar:na]
        at com.vaadin.v7.ui.Table.doPaintContent(Table.java:3287) ~[vaadin-compatibility-server-8.5.2-5-cuba.jar:8.5.2-5-cuba]
        at com.vaadin.v7.ui.Table.paintContent(Table.java:3259) ~[vaadin-compatibility-server-8.5.2-5-cuba.jar:8.5.2-5-cuba]
        at com.vaadin.v7.ui.TreeTable.paintContent(TreeTable.java:527) ~[vaadin-compatibility-server-8.5.2-5-cuba.jar:8.5.2-5-cuba]
        at com.haulmont.cuba.web.widgets.CubaTreeTable.paintContent(CubaTreeTable.java:975) ~[cuba-web-widgets-7.0-SNAPSHOT.jar:na]
        at com.vaadin.server.LegacyPaint.paint(LegacyPaint.java:65) ~[vaadin-server-8.5.2-5-cuba.jar:8.5.2-5-cuba]
        at com.vaadin.server.communication.LegacyUidlWriter.write(LegacyUidlWriter.java:82) ~[vaadin-server-8.5.2-5-cuba.jar:8.5.2-5-cuba]
        at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:146) ~[vaadin-server-8.5.2-5-cuba.jar:8.5.2-5-cuba]
        at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:164) ~[vaadin-server-8.5.2-5-cuba.jar:8.5.2-5-cuba]
        ... 48 common frames omitted
```
[untitled2.zip](https://github.com/cuba-platform/cuba/files/2592658/untitled2.zip)

**Comment by glebfox** [comment]
Fixed in ba9376a
