### ISSUE TITLE
NPE in custom JS component

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/cuba#1558]
### Environment

- Platform version: 7.0.BETA 
- Client type: Web

### Description of the bug or enhancement

Nullpointer exception on custom JS component initialization.
`callbackHelper` is null in ` com.vaadin.ui.AbstractJavaScriptComponent` class

### Error ###
```
java.lang.NullPointerException
	at com.vaadin.ui.AbstractJavaScriptComponent.registerRpc(AbstractJavaScriptComponent.java:178)
	at com.vaadin.server.AbstractClientConnector.registerRpc(AbstractClientConnector.java:224)
	at com.vaadin.ui.AbstractComponent.<init>(AbstractComponent.java:149)
	at com.vaadin.ui.AbstractJavaScriptComponent.<init>(AbstractJavaScriptComponent.java:170)
	at com.haulmont.addon.admintools.web.xterm.js.XtermJsComponent.<init>(XtermJsComponent.java:18)
	at com.haulmont.addon.admintools.web.xterm.component.WebXtermJs.<init>(WebXtermJs.java:10)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.haulmont.cuba.web.gui.WebUiComponents.create(WebUiComponents.java:163)
	at com.haulmont.cuba.web.gui.WebUiComponents.create(WebUiComponents.java:187)
	at com.haulmont.addon.admintools.gui.xterm.XtermJsLoader.createComponent(XtermJsLoader.java:9)
	at com.haulmont.cuba.gui.xml.layout.LayoutLoader.createComponent(LayoutLoader.java:146)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.createSubComponents(ContainerLoader.java:70)
	at com.haulmont.cuba.gui.xml.layout.loaders.VBoxLayoutLoader.createComponent(VBoxLayoutLoader.java:26)
	at com.haulmont.cuba.gui.xml.layout.LayoutLoader.createComponent(LayoutLoader.java:146)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.createSubComponents(ContainerLoader.java:70)
	at com.haulmont.cuba.gui.xml.layout.loaders.WindowLoader.createContent(WindowLoader.java:66)
	at com.haulmont.cuba.gui.xml.layout.LayoutLoader.createWindowContent(LayoutLoader.java:172)
	at com.haulmont.cuba.web.sys.WebScreens.loadWindowFromXml(WebScreens.java:312)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:203)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:155)
	at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:199)
	at com.haulmont.cuba.web.sys.MenuBuilder$MenuCommandExecutor.accept(MenuBuilder.java:256)
	at com.haulmont.cuba.web.sys.MenuBuilder$MenuCommandExecutor.accept(MenuBuilder.java:241)
	at com.haulmont.cuba.web.gui.components.mainwindow.WebAppMenu$MenuItemImpl.menuSelected(WebAppMenu.java:433)
	at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:225)
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:611)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:457)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:400)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:317)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:208)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jreznot** [comment]
Fixed in #1544
