### ISSUE TITLE
Unknown component exception

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/cuba#1569]
### Environment

- Platform version: 7.0-SNAPSHOT

### Steps to reproduce:
1. checkout `releases/cuba_7.0` branch and install locally `rich-search` component (https://github.com/cuba-platform/rich-search-addon)
2. checkout `releases/cuba_7.0` branch and run `rich-search-demo` application (https://github.com/cuba-platform/rich-search-addon-demo)
3. login in application

### Error:
```
2018-11-21 12:26:01.770 WARN  [http-nio-8080-exec-19/app/admin] com.haulmont.cuba.web.app.loginwindow.AppLoginWindow - Unable to login
com.haulmont.cuba.gui.GuiDevelopmentException: Unknown component: richSearch
	at com.haulmont.cuba.gui.xml.layout.LayoutLoader.getLoader(LayoutLoader.java:83) ~[cuba-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.gui.xml.layout.LayoutLoader.createComponent(LayoutLoader.java:144) ~[cuba-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.createSubComponents(ContainerLoader.java:70) ~[cuba-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.gui.xml.layout.loaders.HBoxLayoutLoader.createComponent(HBoxLayoutLoader.java:26) ~[cuba-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.gui.xml.layout.LayoutLoader.createComponent(LayoutLoader.java:146) ~[cuba-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.createSubComponents(ContainerLoader.java:70) ~[cuba-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.gui.xml.layout.loaders.WindowLoader.createContent(WindowLoader.java:66) ~[cuba-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.gui.xml.layout.LayoutLoader.createWindowContent(LayoutLoader.java:172) ~[cuba-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.web.sys.WebScreens.loadWindowFromXml(WebScreens.java:312) ~[cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
```

**Comment by jreznot** [comment]
Please check app-component.xml. There is no `cuba.web.componentsConfig` application property provided from the app component.
