### ISSUE TITLE
Throw IllegalStateException if DataSupplier is injected into a new screen

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/cuba#1633]
### Environment

Platform version: 7.0-SNAPSHOT

### Description of the bug or enhancement

DataSupplier should not be injected in new screens

ClassCastException on controller dependency injection: StandardEditor cannot be cast to LegacyFrame

- Minimal reproducible example
1. Migrate [Loading and Displaying Images](https://doc.cuba-platform.com/manual-latest/images_recipe.html) example to 7.0:

EmployeeEdit.java
```
@UiController("sales_Employee.edit")
@UiDescriptor("employee-edit.xml")
@EditedEntityContainer("employeeDc")
@LoadDataBeforeShow
public class EmployeeEdit extends StandardEditor<Employee> {

    @Inject
    private DataSupplier dataSupplier;
```

2. Run the app and open Employee editor

- Expected behavior
As in the documentation

- Actual behavior
ClassCastException 
```
java.lang.ClassCastException: com.company.sales.web.employee.EmployeeEdit cannot be cast to com.haulmont.cuba.gui.screen.compatibility.LegacyFrame
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.getInjectedInstance(UiControllerDependencyInjector.java:585)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.doInjection(UiControllerDependencyInjector.java:503)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.injectValues(UiControllerDependencyInjector.java:292)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.inject(UiControllerDependencyInjector.java:104)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:211)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:155)
	at com.haulmont.cuba.gui.EditorScreens.createScreen(EditorScreens.java:303)
	at com.haulmont.cuba.gui.EditorScreens.buildEditor(EditorScreens.java:204)
	at com.haulmont.cuba.gui.EditorScreens$EditorBuilder.build(EditorScreens.java:627)
	at com.haulmont.cuba.gui.actions.list.CreateAction.actionPerform(CreateAction.java:120)
```

**Comment by oshiryaeva** [comment]
[sales.zip](https://github.com/cuba-platform/cuba/files/2638788/sales.zip)
There are unnecessary entities in the sample, but anyway it's faster than reproducing yourself
