### ISSUE TITLE
Calendar component should handle the NPE and return suitable message

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1663]
#### Environment

- Platform version: 7.0

#### Description of the bug or enhancement
1. Create an entity with the Start and End columns
```
@Table(name = "CALENDAR_CALENDAR_EVENT_ENTITY")
@Entity(name = "calendar_CalendarEventEntity")
public class CalendarEventEntity extends StandardEntity {
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "START")
    protected Date start;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "END")
    protected Date end;
...
}
```
2. Create browser and editor screens
3. Add the Calendar component to the screen
```
<calendar id="calendar" dataContainer="calendarEventEntitiesDc" endDateProperty="end"
                  startDateProperty="start"  navigationButtonsVisible="true"/>
```
4. Create an empty entity

*A.R.*
```
java.lang.NullPointerException
	at java.util.Calendar.setTime(Calendar.java:1770)
	at com.vaadin.v7.ui.Calendar.getMinuteOfDay(Calendar.java:484)
	at com.vaadin.v7.ui.Calendar.cacheMinMaxTimeOfDay(Calendar.java:465)
	at com.vaadin.v7.ui.Calendar.setupCalendarEvents(Calendar.java:430)
	at com.vaadin.v7.ui.Calendar.beforeClientResponse(Calendar.java:298)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:118)
```
*E.R.* User should see the proper exception

**Comment by Flaurite** [comment]
Also, don't forget to define `captionProperty` in the calendar in order to reproduce the issue.

**Comment by Mihail063** [comment]
If caption property and start or end properties are null it doesn't show the exception
