### ISSUE TITLE
Provide an ability to work with app as anonymous

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1665]
Relates to #280 

See forum:
[Anonymous access](https://www.cuba-platform.ru/discuss/t/kak-otdat-veb-straniczu-neavtorizovannomu-polzovatelyu/869#comment-2952)

### Issues to be addressed:

- [x] Avoid force UI push refreshing after login/logout for anonymous sessions
- [x] Store session in UI
- [x] Main screen with "Login" link

### Updates

To enable the feature set the `cuba.web.allowAnonymousAccess` application property to `true`.

`WebConfig#getAllowAnonymousAccess`

#### App tabs refreshing

Main changes are related to the logic of app tabs refreshing - logging in does not affect anonymous tabs now.

Behavior is different if other logged in tabs exist:

- notification about changed session is shown by default

![image2019-4-26_16-8-58.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/e7338c04-ba55-4962-aa5d-75022ac4ad86)

- force refresh is performed for all "expired" sessions

This behavior is managed by new `cuba.web.forceRefreshAuthenticatedTabs` app property located in `WebConfig` - `WebConfig#getForceRefreshAuthenticatedTabs`

#### Initial screen

Another configuration is "anonymous initial screen" - it defines which screen will be open for non-authenticated user when an application is opened.

It is managed by `cuba.web.initialScreenId` app property located in `WebConfig` - `WebConfig#getInitialScreenId`

The property is set to `login` - it means that default login screen will be opened for `anonymous` user by default.

If a screen that is used as initial screen is not permitted by security for anonymous user default login screen will be opened.

#### User actions button

Default logout button is replace by `User Actions` button. It has two states:

- go to login screen - when app is used in anonymous session
- open sub menu with actions:
    - open "Settings" screen
    - log out

![image2019-4-26_18-29-45.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/00419daa-c838-42eb-9f46-7554fda5f01d)

### Demo

Anonymous Access Sample - [GitHub](https://github.com/cuba-labs/anonymous-access-demo)

### QA

Checklist:

- [x] navigation feature regression testing (both for screen and history navigation)
- [x] app tabs behavior:
    - logging in doesn't affect anonymous sessions
    - authenticated tabs are logged out simultaneously
    - "changed session" notification and dialog refresh app tab correctly
- [x] updated history and screen navigation:
    - public screens can be navigated as anonymous
    - user is redirected to login screen when trying to navigate to screen not permitted by security
    - 404 page is shown when not registered route is navigated both for authenticated and anonymous sessions
    - `UrlParamsChangedEvent` is fired both for authenticated and anonymous sessions
- [x] new configuration properties:
    - `cuba.web.initialScreenId`
    - `cuba.web.forceRefreshLoggedTabs`
- [x] new `UserActionsButton` component:
    - shows `Proceed to login` button when user is not authenticated
    - shows user actions (Settings, Logout) button for authenticated user
- [x] Substitution mechanism

See for additional info on "Anonymous Access" page in Confluence.

**Comment by dtsaryov** [comment]
No default initial screen is configured now. It should help to avoid a problem with extended Login screen with custom id

**Comment by knstvk** [comment]
Remove Settings screen from menu.

**Comment by glebfox** [comment]
The `UrlParamsChangedEvent` should be fired before `AfterShowEvent`.

**Comment by dtsaryov** [comment]
New window and User Actions buttons are misaligned when the current session is anonymous:

![image](https://user-images.githubusercontent.com/6183810/62379624-5e93ba00-b558-11e9-89a9-538b8ca51965.png)

**Comment by natfirst** [comment]
1. Set the following properties
```
cuba.web.allowAnonymousAccess=true
cuba.web.initialScreenId = main
```
2. Create Promo screen as it described in "Anonymous Access" page in Confluence.
3. Start the app and open it
4. Redirect to Promo screen
5. Click `Go to app` button and return to the main screen 
6. Go back to promo using browser history button
7. Click Go Back browser button again. 
Blank screen will appear, url for main screen will be displayed in url field
8. Click Go Back or Forward browser button

*A.R.* Exception occurs
```
12:53:13.051 ERROR com.haulmont.cuba.web.log.AppLog        - Exception in com.haulmont.cuba.web.AppUI: 
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method popstate in com.vaadin.shared.ui.ui.UIServerRpc
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:157) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431) [vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396) [vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260) [vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82) [vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) [vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577) [vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425) [vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329) [cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
    at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215) [cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.19]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.19]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.19]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.19]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.19]
    at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
    at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
    at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93) [cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.19]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.19]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) [catalina.jar:9.0.19]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.19]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [catalina.jar:9.0.19]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.19]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.19]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [catalina.jar:9.0.19]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.19]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.19]
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-coyote.jar:9.0.19]
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.19]
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836) [tomcat-coyote.jar:9.0.19]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747) [tomcat-coyote.jar:9.0.19]
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.19]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.19]
    at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]
Caused by: java.lang.reflect.InvocationTargetException: null
    at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_221]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_221]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    ... 38 common frames omitted
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method uriChanged in com.haulmont.cuba.web.AppUI$$Lambda$237/1777581968 failed.
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:516) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    at com.vaadin.server.Page.fireEvent(Page.java:699) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    at com.vaadin.server.Page.updateLocation(Page.java:1126) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    at com.vaadin.ui.UI$1.popstate(UI.java:169) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    ... 42 common frames omitted
Caused by: java.lang.IllegalStateException: There is no root screen opened
    at com.haulmont.cuba.web.sys.WebScreens.getConfiguredWorkAreaOrNull(WebScreens.java:936) ~[cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
    at com.haulmont.cuba.web.sys.WebScreens.getCurrentBreadcrumbs(WebScreens.java:866) ~[cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
    at com.haulmont.cuba.web.sys.WebScreens$OpenedScreensImpl.getCurrentBreadcrumbs(WebScreens.java:2017) ~[cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
    at com.haulmont.cuba.web.sys.navigation.UrlChangeHandler.getActiveScreen(UrlChangeHandler.java:143) ~[cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
    at com.haulmont.cuba.web.sys.navigation.navigationhandler.ParamsNavigationHandler.doHandle(ParamsNavigationHandler.java:44) ~[cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
    at com.haulmont.cuba.web.sys.navigation.ScreenNavigator.handleScreenNavigation(ScreenNavigator.java:53) ~[cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
    at com.haulmont.cuba.web.sys.navigation.UrlChangeHandler.__handleUrlChange(UrlChangeHandler.java:132) ~[cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
    at com.haulmont.cuba.web.sys.navigation.UrlChangeHandler.handleUrlChange(UrlChangeHandler.java:114) ~[cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
    at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_221]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_221]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496) ~[vaadin-server-8.6.4-17-cuba.jar:8.6.4-17-cuba]
    ... 47 common frames omitted
```
