### ISSUE TITLE
StackOverflowError on closing the screen that contains DataGrid

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#1669]
```
java.lang.StackOverflowError
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.isDefaultDataGridSettingsChanged(WebAbstractDataGrid.java:2193)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.isCommonDataGridSettingsChanged(WebAbstractDataGrid.java:2156)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.isDefaultDataGridSettingsChanged(WebAbstractDataGrid.java:2202)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.isCommonDataGridSettingsChanged(WebAbstractDataGrid.java:2156)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.isDefaultDataGridSettingsChanged(WebAbstractDataGrid.java:2202)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.isCommonDataGridSettingsChanged(WebAbstractDataGrid.java:2156)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.isDefaultDataGridSettingsChanged(WebAbstractDataGrid.java:2202)
```

**Comment by jreznot** [comment]
Relates to #753
