### ISSUE TITLE
@Install handler does not work if name of controller method does not match interface method name 

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/cuba#1688]
### Environment

- Platform version: '7.0-SNAPSHOT'

### Description of the bug

- Minimal reproducible example
1. Create a dataGrid, for example:
```xml
    <data readOnly="true">
        <collection id="ordersDc" class="com.company.sales.entity.Order" view="order-with-customer">
            <loader id="ordersDl">
                <query>
                    <![CDATA[select e from sales_Order e]]>
                </query>
            </loader>
        </collection>
    </data>
    <layout expand="ordersDataGrid" spacing="true">
        <dataGrid id="ordersDataGrid" width="100%" dataContainer="ordersDc">
            <columns>
                <column id="date" property="date"/>
                <column id="amount" property="amount"/>
                <column id="customer" property="customer"/>
            </columns>
            <rowsCount/>
        </dataGrid>
    </layout>
```
2. In the screen controller, select **Install delegate** > dataGrid CellDescriptionProvider
3. You can modify the returned value in the generated method or leave null, no matter.
```java
@Install(to = "ordersDataGrid", subject = "cellDescriptionProvider")
protected String ordersDataGridCellDescriptionProvider(Order order, String string) {
    return "Hi";
}
```
4. Start the app and open the screen

- Expected behavior
"Hi" cell description 

- Actual behavior
UnsupportedOperationException
```java
java.lang.UnsupportedOperationException: InstalledProxyHandler does not support method public abstract java.lang.String com.haulmont.cuba.gui.components.DataGrid$CellDescriptionProvider.getDescription(com.haulmont.cuba.core.entity.Entity,java.lang.String)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector$InstalledProxyHandler.invoke(UiControllerDependencyInjector.java:907)
	at com.sun.proxy.$Proxy316.getDescription(Unknown Source)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.getGeneratedCellDescription(WebAbstractDataGrid.java:2813)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid$CellDescriptionGeneratorAdapter.apply(WebAbstractDataGrid.java:2803)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid$CellDescriptionGeneratorAdapter.apply(WebAbstractDataGrid.java:2793)
	at com.vaadin.ui.Grid$Column$1.generateData(Grid.java:887)
	at com.vaadin.data.provider.DataCommunicator.getDataObject(DataCommunicator.java:480)
	at com.vaadin.data.provider.DataCommunicator.pushData(DataCommunicator.java:460)
	at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:373)
	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:338)
```
![image](https://user-images.githubusercontent.com/11287637/49995281-20d02a00-ffa5-11e8-8849-82cc140bf7e3.png)

**Comment by jreznot** [comment]
CellDescriptionProvider id deprecated, marked as minor
