### ISSUE TITLE
StandardEditor and MasterDetailScreen don't support setting default values to DynamicAttribute components

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#1694]
### Environment
- Platform version: 7.0.0
- Client type: Web

### Description of the bug or enhancement

- Minimal reproducible example
Reproduce in the refapp:
1. Apply following patch: [patch.zip](https://github.com/cuba-platform/cuba/files/2685991/patch.zip)
2. Create dynamicAttribute to `ref_Car` entity;
3. Add visibility to "CarEditor" screen with component id: "form"
4. Save and apply dynamic attributes.
5. Open: _Application -> Screens v7 -> Cars v7_
6. Create new entity

- Expected behavior
Default value should be set
- Actual behavior
Nothing is set

### How to test
In the refapp.

1. Create category for `ref_Car` entity
2.  Create dynamic attribute with datatype and one with entity type.
3. In visibility tab select following screens:
      - CarEditor (v7)
      - CarMasterDetailScreen (v7)
4. Set default value for every attribute.
5. Apply changes.
6. Open: _Application -> Screens v7 -> Cars v7_ and create new item. The default value should be set.
7. Open: _Application -> Screens v7 -> Car Master-Detail Screen v7_ and create new item. The default value should be set.

In _Car Master-Detail Screen v7_ try to create a few entites with some value in dynamic atrtibute field and without value. Try to edit them and save.
Make sure that there are no exceptions while you create or edit entities.

**Comment by gorbunkov** [comment]
NPE when opening an editor for not-persistent entity (doesn't have loader)
```
java.lang.IllegalStateException: Loader of edited entity container not found
	at com.haulmont.cuba.gui.screen.StandardEditor.getEditedEntityLoader(StandardEditor.java:296)
	at com.haulmont.cuba.gui.screen.StandardEditor.setupEntityToEdit(StandardEditor.java:150)
	at com.haulmont.cuba.gui.screen.StandardEditor.beforeShow(StandardEditor.java:98)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:127)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:56)
	at com.haulmont.cuba.web.sys.WebScreens.show(WebScreens.java:400)
	at com.haulmont.cuba.gui.screen.Screen.show(Screen.java:308)
	at com.haulmont.addon.bproc.web.screens.modeler.properties.process.ProcessPropertiesFragment.onMessageDefinitionsTableCreateActionPerformed(ProcessPropertiesFragment.java:296)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.actions.BaseAction.actionPerform(BaseAction.java:221)
	at com.haulmont.cuba.gui.actions.list.CreateAction.actionPerform(CreateAction.java:108)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:62)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:317)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:208)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:412)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1385)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by myatlevEvg** [comment]
In the case when Dynamic Attribute has target component id on some screen then this component does not appear at the screen
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/3b8ddfd5-c8e6-48d3-876c-de56ceac43ac)
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/982d07f1-cf17-4f0c-8a45-41122fdfef99)
