### ISSUE TITLE
Dynamic attribute with collection type and default value leads to NPE when you commit it

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#1702]
### Environment
- Platform version: 6.10.0
- Client type: Web

### Description of the bug or enhancement
- Minimal reproducible example
1. Create category for `User` entity;
2. Create attribute with collection type. Add visibility to `sec$User.edit`. Set the default value for it.
3. Save and apply changes.
4. Create new user and don't set value to dynamic attribute.
5. Try to save it.
- Expected behavior
New user is created.
- Actual behavior
**The default value is not shown in the `ListEditor`** and NPE is occured.
Even we remove visibility for this attribute NPE is still thrown.
StackTrace:
```
java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:177)
	at com.haulmont.cuba.core.app.dynamicattributes.DynamicAttributesManager.storeCategoryAttributeValueWithCollectionType(DynamicAttributesManager.java:295)
	at com.haulmont.cuba.core.app.dynamicattributes.DynamicAttributesManager.doStoreDynamicAttributes(DynamicAttributesManager.java:272)
	at com.haulmont.cuba.core.app.dynamicattributes.DynamicAttributesManager.storeDynamicAttributes(DynamicAttributesManager.java:191)
	at com.haulmont.cuba.core.app.RdbmsStore.commit(RdbmsStore.java:416)
	at com.haulmont.cuba.core.app.DataManagerBean.commit(DataManagerBean.java:161)
	at com.haulmont.cuba.core.app.DataServiceBean.commit(DataServiceBean.java:41)
```

**Comment by andreysubbotin** [comment]
Issue has already fixed in 7.0
