### ISSUE TITLE
NPE on creating new Set from Table

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1703]
### Environment

- Platform version: 7.0.0
- Client type: Web

### Description of the bug or enhancement

- Minimal reproducible example

1. Enable folders pane
2. Enable addToSet action for Table with Filter using `applyTo` attribute:
```
        <filter id="filter"
                applyTo="lessorsTable"
                datasource="lessorsDs">
            <properties include=".*"/>
        </filter>
```
3. Create a record and use `Add to set` action

- Actual behavior
```
java.lang.NullPointerException
	at com.haulmont.cuba.web.app.folders.SaveSetWindow$CreateSetAction$1.run(SaveSetWindow.java:106)
	at com.haulmont.cuba.web.app.folders.FolderEditWindow.commit(FolderEditWindow.java:263)
	at com.haulmont.cuba.web.app.folders.FolderEditWindow.lambda$initButtonOkListener$61446b05$1(FolderEditWindow.java:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041)
	at com.vaadin.ui.Button.fireClick(Button.java:384)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:78)
```

**Comment by natfirst** [comment]
- Create new 7.0 screens for the entity.
- Create entity instance
- Click `Add to set` button
```
java.lang.NullPointerException
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl$AddToSetAction.actionPerform(FilterDelegateImpl.java:2577)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:62)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:317)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:208)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
```
