### ISSUE TITLE
NPE on displaying a table with editable column

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#1709]
If the screen contains a table with editable column, e.g. like this one:
```xml
        <table id="booksTable"
               width="100%"
               editable="true"
               dataContainer="booksDc">
            <actions>
                <action id="create" type="create"/>
                <action id="edit" type="edit"/>
                <action id="remove" type="remove"/>
            </actions>
            <columns>
                <column id="title"/>
                <column id="author" editable="true"/>
            </columns>
            <rowsCount/>
            <buttonsPanel id="buttonsPanel"
                          alwaysVisible="true">
                <button id="createBtn" action="booksTable.create"/>
                <button id="editBtn" action="booksTable.edit"/>
                <button id="removeBtn" action="booksTable.remove"/>
            </buttonsPanel>
        </table>
```
Then an exception is thrown on screen opening:
```java
java.lang.NullPointerException
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.getItemDatasource(WebAbstractTable.java:539)
	at com.haulmont.cuba.web.gui.components.table.WebTableFieldFactory.createField(WebTableFieldFactory.java:63)
	at com.haulmont.cuba.web.widgets.CubaTable.getPropertyValue(CubaTable.java:217)
```

See the project attached (books browse screen) 
[editable-table-bug.zip](https://github.com/cuba-platform/cuba/files/2698078/editable-table-bug.zip)

**Comment by glebfox** [comment]
Will be fixed in #1662
