### ISSUE TITLE
Use FlowLayout for ButtonsPanel implementation

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#178]
Use FlowLayout for ButtonsPanel implementation.

Most likely, we need to use CSS flex-box to enable this:

- If buttons do not fit horizontal space they are wrapped to the next line

### Multiple rows
The user can choose the way how the `buttons panel` will be displayed: in one row or can wrap onto multiple rows. The `GroupTable`, `DataGrid`, `TreeTable`, `TreeDataGrid` and `Table` components can have a `buttons panel`.
The default value is to display a `buttons panel` with wrapping into multiple rows.
```
$cuba-buttonspanel-flow: true !default;
```
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/11f07262-3cfd-480f-9ff3-4958b6b250a4)

### One row
The user can change this value:
1) Create a theme extension
2) Override variable `$cuba-buttonspanel-flow: false`

Then `buttons panel` will be placed in one row.
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/d97d0391-60ad-469b-9363-dd57741f247e)

### Test project
[buttons-panel.zip](https://github.com/cuba-platform/cuba/files/3265493/buttons-panel.zip)

## QA
Checklist:
* Check this case for components:
  * `GroupTable`
  * `Table`
  * `DataGrid`
  * `TreeTable`
  * `TreeDataGrid`
* Check two  `$cuba-buttonspanel-flow` values
* Check in different themes

**Comment by GlebDurygin** [comment]
If the user invoked the context menu of the table element and selected menu item "System information", an error appears:
```
java.lang.IllegalArgumentException: Can not set com.haulmont.cuba.gui.components.BoxLayout field com.haulmont.cuba.gui.app.core.showinfo.SystemInfoWindow.buttonsHbox to com.haulmont.cuba.web.gui.components.WebButtonsPanel
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.assignValue(UiControllerDependencyInjector.java:751)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.doInjection(UiControllerDependencyInjector.java:507)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.injectValues(UiControllerDependencyInjector.java:283)
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.inject(UiControllerDependencyInjector.java:123)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:233)
	at com.haulmont.cuba.web.sys.WebScreens.openWindow(WebScreens.java:1085)
	at com.haulmont.cuba.gui.components.sys.ShowInfoAction.showInfo(ShowInfoAction.java:61)
	at com.haulmont.cuba.gui.components.sys.ShowInfoAction.actionPerform(ShowInfoAction.java:51)
	at com.haulmont.cuba.web.gui.components.WebAbstractActionsHolderComponent.lambda$setContextMenuButtonAction$0(WebAbstractActionsHolderComponent.java:158)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
```

**Comment by GlebDurygin** [comment]
Bug fixed

**Comment by glebfox** [comment]
The `$cuba-buttonspanel-flow` variable is added only for the **Halo** theme.

**Comment by GlebDurygin** [comment]
#### Case:
The ButtonsPanel does not stretch to the entire available width

* **Actual behavior:**
The `ButtonsPanel` component is stretched in its content and does not stretch to the entire available width.
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/2105c49b-d584-4aee-a37e-56267d1d43f5)

* **Expected behavior:**
The `ButtonsPanel` component should stretch to the entire available width.
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/c98e3891-c748-41a4-b1cc-303b8cb9085b)
