### ISSUE TITLE
Incorrect exception in filter if loader does not have query

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1794]
#### Environment

- Platform version: 7.0

#### Description of the bug or enhancement

1. Create browser screen for some entity with CollectionContainer (and loader) defined in XML descriptor
2. Do not set query for the loader. Use `@Install` annotation instead to define custom loading logic.
3. Try to add filter condition

*E.R.* IllegalStateException: filter does not support custom loader/ loader without query
*A.R.*
```
java.lang.NullPointerException: query is null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
	at com.haulmont.cuba.core.sys.jpql.QueryTree.<init>(QueryTree.java:45)
	at com.haulmont.cuba.core.sys.jpql.QueryTree.<init>(QueryTree.java:41)
	at com.haulmont.cuba.core.global.QueryParserAstBased.getTree(QueryParserAstBased.java:68)
	at com.haulmont.cuba.core.global.QueryParserAstBased.getEntityAlias(QueryParserAstBased.java:105)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.getEntityAlias(FilterDelegateImpl.java:1355)
	at com.haulmont.cuba.web.gui.components.WebFilter.getEntityAlias(WebFilter.java:366)
	at com.haulmont.cuba.gui.components.filter.addcondition.ConditionDescriptorsTreeBuilder.<init>(ConditionDescriptorsTreeBuilder.java:97)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
```

**Comment by soraksh** [comment]
There actually should be no exception, conditions should be passed through `loadContext` param to delegate.
