### ISSUE TITLE
Base classes and templates for loginWindow and mainWindow based on new Screen API

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1798]
### Environment

- Platform version: 7.1

### Description of the bug or enhancement

Provide copy of `AbstractMainWindow` and `AppLoginWindow` functionality based on new screen API.

Studio migration required: for old projects we need to use old screens, register them in screen.xml during migration.

#### Breaking changes

Interfaces `Window.MainWindow` and `MainScreen` are removed.

`AbstractMainWindow` directly implements `Window.HasWorkArea`, `Window.HasUserIndicator` and `Window.HasFoldersPane` now.

#### New main screens

Two new main screens are introduced:

- `LoginScreen` (and its `login-screen.xml` descriptor) - new Login screen based on new `Screen` class
- `MainScreen` (and its `main-screen.xml` descriptor) - new Main screen based on new `Screen` class

They are used by default now.

#### How to enable legacy screens

Two new application properties are introduced in `WebConfig`:

- `String getLoginScreenId()` - Defines the screen that will be used as Login screen. Default value - `login`. App property - `cuba.web.loginScreenId`
- `String getMainScreenId()` - Defines the screen that will be used as Main screen. Default value - `main`. App property - `cuba.web.mainScreenId`

To enable legacy screens set `loginWindow` and `mainWindow` values to `cuba.web.loginScreenId` and `cuba.web.mainScreenId` respectively.

**Comment by dtsaryov** [comment]
A part of Main screen layout is changed - `FoldersPane` is removed.

When new screens are used `Add to set` / `Remove from set` actions should not be visible:

![image](https://user-images.githubusercontent.com/6183810/54282054-8fc51b00-45b4-11e9-93db-2e15b26a00f7.png)

**Comment by dtsaryov** [comment]
Reported from @natfirst:

Unable to open screens from menu when legacy main window is extended:

```
java.lang.IllegalStateException: RootWindow does not have any configured work area
    at com.haulmont.cuba.web.sys.WebScreens.getConfiguredWorkArea(WebScreens.java:905)
    at com.haulmont.cuba.web.sys.WebScreens.showFromNavigation(WebScreens.java:472)
    at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:327)
    at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:264)
    at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:249)
    at com.haulmont.cuba.web.gui.components.mainwindow.WebSideMenu$MenuItemImpl.menuSelected(WebSideMenu.java:569)
    at com.haulmont.cuba.web.widgets.CubaSideMenu$1.menuItemTriggered(CubaSideMenu.java:90)
```

**Comment by dtsaryov** [comment]
Reported by @Flaurite 

Login failed when foldersPane and filter with table are used in mainWindow screen:



```
Caused by: java.lang.IllegalStateException: UI yopLevelWindow is null
        at com.haulmont.cuba.web.AppUI.getTopLevelWindowNN(AppUI.java:530) ~[cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.web.gui.components.WebFilterHelper.getUiFoldersPane(WebFilterHelper.java:241) ~[cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.web.gui.components.WebFilterHelper.isFolderActionsEnabled(WebFilterHelper.java:93) ~[cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl$ControlsLayoutBuilder.isActionAllowed(FilterDelegateImpl.java:2854) ~[cuba-gui-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl$ControlsLayoutBuilder.fillSettingsBtn(FilterDelegateImpl.java:2842) ~[cuba-gui-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl$ControlsLayoutBuilder.getControlsLayoutComponent(FilterDelegateImpl.java:2795) ~[cuba-gui-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl$ControlsLayoutBuilder.build(FilterDelegateImpl.java:2764) ~[cuba-gui-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.createControlsLayoutForGeneric(FilterDelegateImpl.java:354) ~[cuba-gui-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.createLayout(FilterDelegateImpl.java:279) ~[cuba-gui-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.init(FilterDelegateImpl.java:243) ~[cuba-gui-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
        ... 98 common frames omitted
```

**Comment by knstvk** [comment]
Support in Studio: https://youtrack.cuba-platform.com/issue/STUDIO-6217
