### ISSUE TITLE
NullPointerException when use excel action

### ISSUE THREAD

**Issue by soraksh** [cuba-platform/cuba#1808]
### Environment

- Cuba version: 7.0
- Screen with group table
- Table have aggregation

### Description

- Try to use excel action
AR:
```
java.lang.NullPointerException
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.getAggregationResults(WebAbstractTable.java:873)
	at com.haulmont.cuba.gui.export.ExcelExporter.createAggregatableRow(ExcelExporter.java:468)
	at com.haulmont.cuba.gui.export.ExcelExporter.exportTable(ExcelExporter.java:232)
	at com.haulmont.cuba.gui.actions.list.ExcelAction.export(ExcelAction.java:159)
	at com.haulmont.cuba.gui.actions.list.ExcelAction.actionPerform(ExcelAction.java:82)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:62)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by myatlevEvg** [comment]
Reopen.
1) Create a screen with the groupTable with aggregation for the table and without aggregation for any table columns: 
```
        <groupTable id="newEntity_2sTable"
                    width="100%"
                    dataContainer="newEntity_2sDc"
                    multiselect="true"
                    aggregatable="true">
            <actions>
                <action id="create" type="create"/>
                <action id="edit" type="edit"/>
                <action id="remove" type="remove"/>
                <action id="excel" type="excel"/>
            </actions>
            <columns>
                <column id="count">
                </column>
            </columns>
            <rowsCount/>
            <buttonsPanel id="buttonsPanel"
                          alwaysVisible="true">
                <button id="createBtn" action="newEntity_2sTable.create"/>
                <button id="editBtn" action="newEntity_2sTable.edit"/>
                <button id="removeBtn" action="newEntity_2sTable.remove"/>
                <button id="excelBtn" action="newEntity_2sTable.excel"/>
            </buttonsPanel>
        </groupTable>
```
2) Start application server and open the screen with this table
3) Click to Excell action button
AR: Exception occurs:
```
java.lang.NullPointerException: Aggregation must be executed at least by one field
	at com.haulmont.cuba.gui.data.impl.AggregatableDelegate.aggregate(AggregatableDelegate.java:35)
	at com.haulmont.cuba.gui.components.data.table.ContainerTableItems.aggregate(ContainerTableItems.java:257)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.__aggregate(WebAbstractTable.java:2572)
	at com.haulmont.cuba.web.gui.components.WebGroupTable$AggregatableGroupTableDataContainer.aggregate(WebGroupTable.java:192)
	at com.haulmont.cuba.web.widgets.CubaTable.aggregate(CubaTable.java:640)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.getAggregationResults(WebAbstractTable.java:874)
	at com.haulmont.cuba.gui.export.ExcelExporter.createAggregatableRow(ExcelExporter.java:468)
	at com.haulmont.cuba.gui.export.ExcelExporter.exportTable(ExcelExporter.java:232)
	at com.haulmont.cuba.gui.actions.list.ExcelAction.export(ExcelAction.java:163)
	at com.haulmont.cuba.gui.actions.list.ExcelAction.actionPerform(ExcelAction.java:86)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:62)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```
