### ISSUE TITLE
Editor screens inheritance is not considered while navigation

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#1826]
Affected version: 7.0.0

1) Create a project with Platform 7.0 version
2) Create an Entity with at least one attribute
3) Create Browser-Editor screens for the Entity from step 2
4) Create an abstract class which extends `StandardEditor<YourEntity>`

```Java
public abstract class CarEditorBase extends StandardEditor<Car> {
}
```
5) Change extended class for editor screen from `StandardEditor<YourEntity>` to your class from step 4
```Java
public class CarEdit extends CarEditorBase {
}
```
6) Start an application server
7) Create an instance of the entity and copy the link from the browser address line
8) Open new tab in the browser and paste the link to entity instance editor
ER: Opened the tab with editor screen and specific entity instance
AR: Opens main screen of Platform

See the project in the attachments
[testt.zip](https://github.com/cuba-platform/cuba/files/2806640/testt.zip)

**Comment by myatlevEvg** [comment]
Reopen.
1) In the demo project from the top open editor screen
2) Do not fill any field
3) Copy the URL of the page
4) Paste the URL in the new browser tab

AR: Here should be IllegalAccessException instead of IllegalArgumentException
```
java.lang.IllegalArgumentException: entity is null
	at com.haulmont.bali.util.Preconditions.checkNotNullArgument(Preconditions.java:102)
	at com.haulmont.cuba.core.global.EntityStates.isNew(EntityStates.java:65)
	at com.haulmont.cuba.gui.screen.StandardEditor.setupEntityToEdit(StandardEditor.java:177)
	at com.haulmont.cuba.gui.screen.StandardEditor.beforeShow(StandardEditor.java:102)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:128)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:56)
	at com.haulmont.cuba.web.sys.WebScreens.show(WebScreens.java:423)
	at com.haulmont.cuba.gui.screen.Screen.show(Screen.java:309)
	at com.haulmont.cuba.web.sys.navigation.UrlChangeHandler.openScreen(UrlChangeHandler.java:444)
	at com.haulmont.cuba.web.sys.navigation.UrlChangeHandler.handleScreenChange(UrlChangeHandler.java:328)
	at com.haulmont.cuba.web.sys.navigation.UrlChangeHandler.handleScreenNavigation(UrlChangeHandler.java:243)
	at com.haulmont.cuba.web.sys.navigation.UrlChangeHandler.__handleUrlChange(UrlChangeHandler.java:125)
	at com.haulmont.cuba.web.sys.navigation.UrlChangeHandler.handleUrlChangeInternal(UrlChangeHandler.java:849)
	at com.haulmont.cuba.web.AppUI.processRequest(AppUI.java:624)
	at com.haulmont.cuba.web.AppUI.processExternalLink(AppUI.java:579)
	at com.haulmont.cuba.web.AppUI.init(AppUI.java:328)
	at com.vaadin.ui.UI.doInit(UI.java:738)
	at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:209)
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:67)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```
