### ISSUE TITLE
IllegalStateException: Dynamic attributes should be loaded explicitly

### ISSUE THREAD

**Issue by PolinaSannikova** [cuba-platform/cuba#1849]
### Environment

- Platform version: 6.8.14

### Description of the bug or enhancement

Data Model:

foo$CompanyInfo

Property | Column | Type | Description | Cardinality | Annotations
-- | -- | -- | -- | -- | --
bankDetails | BANK_DETAILS_ID | foo$BankDetails | Bank Details | 1:1 | cuba.persistent

foo$CompanyInfo.edit screen DsContext:
```
    <dsContext>
        <datasource id="companyInfoDs"
                    class="com.foo.core.entity.company.CompanyInfo"
                    view="companyInfo.edit">
            <datasource id="bankDetailsDs" property="bankDetails"/>
        </datasource>
    </dsContext>
```

foo$CompanyInfo.edit components:
```
<fieldGroup id="infoFieldGroup" datasource="companyInfoDs"
                                        border="visible"
                                        caption="msg://companyInfo.editor.info" width="100%">
<fieldGroup id="contactsFieldGroup" datasource="companyInfoDs"
                                        border="visible"
                                        caption="msg://companyInfo.editor.contacts" width="100%">
<fieldGroup id="bankDetailsGroup" datasource="bankDetailsDs"
                                        border="visible"
                                        caption="msg://companyInfo.editor.bankDetails" width="100%">
```

Steps:

1. Create a dynamic attribute for foo$BankDetails entity
2. In Visibility settings for that dynamic attribute, set foo$CompanyInfo.edit screen (optionally, specify component bankDetailsGroup - does not affect result, error appears anyway)
3. On Dynamic Attributes screen, click Apply Changes button
4. Try to open foo$CompanyInfo.edit screen

- Expected behavior
The screen will be opened without error; if bankDetailsGroup component is specified, the dynamic attribute would be displayed there
- Actual behavior

```
java.lang.IllegalStateException: Dynamic attributes should be loaded explicitly
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.getValue(BaseGenericIdEntity.java:131)
	at com.haulmont.chile.core.model.utils.InstanceUtils.getValueEx(InstanceUtils.java:139)
	at com.haulmont.cuba.web.gui.data.PropertyWrapper.getValue(PropertyWrapper.java:76)
	at com.vaadin.ui.AbstractField.readValueFromProperty(AbstractField.java:1364)
	at com.vaadin.ui.AbstractField.valueChange(AbstractField.java:1357)
	at com.haulmont.cuba.web.gui.data.AbstractPropertyWrapper.fireValueChangeEvent(AbstractPropertyWrapper.java:58)
	at com.haulmont.cuba.web.gui.data.PropertyWrapper.lambda$new$0(PropertyWrapper.java:54)
	at com.haulmont.cuba.gui.data.impl.WeakItemChangeListener.itemChanged(WeakItemChangeListener.java:40)
	at com.haulmont.bali.events.EventRouter.fireEvent(EventRouter.java:45)
	at com.haulmont.cuba.gui.data.impl.AbstractDatasource.fireItemChanged(AbstractDatasource.java:283)
	at com.haulmont.cuba.gui.data.impl.PropertyDatasourceImpl.lambda$initParentDsListeners$0(PropertyDatasourceImpl.java:57)
	at com.haulmont.bali.events.EventRouter.fireEvent(EventRouter.java:45)
	at com.haulmont.cuba.gui.data.impl.AbstractDatasource.fireItemChanged(AbstractDatasource.java:283)
	at com.haulmont.cuba.gui.data.impl.DatasourceImpl.setItem(DatasourceImpl.java:190)
	at com.haulmont.cuba.gui.components.EditorWindowDelegate.setItem(EditorWindowDelegate.java:190)
	at com.haulmont.cuba.web.gui.WebWindow$Editor.setItem(WebWindow.java:1683)
	at com.haulmont.cuba.gui.components.AbstractEditor.setItem(AbstractEditor.java:69)
	at com.foo.client.ui.company.edit.CompanyInfoEditor.setItem(CompanyInfoEditor.java:109)
	at com.haulmont.cuba.gui.WindowManager.openEditor(WindowManager.java:888)
	at com.haulmont.cuba.web.WebWindowManager.openEditor(WebWindowManager.java:178)
	at com.haulmont.cuba.gui.components.WindowDelegate.openEditor(WindowDelegate.java:258)
	at com.haulmont.cuba.web.gui.WebWindow.openEditor(WebWindow.java:487)
	at com.haulmont.cuba.gui.components.actions.EditAction.internalOpenEditor(EditAction.java:274)
	at com.haulmont.cuba.gui.components.actions.EditAction.actionPerform(EditAction.java:223)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.handleClickAction(WebAbstractTable.java:838)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.lambda$initComponent$4fd149ee$1(WebAbstractTable.java:724)
	at sun.reflect.GeneratedMethodAccessor1411.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1037)
	at com.vaadin.ui.Table.handleClickEvent(Table.java:3175)
```

**Comment by alexbudarov** [comment]
Even if you add
> loadDynamicAtttributes="true"
to screen datasource, it will still fail with exception because it loads dynamic attributes only for main entity.

**Comment by andreysubbotin** [comment]
Test project: 
[dynamicerror.zip](https://github.com/cuba-platform/cuba/files/2851287/dynamicerror.zip)
