### ISSUE TITLE
The report does not run because "where" section is skipped"

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#1857]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement

There is a query in entity browser:
```
<query>
    <![CDATA[select e from library$BookInstance e order by e.inventoryNumber]]>
    <condition>
        <q:jpql>
            <q:where>e.bookPublication = :property</q:where>
        </q:jpql>
    </condition>
</query>
```

When the report runs, the exception occurs:
```
com.haulmont.reports.exception.ReportingException: java.lang.IllegalArgumentException: You have attempted to set a parameter value using a name of property that does not exist in the query string select e from library$BookInstance e order by e.inventoryNumber.
	at com.haulmont.reports.PrototypesLoader.loadData(PrototypesLoader.java:93)
	at com.haulmont.reports.ReportingBean.loadDataForParameterPrototype(ReportingBean.java:385)
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:335)
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:315)
	at com.haulmont.reports.ReportingBean.createReport(ReportingBean.java:209)
	at com.haulmont.reports.ReportServiceBean.createReport(ReportServiceBean.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:117)
	at sun.reflect.GeneratedMethodAccessor125.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy269.createReport(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154)
	at com.sun.proxy.$Proxy63.createReport(Unknown Source)
	at com.haulmont.reports.gui.ReportGuiManager.getReportResult(ReportGuiManager.java:283)
	at com.haulmont.reports.gui.ReportGuiManager.printReportSync(ReportGuiManager.java:254)
	at com.haulmont.reports.gui.ReportGuiManager.printReport(ReportGuiManager.java:223)
	at com.haulmont.reports.gui.ReportGuiManager.printReport(ReportGuiManager.java:201)
	at com.haulmont.reports.gui.ReportGuiManager.runReport(ReportGuiManager.java:152)
	at com.haulmont.reports.gui.actions.AbstractPrintFormAction.openRunReportScreen(AbstractPrintFormAction.java:90)
	at com.haulmont.reports.gui.actions.AbstractPrintFormAction.openRunReportScreen(AbstractPrintFormAction.java:56)
	at com.haulmont.reports.gui.actions.ListPrintFormAction.printAll(ListPrintFormAction.java:173)
	at com.haulmont.reports.gui.actions.ListPrintFormAction$2.actionPerform(ListPrintFormAction.java:86)
	at com.haulmont.cuba.web.sys.WebDialogs$OptionDialogBuilderImpl.lambda$show$0(WebDialogs.java:319)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
```

**Comment by knstvk** [comment]
Issue moved to [cuba-platform/reports #156](https://github.com/cuba-platform/reports/issues/156) via [**ZenHub**](https://www.zenhub.com/)
