### ISSUE TITLE
Multiplying ValueChangeListeners in case of generated table columns

### ISSUE THREAD

**Issue by soraksh** [cuba-platform/cuba#1889]
### Environment

- Platform version: 7.0.1
- Test project: [GenTableTest.zip](https://github.com/cuba-platform/cuba/files/2883252/GenTableTest.zip)

### Description of the bug or enhancement

- Create table with generated column where you use (so add at generation, inside `generateCell()` method) `ValueChangeListener` to listen this column and modify field value in it doesn't match some criteria.
- Try to open screen with this table and modify value (set value of first to `A`, then `B`, then `C`) few times. 
- For example see attached test project. Where on `New Screen` you can modify entity instance name in generated column. It should starts from character `0` or this character will be added.

### Actual behavior:

You get `StackOverflowError` or `OutOfMemoryError`.

`StackOverflowError` example:
```
java.lang.StackOverflowError
	at java.lang.String.split(String.java:2351)
	at java.lang.String.split(String.java:2422)
	at com.haulmont.chile.core.model.impl.MetaClassImpl.getPropertyPath(MetaClassImpl.java:114)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.canUpdateMasterRefs(ContainerValueSource.java:237)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.setValue(ContainerValueSource.java:169)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.setValueToSource(ValueBinder.java:276)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.componentValueChanged(ValueBinder.java:269)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.web.gui.components.WebAbstractComponent.publish(WebAbstractComponent.java:88)
	at com.haulmont.cuba.web.gui.components.WebAbstractValueComponent.setValue(WebAbstractValueComponent.java:102)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.sourceValueChanged(ValueBinder.java:282)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.containerItemPropertyChanged(ContainerValueSource.java:232)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.model.impl.InstanceContainerImpl.itemPropertyChanged(InstanceContainerImpl.java:178)
	at com.haulmont.chile.core.model.impl.AbstractInstance.propertyChanged(AbstractInstance.java:53)
	at com.company.gentabletest.entity.TestEntity.setName(TestEntity.java:21)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:132)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:126)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:114)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:214)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:172)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValueEx(AbstractInstance.java:149)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.setValue(ContainerValueSource.java:172)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.setValueToSource(ValueBinder.java:276)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.componentValueChanged(ValueBinder.java:269)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.web.gui.components.WebAbstractComponent.publish(WebAbstractComponent.java:88)
	at com.haulmont.cuba.web.gui.components.WebAbstractValueComponent.setValue(WebAbstractValueComponent.java:102)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.sourceValueChanged(ValueBinder.java:282)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.containerItemPropertyChanged(ContainerValueSource.java:232)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.model.impl.InstanceContainerImpl.itemPropertyChanged(InstanceContainerImpl.java:178)
	at com.haulmont.chile.core.model.impl.AbstractInstance.propertyChanged(AbstractInstance.java:53)
	at com.company.gentabletest.entity.TestEntity.setName(TestEntity.java:21)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:132)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:126)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:114)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:214)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:172)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValueEx(AbstractInstance.java:149)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.setValue(ContainerValueSource.java:172)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.setValueToSource(ValueBinder.java:276)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.componentValueChanged(ValueBinder.java:269)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.web.gui.components.WebAbstractComponent.publish(WebAbstractComponent.java:88)
	at com.haulmont.cuba.web.gui.components.WebAbstractValueComponent.setValue(WebAbstractValueComponent.java:102)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.sourceValueChanged(ValueBinder.java:282)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.containerItemPropertyChanged(ContainerValueSource.java:232)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.model.impl.InstanceContainerImpl.itemPropertyChanged(InstanceContainerImpl.java:178)
	at com.haulmont.chile.core.model.impl.AbstractInstance.propertyChanged(AbstractInstance.java:53)
	at com.company.gentabletest.entity.TestEntity.setName(TestEntity.java:21)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:132)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:126)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:114)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:214)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:172)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValueEx(AbstractInstance.java:149)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.setValue(ContainerValueSource.java:172)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.setValueToSource(ValueBinder.java:276)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.componentValueChanged(ValueBinder.java:269)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.web.gui.components.WebAbstractComponent.publish(WebAbstractComponent.java:88)
	at com.haulmont.cuba.web.gui.components.WebAbstractValueComponent.setValue(WebAbstractValueComponent.java:102)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.sourceValueChanged(ValueBinder.java:282)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.containerItemPropertyChanged(ContainerValueSource.java:232)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.model.impl.InstanceContainerImpl.itemPropertyChanged(InstanceContainerImpl.java:178)
	at com.haulmont.chile.core.model.impl.AbstractInstance.propertyChanged(AbstractInstance.java:53)
	at com.company.gentabletest.entity.TestEntity.setName(TestEntity.java:21)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:132)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:126)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:114)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:214)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:172)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValueEx(AbstractInstance.java:149)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.setValue(ContainerValueSource.java:172)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.setValueToSource(ValueBinder.java:276)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.componentValueChanged(ValueBinder.java:269)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.web.gui.components.WebAbstractComponent.publish(WebAbstractComponent.java:88)
	at com.haulmont.cuba.web.gui.components.WebAbstractValueComponent.setValue(WebAbstractValueComponent.java:102)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.sourceValueChanged(ValueBinder.java:282)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.containerItemPropertyChanged(ContainerValueSource.java:232)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.model.impl.InstanceContainerImpl.itemPropertyChanged(InstanceContainerImpl.java:178)
	at com.haulmont.chile.core.model.impl.AbstractInstance.propertyChanged(AbstractInstance.java:53)
	at com.company.gentabletest.entity.TestEntity.setName(TestEntity.java:21)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:132)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:126)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:114)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:214)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:172)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValueEx(AbstractInstance.java:149)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.setValue(ContainerValueSource.java:172)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.setValueToSource(ValueBinder.java:276)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.componentValueChanged(ValueBinder.java:269)
```

**Comment by jreznot** [comment]
Reopened, ListEditor does not commit new value to DB in case of dynamic attributes with Collection type. See UI Test CollectionDynamicAttributesUiTest.tableWithCollectionAttribute
