### ISSUE TITLE
NotSerializableException on inject of PersistenceManagerService to Spring prototype bean

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1908]
### Environment

- Platform version:  7.0.1

### Description of the bug or enhancement

- Minimal reproducible example

1. Create a new Java class in web module:
```java
@Component
@Scope(BeanDefinition.SCOPE_PROTOTYPE)
public class DemoBean {
    @Inject
    protected PersistenceManagerService persistenceManagerService;

    public PersistenceManagerService getPersistenceManagerService() {
        return persistenceManagerService;
    }
}
```

2. Create a screen with code:
```java
public class ClientBrowse extends StandardLookup<Client> {
    @Subscribe
    protected void onInit(InitEvent event) {
        getBeanLocator().get(DemoBean.class);
    }
}
```

3. Run application and open the screen

Project: 
[action-captions.zip](https://github.com/cuba-platform/cuba/files/2894385/action-captions.zip)

- Actual behavior

Exception
```
java.io.NotSerializableException: com.haulmont.cuba.core.sys.CubaClassPathXmlApplicationContext
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.haulmont.cuba.core.sys.serialization.StandardSerialization.serialize(StandardSerialization.java:34)
	at com.haulmont.cuba.core.sys.serialization.StandardSerialization.serialize(StandardSerialization.java:80)
	at com.haulmont.cuba.core.sys.serialization.SerializationSupport.serialize(SerializationSupport.java:61)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:129)
	at com.sun.proxy.$Proxy36.equals(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.containsValue(ConcurrentHashMap.java:985)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.determineAutowireCandidate(DefaultListableBeanFactory.java:1493)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166)
	at com.haulmont.cuba.core.sys.CubaDefaultListableBeanFactory.resolveDependency(CubaDefaultListableBeanFactory.java:59)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:338)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:224)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1114)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:407)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:341)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:335)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1101)
	at com.haulmont.cuba.core.sys.BeanLocatorImpl.get(BeanLocatorImpl.java:57)
	at com.company.demo.web.client.ClientBrowse.onInit(ClientBrowse.java:13)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:128)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:56)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:247)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:171)
	at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:212)
	at com.haulmont.cuba.web.sys.MenuBuilder$MenuCommandExecutor.accept(MenuBuilder.java:256)
	at com.haulmont.cuba.web.sys.MenuBuilder$MenuCommandExecutor.accept(MenuBuilder.java:241)
	at com.haulmont.cuba.web.gui.components.mainwindow.WebAppMenu$MenuItemImpl.menuSelected(WebAppMenu.java:435)
```

**Comment by Mihail063** [comment]
Error reproduces on a platform version 7.1.0
