### ISSUE TITLE
Script for insert from "System info" screen throws IllegalStateException: Cannot get unfetched attribute

### ISSUE THREAD

**Issue by w1nter27** [cuba-platform/cuba#1920]
- Platform version: 6.10.7

### Description of the bug or enhancement

1. Create entity with at least two or more lazy fetched fields
2. Add this entity on some screen component
3. Execute "Script for insert" action

- ER: all work correct
- AE:
```java
IllegalStateException: Cannot get unfetched attribute [message] from detached object com.haulmont.cuba.core.entity.SendingAttachment-faf904f2-8def-9403-346b-a768a48d0afc [detached].
java.lang.IllegalStateException: Cannot get unfetched attribute [message] from detached object com.haulmont.cuba.core.entity.SendingAttachment-faf904f2-8def-9403-346b-a768a48d0afc [detached].
    at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.throwUnfetchedAttributeException(UnitOfWorkValueHolder.java:322)
    at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:95)
    at com.haulmont.cuba.core.entity.SendingAttachment._persistence_get_message(SendingAttachment.java)
    at com.haulmont.cuba.core.entity.SendingAttachment.getMessage(SendingAttachment.java:59)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.haulmont.chile.core.model.utils.MethodsCache.invokeGetter(MethodsCache.java:71)
    at com.haulmont.chile.core.model.impl.AbstractInstance.getValue(AbstractInstance.java:102)
    at com.haulmont.cuba.core.entity.BaseGenericIdEntity.getValue(BaseGenericIdEntity.java:139)
    at com.haulmont.chile.core.model.utils.InstanceUtils.getValueEx(InstanceUtils.java:139)
    at com.haulmont.chile.core.model.utils.InstanceUtils.getValueEx(InstanceUtils.java:123)
    at com.haulmont.chile.core.model.impl.AbstractInstance.getValueEx(AbstractInstance.java:139)
    at com.haulmont.cuba.core.app.entitysql.EntitySqlGenerator$Table.insert(EntitySqlGenerator.java:254)
    at com.haulmont.cuba.core.app.entitysql.EntitySqlGenerator.generateInsertScript(EntitySqlGenerator.java:98)
    at com.haulmont.cuba.core.app.entitysql.EntitySqlGenerationServiceBean.generateInsertScript(EntitySqlGenerationServiceBean.java:57)
```

For fixing this, need enable partial view in **EntitySqlGenerationServiceBean**

**Comment by andreysubbotin** [comment]
`Works fine for Car entity in RefApp

**Comment by w1nter27** [comment]
In out case, we have next lazy fields:
1. message_id - fk column (not null)
2. content - byte array (have some content)
3. content_file_id - fk column (not null)

See entity class: **com.haulmont.cuba.core.entity.SendingAttachment**

**Comment by w1nter27** [comment]
We can reproduce it on ref-app 6.10

1. Send email from jmx console
2. Open **Entity Inspector** screen
3. Select "Sending Attachment" entity type
4. Select any attachment. Open "System Info" screen and click on "Script for insert" button.

**Comment by andreysubbotin** [comment]
For QA: tests only
* Send email from jmx console
* Open Entity Inspector screen
* Select "Sending Attachment" entity type
* Select any attachment. Open "System Info" screen and click on "Script for insert" button.

Do not use @Basic(LAZY) fields in entity models.

**Comment by w1nter27** [comment]
In case when entity have a lot of lazy fields, this fix isn't valid.
Because *com.haulmont.cuba.core.app.entitysql.EntitySqlGenerator#insert* or *com.haulmont.cuba.core.app.entitysql.EntitySqlGenerator#update* methods load each fields from database and EclipseLink could reset earlier loaded lazy fields.

**Comment by andreysubbotin** [comment]
Could you provide a sample project? we don't recommend using Basic(LAZY) for not relational properties.
