### ISSUE TITLE
Early detect and report that entities are not enhanced

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#1926]
### Environment
- Platform version: 6.10
- .ipr project produced with gradlew idea

### Description of the bug or enhancement
EclipseLink produces cryptic error messages if entities are not enhanced.
Currently it can happen:
a) with old .ipr project structure when forgot to gradlew assemble the project
b) when build scripts are broken for some reason

How to reproduce:
- Open refapp 6.10
- Run gradlew startHsqlDb createTestDb :cuba-global:clean
- Launch DataManagerTest and DataManagerCommitTest and IDEA.

During start below is the only clue that something is wrong with persistent entities:
> 11:44:33.936 WARN  eclipselink.metadata - metadata_warning_ignore_lazy [firstChild, class com.haulmont.cuba.testmodel.cascadedelete.CascadeEntity]
> 11:44:33.936 WARN  eclipselink.metadata - metadata_warning_ignore_lazy [father, class com.haulmont.cuba.testmodel.cascadedelete.CascadeEntity]
> ...

This is error message for attempt to commit entities in DataManagerCommitTest:
```
javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.2.cuba24): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_11541 table: SEC_USER column: LOGIN_LC
Error Code: -10
Call: INSERT INTO SEC_USER (ID, ACTIVE, CHANGE_PASSWORD_AT_LOGON, CREATE_TS, CREATED_BY, DELETE_TS, DELETED_BY, EMAIL, FIRST_NAME, IP_MASK, LANGUAGE_, LAST_NAME, LOGIN, LOGIN_LC, MIDDLE_NAME, NAME, PASSWORD, POSITION_, TIME_ZONE, TIME_ZONE_AUTO, UPDATE_TS, UPDATED_BY, VERSION, GROUP_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [4a4144b5-5a43-eb8b-8e8e-0ef7955739e5, true, false, 2019-03-05 11:44:34.257, test_admin, null, null, null, null, null, null, null, login4a4144b5-5a43-eb8b-8e8e-0ef7955739e5, null, null, testUser, 000, null, null, null, 2019-03-05 11:44:34.257, null, 1, 0fa2b1a5-1d68-4d69-9fbd-dff348347f93]
Query: InsertObjectQuery(com.haulmont.cuba.security.entity.User-4a4144b5-5a43-eb8b-8e8e-0ef7955739e5 [new,managed])

	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:883)
	at com.haulmont.cuba.core.sys.persistence.PersistenceImplSupport$ContainerResourceSynchronization.detachAll(PersistenceImplSupport.java:496)
	at com.haulmont.cuba.core.sys.persistence.PersistenceImplSupport$ContainerResourceSynchronization.beforeCommit(PersistenceImplSupport.java:449)
...
```

This is error message for attempt to load entities in DataManagerTest:
```
javax.persistence.PersistenceException: Exception [EclipseLink-6114] (Eclipse Persistence Services - 2.6.2.cuba24): org.eclipse.persistence.exceptions.QueryException
Exception Description: You must define a fetch group manager at descriptor (com.haulmont.cuba.core.entity.Server) in order to set a fetch group on the query (null)
Query: ReadAllQuery(referenceClass=Server sql="SELECT ID, CREATE_TS, CREATED_BY, DATA, NAME, IS_RUNNING, UPDATE_TS, UPDATED_BY FROM SYS_SERVER")
FetchGroup(){running, data, name}

	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:484)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultFromCache(QueryImpl.java:676)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultList(QueryImpl.java:360)
	at com.haulmont.cuba.core.app.RdbmsStore.executeQuery(RdbmsStore.java:755)
	at com.haulmont.cuba.core.app.RdbmsStore.getResultList(RdbmsStore.java:663)
	at com.haulmont.cuba.core.app.RdbmsStore.loadList(RdbmsStore.java:227)
	at com.haulmont.cuba.core.app.DataManagerBean.loadList(DataManagerBean.java:74)
...
```

We need to check that all persistent (and non-persistent also?) entities are enhanced on application start and issue a descriptive error message to developer.

**Comment by knstvk** [comment]
It must not increase startup time significantly.

**Comment by andreysubbotin** [comment]
Also detect `@Basic(LAZY)`, EAGER reference fields -> write WARN to log file and setup recommended fetch types for CUBA application:
for `@Basic(LAZY)` set `EAGER` and for `EAGER` reference fields (`@OneToMany, @ManyToMany, @OneToMany and other` ) set LAZY.
