### ISSUE TITLE
ClassCastException when trying to add value with numbers to CurrencyField with String datatype

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1932]
#### Environment

- Platform version: 7.0-S, 7.1-S

#### Description of the bug or enhancement

1. Add CurrencyField with String datatype to screen
`    <currencyField datatype="string"/>`
2. Add incorrect value with numbers to the field

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at com.haulmont.cuba.web.gui.components.WebCurrencyField.convertToModel(WebCurrencyField.java:108)
	at com.haulmont.cuba.web.gui.components.WebCurrencyField.convertToModel(WebCurrencyField.java:43)
	at com.haulmont.cuba.web.gui.components.WebAbstractValueComponent.componentValueChanged(WebAbstractValueComponent.java:131)
	at com.haulmont.cuba.web.gui.components.WebCurrencyField.lambda$attachValueChangeListener$1ebec749$1(WebCurrencyField.java:75)
	at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:144)
	at com.vaadin.ui.AbstractTextField$AbstractTextFieldServerRpcImpl.setText(AbstractTextField.java:57)
	at sun.reflect.GeneratedMethodAccessor141.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
Also, currencyField with the following datatypes works fine, but should not
```
<currencyField datatype="date"/>
<currencyField datatype="dateTime"/>
<currencyField datatype="uuid"/>
<currencyField datatype="string"/>
<currencyField datatype="boolean"/>
```

**Comment by jreznot** [comment]
We need to check datatype and throw an exception if datatype is not supported by `CurrencyField`. `CurrencyField.setDatatype` must check if datatype has Java class of type Number.
