### ISSUE TITLE
Allow to use NULL after 'then' with 'case when' jpql function

### ISSUE THREAD

**Issue by soraksh** [cuba-platform/cuba#1934]
### Environment

- Platform version: 6.9.7

### Description of enhancement

- Minimal reproducible example: Create any `Select` jpql query with `Case When` function with `Then null` part. For exmple: `select e.id, case when (a.id is null) then null else a.internalCode end from cwt$Product e left join e.agent a`
- Actual behavior: 
```
com.haulmont.cuba.core.sys.jpql.JpqlSyntaxException: Errors found for input jpql:[select e.id, case when (a.id is null) then null else a.internalCode end from cwt$Product e left join e.agent a]
CommonErrorNode [<unexpected: [@9,18:21='when',<60>,1:18], resync=case when (>]
CommonErrorNode [<mismatched token: [@13,25:25='.',<68>,1:25], resync=.id is null) then null else a.internalCode end from cwt$Product e left join e.agent a>]

	at com.haulmont.cuba.core.sys.jpql.Parser.checkTreeForExceptions(Parser.java:104)
	at com.haulmont.cuba.core.sys.jpql.Parser.parse(Parser.java:40)
	at com.haulmont.cuba.core.sys.jpql.QueryTreeAnalyzer.prepare(QueryTreeAnalyzer.java:54)
	at com.haulmont.cuba.core.sys.jpql.QueryTreeAnalyzer.prepare(QueryTreeAnalyzer.java:46)
	at com.haulmont.cuba.core.global.QueryParserAstBased.getQueryAnalyzer(QueryParserAstBased.java:77)
	at com.haulmont.cuba.core.global.QueryParserAstBased.getEntityName(QueryParserAstBased.java:109)
	at com.haulmont.cuba.core.sys.QueryImpl.transformQueryString(QueryImpl.java:224)
	at com.haulmont.cuba.core.sys.QueryImpl.getQuery(QueryImpl.java:117)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultList(QueryImpl.java:339)
...
```

It is better to make possible returning `Null` value from `Case When` function.

**Comment by pctF** [comment]
I believe it is necessary limitation. 
```
CASE
    WHEN (a.id is not null) THEN a.internalCode
END
```
```
a.internalCode
```
both of examples will return you null if  **a** is not defined and doesn't throw exception
