### ISSUE TITLE
Unable to open screens from SideMenu

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1982]
#### Environment

- Platform version: 7.1

### Description of the bug or enhancement

1. Create app with SideMenu extension of main window (v6.10.7)
2. Launch application and open "Administration" menu item

```
java.lang.IllegalStateException: RootWindow does not have any configured work area
	at com.haulmont.cuba.web.sys.WebScreens.getConfiguredWorkArea(WebScreens.java:905)
	at com.haulmont.cuba.web.sys.WebScreens.showFromNavigation(WebScreens.java:472)
	at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:327)
	at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:264)
	at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:249)
	at com.haulmont.cuba.web.gui.components.mainwindow.WebSideMenu$MenuItemImpl.menuSelected(WebSideMenu.java:569)
	at com.haulmont.cuba.web.widgets.CubaSideMenu$1.menuItemTriggered(CubaSideMenu.java:90)
```

**Comment by dtsaryov** [comment]
Caused by #1798

Moved as a comment into initial issue.
