### ISSUE TITLE
SQLSyntaxErrorException is occurred when opening Scheduled Task screen on hsqldb

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#1991]
### Environment
- Platform version: 7.0.2
**Studio plugin: v9;**

### Description of the bug or enhancement
- Breaking changes:
Column `PERIOD` renamed to `PERIOD_` in `SYS_SCHEDULED_TASK` table

- Minimal reproducible example
1. Create app with hsqldb
2. Launch anf open _Scheduled Task_ screen
- Expected behavior
There is no exceptions
- Actual behavior
SQLSyntaxErrorException is occured.

```
java.sql.SQLSyntaxErrorException: unexpected token: AS required: ( in statement [SELECT LIMIT ? ? ID AS a1, IS_ACTIVE AS a2, BEAN_NAME AS a3, CLASS_NAME AS a4, CRON AS a5, DEFINED_BY AS a6, DELETE_TS AS a7, DELETED_BY AS a8, DESCRIPTION AS a9, LAST_START_SERVER AS a10, LAST_START_TIME AS a11, LOG_FINISH AS a12, LOG_START AS a13, METHOD_NAME AS a14, METHOD_PARAMS AS a15, PERIOD AS a16, PERMITTED_SERVERS AS a17, SCHEDULING_TYPE AS a18, SCRIPT_NAME AS a19, IS_SINGLETON AS a20, START_DATE AS a21, START_DELAY AS a22, TIME_FRAME AS a23, TIMEOUT AS a24, USER_NAME AS a25 FROM SYS_SCHEDULED_TASK WHERE (DELETE_TS IS NULL) ORDER BY BEAN_NAME, METHOD_NAME]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:292)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:292)
	at com.haulmont.cuba.core.sys.jdbc.ProxyConnection.prepareStatement(ProxyConnection.java:38)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.prepareStatement(DatabaseAccessor.java:1639)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.prepareStatement(DatabaseAccessor.java:1588)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseCall.prepareStatement(DatabaseCall.java:806)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:638)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:564)
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2093)
	at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:603)
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:263)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:275)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.executeCall(ExpressionQueryMechanism.java:2897)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:261)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:332)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:728)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2785)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2738)
	at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:565)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1221)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:914)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1180)
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:466)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1268)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:3020)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1892)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1874)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:262)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:482)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultFromCache(QueryImpl.java:715)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultList(QueryImpl.java:372)
	at com.haulmont.cuba.core.app.RdbmsStore.executeQuery(RdbmsStore.java:756)
	at com.haulmont.cuba.core.app.RdbmsStore.getResultList(RdbmsStore.java:664)
	at com.haulmont.cuba.core.app.RdbmsStore.loadList(RdbmsStore.java:225)
	at com.haulmont.cuba.core.app.DataManagerBean.loadList(DataManagerBean.java:74)
	at com.haulmont.cuba.core.app.DataServiceBean.loadList(DataServiceBean.java:54)
```

**Comment by andreysubbotin** [comment]
Revert changes from 6.10 and 7.0.
