### ISSUE TITLE
Login failed when foldersPane and filter with table are used in mainWindow screen

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#1996]
### Environment
- Platform version: 7.1
- Client type: Web

### Description of the bug or enhancement
- Minimal reproducible example
1. Download attached project: [folderdemo.zip](https://github.com/cuba-platform/cuba/files/3008316/folderdemo.zip)
2. Launch app and try to login

- Actual behavior
Stacktrace:
```
Caused by: java.lang.IllegalStateException: UI yopLevelWindow is null
        at com.haulmont.cuba.web.AppUI.getTopLevelWindowNN(AppUI.java:530) ~[cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.web.gui.components.WebFilterHelper.getUiFoldersPane(WebFilterHelper.java:241) ~[cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.web.gui.components.WebFilterHelper.isFolderActionsEnabled(WebFilterHelper.java:93) ~[cuba-web-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl$ControlsLayoutBuilder.isActionAllowed(FilterDelegateImpl.java:2854) ~[cuba-gui-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl$ControlsLayoutBuilder.fillSettingsBtn(FilterDelegateImpl.java:2842) ~[cuba-gui-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl$ControlsLayoutBuilder.getControlsLayoutComponent(FilterDelegateImpl.java:2795) ~[cuba-gui-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl$ControlsLayoutBuilder.build(FilterDelegateImpl.java:2764) ~[cuba-gui-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.createControlsLayoutForGeneric(FilterDelegateImpl.java:354) ~[cuba-gui-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.createLayout(FilterDelegateImpl.java:279) ~[cuba-gui-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.init(FilterDelegateImpl.java:243) ~[cuba-gui-7.1-SNAPSHOT.jar:7.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
        ... 98 common frames omitted
```

**Comment by dtsaryov** [comment]
Caused by #1798

Moved to origin
