### ISSUE TITLE
Rework PopupButton with Vaadin Button and CssLayout

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#202]
Original problem:

If action is defined in PopupButton - it passes WebButton to actionPerform of Action, but it should pass owner - WebPopupButton

TC:

1) Add PopupButton to table panel
2) Add RunReportAction into popup button
3) Try to perform action

E.R. Report window is shown
A.R. NPE

```
java.lang.NullPointerException
	at com.haulmont.reports.gui.actions.RunReportAction.openLookup(RunReportAction.java:99)
	at com.haulmont.reports.gui.actions.RunReportAction.actionPerform(RunReportAction.java:78)
	at com.haulmont.cuba.web.gui.components.WebPopupButton$PopupActionWrapper.actionPerform(WebPopupButton.java:353)
	at com.haulmont.cuba.web.gui.components.WebButton.performAction(WebButton.java:53)
	at com.haulmont.cuba.web.gui.components.WebButton$1.buttonClick(WebButton.java:44)
```

---
Original issue: https://youtrack.haulmont.com/issue/PL-7049

**Comment by jreznot** [comment]
Check regressions with PopupButton component
