### ISSUE TITLE
The split position between app and search folders are not saved during logout

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2106]
### Environment

- Platform version: 7.0.0

### Description of the bug or enhancement

- Minimal reproducible example

1. Enable application folders
2. Add app folders and search folders
3. Change the vertical split position
4. Logout
5. Login

- Expected behavior

The vertical split position is saved

- Actual behavior

The vertical split position isn't saved

## Updates

Provide interface `HasSettings` to component `WebFoldersPane`

### Test project
[folderspane-split-v7.zip](https://github.com/cuba-platform/cuba/files/3211829/folderspane-split-v7.zip)

## QA
Check the above case with different main window's screens

**Comment by jreznot** [comment]
NPE is thrown during UI tests:
```
2019-05-25 05:46:32.601 WARN  [http-nio-8080-exec-3/app/testUser] com.haulmont.cuba.web.app.login.LoginScreen - Unable to login
java.lang.NullPointerException: null
	at com.haulmont.cuba.web.app.folders.CubaFoldersPane.setVerticalSplitPosition(CubaFoldersPane.java:144) ~[cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.gui.components.mainwindow.WebFoldersPane.applySettings(WebFoldersPane.java:80) ~[cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.screen.ScreenSettings.lambda$applySettings$0(ScreenSettings.java:58) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.ComponentsHelper.__walkComponents(ComponentsHelper.java:294) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.ComponentsHelper.__walkComponents(ComponentsHelper.java:300) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.ComponentsHelper.walkComponents(ComponentsHelper.java:277) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.screen.ScreenSettings.applySettings(ScreenSettings.java:50) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.screen.Screen.applySettings(Screen.java:434) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.components.AbstractWindow.applySettings(AbstractWindow.java:689) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.screen.UiControllerUtils.applySettings(UiControllerUtils.java:110) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.sys.WebScreens.afterShowWindow(WebScreens.java:567) ~[cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.sys.WebScreens.show(WebScreens.java:456) ~[cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.App.createTopLevelWindow(App.java:299) ~[cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.DefaultApp.initializeUi(DefaultApp.java:242) ~[cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.DefaultApp.connectionStateChanged(DefaultApp.java:110) ~[cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170) ~[cuba-global-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.security.ConnectionImpl.fireStateChangeListeners(ConnectionImpl.java:228) ~[cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.security.ConnectionImpl.login(ConnectionImpl.java:106) ~[cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.app.login.LoginScreen.doLogin(LoginScreen.java:340) [cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.app.login.LoginScreen.doLogin(LoginScreen.java:309) [cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.app.login.LoginScreen.login(LoginScreen.java:253) [cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
```

**Comment by GlebDurygin** [comment]
Fix NPE in setVerticalSplitPosition function
