### ISSUE TITLE
Exception report fails to be sent because of restrictions for "From" email header

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2125]
### Environment
- Platform version: 6.8

### Description of the bug or enhancement
Many SMTP servers have restrictions for "From" email headers (to fight spam and fishing).
Basically, you have only one valid "From" address like user@mycompany.com, where user = cuba.email.smtpUser.

If you try to send email on behalf of e.g. From = "alex@gmail.com" or even "anotheruser@mycompany.com" - then SMTP server will simply reject your message.
Production example of exception from GMail SMTP server:
<details>
 <summary>Click to expand</summary>
 
```java
2019-05-15 12:48:48,938 WARN  [http-nio-8080-exec-62/app-core/patrick.xxxxxxx] [com.haulmont.cuba.core.app.Emailer] Unable to send email to 'xxxxxx@haulmont.com'
org.springframework.mail.MailSendException: Failed to close server connection after message failures; nested exception is javax.mail.MessagingException: Can't send command to SMTP host;
  nested exception is:
        java.net.SocketException: Connection closed by remote host. Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 550-5.7.0 Mail relay denied [37.48.xxx.xxx]. Invalid credentials
 for relay for one
550-5.7.0 of the domains in: xxxxxx.yy (as obtained from HELO and MAIL
550-5.7.0 FROM).
550-5.7.0 Email is being sent from a domain or IP address which isn't registered
550-5.7.0 in your G Suite account. Please login to your G Suite account and
550-5.7.0 verify that your sending device IP address has been registered within
550-5.7.0 the G Suite SMTP Relay Settings. For more information, please visit
550 5.7.0  https://support.google.com/a/answer/6140680#maildenied h128sm25243wmh.46 - gsmtp
;
  nested exception is:
        com.sun.mail.smtp.SMTPSenderFailedException: 550-5.7.0 Mail relay denied [37.48.xxx.xx]. Invalid credentials for relay for one
550-5.7.0 of the domains in: xxxxxx.yy (as obtained from HELO and MAIL
550-5.7.0 FROM).
550-5.7.0 Email is being sent from a domain or IP address which isn't registered
550-5.7.0 in your G Suite account. Please login to your G Suite account and
550-5.7.0 verify that your sending device IP address has been registered within
550-5.7.0 the G Suite SMTP Relay Settings. For more information, please visit
550 5.7.0  https://support.google.com/a/answer/6140680#maildenied h128sm25243wmh.46 - gsmtp

        at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:464)
        at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:345)
        at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:340)
        at com.haulmont.cuba.core.app.EmailSender.sendEmail(EmailSender.java:67)
        at com.haulmont.cuba.core.app.Emailer.persistAndSendEmail(Emailer.java:200)
        at com.haulmont.cuba.core.app.Emailer.sendEmail(Emailer.java:104)
        at com.haulmont.cuba.core.app.ExceptionReportServiceBean.sendExceptionReport(ExceptionReportServiceBean.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
        at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:117)
        at sun.reflect.GeneratedMethodAccessor758.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy149.sendExceptionReport(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy786.sendExceptionReport(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.remoting.support.RemoteInvocation.invoke(RemoteInvocation.java:212)
        at com.haulmont.cuba.core.sys.remoting.CubaRemoteInvocationExecutor.invoke(CubaRemoteInvocationExecutor.java:110)
        at org.springframework.remoting.support.RemoteInvocationBasedExporter.invoke(RemoteInvocationBasedExporter.java:78)
        at org.springframework.remoting.support.RemoteInvocationBasedExporter.invokeAndCreateResult(RemoteInvocationBasedExporter.java:114)
        at com.haulmont.taxi.core.common.remoting.TaxiHttpServiceExporter.handleRequest(TaxiHttpServiceExporter.java:58)
        at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at com.haulmont.cuba.core.sys.remoting.RemotingServlet.doService(RemotingServlet.java:152)
        at com.haulmont.taxi.core.sys.remoting.TaxiRemotingServlet.doService(TaxiRemotingServlet.java:27)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239)
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:322)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.mail.MessagingException: Can't send command to SMTP host
        at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:2260)
        at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:2247)
        at com.sun.mail.smtp.SMTPTransport.close(SMTPTransport.java:1288)
        at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:459)
        ... 80 common frames omitted
Caused by: java.net.SocketException: Connection closed by remote host
        at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1547)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
        at com.sun.mail.util.TraceOutputStream.write(TraceOutputStream.java:138)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:2258)
        ... 83 common frames omitted
```
</details>

ExceptionReportServiceBean *causes* above problem because of the following code:
```
            User user = userSessionSource.getUserSession().getUser();
            if (user.getEmail() != null) {
                info.setFrom(user.getEmail());
            }

```
One simply cannot send emails on behalf of any user he wants!
We have suddenly discovered that half of our users' exception reports are not sent because of this problem. See screenshot:
<details>
 <summary>Screenshot</summary>
 
![image](https://user-images.githubusercontent.com/6158807/57773773-db698180-7729-11e9-8c7e-dac42720e3a5.png)

</details>

Proposed solution: do not fill email "From" header with user's email. User's email can be put to email body instead.

**Comment by alexbudarov** [comment]
Related improvement: #610

**Comment by Flaurite** [comment]
### Changes
Added `${userEmail}` to `exception-report-template-body` and removed logic to setting `from` to `Emailnfo`.
Full template:
```
<html>
<body>
<p>${timestamp}</p>
<p>${toHtml(errorMessage)}</p>
<p>${toHtml(stacktrace)}</p>
<p>${userEmail}</p>
</body>
</html>
```
If user has email it will be set to `userEmail`, otherwise `cuba.email.fromAddress` will be used.

### How to test
1. Try to send email - user's email should be used or defalut value from property.
2. Try to replace template by your own and remove `${userEmail}`. You should be able to send email without errors.
3. Ask me about credentials for smtp (if you don't have)

**Comment by alexbudarov** [comment]
@Flaurite If we want to put user details to email - why not add user login, user name?
User email is not mandatory and is not unique.
