### ISSUE TITLE
GuiDevelopmentException: BulkEditor component can be used only in legacy screens based on AbstractWindow

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#2127]
### Environment

- Platform version: 7.0.5
- Client type: Web

### Description of the bug or enhancement

Caused by #2083

BulkEditor always throws the exception (even in legacy windows):

```
com.haulmont.cuba.gui.GuiDevelopmentException: BulkEditor component can be used only in legacy screens based on AbstractWindow
	at com.haulmont.cuba.gui.xml.layout.loaders.BulkEditorLoader.loadComponent(BulkEditorLoader.java:80) ~[cuba-gui-7.0.5.jar:7.0.5]
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:37) ~[cuba-gui-7.0.5.jar:7.0.5]
	at com.haulmont.cuba.gui.xml.layout.loaders.ButtonsPanelLoader.loadComponent(ButtonsPanelLoader.java:61) ~[cuba-gui-7.0.5.jar:7.0.5]
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractTableLoader.loadButtonsPanel(AbstractTableLoader.java:361) ~[cuba-gui-7.0.5.jar:7.0.5]
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractTableLoader.loadComponent(AbstractTableLoader.java:125) ~[cuba-gui-7.0.5.jar:7.0.5]
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:37) ~[cuba-gui-7.0.5.jar:7.0.5]
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:88) ~[cuba-gui-7.0.5.jar:7.0.5]
	at com.haulmont.cuba.gui.xml.layout.loaders.WindowLoader.loadComponent(WindowLoader.java:99) ~[cuba-gui-7.0.5.jar:7.0.5]
	at com.haulmont.cuba.web.sys.WebScreens.loadWindowFromXml(WebScreens.java:354) ~[cuba-web-7.0.5.jar:7.0.5]
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:227) ~[cuba-web-7.0.5.jar:7.0.5]
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:171)
```

See https://www.cuba-platform.ru/discuss/t/oshibka-guidevelopmentexception-bulkeditor-component-can-be-used-only-in-legacy-screens-v-versii-cuba-7-0-5/3069

**Comment by jreznot** [comment]
Commit to master 497ac626
