### ISSUE TITLE
Unclear exception if table has editable column and this column is not permitted to read

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#213]
- Create a role that denies permission to Read roles
- Login as a user with the new role
- Open Roles browser:
```
11:51:31.666 ERROR com.haulmont.cuba.web.log.AppLog - Exception in com.haulmont.cuba.web.toolkit.ui.CubaMenuBar:
java.lang.IllegalArgumentException: Ids must exist in the Container and it must be not a generated column, incorrect id: defaultRole
        at com.haulmont.cuba.web.toolkit.ui.CubaTable.setEditableColumns(CubaTable.java:248)
        at com.haulmont.cuba.web.gui.components.WebAbstractTable.setEditableColumns(WebAbstractTable.java:355)
        at com.haulmont.cuba.web.gui.components.WebAbstractTable.setDatasource(WebAbstractTable.java:819)
        at com.haulmont.cuba.gui.xml.layout.loaders.AbstractTableLoader.loadComponent(AbstractTableLoader.java:148)
        at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:39)
        at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:78)
        at com.haulmont.cuba.gui.xml.layout.loaders.WindowLoader.loadComponent(WindowLoader.java:79)
        at com.haulmont.cuba.gui.WindowManager.createWindow(WindowManager.java:385)
        at com.haulmont.cuba.gui.WindowManager.openWindow(WindowManager.java:560)
        at com.haulmont.cuba.gui.config.MenuCommand.execute(MenuCommand.java:99)
        at com.haulmont.cuba.web.sys.MenuBuilder$1.menuSelected(MenuBuilder.java:163)
        at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:207)
        at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:609)
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:428)
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:79)
        at com.haulmont.cuba.web.sys.CubaVaadinServletService$CubaUidlRequestHandler.lambda$synchronizedHandleRequest$82(CubaVaadinServletService.java:306)
        at com.haulmont.cuba.web.sys.CubaVaadinServletService.withUserSession(CubaVaadinServletService.java:187)
        at com.haulmont.cuba.web.sys.CubaVaadinServletService$CubaUidlRequestHandler.synchronizedHandleRequest(CubaVaadinServletService.java:306)
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1409)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:369)
        at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:242)
        at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:165)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.haulmont.cuba.web.sys.CubaHttpFilter.handleNotFiltered(CubaHttpFilter.java:110)
        at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:97)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

---
Original issue: https://youtrack.haulmont.com/issue/PL-7189

## Updates
* If the table has editable column and this column is not permitted to read or update, then this column becomes non-editable, and a message is added to the log: 
`Editable column '{columnId}' is not permitted to read or update`
* If the entity is not permitted to read or update and the table has editable columns, then these columns becomes non-editable, and a message is added to the log: 
`Entity '{entity_name}' is not permitted to read or update`

## QA
Checklist:
* Check when the entity is not permitted to read or update.
1) Create a role that denies permission to Read or Update roles
2) Login as a user with the new role
3) Open Roles browser
* Check when the editable column is not permitted to read or update.
1) Make the column group editable in User browser
2) Create a role that denies permission to Read or Update attribute group for entity User
3) Login as a user with the new role
4) Open User browser

**Comment by sukhova** [comment]
[prj213.zip](https://github.com/cuba-platform/cuba/files/3329289/prj213.zip)

See the project in the attach or reproduce these steps:

1) Create an entity with an association attribute, e.g., the `user` attribute
2) Create editor and browser screens for it
3) Make the `user` column editable
4) Define the `optionsContainer` and the `captionProperty` attributes for this column
5) Create a role that denies permission to Update your entity or the `user` attribute
6) Login as a user with the new role
7) Open your entity browser

**AR**:

```
java.lang.IllegalArgumentException: Can't find getter for property 'login' at class com.company.prj213.entity.Customer
	at com.haulmont.chile.core.model.utils.MethodsCache.invokeGetter(MethodsCache.java:68)
	at com.haulmont.chile.core.model.impl.AbstractInstance.getValue(AbstractInstance.java:96)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.getValue(BaseGenericIdEntity.java:146)
	at com.haulmont.chile.core.model.utils.InstanceUtils.getValueEx(InstanceUtils.java:153)
	at com.haulmont.chile.core.model.utils.InstanceUtils.getValueEx(InstanceUtils.java:117)
	at com.haulmont.chile.core.model.impl.AbstractInstance.getValueEx(AbstractInstance.java:133)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.formatCellValue(WebAbstractTable.java:1144)
	at com.haulmont.cuba.web.widgets.CubaTable.formatPropertyValue(CubaTable.java:317)
	at com.haulmont.cuba.web.widgets.CubaTable.getPropertyValue(CubaTable.java:233)
	at com.vaadin.v7.ui.Table.parseItemIdToCells(Table.java:2355)
	at com.vaadin.v7.ui.Table.getVisibleCellsNoCache(Table.java:2203)
	at com.vaadin.v7.ui.Table.refreshRenderedCells(Table.java:1746)
	at com.haulmont.cuba.web.widgets.CubaGroupTable.refreshRenderedCells(CubaGroupTable.java:747)
	at com.vaadin.v7.ui.Table.attach(Table.java:4260)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.ui.AbstractComponent.setParent(AbstractComponent.java:571)
	at com.vaadin.ui.AbstractComponentContainer.addComponent(AbstractComponentContainer.java:178)
	at com.vaadin.ui.TabSheet.addTab(TabSheet.java:397)
	at com.vaadin.ui.TabSheet.addTab(TabSheet.java:433)
	at com.vaadin.ui.TabSheet.addTab(TabSheet.java:414)
	at com.haulmont.cuba.web.widgets.CubaMainTabSheet$TabSheetBehaviourImpl.addTab(CubaMainTabSheet.java:464)
	at com.haulmont.cuba.web.sys.WebScreens.createNewTabLayout(WebScreens.java:1604)
	at com.haulmont.cuba.web.sys.WebScreens.showNewTabWindow(WebScreens.java:1561)
	at com.haulmont.cuba.web.sys.WebScreens.show(WebScreens.java:444)
	at com.haulmont.cuba.web.sys.WebScreens.showFromNavigation(WebScreens.java:528)
	at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:213)
	at com.haulmont.cuba.web.sys.MenuBuilder$MenuCommandExecutor.accept(MenuBuilder.java:256)
	at com.haulmont.cuba.web.sys.MenuBuilder$MenuCommandExecutor.accept(MenuBuilder.java:241)
	at com.haulmont.cuba.web.gui.components.mainwindow.WebAppMenu$MenuItemImpl.menuSelected(WebAppMenu.java:435)
	at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:225)
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:611)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:457)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:400)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dtsaryov** [comment]
@sukhova 

The case is not related to issue changes. Will investigate the problem

**Comment by dtsaryov** [comment]
@sukhova consider #2224
