### ISSUE TITLE
The exception occurs after clicking on the open button in SuggestionPickerField in the new screens

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#2131]
Platform 7.0+

1) Create a new blank screen
2) Add a suggestionPickerField to the screen
3) Specify metaclass or DataContainer for it
4) Start app server and open the screen
5) Select something in the suggestionPickerField
6) Click the open button
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/ccd730bf-8b29-4628-93c5-7b17f62c3473)

AR: 
```
java.lang.ClassCastException: com.company.sugfld.web.screens.NewScreen cannot be cast to com.haulmont.cuba.gui.screen.compatibility.LegacyFrame
	at com.haulmont.cuba.gui.components.PickerField$OpenAction.actionPerform(PickerField.java:715)
	at com.haulmont.cuba.web.gui.components.WebPickerField.lambda$setPickerButtonAction$0(WebPickerField.java:328)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

## QA
Check the above case

**Comment by jreznot** [comment]
Most likely, the platform creates incorrect action instances
