### ISSUE TITLE
Default screen functionality doesn't consider both declared id and screen

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#2150]
A topic on support forum: [Error opening Help/Settings window](https://www.cuba-platform.com/discuss/t/error-opening-help-settings-window/9192)

### Environment

- Platform version: 6.10
- Client type: Web

### Description of the bug or enhancement

Default screen functionality doesn't consider when both "id" and "screen" are defined for menu item.

- Minimal reproducible example

1. Declare two menu items with different ids but with the same screen
2. Declare few params for the second menu item
3. Choose as a default screen item with params
4. Relogin

- Expected behavior

Settings screen is successfully opened, chosen screen is opened, params are passed

- Actual behavior

**In CUBA 6.10:** screen will be opened, but params will not be passed

**In CUBA 7:** `IllegalArgumentException` will be thrown when the `Settings` screen will be opened

## Updates
The user can declare menu items with different ids and with the same screen. But the following information will be recorded in the log: `Menu contains items with the same screen: 'screen_id'. The entry with id 'menu_id' will be ignored`
When you set the default screen, the settings screen is successfully opened, the chosen screen by screen id is opened, but you can't pass the params into the default screen. Because the default screen setting considers only the screen identifier.
## QA
Check that when creating two menu items with different ids and with the same screen:
1) does not appear an error when opening the settings screen;
2) message is written to the log;
3) you can select this screen as the default screen.

**Comment by natfirst** [comment]
Same error occurs with the following menu config (platform 7.0 and higher)
```
<item screen="defscrtest_NewScreen" id="fist-scr"/>
        <item screen="defscrtest_NewScreen"/>
```
```
java.lang.IllegalArgumentException: Multiple entries with same value: New Screen=defscrtest_NewScreen and Second screen=defscrtest_NewScreen
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
	at com.google.common.collect.RegularImmutableBiMap.checkNoConflictInValueBucket(RegularImmutableBiMap.java:131)
	at com.google.common.collect.RegularImmutableBiMap.fromEntryArray(RegularImmutableBiMap.java:89)
	at com.google.common.collect.RegularImmutableBiMap.fromEntries(RegularImmutableBiMap.java:58)
	at com.google.common.collect.ImmutableBiMap.copyOf(ImmutableBiMap.java:368)
	at com.google.common.collect.ImmutableBiMap.copyOf(ImmutableBiMap.java:340)
	at com.haulmont.cuba.gui.components.OptionsField.setOptionsMap(OptionsField.java:73)
	at com.haulmont.cuba.web.app.ui.core.settings.SettingsWindow.initDefaultScreenField(SettingsWindow.java:212)
	at com.haulmont.cuba.web.app.ui.core.settings.SettingsWindow.init(SettingsWindow.java:202)
	at com.haulmont.cuba.gui.components.AbstractWindow.init(AbstractWindow.java:96)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:128)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:58)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:248)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:171)
	at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:212)
	at com.haulmont.cuba.web.sys.MenuBuilder$MenuCommandExecutor.accept(MenuBuilder.java:256)
	at com.haulmont.cuba.web.sys.MenuBuilder$MenuCommandExecutor.accept(MenuBuilder.java:241)
	at com.haulmont.cuba.web.gui.components.mainwindow.WebAppMenu$MenuItemImpl.menuSelected(WebAppMenu.java:435)
	at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:225)
```

**Comment by GlebDurygin** [comment]
The error has been fixed. 
Removed the check for equality of the id and screen id.
