### ISSUE TITLE
Standalone UberJar applications cannot start with the front module

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#2161]
Platform 7.1+

1) Create a new project
2) Add frontend module into it
3) Create buildUberJar task with (without singleMode option)
4) Try to run JARs

AR: At the attempt to start app.jar exception occurred

Probably relates to this [issue](https://github.com/cuba-platform/cuba-gradle-plugin/issues/105)

```
11:13:31.722 INFO  c.h.frontservlet.AppFrontServlet        - Initializing Servlet 'app_front_servlet'
11:13:31.742 WARN  o.s.w.c.s.AnnotationConfigWebApplicationContext- Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.haulmont.frontservlet.AppFrontConfig]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class com.haulmont.frontservlet.AppFrontConfig
11:13:31.745 ERROR c.h.frontservlet.AppFrontServlet        - Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.haulmont.frontservlet.AppFrontConfig]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class com.haulmont.frontservlet.AppFrontConfig
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:181) ~[shared/:na]        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:315) ~[shared/:na]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232) ~[shared/:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[shared/:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95) ~[shared/:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705) ~[shared/:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[shared/:na]
        at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:701) ~[shared/:na]
        at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:667) ~[shared/:na]
        at com.haulmont.frontservlet.AppFrontServlet.initWebApplicationContext(AppFrontServlet.java:70) [classes/:na]
        at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:529) ~[shared/:na]
        at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:169) [shared/:na]
        at javax.servlet.GenericServlet.init(GenericServlet.java:244) [app.jar:na]
        at com.haulmont.frontservlet.AppFrontServlet.init(AppFrontServlet.java:89) [classes/:na]
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:643) [app.jar:na]
Caused by: java.lang.IllegalStateException: Failed to introspect annotated methods on class com.haulmont.frontservlet.AppFrontConfig
        at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:169) ~[shared/:na]
        at org.springframework.context.annotation.ConfigurationClassParser.retrieveBeanMethodMetadata(ConfigurationClassParser.java:392) ~[shared/:na]
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:317) ~[shared/:na]
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242) ~[shared/:na]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:199) ~[shared/:na]        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:167) ~[shared/:na]        ... 36 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/ui/freemarker/FreeMarkerConfigurationFactory
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_171]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_171]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_171]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_171]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_171]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_171]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_171]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_171]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411) ~[na:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_171]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_171]
        at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_171]
        at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:158) ~[na:na]
        ... 41 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.ui.freemarker.FreeMarkerConfigurationFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]
        ... 57 common frames omitted
```

**Comment by jreznot** [comment]
Studio did not add rest-api add-on

**Comment by jreznot** [comment]
Most likely, there is a problem with class loading of front context in Jetty. It seems that UberJAR building task do not register spring-context-config in context dependencies.

**Comment by jreznot** [comment]
Normal cuba contexts have cuba-app-libs.txt file with all dependencies, but front does not. And it can get spring-context-support only from shared.
