### ISSUE TITLE
NPE occurs when selecting entity list param dependent on other param in Filter

### ISSUE THREAD

**Issue by soraksh** [cuba-platform/cuba#2181]
### Environment

- Platform version: 7.1
- Client type: Web

### Description

Minimal reproducible example:

- Create custom condition for some Filter with `Entity` param type
- Create another custom condition with `Entity` param type. Set `Where` clause using param from first condition. Set `List` checkbox to `true`.
- Try to select value for second param

Actual behavior:
```
java.lang.NullPointerException
	at com.haulmont.cuba.gui.data.impl.AbstractCollectionDatasource.getQueryParameters(AbstractCollectionDatasource.java:262)
	at com.haulmont.cuba.gui.data.impl.AbstractCollectionDatasource.createDataQuery(AbstractCollectionDatasource.java:511)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.beforeLoadData(CollectionDatasourceImpl.java:645)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.loadData(CollectionDatasourceImpl.java:619)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.refresh(CollectionDatasourceImpl.java:165)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.refresh(CollectionDatasourceImpl.java:123)
	at com.haulmont.cuba.gui.dynamicattributes.DynamicAttributesGuiTools.createOptionsDatasourceForLookup(DynamicAttributesGuiTools.java:308)
	at com.haulmont.cuba.gui.components.listeditor.ListEditorPopupWindow.createComponentForEntity(ListEditorPopupWindow.java:289)
	at com.haulmont.cuba.gui.components.listeditor.ListEditorPopupWindow.initAddComponentLayout(ListEditorPopupWindow.java:170)
	at com.haulmont.cuba.gui.components.listeditor.ListEditorPopupWindow.init(ListEditorPopupWindow.java:128)
	at com.haulmont.cuba.gui.components.AbstractWindow.init(AbstractWindow.java:99)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:128)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:60)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:244)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:166)
	at com.haulmont.cuba.gui.components.listeditor.ListEditorDelegateImpl.openEditor(ListEditorDelegateImpl.java:128)
	at com.haulmont.cuba.gui.components.listeditor.ListEditorDelegateImpl.lambda$init$0(ListEditorDelegateImpl.java:97)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.web.gui.components.WebAbstractComponent.publish(WebAbstractComponent.java:92)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:68)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.GeneratedMethodAccessor151.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
...
```

If you set `List` checkbox to `false` filter works fine.

**Comment by Mihail063** [comment]
Relates to #2256
