### ISSUE TITLE
Message keys in bean validation annotations don't support some cases

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#2228]
### Environment

- Platform version: 7.1-SNAPSHOT

### Description of the bug or enhancement

**Case1**:

1) Create a project
2) Create an entity 
3) Create an attribute with 
```
@NotNull(message = "{msg://My message}")
```
4) Create a message in the `messages.properties` file:
```
My\ message=My message
```
5) Create an editor screen
6) Run the application
7) Open the editor screen

**AR**:
```
java.lang.UnsupportedOperationException: Unsupported resource string format: 'msg://My message', messagesPack=null
	at com.haulmont.cuba.core.global.MessageTools.loadString(MessageTools.java:142)
	at com.haulmont.cuba.core.global.MessageTools.loadString(MessageTools.java:108)
	at com.haulmont.cuba.core.global.MessageTools.loadString(MessageTools.java:83)
	at com.haulmont.cuba.core.global.MessageTools.getNotNullMessage(MessageTools.java:338)
	at com.haulmont.cuba.core.global.MessageTools.getDefaultRequiredMessage(MessageTools.java:314)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder.initRequired(ValueBinder.java:123)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder.bind(ValueBinder.java:85)
	at com.haulmont.cuba.web.gui.components.WebAbstractValueComponent.setValueSource(WebAbstractValueComponent.java:56)
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractComponentLoader.lambda$loadContainer$0(AbstractComponentLoader.java:968)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractComponentLoader.loadContainer(AbstractComponentLoader.java:967)
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractFieldLoader.loadComponent(AbstractFieldLoader.java:38)
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractTextFieldLoader.loadComponent(AbstractTextFieldLoader.java:33)
	at com.haulmont.cuba.gui.xml.layout.loaders.TextFieldLoader.loadComponent(TextFieldLoader.java:26)
	at com.haulmont.cuba.gui.xml.layout.loaders.FormLoader.loadComponent(FormLoader.java:166)
	at com.haulmont.cuba.gui.xml.layout.loaders.FormLoader.loadComponents(FormLoader.java:151)
	at com.haulmont.cuba.gui.xml.layout.loaders.FormLoader.loadColumns(FormLoader.java:128)
	at com.haulmont.cuba.gui.xml.layout.loaders.FormLoader.loadComponent(FormLoader.java:90)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:37)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:75)
	at com.haulmont.cuba.gui.xml.layout.loaders.WindowLoader.loadComponent(WindowLoader.java:93)
	at com.haulmont.cuba.web.sys.WebScreens.loadWindowFromXml(WebScreens.java:356)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:223)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:166)
	at com.haulmont.cuba.gui.builders.EditorBuilderProcessor.createScreen(EditorBuilderProcessor.java:286)
	at com.haulmont.cuba.gui.builders.EditorBuilderProcessor.buildEditor(EditorBuilderProcessor.java:88)
	at com.haulmont.cuba.gui.builders.EditorBuilder.build(EditorBuilder.java:359)
	at com.haulmont.cuba.gui.actions.list.CreateAction.actionPerform(CreateAction.java:110)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:65)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

This case is repeated for the next keys looking like:
`my$key`
`my_key`

For **other annotations** (`@NotEmpty`, `@NotBlank` and so on) there are the next cases:

1) Create a project
2) Create an entity 
3) Create an attribute with 
```
@NotEmpty(message = "{msg://My message}")
```
4) Create a message in the `messages.properties` file:
```
My\ message=This is my very long message
```
5) Create an editor screen
6) Run the application
7) Open the editor screen
8) Leave the field blank and try to save the entity

**AR**:
Notification is:
`{msg://My message}`

**ER**:
Notification should be:
`This is my very long message`

This case is repeated for the next keys looking like:
`my$key`
`my_key`

**Comment by sukhova** [comment]
This ticket is associated with https://github.com/cuba-platform/cuba-gradle-plugin/issues/46

**Comment by GlebDurygin** [comment]
The user cannot use literal `$` and `space` in the annotation message parameter (see https://beanvalidation.org/2.0/spec/#validationapi-message).
The literal `_` can be used in the message parameter.
