### ISSUE TITLE
IllegalArgumentException occurs after trying to save a filter dependent on another parameter in the filter

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/cuba#2256]
### Environment

- Platform version: 7.1.0

### Description of the bug or enhancement

1. Create a new entity with browse and editor screens
2. Create a new instance of the entity
3. Add the first search condition with the following parameters:
Where: `{E}.id= ?`
Param type: Entity
List: false
Entity/Enum: Select the added entity from the previous step
Param Where: empty
4. Add the second search condition with the following parameters:
Where: `{E}.id in ?`
Param type: Entity
List: true
Entity/Enum: Select the added entity from the previous step
Param Where: `{E} = :` Select the added condition from the previous step by Ctrl+Space
5. Select the added instance from the previous step in the first condition
6.  Select the added instance from the previous step in the second condition
- Actual behavior
IllegalArgumentException occurs after trying to save the second condition

```
java.lang.IllegalArgumentException: You have attempted to set a value of type class java.util.ArrayList for parameter filter_WKFcwcIjJl53407 with expected type of class java.util.UUID from query string select e from untitled7_Custtomer e where (e.id = :filter_wSITxiGSBK40057 and e.id = :filter_WKFcwcIjJl53407).
	at org.eclipse.persistence.internal.jpa.QueryImpl.setParameterInternal(QueryImpl.java:946)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setParameter(EJBQueryImpl.java:611)
	at com.haulmont.cuba.core.sys.QueryImpl$Param.apply(QueryImpl.java:804)
	at com.haulmont.cuba.core.sys.QueryImpl.getQuery(QueryImpl.java:157)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultList(QueryImpl.java:406)
	at com.haulmont.cuba.core.app.RdbmsStore.executeQuery(RdbmsStore.java:812)
	at com.haulmont.cuba.core.app.RdbmsStore.getResultList(RdbmsStore.java:720)
	at com.haulmont.cuba.core.app.RdbmsStore.loadList(RdbmsStore.java:228)
	at com.haulmont.cuba.core.app.DataManagerBean.loadList(DataManagerBean.java:78)
	at com.haulmont.cuba.core.app.DataServiceBean.loadList(DataServiceBean.java:54)
	at sun.reflect.GeneratedMethodAccessor156.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
...
```
Relates to: #2181

**Comment by andreysubbotin** [comment]
Use `{E}.id = :` for param where
