### ISSUE TITLE
Add ability to specify position of the dynamic attributes in the DynamicAttributesPanel

### ISSUE THREAD

**Issue by invviz** [cuba-platform/cuba#2310]
### Environment

- Platform version: 7.1

### Description of the bug or enhancement

You should be able to specify the position (column and row) at which the dynamic attribute should be located inside the DynamicAttributesPanel. 

Add a tab to the category editing screen with the ability to customize the location of each dynamic attribute of this category.

**Comment by invviz** [comment]
Feature branch: https://github.com/cuba-platform/cuba/tree/feature/dynamic_attributes_settings

**Comment by invviz** [comment]
A new tab 'Attributes Location' has been added to the 'Category editor' page. This tab displays the location of the attributes in the DynamicAttributesPanel. To change the location of an attribute, drag it to the desired column and the desired line. After making the changes, click on the "Save configuration" button.

Example:
1) First opening of the tab:
![изображение](https://user-images.githubusercontent.com/7254454/62602303-81312480-b904-11e9-9f51-2b4714246fc3.png)

2) After making changes:
![изображение](https://user-images.githubusercontent.com/7254454/62602459-d79e6300-b904-11e9-928b-c0462f512e50.png)

3) Resulting DynamicAttributesPanel:
![изображение](https://user-images.githubusercontent.com/7254454/62602527-0caab580-b905-11e9-8f29-42b2b60f0729.png)

**Comment by natfirst** [comment]
1. Set `columnsCollapsingAllowed` to false for all DataGrids in the screen (to hide the unnecessary gear)
![image](https://user-images.githubusercontent.com/17950251/62950399-ffa42f80-bdf8-11e9-87cd-8bbb93228d7c.png)

2. Align `Save configuration` button and column table in havana and halo themes
![image](https://user-images.githubusercontent.com/17950251/62945842-93bdc900-bdf0-11e9-90e6-415d5229e55a.png)

3.Exception
- Create categorized entity, add dynamicAttributesPanel to the edit screen
- Create category and several attributes
- Configure attributes location, save and apply all changes
- Create entity instance with some dynamic attributes values
- Change attributes location configuration, save and apply all changes
- Try to open entity instance for edit 
```
java.lang.NullPointerException
	at com.haulmont.cuba.core.app.dynamicattributes.DynamicAttributesManager.lambda$loadAttributeValues$6(DynamicAttributesManager.java:430)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Vector$VectorSpliterator.forEachRemaining(Vector.java:1440)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.haulmont.cuba.core.app.dynamicattributes.DynamicAttributesManager.loadAttributeValues(DynamicAttributesManager.java:431)
	at com.haulmont.cuba.core.app.dynamicattributes.DynamicAttributesManager.handleAttributeValuesForIds(DynamicAttributesManager.java:393)
	at com.haulmont.cuba.core.app.dynamicattributes.DynamicAttributesManager.doFetchDynamicAttributes(DynamicAttributesManager.java:374)
	at com.haulmont.cuba.core.app.dynamicattributes.DynamicAttributesManager.lambda$fetchDynamicAttributes$2(DynamicAttributesManager.java:244)
	at com.google.common.collect.Maps$KeySet.lambda$forEach$0(Maps.java:3705)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at com.google.common.collect.Maps$KeySet.forEach(Maps.java:3705)
	at com.haulmont.cuba.core.app.dynamicattributes.DynamicAttributesManager.fetchDynamicAttributes(DynamicAttributesManager.java:242)
	at com.haulmont.cuba.core.app.RdbmsStore.load(RdbmsStore.java:156)
	at com.haulmont.cuba.core.app.DataManagerBean.load(DataManagerBean.java:67)
	at com.haulmont.cuba.core.app.DataServiceBean.load(DataServiceBean.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:116)
	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy194.load(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154)
	at com.sun.proxy.$Proxy34.load(Unknown Source)
	at com.haulmont.cuba.client.sys.DataManagerClientImpl.load(DataManagerClientImpl.java:51)
	at com.haulmont.cuba.gui.model.impl.InstanceLoaderImpl.load(InstanceLoaderImpl.java:98)
	at com.haulmont.cuba.gui.model.impl.ScreenDataImpl.loadAll(ScreenDataImpl.java:80)
	at com.haulmont.cuba.gui.model.impl.AnnotationBasedLoaderBeforeShow.loadData(AnnotationBasedLoaderBeforeShow.java:36)
	at com.haulmont.cuba.web.sys.WebScreens.loadDataBeforeShow(WebScreens.java:549)
	at com.haulmont.cuba.web.sys.WebScreens.show(WebScreens.java:437)
	at com.haulmont.cuba.gui.screen.Screen.show(Screen.java:309)
	at com.haulmont.cuba.gui.actions.list.EditAction.actionPerform(EditAction.java:144)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.handleClickAction(WebAbstractTable.java:1267)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.lambda$initComponent$db766529$1(WebAbstractTable.java:1039)
	at sun.reflect.GeneratedMethodAccessor176.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041)
	at com.vaadin.v7.ui.Table.handleClickEvent(Table.java:3126)
	at com.vaadin.v7.ui.Table.changeVariables(Table.java:2918)
	at com.haulmont.cuba.web.widgets.CubaTable.changeVariables(CubaTable.java:329)
	at com.haulmont.cuba.web.widgets.CubaGroupTable.changeVariables(CubaGroupTable.java:298)
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:611)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:457)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:400)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```
4. Attributes are duplicated sometimes instead of reordering (see gif)
![reorder](https://user-images.githubusercontent.com/17950251/62950980-2e6ed580-bdfa-11e9-93fd-dadf38d5174a.gif)

**Comment by natfirst** [comment]
Case 3 still reproduced.

Maybe problem in AttributesLocationFrame:
```
protected List<CategoryAttribute> sourceDataContainer = new ArrayList<>();
protected List<List<CategoryAttribute>> dataContainers = new ArrayList<>();
protected List<DataGrid<CategoryAttribute>> childComponents = new ArrayList<>();
```
Use Set instead of List

**Comment by andreysubbotin** [comment]
Created issue #2374 for case 3
