### ISSUE TITLE
Use own database connection pool

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#2315]
- By default, use own database connection pool configurable via app properties
- Optionally use a pool provided by app server
- For backward compatibility, current datasource settings should work as is

**Comment by alexbudarov** [comment]
consider previously discussed possibility to unify database parameters (dev environment) with ones defined in build.gradle - to remove duplication

**Comment by andreysubbotin** [comment]
Implementation details: 
- Introduce new property `cuba.dataSourceType` or `cuba.dataSourceType_<additional store name>`. Property stores datasource type: 
  - `jndi` - create datasource from JNDI
  - `application` - create datasource from a config defined in a application properties
  - 'auto` - default value. Try to create datasource from JNDI. If datasource doesn't exist, create from a config defined in a application properties. Throw error if we could't create datasource. 
- Add ability to read properties `cuba.dataSource.<propertyName>` or `cuba.dataSource_<additional store name>.<propertyName>` from application properties of a core module. Use  this properties for datasource configuration. `propertyName`s equal Hikary pool property names e.g.  `cuba.dataSource.jdbcUrl`

**Comment by belyaev-andrey** [comment]
Please consider implementing an option to get environment variables to use in datasource connection properties. Or at least check this: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/java-rds.html#java-rds-tomcat

**Comment by andreysubbotin** [comment]
Studio issue: https://youtrack.haulmont.com/issue/STUDIO-7220

**Comment by alexbudarov** [comment]
Application fails to start if we don't define "jndiNameAppProperty" bean property in spring.xml for "Application" additional data store:
```
<bean id="cubaDataSource_compkey" class="com.haulmont.cuba.core.sys.CubaDataSourceFactoryBean">
        <property name="storeName" value="compkey"/>
    </bean>

cuba.dataSourceProvider_compkey=application
cuba.dataSource_compkey.jdbcUrl=jdbc:postgresql://localhost/compkey
cuba.dataSource_compkey.username=cuba
cuba.dataSource_compkey.password=cuba
cuba.dataSource_compkey.dbName=compkey
cuba.dataSource_compkey.host=localhost
cuba.dataSource_compkey.port=localhost
cuba.additionalStores=compkey
cuba.persistenceConfig_compkey=+com/company/kcompkey2/compkey-persistence.xml
cuba.dbmsType_compkey=postgres

```

exception:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory_compkey' defined in class path resource [com/company/kcompkey2/spring.xml]: Cannot resolve reference to bean 'cubaDataSource_compkey' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cubaDataSource_compkey' defined in class path resource [com/company/kcompkey2/spring.xml]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Null key passed as parameter
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1706) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1451) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108) ~[spring-context-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.context.support.AbstractRefreshableConfigApplicationContext.afterPropertiesSet(AbstractRefreshableConfigApplicationContext.java:154) ~[spring-context-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at com.haulmont.cuba.core.sys.CubaClassPathXmlApplicationContext.<init>(CubaClassPathXmlApplicationContext.java:39) ~[cuba-global-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.core.sys.CubaCoreApplicationContext.<init>(CubaCoreApplicationContext.java:32) ~[cuba-core-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.core.sys.AppContextLoader.createApplicationContext(AppContextLoader.java:112) [cuba-core-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.core.sys.AppContextLoader.createApplicationContext(AppContextLoader.java:42) [cuba-core-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.core.sys.AbstractAppContextLoader.initAppContext(AbstractAppContextLoader.java:65) ~[cuba-global-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.core.sys.AbstractWebAppContextLoader.contextInitialized(AbstractWebAppContextLoader.java:83) ~[cuba-global-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.core.sys.AppContextLoader.contextInitialized(AppContextLoader.java:51) [cuba-core-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4685) [catalina.jar:9.0.27]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5146) [catalina.jar:9.0.27]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.27]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717) [catalina.jar:9.0.27]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690) [catalina.jar:9.0.27]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705) [catalina.jar:9.0.27]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1133) [catalina.jar:9.0.27]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1867) [catalina.jar:9.0.27]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.27]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) [na:1.8.0_201]
	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1045) [catalina.jar:9.0.27]
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:429) [catalina.jar:9.0.27]
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576) [catalina.jar:9.0.27]
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309) [catalina.jar:9.0.27]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) [catalina.jar:9.0.27]
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423) [catalina.jar:9.0.27]
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366) [catalina.jar:9.0.27]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936) [catalina.jar:9.0.27]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) [catalina.jar:9.0.27]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.27]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) [catalina.jar:9.0.27]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) [catalina.jar:9.0.27]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.27]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [na:1.8.0_201]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) [catalina.jar:9.0.27]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) [catalina.jar:9.0.27]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.27]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421) [catalina.jar:9.0.27]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.27]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) [catalina.jar:9.0.27]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.27]
	at org.apache.catalina.startup.Catalina.start(Catalina.java:633) [catalina.jar:9.0.27]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:344) [bootstrap.jar:9.0.27]
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:475) [bootstrap.jar:9.0.27]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cubaDataSource_compkey' defined in class path resource [com/company/kcompkey2/spring.xml]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Null key passed as parameter
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	... 61 common frames omitted
Caused by: java.lang.IllegalArgumentException: Null key passed as parameter
	at com.haulmont.cuba.core.sys.AppProperties.getProperty(AppProperties.java:102) ~[cuba-global-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.core.sys.AppContext.getProperty(AppContext.java:119) ~[cuba-global-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.core.sys.CubaDataSourceFactoryBean.afterPropertiesSet(CubaDataSourceFactoryBean.java:59) ~[cuba-core-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	... 68 common frames omitted

```

**Comment by IskandarovRost** [comment]
MariaDb and probably Redshift are not supported.
1) Create a new project
2) Switch the main Datastore DBMS type to MariaDB
3) Using JNDI: Generate Db scripts, Create database start the server and ensure everything is OK
4) Change the main datastore to "Application". Save.
![image](https://user-images.githubusercontent.com/19840141/71097297-3afca380-21c9-11ea-8f09-e78012eb9d69.png)


5) Start the application
**AR:** the application does not work

```
19:10:21.305 ERROR com.zaxxer.hikari.util.PropertyElf      - Failed to set property driverClassName on target class com.zaxxer.hikari.HikariConfig
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_221]
	at com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:150) [HikariCP-3.4.1.jar:na]
	at com.zaxxer.hikari.util.PropertyElf.lambda$setTargetFromProperties$0(PropertyElf.java:59) [HikariCP-3.4.1.jar:na]
	at java.util.Hashtable.forEach(Hashtable.java:879) ~[na:1.8.0_221]
	at com.zaxxer.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:54) [HikariCP-3.4.1.jar:na]
	at com.zaxxer.hikari.HikariConfig.<init>(HikariConfig.java:134) ~[HikariCP-3.4.1.jar:na]
	at com.haulmont.cuba.core.sys.DataSourceProvider.getConnectionPoolConfig(DataSourceProvider.java:146) ~[cuba-core-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.core.sys.DataSourceProvider.getApplicationDataSource(DataSourceProvider.java:120) ~[cuba-core-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.core.sys.DataSourceProvider.getDataSource(DataSourceProvider.java:80) ~[cuba-core-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.core.sys.CubaDataSourceFactoryBean.afterPropertiesSet(CubaDataSourceFactoryBean.java:60) ~[cuba-core-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	
........

Caused by: java.lang.RuntimeException: Failed to load driver class com.mysql.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:485) ~[HikariCP-3.4.1.jar:na]
	... 243 common frames omitted
```

**Comment by IskandarovRost** [comment]
Unneccessary connection params are applied for MariaDB (and other MySQL inheritors) when running _without jdbcUrl_

1) For MariaDb adjust connection params _without jdbcUrl_
```
cuba.dbmsType = mysql

cuba.dataSourceProvider=application
#cuba.dataSource.jdbcUrl=jdbc:mariadb://localhost/maria7
cuba.dataSource.username=root
cuba.dataSource.password=root
cuba.dataSource.dbName=maria7
cuba.dataSource.host=localhost
cuba.dataSource.port=

cuba.dataSource.driverClassName = org.mariadb.jdbc.Driver
```
2) Debug the application. DataSourceProvider.constructJdbcUrl

**AR:** Exessive "?useSSL=false&allowMultiQueries=true&serverTimezone=UTC"; is added.
When using JNDI such params are not applied _for MariaDB_ and it works OK.
![image](https://user-images.githubusercontent.com/19840141/71260542-85f6f200-2354-11ea-91c1-53437894ee29.png)

**Comment by andreysubbotin** [comment]
* Specify `driverClassName` and  `jdbcUrl` properties for application datasource in an app.properties. Sample: 
   ```
   cuba.dataSource.jdbcUrl=jdbc:mariadb://localhost/mariadbtest?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
   cuba.dataSource.driverClassName=org.mariadb.jdbc.Driver
   ```
* Specify `masterUrl` for createDb task. `timeStampType` isn't required for createDb/updateDb tasks. Sample:
   ```
    task createDb(dependsOn: assembleDbScripts, description: 'Creates local database', type: CubaDbCreation) {
        masterUrl = 'jdbc:mariadb://localhost?useSSL=false&allowMultiQueries=true&serverTimezone=UTC'
    }

    task updateDb(dependsOn: assembleDbScripts, description: 'Updates local database', type: CubaDbUpdate) {
    }
   ```

Studio issue: https://youtrack.cuba-platform.com/issue/STUDIO-7497
