### ISSUE TITLE
Support 12 hours format for TimeField

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba#2347]
https://www.cuba-platform.com/discuss/t/localtime-illegalargumentexception/9811

### Description of the bug or enhancement

Currently `hh:mm a` time format doesn't work. Let's implement support for 12 hours format with AM/PM part represented as a separate combo box.

Upd:
Provide a separate attribute with a type such as `FORMAT_12_H`, `FORMAT_24_H`.

Upd2:
`DateField` should support 12 hours format either.

### Updates

12h time mode is supported for `DateField` and `TimeField` components. This mode is supported as additional dropdown next to inputs and automatic conversion 24h time values into 12h format.

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/eee8e3f4-9690-410f-9489-645616408254)

#### Declarative settings

The time mode can be set in XML screen descriptor via new `timeMode` attribute:

```XML
<dateField timeMode="H_12"/>

<!-- default value -->
<timeField timeMode="H_24">
```

#### API

New pair of methods `getTimeMode / setTimeMode` is added for `DateField` and `TimeField` components:

```Java
TimeField.TimeMode timeMode = dateField.getTimeMode();

timeField.setTimeMode(TimeField.TimeMode.H_12);
```

### Demo project

https://github.com/cuba-labs/cuba-timefield-ampm-demo

### QA

Check that:

- [x] `TimeMode` switching is done correctly - components display correctly converted value
- [x] 24h time value are correctly converted into 12h format
- [x] Components have correct value while conversions

**Comment by andreysubbotin** [comment]
Please provide any workaround in the original topic

**Comment by dmakagonova** [comment]
@andreysubbotin the button Set 13:45 set 01:45 for 24 hours format and 01:45 am for 12 hours format. Please, fix it.
![2019-11-18_15-06-09](https://user-images.githubusercontent.com/39261656/69047672-29cb4600-0a15-11ea-9735-f173036bdb22.png)

**Comment by dtsaryov** [comment]
Hi, @dmakagonova 

@andreysubbotin is not involved into this task.

Could you clarify what is wrong in your opinion?

**Comment by dmakagonova** [comment]
@dtsaryov  the button is named Set 13:45. I guess, it means that the button set 13:45 for 24 hours format and 01:45 for 12 hours format. Is it correct? Now the button set 01:45 for both formats. The button should be named Set 01:45.

**Comment by dtsaryov** [comment]
Let me clarify. In fact AM / PM mode is just another way of presentation of the same value. So in fact the second field contains the same value, but formatted into 12h with AM/PM part.

Moreover, the button we are talking about - is just a demo.

**Comment by dmakagonova** [comment]
@dtsaryov it's not just a demo. it's a demonstration of Time Field. it's the case when a user set time automatically. code for the button Set 13:45
     Calendar cal = Calendar.getInstance();

        cal.set(Calendar.HOUR, 13);
        cal.set(Calendar.MINUTE, 45);

        timeField.setValue(cal.getTime());
what can be wrong? if the button doesn't matter why is it there?

**Comment by natfirst** [comment]
1. Create an entity with DateTime attribute
2. Generate browser and editor
3. Set time mode for the Date field
4. Run the app and open the editor
![image](https://user-images.githubusercontent.com/17950251/69711167-06418300-111a-11ea-8583-a6bd36f32579.png)

**Comment by natfirst** [comment]
1. Select PM mode from the drop down list
2. Set the time value e.g. 04:12
3. Time mode will be changed to AM

**Comment by natfirst** [comment]
1. Create date field with H_12 time mode
```
 <dateField id="dateField" property="date" timeMode="H_12"/>
```
2. Run the app, set only time to the field
![image](https://user-images.githubusercontent.com/17950251/69973429-ee646780-153c-11ea-857d-69d55a656ca1.png)

*A.R.* Set focus somewere in the screen. NPE will occurs
```
java.lang.NullPointerException
	at com.haulmont.cuba.web.widgets.CubaTimeFieldWrapper.convertTo12hFormat(CubaTimeFieldWrapper.java:225)
	at com.haulmont.cuba.web.widgets.CubaTimeFieldWrapper.convertToPresentation(CubaTimeFieldWrapper.java:205)
	at com.haulmont.cuba.web.widgets.CubaTimeFieldWrapper.doSetValue(CubaTimeFieldWrapper.java:115)
	at com.haulmont.cuba.web.widgets.CubaTimeFieldWrapper.doSetValue(CubaTimeFieldWrapper.java:31)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:140)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:53)
	at com.haulmont.cuba.web.gui.components.WebDateField.setValueToPresentation(WebDateField.java:383)
	at com.haulmont.cuba.web.gui.components.WebDateField.componentValueChanged(WebDateField.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041)
	at com.haulmont.cuba.web.widgets.CubaTimeFieldWrapper.componentValueChanged(CubaTimeFieldWrapper.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:144)
	at com.haulmont.cuba.web.widgets.CubaTimeField.setValue(CubaTimeField.java:91)
	at com.haulmont.cuba.web.widgets.CubaTimeField$AbstractTextFieldServerRpcImpl.setText(CubaTimeField.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by natfirst** [comment]
Time mode field width should be smaller (~62px)
![image](https://user-images.githubusercontent.com/17950251/70050149-bc5c0f80-15e7-11ea-999c-44dde154510a.png)
