### ISSUE TITLE
Exception that occurred while the screen is opening causes problems with the screen tab 

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#2361]
#### Environment

- Platform version: 7.1

#### Description of the bug or enhancement

- Create an entity with association with another entity (e.g. User)
- Create a view for this entity with a minimal view of the associated entity
- Create browser and editor screens
- Add user attribute which is not included to the view on browser
- Start the app and try to open the screen

*A.R.* Tab's caption is disappeared, there is no ability to close the tab
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/c38ad6fd-e680-490f-8103-4172607f9b0f)

After page refreshing exception occurs
```
    javax.servlet.ServletException: com.vaadin.server.ServiceException: java.lang.NullPointerException
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:427)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.vaadin.server.ServiceException: java.lang.NullPointerException
	at com.vaadin.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1629)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1589)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	... 30 more
Caused by: java.lang.NullPointerException
	at com.haulmont.cuba.web.sys.navigation.navigationhandler.ScreenNavigationHandler.isScreenChanged(ScreenNavigationHandler.java:205)
	at com.haulmont.cuba.web.sys.navigation.navigationhandler.ScreenNavigationHandler.doHandle(ScreenNavigationHandler.java:81)
	at com.haulmont.cuba.web.sys.navigation.ScreenNavigator.handleScreenNavigation(ScreenNavigator.java:53)
	at com.haulmont.cuba.web.AppUI.processRequest(AppUI.java:650)
	at com.haulmont.cuba.web.AppUI.processExternalLink(AppUI.java:608)
	at com.haulmont.cuba.web.AppUI.handleRequest(AppUI.java:527)
	at com.vaadin.server.communication.UIInitHandler.reinitUI(UIInitHandler.java:262)
	at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:162)
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:67)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	... 31 more

```

**Comment by natfirst** [comment]
New issue is created for the tab caption disappearing problem #2390
