### ISSUE TITLE
Error when opening filter with removed enum value

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba#2424]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement
- Minimal reproducible example
  - Sample project: 
[filterenum.zip](https://github.com/cuba-platform/cuba/files/3604217/filterenum.zip)
  - Data model: create an enum and an entity with the enum field.
  - Start application. Create a filter for the entity with an enum condition. Specify a value for the enum. Save the filter with default values. 
   - Remove the selected value from the enum model and restart the application.
   - Try to open filter.
- Expected behavior
- Actual behavior
```
java.lang.IllegalArgumentException: No enum constant com.company.filterenum.entity.TestEnum.V2
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.haulmont.cuba.gui.components.filter.Param.parseSingleValue(Param.java:419)
	at com.haulmont.cuba.gui.components.filter.Param.parseValue(Param.java:407)
	at com.haulmont.cuba.gui.components.filter.condition.AbstractCondition.resolveParam(AbstractCondition.java:201)
	at com.haulmont.cuba.gui.components.filter.condition.AbstractCondition.<init>(AbstractCondition.java:137)
	at com.haulmont.cuba.gui.components.filter.condition.PropertyCondition.<init>(PropertyCondition.java:56)
	at com.haulmont.cuba.gui.components.filter.FilterParserImpl.createCondition(FilterParserImpl.java:98)
	at com.haulmont.cuba.gui.components.filter.FilterParserImpl.recursiveFromXml(FilterParserImpl.java:65)
	at com.haulmont.cuba.gui.components.filter.FilterParserImpl.getConditions(FilterParserImpl.java:51)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.setFilterEntity(FilterDelegateImpl.java:596)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl$5.actionPerform(FilterDelegateImpl.java:1265)
	at com.haulmont.cuba.web.gui.components.WebPopupButton.lambda$setPopupButtonAction$1(WebPopupButton.java:328)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by gorbunkov** [comment]
The new behavior is to display an empty field for the deleted enum and to write an error message to the log.
