### ISSUE TITLE
Incorrect route is generated

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2436]
### Environment

- Platform version: 7.0+

### Description of the bug or enhancement

**Case 1**

Inspect any **MBean** in **JMX Console**

AR: 

route: `.../#main/1/jmx-console/mbean?id=new`

After redirection, the empty MBean inspector is shown:

![Screenshot 2019-09-17 at 16 31 29](https://user-images.githubusercontent.com/6077149/65041825-a2a41800-d968-11e9-994f-7e4879a24715.png)

**Case 2**

[sample-sales.zip](https://github.com/cuba-platform/cuba/files/3621655/sample-sales.zip)

Open an editor for a nested entity, e.g.

1. Open Application > Orders
2. Edit any Order
3. Create or edit an OrderLine

AR:

route: `.../#main/4/orders/edit`
After redirection, an exception occurs

![Screenshot 2019-09-17 at 16 36 13](https://user-images.githubusercontent.com/6077149/65042135-4b527780-d969-11e9-8948-dd3d44b3e0da.png)

```
2019-09-17 17:48:43.594 WARN  [http-nio-8080-exec-1/app/admin] com.haulmont.cuba.web.app.loginwindow.AppLoginWindow - Unable to login
java.lang.IllegalArgumentException: entity is null
    at com.haulmont.bali.util.Preconditions.checkNotNullArgument(Preconditions.java:102) ~[cuba-global-7.1.0.jar:7.1.0]
    at com.haulmont.cuba.core.global.EntityStates.isNew(EntityStates.java:65) ~[cuba-global-7.1.0.jar:7.1.0]
    at com.haulmont.cuba.gui.screen.StandardEditor.setupEntityToEdit(StandardEditor.java:179) ~[cuba-gui-7.1.0.jar:7.1.0]
    at com.haulmont.cuba.gui.screen.StandardEditor.beforeShow(StandardEditor.java:104) ~[cuba-gui-7.1.0.jar:7.1.0]
    at com.haulmont.bali.events.EventHub.publish(EventHub.java:170) ~[cuba-global-7.1.0.jar:7.1.0]
    at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:128) ~[cuba-gui-7.1.0.jar:7.1.0]
    at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:60) ~[cuba-gui-7.1.0.jar:7.1.0]
    at com.haulmont.cuba.web.sys.WebScreens.show(WebScreens.java:435) ~[cuba-web-7.1.0.jar:7.1.0]
    at com.haulmont.cuba.gui.screen.Screen.show(Screen.java:309) ~[cuba-gui-7.1.0.jar:7.1.0]
    at com.haulmont.cuba.web.sys.navigation.navigationhandler.ScreenNavigationHandler.openScreen(ScreenNavigationHandler.java:241) ~[cuba-web-7.1.0.jar:7.1.0]
    at com.haulmont.cuba.web.sys.navigation.navigationhandler.ScreenNavigationHandler.navigate(ScreenNavigationHandler.java:153) ~[cuba-web-7.1.0.jar:7.1.0]
    at com.haulmont.cuba.web.sys.navigation.navigationhandler.ScreenNavigationHandler.doHandle(ScreenNavigationHandler.java:136) ~[cuba-web-7.1.0.jar:7.1.0]
    at com.haulmont.cuba.web.sys.navigation.ScreenNavigator.handleScreenNavigation(ScreenNavigator.java:50) ~[cuba-web-7.1.0.jar:7.1.0]
    at com.haulmont.cuba.web.sys.RedirectHandler.redirect(RedirectHandler.java:132) ~[cuba-web-7.1.0.jar:7.1.0]
    at com.haulmont.cuba.web.DefaultApp.connectionStateChanged(DefaultApp.java:123) ~[cuba-web-7.1.0.jar:7.1.0]
    at com.haulmont.bali.events.EventHub.publish(EventHub.java:170) ~[cuba-global-7.1.0.jar:7.1.0]
```

#### Case 1

Since MBean is a MetaClass and has no persistent id, it cannot be navigated. Route for this screen is removed.

#### Case 2

In case when editor is opened without entity id param, it will be considered as creating a new entity

### QA

- Check that route is not changed when you're expecting any bean.
- Check that new entity is created when entity id param is not passed

**Comment by dtsaryov** [comment]
> Case 2

The behavior in this case is valid since parameters are displayed only for two levels of nesting.

**Comment by glebfox** [comment]
> The behavior in this case is valid since parameters are displayed only for two levels of nesting.

But getting NPE doesn't seem valid for users. Can we handle it somehow?
