### ISSUE TITLE
Add support for new Java Date API to Calendar component

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/cuba#2500]
### Environment

- Platform version: 7.2 

### Description of the bug or enhancement

When you create an entity and use LocalDateTime instead of regular java.util.Date as an attribute type, the Calendar component does not "see" these fields for startDateProperty and endDateProperty.

### Updates
The `Calendar` component has a datatype for `startDate` and `endDate` attributes. The default datatype is `DateTimeDatatype` and the default type is `java.util.Date`. The user can set the following data types:
* `DateDatatype`
* `DateTimeDatatype`
* `LocalDate`
* `LocalDateTime`
* `OffsetDateTime`

All calendar events have the type that was set via `startDateProperty`, `endDateProperty` or `datatype` properties or the default type - `java.util.Date`.
`SimpleCalendarEvent` has a type for start and end values. The user can set the same types, as for the Calendar component.
##### An example of the direct event adding:
```
@Inject
protected Calendar<LocalDate> calendar;

public void generateEvent(String caption, String description, LocalDate start, LocalDate end, boolean isAllDay, String stylename) {
    SimpleCalendarEvent<LocalDate> calendarEvent = new SimpleCalendarEvent<>();
    calendarEvent.setCaption(caption);
    calendarEvent.setDescription(description);
    calendarEvent.setStart(start);
    calendarEvent.setEnd(end);
    calendarEvent.setAllDay(isAllDay);
    calendarEvent.setStyleName(stylename);
    calendar.getEventProvider().addEvent(calendarEvent);
}
```
Support for this feature in CUBA Studio: [issue](https://youtrack.cuba-platform.com/issue/STUDIO-7221)

### QA
* Try setting the datatype using XML descriptor. Check the `startDate` or `endDate` data type.
* Try setting the datatype via Controller. Check the `startDate` or `endDate` data type.
* Try binding the component with the data source and set the `startDateProperty` or `endDateProperty` in XML descriptor. Check the `startDate` or `endDate` data type.
* Try subscribing to calendar events and check the event datatype.
* Try creating the `SimpleCalendarEvent` with different types.

**Comment by natfirst** [comment]
Nothing is working because  EntityCalendarEvent has no type
```
java.lang.ClassCastException: java.time.LocalDate cannot be cast to java.util.Date
	at com.haulmont.cuba.gui.components.calendar.EntityCalendarEvent.getStart(EntityCalendarEvent.java:55)
	at com.haulmont.cuba.web.gui.components.calendar.CalendarEventWrapper.getStart(CalendarEventWrapper.java:49)
	at com.vaadin.v7.ui.Calendar.cacheMinMaxTimeOfDay(Calendar.java:465)
	at com.vaadin.v7.ui.Calendar.setupCalendarEvents(Calendar.java:430)
	at com.vaadin.v7.ui.Calendar.beforeClientResponse(Calendar.java:298)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:118)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:115)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:84)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by GlebDurygin** [comment]
Now, `EntityCalendarEvent` and `SimpleCalendarEvent` have a type

**Comment by natfirst** [comment]
Some methods still do not have type
For example `com.haulmont.cuba.gui.components.Calendar.CalendarEventClickEvent#getCalendarEvent`
![image](https://user-images.githubusercontent.com/17950251/70419630-3e808400-1a7f-11ea-90ba-fc59bb505c33.png)

**Comment by GlebDurygin** [comment]
Add type for `CalendarEvent`
