### ISSUE TITLE
"LambdaConversionException: Invalid caller" on application start when launched under OpenJ9 JVM

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2515]
### Environment

- Platform version: 7.1.1

### Description of the bug or enhancement

Forum topic: https://www.cuba-platform.ru/discuss/t/migracziya-na-openjdk/3607/5

Download 8u232 [OpenJ9 JVM](https://adoptopenjdk.net/index.html?variant=openjdk8&jvmVariant=openj9)

Start the CUBA application using this JVM. The following exception is thrown on start:

<details>
 <summary>Click to expand</summary>
 
```java
10:34:38.456 ERROR com.haulmont.cuba.web.AppUI             - Unable to init ui
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Unable to build lambda consumer MethodHandle(AbstractWindow,AfterShowEvent)void
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[guava-27.1-jre.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953) ~[guava-27.1-jre.jar:na]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4873) ~[guava-27.1-jre.jar:na]
	at com.haulmont.cuba.gui.sys.UiControllerReflectionInspector.getConsumerMethodFactory(UiControllerReflectionInspector.java:180) ~[cuba-gui-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.initSubscribeListeners(UiControllerDependencyInjector.java:361) ~[cuba-gui-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.gui.sys.UiControllerDependencyInjector.inject(UiControllerDependencyInjector.java:114) ~[cuba-gui-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:241) ~[cuba-web-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:175) ~[cuba-web-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.gui.Screens.create(Screens.java:70) ~[cuba-gui-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.App.createTopLevelWindow(App.java:300) ~[cuba-web-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.DefaultApp.initializeUi(DefaultApp.java:243) ~[cuba-web-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.DefaultApp.connectionStateChanged(DefaultApp.java:111) ~[cuba-web-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.DefaultApp$$Lambda$243.0000000000000000.accept(Unknown Source) ~[na:na]
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170) ~[cuba-global-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.security.ConnectionImpl.fireStateChangeListeners(ConnectionImpl.java:228) ~[cuba-web-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.security.ConnectionImpl.login(ConnectionImpl.java:106) ~[cuba-web-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.DefaultApp.loginOnStart(DefaultApp.java:311) ~[cuba-web-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.AppUI.setupUI(AppUI.java:477) ~[cuba-web-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.AppUI.init(AppUI.java:337) ~[cuba-web-7.1.1.jar:7.1.1]
	at com.vaadin.ui.UI.doInit(UI.java:738) [vaadin-server-8.6.4-20-cuba.jar:8.6.4-20-cuba]
	at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:209) [vaadin-server-8.6.4-20-cuba.jar:8.6.4-20-cuba]
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:67) [vaadin-server-8.6.4-20-cuba.jar:8.6.4-20-cuba]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) [vaadin-server-8.6.4-20-cuba.jar:8.6.4-20-cuba]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577) [vaadin-server-8.6.4-20-cuba.jar:8.6.4-20-cuba]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425) [vaadin-server-8.6.4-20-cuba.jar:8.6.4-20-cuba]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329) [cuba-web-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215) [cuba-web-7.1.1.jar:7.1.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.19]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.19]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.19]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.19]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.19]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93) [cuba-web-7.1.1.jar:7.1.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.19]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.19]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) [catalina.jar:9.0.19]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.19]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [catalina.jar:9.0.19]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.19]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.19]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [catalina.jar:9.0.19]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.19]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.19]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-coyote.jar:9.0.19]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.19]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836) [tomcat-coyote.jar:9.0.19]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747) [tomcat-coyote.jar:9.0.19]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.19]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_232]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.19]
	at java.lang.Thread.run(Thread.java:819) [na:1.8.0_232]
Caused by: java.lang.RuntimeException: Unable to build lambda consumer MethodHandle(AbstractWindow,AfterShowEvent)void
	at com.haulmont.cuba.gui.sys.UiControllerReflectionInspector.lambda$getConsumerMethodFactory$1(UiControllerReflectionInspector.java:197) ~[cuba-gui-7.1.1.jar:7.1.1]
	at com.haulmont.cuba.gui.sys.UiControllerReflectionInspector$$Lambda$317.0000000000000000.call(Unknown Source) ~[na:na]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4878) ~[guava-27.1-jre.jar:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[guava-27.1-jre.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[guava-27.1-jre.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[guava-27.1-jre.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[guava-27.1-jre.jar:na]
	... 54 common frames omitted
Caused by: java.lang.invoke.LambdaConversionException: Invalid caller: com.haulmont.cuba.web.app.loginwindow.AppLoginWindow
	at java.lang.invoke.AbstractValidatingLambdaMetafactory.<init>(AbstractValidatingLambdaMetafactory.java:118) ~[na:1.8.0_232]
	at java.lang.invoke.InnerClassLambdaMetafactory.<init>(InnerClassLambdaMetafactory.java:155) ~[na:1.8.0_232]
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:299) ~[na:1.8.0_232]
	at com.haulmont.cuba.gui.sys.UiControllerReflectionInspector.lambda$getConsumerMethodFactory$1(UiControllerReflectionInspector.java:194) ~[cuba-gui-7.1.1.jar:7.1.1]
	... 60 common frames omitted
```
</details>

We should either test and fix problems with OpenJ9 or declare that we don't support it.

If we don't support it - we could add additional environment sanity check on server start.

**Comment by soraksh** [comment]
It was decided to add additional environment sanity check on server start. If server starts using OpenJ9 JVM it should be noted in the log.
