### ISSUE TITLE
Duplicate entry for key 'PRIMARY' in EntityLog

### ISSUE THREAD

**Issue by pavel-grigorev** [cuba-platform/cuba#2548]
### Environment

- Platform version: 7.1

### Description of the bug or enhancement

An intermittent error occurs in EntityLog#flush:
```
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '643bde8307b5aec4e32f4e6d08ce26ec' for key 'PRIMARY'
Error Code: 1062
Call: INSERT INTO SEC_ENTITY_LOG (ID, CHANGES, CREATE_TS, CREATED_BY, ENTITY, ENTITY_INSTANCE_NAME, EVENT_TS, CHANGE_TYPE, ENTITY_ID, INT_ENTITY_ID, LONG_ENTITY_ID, STRING_ENTITY_ID, USER_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
bind => [643bde8307b5aec4e32f4e6d08ce26ec, ...
...
Query: InsertObjectQuery(com.haulmont.cuba.security.entity.EntityLogItem-643bde83-07b5-aec4-e32f-4e6d08ce26ec [managed])
...
at com.haulmont.cuba.security.app.EntityLog.saveItem(EntityLog.java:226)
at com.haulmont.cuba.security.app.EntityLog.flush(EntityLog.java:122)
...
```

Sorry I don't have steps to reproduce but here's a sample code that might help:
```
package com.yieldmo.ymcuba;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import com.haulmont.cuba.core.entity.BaseIdentityIdEntity;
import com.haulmont.cuba.security.entity.EntityLogItem;

public class Test {
  public static void main(String[] args) {
    TestEntity entity = new TestEntity();

    List<EntityLogItem> items = new ArrayList<>();
    items.add(createItem(entity));
    items.add(createItem(entity));

    flush(items);
  }

  private static void flush(List<EntityLogItem> items) {
    Set<EntityLogItem> committed = new HashSet<>();

    for (EntityLogItem item : items) {
      // copy pasted from EntityLog#flush
      List<EntityLogItem> sameEntityList = items.stream()
                                                .filter(entityLogItem -> entityLogItem.getDbGeneratedIdEntity() != null ?
                                                    entityLogItem.getDbGeneratedIdEntity().equals(item.getDbGeneratedIdEntity()) :
                                                    entityLogItem.getObjectEntityId().equals(item.getObjectEntityId()))
                                                .collect(Collectors.toList());

      EntityLogItem itemToSave = sameEntityList.get(0);

      if (!committed.add(itemToSave)) {
        throw new IllegalStateException("Duplicate entry");
      }
    }
  }

  private static EntityLogItem createItem(TestEntity entity) {
    EntityLogItem item = new EntityLogItem();
    item.setDbGeneratedIdEntity(entity);
    return item;
  }

  private static class TestEntity extends BaseIdentityIdEntity {
  }
}
```

**Comment by andreysubbotin** [comment]
@pavel-grigorev  please attach a full stack trace for the error?
