### ISSUE TITLE
Properties of Kotlin entity  with names started with "is" cause errors

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#2552]
1. Create a Kotlin entity (e.g. `Contract`)
2. Add a property with a name that starts with "is" (e.g. `isApproved`)
```kotlin
@Table(name = "SAMPLE_CONTRACT")
@Entity(name = "sample_Contract")
class Contract : StandardEntity() {
    @Column(name = "NUMBER_")
    var number: String? = null

    @Column(name = "IS_APPROVED")
    var isApproved: Boolean? = null

    companion object {
        private const val serialVersionUID = -9155125805327512707L
    }
}
```

3. Using the Studio generate browser and editor screens for the `Contract` entity. 
4. Try to create a new contract

You'll get the following exception on Contract entity opening:
```
Caused by: java.lang.IllegalArgumentException: Can't find getter for property 'isApproved' at class com.company.sample.entity.Contract
	at com.haulmont.chile.core.model.utils.MethodsCache.getGetterNN(MethodsCache.java:126) ~[cuba-global-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.chile.core.model.impl.AbstractInstance.getValue(AbstractInstance.java:107) ~[cuba-global-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.getValue(BaseGenericIdEntity.java:146) ~[cuba-global-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.model.impl.DataContextImpl.mergeState(DataContextImpl.java:248) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.model.impl.DataContextImpl.internalMerge(DataContextImpl.java:198) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.model.impl.DataContextImpl.merge(DataContextImpl.java:154) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.screen.StandardEditor.setupEntityToEdit(StandardEditor.java:205) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.screen.StandardEditor.beforeShow(StandardEditor.java:129) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170) ~[cuba-global-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:128) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:60) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.sys.WebScreens.show(WebScreens.java:431) ~[cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.screen.Screen.show(Screen.java:309) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.actions.list.CreateAction.execute(CreateAction.java:327) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.gui.actions.list.CreateAction.actionPerform(CreateAction.java:274) ~[cuba-gui-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:67) ~[cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76) ~[cuba-web-widgets-7.2-SNAPSHOT.jar:na]
	at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-8.8.5-7-cuba.jar:8.8.5-7-cuba]
	... 43 common frames omitted
```

The problem is that CUBA expects property getter with a name `getIsApproved` and setter with a name `setIsApproved`, but Kotlin uses different mapping rules: for the `isApproved` property the getter name is `isApproved()`, the setter is `setApproved(..)`. See [Kotlin documentation](https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html#properties)

**Comment by gorbunkov** [comment]
The easiest workaroud is to explicitly set the generated accessor method name using the `@JvmName` annotation (see [Kotlin documentation](https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html#handling-signature-clashes-with-jvmname))

```java
@Column(name = "IS_APPROVED")
@set:JvmName("setIsApproved")
@get:JvmName("getIsApproved")
var isApproved: Boolean? = null
```
