### ISSUE TITLE
Unfetched attribute errors with lookup actions

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2569]
### Environment

- Platform version: 7.1.2
- Sample project with prefilled data: 
[lookup_problems.zip](https://github.com/cuba-platform/cuba/files/3900743/lookup_problems.zip)

### Description of the bug or enhancement
You can very easily get unfetched attribute errors when using lookup actions that lookup something from lookup screen, with basic CUBA components and functionality.
The error happens when calling screen uses attributes that were not shown / loaded in the lookup screen's view.

Examples in the sample project:
1) University -> Groups -> Edit any group.
Group -> Students is a one-to-many relation, edited with a __tokenList__ component.
Press "Add" -> select any Student -> Select.
```
java.lang.IllegalStateException: Cannot get unfetched attribute [group] from detached object com.company.lookupprb.entity.Student-273e18af-b677-ac08-6194-b0a29b39cf6b [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100)
	at com.haulmont.cuba.core.sys.persistence.CubaEntityFetchGroup.onUnfetchedAttribute(CubaEntityFetchGroup.java:74)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:2998)
	at com.haulmont.chile.core.model.impl.AbstractInstance._persistence_checkFetched(AbstractInstance.java)
	at com.company.lookupprb.entity.Student._persistence_get_group(Student.java)
	at com.company.lookupprb.entity.Student.getGroup(Student.java:24)
	at com.haulmont.chile.core.model.impl.AbstractInstance.getValue(AbstractInstance.java:99)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.getValue(BaseGenericIdEntity.java:146)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:129)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:126)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:114)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.updateMasterRefs(ContainerValueSource.java:283)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.setValue(ContainerValueSource.java:170)
	at com.haulmont.cuba.web.gui.components.WebTokenList.handleSelection(WebTokenList.java:475)
	at com.haulmont.cuba.web.gui.components.WebTokenList.handleLookupSelection(WebTokenList.java:454)
```

2) Sales menu -> Shops -> Edit any Shop.
Shop -> Consultants is a one-to-many relation. This editor screen uses a table and __Add__/Exclude actions.
Press "Add" -> select any Consultant -> Select.
```
java.lang.IllegalStateException: Cannot get unfetched attribute [shop] from detached object com.company.lookupprb.entity.Consultant-4ad14b65-a6a0-4241-8089-d0c9b056325e [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100)
	at com.haulmont.cuba.core.sys.persistence.CubaEntityFetchGroup.onUnfetchedAttribute(CubaEntityFetchGroup.java:74)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:2998)
	at com.haulmont.chile.core.model.impl.AbstractInstance._persistence_checkFetched(AbstractInstance.java)
	at com.company.lookupprb.entity.Consultant._persistence_get_shop(Consultant.java)
	at com.company.lookupprb.entity.Consultant.getShop(Consultant.java:24)
	at com.haulmont.chile.core.model.impl.AbstractInstance.getValue(AbstractInstance.java:99)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.getValue(BaseGenericIdEntity.java:146)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:129)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:126)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:114)
	at com.haulmont.cuba.gui.builders.LookupBuilderProcessor.handleSelectionWithContainer(LookupBuilderProcessor.java:237)
	at com.haulmont.cuba.gui.builders.LookupBuilderProcessor.lambda$buildLookup$3(LookupBuilderProcessor.java:110)
	at com.haulmont.cuba.gui.screen.StandardLookup.lambda$select$1(StandardLookup.java:178)
	at com.haulmont.cuba.gui.util.SuccessOperationResult.then(SuccessOperationResult.java:44)
	at com.haulmont.cuba.gui.screen.StandardLookup.select(StandardLookup.java:178)
	at com.haulmont.cuba.gui.screen.StandardLookup.select(StandardLookup.java:162)	
```

3) A more complex case.
Menu -> Vehicle Management -> Vehicles.
Vehicle -> VehicleModel is a Many-to-one relation.
Vehicle Editor shows read-only Vehicle.Model.emission field that is not displayed in the Vehicle Model browser.

Create new Vehicle.
Select Model using a __PickerField__.
```
java.lang.IllegalStateException: Cannot get unfetched attribute [emission] from detached object com.company.lookupprb.entity.VehicleModel-9ba71409-8c86-710b-0b42-6e5ac3009325 [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100)
	at com.haulmont.cuba.core.sys.persistence.CubaEntityFetchGroup.onUnfetchedAttribute(CubaEntityFetchGroup.java:74)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:2998)
	at com.haulmont.chile.core.model.impl.AbstractInstance._persistence_checkFetched(AbstractInstance.java)
	at com.company.lookupprb.entity.VehicleModel._persistence_get_emission(VehicleModel.java)
	at com.company.lookupprb.entity.VehicleModel.getEmission(VehicleModel.java:31)
	at com.haulmont.chile.core.model.impl.AbstractInstance.getValue(AbstractInstance.java:99)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.getValue(BaseGenericIdEntity.java:146)
	at com.haulmont.chile.core.model.utils.InstanceUtils.getValueEx(InstanceUtils.java:156)
	at com.haulmont.chile.core.model.utils.InstanceUtils.getValueEx(InstanceUtils.java:120)
	at com.haulmont.chile.core.model.impl.AbstractInstance.getValueEx(AbstractInstance.java:138)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.lambda$setBeanLocator$1(ContainerValueSource.java:117)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.model.impl.InstanceContainerImpl.itemPropertyChanged(InstanceContainerImpl.java:178)
	at com.haulmont.chile.core.model.impl.AbstractInstance.propertyChanged(AbstractInstance.java:53)
	at com.company.lookupprb.entity.Vehicle.setModel(Vehicle.java:28)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:132)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:126)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:114)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:217)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:175)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValueEx(AbstractInstance.java:149)
	at com.haulmont.cuba.gui.components.data.value.ContainerValueSource.setValue(ContainerValueSource.java:172)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.setValueToSource(ValueBinder.java:286)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.componentValueChanged(ValueBinder.java:279)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.web.gui.components.WebAbstractComponent.publish(WebAbstractComponent.java:92)
	at com.haulmont.cuba.web.gui.components.WebPickerField.setValueFromUser(WebPickerField.java:113)
	at com.haulmont.cuba.web.gui.components.WebPickerField.setValueFromUser(WebPickerField.java:59)
	at com.haulmont.cuba.gui.builders.LookupBuilderProcessor.handleSelectionWithField(LookupBuilderProcessor.java:189)
	at com.haulmont.cuba.gui.builders.LookupBuilderProcessor.lambda$buildLookup$1(LookupBuilderProcessor.java:81)
	at com.haulmont.cuba.gui.screen.StandardLookup.lambda$select$1(StandardLookup.java:178)
	at com.haulmont.cuba.gui.util.SuccessOperationResult.then(SuccessOperationResult.java:44)
	at com.haulmont.cuba.gui.screen.StandardLookup.select(StandardLookup.java:178)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.lambda$setLookupSelectHandler$4(WebAbstractTable.java:1275)
```

Case no. 3 was especially ubiquitous in Sherlock. We've met dozens and dozens of such errors in complex screens with picker fields when doing migration to CUBA 6.

The worst thing is - the easiest way to fix such errors is to add more attributes to the lookup screen. Which is a bad way to do it - the browser screen starts to load unnecessary data.

**Comment by alexbudarov** [comment]
Also for case no. 3.
You could use SuggestionPickerField instead of PickerField that selects VehicleModel.
In this case you have two ways to select model:
1) from lookup screen - its view is used
2) from suggestions - then `<suggestionPickerField><query>` view is used, and it would also be a bad thing to load more data than it is necessary to show the suggestion caption

**Comment by gorbunkov** [comment]
The entity will be automatically reloaded (in case of missing fields) in the following cases:
* when it is set to the PickerField from the lookup screen
* when it is added to the collection container using the "Add" action
* when it is added to the token list using the lookup screen.

This behavior is enabled by default. The boolean application property `cuba.gui.reloadUnfetchedAttributesFromLookupScreens` (stored in the DB) may be used to disable this functionality.
