### ISSUE TITLE
IllegalArgumentException: Negative MaxResult is not allowed.

### ISSUE THREAD

**Issue by daring2** [cuba-platform/cuba#2583]
### Environment

- Platform version: 7.1.2
- Client type: Web

### Description of the bug or enhancement

The problem could be reproduced in project [sample-library-cuba7](https://github.com/daring2/sample-library-cuba7).

Steps to reproduce:
1. open the Books screen
2. enter negative value (for example, -1) to "Show rows" field
3. close the screen
4. try to open the Books screen

Actual behavior: 
IllegalArgumentException: Negative MaxResult is not allowed.

Stacktrace:
```
java.lang.IllegalArgumentException: Negative MaxResult is not allowed.
	at org.eclipse.persistence.internal.jpa.QueryImpl.setMaxResultsInternal(QueryImpl.java:882)
	at org.eclipse.persistence.internal.jpa.QueryImpl.setMaxResults(QueryImpl.java:847)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setMaxResults(EJBQueryImpl.java:439)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setMaxResults(EJBQueryImpl.java:1)
	at com.haulmont.cuba.core.sys.QueryImpl.getQuery(QueryImpl.java:174)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultList(QueryImpl.java:409)
	at com.haulmont.cuba.core.app.RdbmsStore.executeQuery(RdbmsStore.java:841)
	at com.haulmont.cuba.core.app.RdbmsStore.getResultList(RdbmsStore.java:749)
	at com.haulmont.cuba.core.app.RdbmsStore.loadList(RdbmsStore.java:233)
...
```

After this error it is impossible to open the Books screen. Workaround - reset screen settings in "Help - Settings" panel.

**Comment by gorbunkov** [comment]
@natfirst I cannot reproduce the issue. Could you please check?

**Comment by daring2** [comment]
Sorry, I specified wrong version in description. Actually the issue can be reproduced in version 7.1-SNAPSHOT. 

Probably the problem is related with changes made in #2572.
