### ISSUE TITLE
'UNION' does not work with jpql queries

### ISSUE THREAD

**Issue by soraksh** [cuba-platform/cuba#2625]
### Environment

- Platform version: 7+

### Description of the bug

See [forum topic](https://www.cuba-platform.com/discuss/t/cuba-7-upgrade-ommonerrornode-mismatched-token-51-197-201-union-61-1-197-resync/10945).
- Minimal reproducible example:
1. Create jpql query using `UNION` statement, e.g. `select e from oct$UnionEntity e where e.name = '1' union all select e from oct$UnionEntity e where e.name = '2'`
2. Use `dataManager.loadValues()` to load values using query with `UNION`
- Expected behavior:
Values loaded correctly (worked with Cuba 6.10)
- Actual behavior:
```com.haulmont.cuba.core.sys.jpql.JpqlSyntaxException: Errors found for input jpql:[select e from mqt$TestEntity e where e.name = '1' union all select e from mqt$TestEntity e where e.name = '2']
CommonErrorNode [<mismatched token: [@20,50:54='union',<61>,1:50], resync=select e from mqt$TestEntity e where e.name = '1' union all select e from mqt$TestEntity e where e.name = '2'>]
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy191.loadValues(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:155)
	at com.sun.proxy.$Proxy34.loadValues(Unknown Source)
	at com.haulmont.cuba.client.sys.DataManagerClientImpl.loadValues(DataManagerClientImpl.java:146)
	at com.haulmont.cuba.core.global.FluentValuesLoader.list(FluentValuesLoader.java:47)
...
```

**Comment by andreysubbotin** [comment]
UNION isn't supported by JPA specification
