### ISSUE TITLE
Implement "where :nullParameter is null" handling

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#263]
см. патч к рефаппу.

В OpenJPA работал такой трюк:
```
"select c from ref$Car c where c.vin = :vin or :param is null"
...
           .setParameter("param", null)
```

OpenJPA трансформировал это условие:
-  ":null-parameter is null"  в "0 = 0", 
- а ":not-null-parameter is null" в "1 = 0". 

В EclipseLink такой запрос падает с исключением postgres:
```
javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.2.cuba7): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: could not determine data type of parameter $2
Error Code: 0
Call: SELECT ID, CREATE_TS, CREATED_BY, DELETE_TS, DELETED_BY, UPDATE_TS, UPDATED_BY, VERSION, VIN, CATEGORY_ID, COLOUR_ID, CURRENCY_CODE, MODEL_ID, SELLER_ID, TOKEN_ID FROM REF_CAR WHERE (((VIN = ?) AND (? IS NULL)) AND (DELETE_TS IS NULL))
	bind => [99988, null]
Query: ReadAllQuery(referenceClass=Car sql="SELECT ID, CREATE_TS, CREATED_BY, DELETE_TS, DELETED_BY, UPDATE_TS, UPDATED_BY, VERSION, VIN, CATEGORY_ID, COLOUR_ID, CURRENCY_CODE, MODEL_ID, SELLER_ID, TOKEN_ID FROM REF_CAR WHERE (((VIN = ?) AND (? IS NULL)) AND (DELETE_TS IS NULL))")

	at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:382)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:260)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:473)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultFromCache(QueryImpl.java:600)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultList(QueryImpl.java:308)
	at com.haulmont.refapp.core.CompareParameterWithNullTest.lambda$testAndTrue$1(CompareParameterWithNullTest.java:52)
	at com.haulmont.cuba.core.sys.TransactionImpl.execute(TransactionImpl.java:69)
	at com.haulmont.cuba.core.sys.TransactionImpl.execute(TransactionImpl.java:63)
	at com.haulmont.cuba.core.sys.PersistenceImpl.callInTransaction(PersistenceImpl.java:99)
	at com.haulmont.refapp.core.CompareParameterWithNullTest.testAndTrue(CompareParameterWithNullTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.2.cuba7): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: could not determine data type of parameter $2
Error Code: 0
Call: SELECT ID, CREATE_TS, CREATED_BY, DELETE_TS, DELETED_BY, UPDATE_TS, UPDATED_BY, VERSION, VIN, CATEGORY_ID, COLOUR_ID, CURRENCY_CODE, MODEL_ID, SELLER_ID, TOKEN_ID FROM REF_CAR WHERE (((VIN = ?) AND (? IS NULL)) AND (DELETE_TS IS NULL))
	bind => [99988, null]
Query: ReadAllQuery(referenceClass=Car sql="SELECT ID, CREATE_TS, CREATED_BY, DELETE_TS, DELETED_BY, UPDATE_TS, UPDATED_BY, VERSION, VIN, CATEGORY_ID, COLOUR_ID, CURRENCY_CODE, MODEL_ID, SELLER_ID, TOKEN_ID FROM REF_CAR WHERE (((VIN = ?) AND (? IS NULL)) AND (DELETE_TS IS NULL))")
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:684)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:560)
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2052)
	at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570)
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:258)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.executeCall(ExpressionQueryMechanism.java:2863)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:299)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:694)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2751)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2704)
	at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:559)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1175)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1134)
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:460)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1222)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2944)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1854)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1836)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1801)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258)
	... 14 more
Caused by: org.postgresql.util.PSQLException: ERROR: could not determine data type of parameter $2
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:305)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1009)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:644)
	... 36 more


```

Вообще переписать все запросы можно. Но этот трюк был очень удобен и в браузерах, и в запросах на среднем слое (из-за отсутствия query builder api).

Пример 1.
```
// было
// запрос с опциональным параметром
    DriverGroupCharge res = (DriverGroupCharge) em.createQuery("select t from taxi$DriverGroupCharge t " +
            "   where t.chargeType.id = :chargeTypeId" +
            "       and (:dcFinishDate is null or t.startPeriod.startDate < :dcFinishDate)")
            .setParameter("chargeTypeId", driverCharge.getChargeType().getId())
            .setParameter("dcFinishDate", finishDate);
            .setView(DriverGroupCharge.class, "driver-wages-driver-group-charge")
            .getFirstResult();

// стало
// лишние условия
    Query query = em.createQuery("select t from taxi$DriverGroupCharge t " +
            "   where t.chargeType.id = :chargeTypeId" +
            (finishDate != null ? "       and t.startPeriod.startDate < :dcFinishDate" : "")
            .setParameter("chargeTypeId", driverCharge.getChargeType().getId());
    if (finishDate != null) {
        query.setParameter("dcFinishDate", finishDate);
    }
    DriverGroupCharge res = (DriverGroupCharge) query
            .setView(DriverGroupCharge.class, "driver-wages-driver-group-charge")
            .getFirstResult();
```

Пример 2.
Браузер. Одно из условий фильтрации использует параметры: сущность (аккаунт) и булевский чекбокс.
Т.к. булевский чекбокс выдает либо true либо false, то стандартным образом датасорс не может "выбросить" условие из рассмотрения, как он обычно это делает.
```
<c>
   (
         (inv.customer.id = :component$customerNumberPfield and :component$linkedAccounts = false) 
       or
         (
             (inv.customer.id = :component$customerNumberPfield or inv.customer.parent.id = :component$customerNumberPfield) 
               and  
              :component$linkedAccounts = true
              ) 
       or
          :component$customerNumberPfield is null
   )
</c>
```
В этом варианте он мб выглядит сложно, но работает, опираясь напрямую на значения компонентов в фильтре.
В новой кубе "null is null" выкидывает исключение, и это условие не переписать без использования дополнительного кода и custom$ параметров.

---
Original issue: https://youtrack.haulmont.com/issue/PL-7861

**Comment by invviz** [comment]
Changes: the "is null" and "is not null" conditions in JPQL queries are converted to "1 = 1" or "1 = 0" before sending them to the database.
