### ISSUE TITLE
Unfetched attribute exception occurs in entity inspector when there is a transient attribute of related entity which uses persistent fields in accessor

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#2680]
### Environment

- Platform version: 7.1.4, 7.2-beta1 

### Description of the bug or enhancement

- Minimal reproducible example
In one of our projects we have the following entities
1) Simple entry 'Tag' which is linked (N:N) to Customer
```
@Table(name = "ENTINSTEST_TAG")
@Entity(name = "entinstest_Tag")
public class Tag extends StandardEntity {
    private static final long serialVersionUID = 7634066445907003765L;

    @Column(name = "VALUE_")
    protected String value;

    @JoinTable(name = "ENTINSTEST_TAG_CUSTOMER_LINK",
            joinColumns = @JoinColumn(name = "TAG_ID"),
            inverseJoinColumns = @JoinColumn(name = "CUSTOMER_ID"))
    @ManyToMany
    protected List<Customer> customers;

```

2) Customer which has a collection of Tags. It has a Transient field, which uses another persistent field in getter-function.
```
@NamePattern("%s|name")
@Table(name = "ENTINSTEST_CUSTOMER")
@Entity(name = "entinstest_Customer")
public class Customer extends StandardEntity {
    private static final long serialVersionUID = -7206556295563873819L;

    @Column(name = "NAME")
    protected String name;

    @JoinTable(name = "ENTINSTEST_TAG_CUSTOMER_LINK",
            joinColumns = @JoinColumn(name = "CUSTOMER_ID"),
            inverseJoinColumns = @JoinColumn(name = "TAG_ID"))
    @ManyToMany
    protected List<Tag> tags;

    @Transient
    @MetaProperty
    protected String tagList;
    
    public String getTagList() {

        return tags.toString();

    }
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "GROUP_ID")
    protected Group group;
```

3) Group which has a collection of Customers 
```
@Table(name = "ENTINSTEST_GROUP")
@Entity(name = "entinstest_Group")
public class Group extends StandardEntity {
    private static final long serialVersionUID = -278817713106750611L;

    @Column(name = "GRP_NAME")
    protected String grpName;

    @OneToMany(mappedBy = "group")
    protected List<Customer> customers;
```

- Actual behavior

When the Customer entity is opened in entity inspetor - it is OK
But when the Group entity instance is opened in Entity inspector, the following Unfetched Attribute exception occurs.

And could not close the entity inspector screen (IllegalStateException: Screen is not opened entityInspector.browse).

![image](https://user-images.githubusercontent.com/19840141/73865305-7b3ce180-485c-11ea-8841-db875ca522e8.png)

```
java.lang.IllegalStateException: Cannot get unfetched attribute [tags] from detached object com.company.entinstest.entity.Customer-f94442e9-ae8f-add9-706e-540497121c5f [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100)
	at com.haulmont.cuba.core.sys.persistence.CubaEntityFetchGroup.onUnfetchedAttribute(CubaEntityFetchGroup.java:74)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:2998)
	at com.haulmont.chile.core.model.impl.AbstractInstance._persistence_checkFetched(AbstractInstance.java)
	at com.company.entinstest.entity.Customer._persistence_get_tags(Customer.java)
	at com.company.entinstest.entity.Customer.getTagList(Customer.java:31)
	at com.haulmont.chile.core.model.impl.AbstractInstance.getValue(AbstractInstance.java:108)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.getValue(BaseGenericIdEntity.java:146)
	at com.haulmont.chile.core.model.utils.InstanceUtils.getValueEx(InstanceUtils.java:134)
	at com.haulmont.chile.core.model.impl.AbstractInstance.getValueEx(AbstractInstance.java:172)
	at com.haulmont.cuba.gui.components.data.table.DatasourceTableItems.getItemValue(DatasourceTableItems.java:119)
	at com.haulmont.cuba.web.gui.components.table.TableItemWrapper.getPropertyValue(TableItemWrapper.java:74)
	at com.haulmont.cuba.web.gui.components.table.TableItemPropertyWrapper.getValue(TableItemPropertyWrapper.java:34)
	at com.haulmont.cuba.web.gui.components.table.AbbreviatedColumnGenerator.generateCell(AbbreviatedColumnGenerator.java:44)
	at com.vaadin.v7.ui.Table.parseItemIdToCells(Table.java:2333)
	at com.vaadin.v7.ui.Table.getVisibleCellsNoCache(Table.java:2203)
	at com.vaadin.v7.ui.Table.refreshRenderedCells(Table.java:1746)
	at com.vaadin.v7.ui.Table.attach(Table.java:4260)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.ui.AbstractComponent.setParent(AbstractComponent.java:571)
	at com.vaadin.ui.AbstractComponentContainer.addComponent(AbstractComponentContainer.java:178)
	at com.vaadin.ui.CssLayout.addComponent(CssLayout.java:121)
	at com.haulmont.cuba.web.sys.WebScreens.showThisTabWindow(WebScreens.java:1707)
	at com.haulmont.cuba.web.sys.WebScreens.show(WebScreens.java:448)
	at com.haulmont.cuba.web.sys.WebScreens.openWindow(WebScreens.java:1106)
	at com.haulmont.cuba.gui.components.HasWindowManager.openWindow(HasWindowManager.java:57)
	at com.haulmont.cuba.gui.app.core.entityinspector.EntityInspectorBrowse$EditAction.actionPerform(EntityInspectorBrowse.java:514)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.handleClickAction(WebAbstractTable.java:1295)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.lambda$initComponent$db766529$1(WebAbstractTable.java:1048)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041)
	at com.vaadin.v7.ui.Table.handleClickEvent(Table.java:3126)
	at com.vaadin.v7.ui.Table.changeVariables(Table.java:2918)
	at com.haulmont.cuba.web.widgets.CubaTable.changeVariables(CubaTable.java:356)
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:611)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:457)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:400)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)


```

**Comment by NikitaShchienko** [comment]
To solve the problem, add a link to the field:
```
@Transient
@MetaProperty(related = "tags")
```
Or

In the get method, you need to check the reference field for "isLoaded".
