### ISSUE TITLE
Declarative DataGrid icon renderer dosn't work

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2695]
### Environment
- Platform version: 7.2

### Description of the bug or enhancement

- Create new project
- Create blank screen with User collection container and DataGrid

Initial layout:
 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<window xmlns="http://schemas.haulmont.com/cuba/screen/window.xsd"
        caption="msg://caption"
        messagesPack="com.company.grid.web.screens">
    <data>
        <collection id="usersDc" class="com.haulmont.cuba.security.entity.User" view="_local">
            <loader id="usersDl">
                <query>
                    <![CDATA[select e from sec$User e]]>
                </query>
            </loader>
        </collection>
    </data>
    <layout>
        <dataGrid id="usersTable" height="100px" width="200px" dataContainer="usersDc">
            <columns>
                <column id="login" property="login"/>
                <column id="name" property="name"/>
            </columns>
        </dataGrid>
    </layout>
</window>
```

- Try to add various declarative column generators from #1983 (with Studio or manually):

1) Icon - doesn't work, fails with `java.lang.ClassNotFoundException: com.haulmont.cuba.gui.icons.Icons.Icon`

```
                <column id="userIcon" generatedType="com.haulmont.cuba.gui.icons.Icons.Icon">
                    <renderer type="com.haulmont.cuba.gui.components.DataGrid$IconRenderer"/>
                </column>

    @Install(to = "usersTable.userIcon", subject = "columnGenerator")
    private Icons.Icon usersTableUserIconColumnGenerator(DataGrid.ColumnGeneratorEvent<User> event) {
        return CubaIcon.ADDRESS_BOOK;
    }

```
Exception when opening screen:
<details>
 <summary>Click to expand</summary>
 
```java
18:39:25.241 ERROR com.haulmont.cuba.web.log.AppLog        - Exception in com.haulmont.cuba.web.widgets.CubaSideMenu: 
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method menuItemTriggered in com.haulmont.cuba.web.widgets.client.verticalmenu.CubaSideMenuServerRpc
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:157) ~[vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115) ~[vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431) [vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396) [vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260) [vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82) [vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) [vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578) [vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425) [vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329) [cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215) [cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.27]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.27]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93) [cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.27]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.27]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.27]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [catalina.jar:9.0.27]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.27]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.27]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [catalina.jar:9.0.27]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.27]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.27]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-coyote.jar:9.0.27]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.27]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-coyote.jar:9.0.27]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579) [tomcat-coyote.jar:9.0.27]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.27]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.27]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153) ~[vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	... 38 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to load class
	at com.haulmont.cuba.core.sys.AbstractScripting.loadClassNN(AbstractScripting.java:306) ~[cuba-global-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractDataGridLoader.loadGeneratedType(AbstractDataGridLoader.java:584) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractDataGridLoader.loadColumn(AbstractDataGridLoader.java:555) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractDataGridLoader.loadColumns(AbstractDataGridLoader.java:439) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractDataGridLoader.loadComponent(AbstractDataGridLoader.java:190) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:38) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:76) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.xml.layout.loaders.WindowLoader.loadComponent(WindowLoader.java:94) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.sys.WebScreens.loadWindowFromXml(WebScreens.java:365) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:232) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:175) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:319) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:264) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:249) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.gui.components.mainwindow.WebSideMenu$MenuItemImpl.menuSelected(WebSideMenu.java:573) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.widgets.CubaSideMenu$1.menuItemTriggered(CubaSideMenu.java:90) ~[cuba-web-widgets-7.2.0.BETA1.jar:na]
	... 43 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.haulmont.cuba.gui.icons.Icons.Icon
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_201]
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:773) ~[groovy-2.5.8.jar:2.5.8]
	at com.haulmont.cuba.core.sys.AbstractScripting$CubaGroovyClassLoader.loadClass(AbstractScripting.java:490) ~[cuba-global-7.2.0.BETA1.jar:7.2.0.BETA1]
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:648) ~[groovy-2.5.8.jar:2.5.8]
	at com.haulmont.cuba.core.sys.AbstractScripting.loadClassNN(AbstractScripting.java:304) ~[cuba-global-7.2.0.BETA1.jar:7.2.0.BETA1]
	... 58 common frames omitted

```
</details>

2) Date, LocalDate, LocalDateTime renderers - don't work because required renderer parameters are missing. How are we supposed to set these parameters declaratively?

Example with LocalDateTime:
```
                <column id="changeTs" generatedType="java.time.LocalDateTime">
                    <renderer type="com.haulmont.cuba.gui.components.DataGrid$LocalDateTimeRenderer"/>
                </column>

    @Install(to = "usersTable.changeTs", subject = "columnGenerator")
    private LocalDateTime usersTableChangeTsColumnGenerator(DataGrid.ColumnGeneratorEvent<User> event) {
        return LocalDateTime.now();
    }
```
Exception:
<details>
 <summary>Click to expand</summary>
 
```java
18:47:57.934 ERROR com.haulmont.cuba.web.log.AppLog        - Exception in com.haulmont.cuba.web.widgets.CubaSideMenu: 
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method menuItemTriggered in com.haulmont.cuba.web.widgets.client.verticalmenu.CubaSideMenuServerRpc
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:157) ~[vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115) ~[vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431) [vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396) [vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260) [vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82) [vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) [vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578) [vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425) [vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329) [cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215) [cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.27]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.27]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93) [cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.27]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.27]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.27]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [catalina.jar:9.0.27]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.27]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.27]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [catalina.jar:9.0.27]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.27]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.27]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-coyote.jar:9.0.27]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.27]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-coyote.jar:9.0.27]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579) [tomcat-coyote.jar:9.0.27]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.27]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.27]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153) ~[vaadin-server-8.9.2-0-cuba.jar:8.9.2-0-cuba]
	... 38 common frames omitted
Caused by: java.lang.IllegalArgumentException: Format pattern may not be null
	at com.haulmont.bali.util.Preconditions.checkNotNullArgument(Preconditions.java:102) ~[cuba-global-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.gui.components.renderers.WebLocalDateTimeRenderer.createImplementation(WebLocalDateTimeRenderer.java:84) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.gui.components.renderers.WebLocalDateTimeRenderer.createImplementation(WebLocalDateTimeRenderer.java:35) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid$AbstractRenderer.getImplementation(WebAbstractDataGrid.java:3486) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.gui.components.renderers.WebLocalDateTimeRenderer.getImplementation(WebLocalDateTimeRenderer.java:78) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.gui.components.renderers.WebLocalDateTimeRenderer.getImplementation(WebLocalDateTimeRenderer.java:35) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid$ColumnImpl.updateRendererInternal(WebAbstractDataGrid.java:3913) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid$ColumnImpl.setRenderer(WebAbstractDataGrid.java:3901) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid$ColumnImpl.setRenderer(WebAbstractDataGrid.java:3883) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractDataGridLoader.loadColumn(AbstractDataGridLoader.java:558) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractDataGridLoader.loadColumns(AbstractDataGridLoader.java:439) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractDataGridLoader.loadComponent(AbstractDataGridLoader.java:190) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:38) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:76) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.xml.layout.loaders.WindowLoader.loadComponent(WindowLoader.java:94) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.sys.WebScreens.loadWindowFromXml(WebScreens.java:365) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:232) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:175) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:319) ~[cuba-gui-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:264) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:249) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.gui.components.mainwindow.WebSideMenu$MenuItemImpl.menuSelected(WebSideMenu.java:573) ~[cuba-web-7.2.0.BETA1.jar:7.2.0.BETA1]
	at com.haulmont.cuba.web.widgets.CubaSideMenu$1.menuItemTriggered(CubaSideMenu.java:90) ~[cuba-web-widgets-7.2.0.BETA1.jar:na]
	... 43 common frames omitted
```
</details>

**Comment by alexbudarov** [comment]
@web-devel So what about other renderers?
> Date, LocalDate, LocalDateTime renderers - don't work because required renderer parameters are missing.

**Comment by dtsaryov** [comment]
@alexbudarov these cases were not described in issue. Could you please update description with problem details?

**Comment by web-devel** [comment]
Parameterized renderers support: #2737
