### ISSUE TITLE
NPE on role edit screen

### ISSUE THREAD

**Issue by longirun** [cuba-platform/cuba#2717]
### Environment

- Platform version: 6.10.13 (most probably all cuba versions affected up to latest 7.3)

### Description of the bug or enhancement
1. Go to Administration -> Entity Inspector -> Permission (sec$Permission).
2. Assume there exists either UI or Entity. For example, edit UI: remove 'Value' and save.
3. Go to Administration -> Role -> edit role (with removed UI value) -> open UI tab.
ER: tab should open
AR: NPE:

```
java.lang.NullPointerException: null
	at com.haulmont.cuba.gui.app.security.ds.UiPermissionsDatasource.getPermissionVariant(UiPermissionsDatasource.java:73)
	at com.haulmont.cuba.gui.app.security.ds.UiPermissionsDatasource.loadData(UiPermissionsDatasource.java:57)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.refresh(CollectionDatasourceImpl.java:161)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.refresh(CollectionDatasourceImpl.java:119)
	at com.haulmont.cuba.gui.app.security.role.edit.tabs.UiPermissionsFrame.init(UiPermissionsFrame.java:155)
	at com.haulmont.cuba.gui.xml.layout.loaders.FrameLoader$FrameLoaderInitTask.execute(FrameLoader.java:271)
	at com.haulmont.cuba.gui.xml.layout.loaders.ComponentLoaderContext$InitTaskExecutor.run(ComponentLoaderContext.java:273)
	at com.haulmont.cuba.gui.xml.layout.loaders.ComponentLoaderContext.executeInitTasks(ComponentLoaderContext.java:162)
	at com.haulmont.cuba.web.gui.components.WebTabSheet.lambda$initComponentTabChangeListener$ba8aefab$1(WebTabSheet.java:519)
	at sun.reflect.GeneratedMethodAccessor309.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	... 48 common frames omitted
Wrapped by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method selectedTabChange in com.haulmont.cuba.web.gui.components.WebTabSheet$$Lambda$237/622609074 failed.
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:530)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1037)
	at com.vaadin.ui.TabSheet.fireSelectedTabChange(TabSheet.java:904)
	at com.vaadin.ui.TabSheet.setSelectedTab(TabSheet.java:571)
	at com.haulmont.cuba.web.toolkit.ui.CubaTabSheet.setSelectedTab(CubaTabSheet.java:186)
	at com.vaadin.ui.TabSheet$TabsheetServerRpcImpl.setSelected(TabSheet.java:92)
	... 41 common frames omitted
Wrapped by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor314.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
	... 37 common frames omitted
Wrapped by: com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method setSelected in com.vaadin.shared.ui.tabsheet.TabsheetServerRpc
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:160)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:444)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:409)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:361)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:324)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:210)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

The same happens for Entities and Specific tabs.
The root cause is unwrapping big Integer value (that is null) with the small int from Enum in the following code snippet:
```
UiPermissionsDatasource.java:72
    private UiPermissionVariant getPermissionVariant(Permission permission) {
        if (permission.getValue() == UiPermissionValue.READ_ONLY.getValue())
            return UiPermissionVariant.READ_ONLY;
        else if (permission.getValue() == UiPermissionValue.HIDE.getValue())
            return UiPermissionVariant.HIDE;
        else if (permission.getValue() == UiPermissionValue.SHOW.getValue())
            return UiPermissionVariant.SHOW;
        else
            return UiPermissionVariant.NOTSET;
    }
```
At lest EntityPermissionTargetsDatasource.java and MultiplePermissionTargetsDatasource.java affected with the issue also.

### QA
Please check all types of permissions

**Comment by web-devel** [comment]
Please use Role edit UI to manage permissions. If you still want to clear permission manually you should remove the instance itself instead of clearing value.
