### ISSUE TITLE
Unfetched attribute exception after committing DataContext if NamePattern contains a referenced attribute

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2745]
### Environment

- Platform version: 7.1.5

### Description of the bug or enhancement

- Minimal reproducible example

[unfetched-test.zip](https://github.com/cuba-platform/cuba/files/4286937/unfetched-test.zip)

1. Create an order
2. Edit an existing order
3. Change `person`
4. Commit changes

- Expected behavior

Changes are committed.

- Actual behavior

```
java.lang.IllegalStateException: Cannot get unfetched attribute [user] from detached object com.company.demo.entity.Person-871b65ba-9bd5-574e-4036-e1f764f5310c [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100)
	at com.haulmont.cuba.core.sys.persistence.CubaEntityFetchGroup.onUnfetchedAttribute(CubaEntityFetchGroup.java:74)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:2998)
	at com.haulmont.chile.core.model.impl.AbstractInstance._persistence_checkFetched(AbstractInstance.java)
	at com.company.demo.entity.Person._persistence_get_user(Person.java)
	at com.company.demo.entity.Person.getUser(Person.java:34)
...
```

**Comment by knstvk** [comment]
Caused by #2610
