### ISSUE TITLE
Confusing behavior when both run-time and design-time roles have the same name

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2747]
### Environment

- Platform version: 7.2.0

### Description of the bug or enhancement

- Minimal reproducible example

[petclinic.zip](https://github.com/cuba-platform/cuba/files/4287350/petclinic.zip)

1. Create a run-time group
2. Assign this group to a user
3. Create a design-time group with the same name

In the demo above such group is `Veterinarians`.

#### Actual behavior

* Only design-time group is displayed in **Administration -> Access Groups** screen
* Exception when changing a group for a user with a run-time group (`jack` in the demo app )

```
java.lang.IllegalStateException: Datasource doesn't contain items
	at com.haulmont.cuba.web.gui.components.WebTree.setSelected(WebTree.java:1142)
	at com.haulmont.cuba.web.gui.components.WebTree.setSelected(WebTree.java:1130)
	at com.haulmont.cuba.gui.app.security.group.lookup.GroupLookup.init(GroupLookup.java:52)
	...
```

#### Expected behavior

* All Groups are displayed
* Warning notification if there are groups with the same name
* No exceptions while changing user group

**Comment by alexbudarov** [comment]
I suppose we should fail application to start in this case (fail-fast).
Names duplication is source of confusion and mess.
