### ISSUE TITLE
IllegalStateException when opening a legacy screen with DataGrid related to a nested collection datasource

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2761]
### Environment

- Platform version: 7.2.0

### Description of the bug or enhancement

- Minimal reproducible example

[datagrid-test.zip](https://github.com/cuba-platform/cuba/files/4316823/datagrid-test.zip)

1. Open Orders browser
2. Select any item
3. Click **Legacy Edit**

- Expected behavior

An editor screen is opened.

- Actual behavior

```
java.lang.IllegalStateException: DataGridItems is not active
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.getDataGridItemsNN(WebAbstractDataGrid.java:847)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.getEntityDataGridItemsNN(WebAbstractDataGrid.java:858)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.getInitialVisibleColumns(WebAbstractDataGrid.java:1967)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.setItems(WebAbstractDataGrid.java:889)
	at com.haulmont.cuba.gui.components.DataGrid.setDatasource(DataGrid.java:207)
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractDataGridLoader.loadComponent(AbstractDataGridLoader.java:205)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:38)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:76)
	at com.haulmont.cuba.gui.xml.layout.loaders.GroupBoxLayoutLoader.loadComponent(GroupBoxLayoutLoader.java:67)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:38)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:76)
	at com.haulmont.cuba.gui.xml.layout.loaders.WindowLoader.loadComponent(WindowLoader.java:94)
	at com.haulmont.cuba.web.sys.WebScreens.loadWindowFromXml(WebScreens.java:366)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:233)
```

**Comment by natfirst** [comment]
Try to create any item from the legacy edit screen
```
java.lang.IllegalStateException: Datasource doesn't contain items
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.setSelected(WebAbstractDataGrid.java:1783)
	at com.haulmont.cuba.web.gui.components.WebAbstractDataGrid.setSelected(WebAbstractDataGrid.java:1773)
	at com.haulmont.cuba.gui.components.actions.CreateAction.lambda$internalOpenEditor$0(CreateAction.java:323)
	at com.haulmont.cuba.gui.components.compatibility.AfterCloseListenerAdapter.accept(AfterCloseListenerAdapter.java:58)
	at com.haulmont.cuba.gui.components.compatibility.AfterCloseListenerAdapter.accept(AfterCloseListenerAdapter.java:26)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:128)
	at com.haulmont.cuba.gui.screen.Screen.close(Screen.java:343)
	at com.haulmont.cuba.gui.screen.StandardEditor.lambda$closeWithCommit$6(StandardEditor.java:588)
	at com.haulmont.cuba.gui.util.SuccessOperationResult.compose(SuccessOperationResult.java:39)
	at com.haulmont.cuba.gui.screen.StandardEditor.closeWithCommit(StandardEditor.java:588)
	at com.haulmont.cuba.gui.screen.StandardEditor.commitAndClose(StandardEditor.java:553)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.actions.BaseAction.actionPerform(BaseAction.java:222)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:67)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by andreysubbotin** [comment]
The last error is not a bug. It's the unsupported case with a master screen on new screen API and detail screen  on legacy screen API.
