### ISSUE TITLE
Enable WebSocket support on Jetty

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba#2795]
https://www.cuba-platform.ru/discuss/t/web-sockets-stomp/4052

### Environment

- Platform version: 7.2

### Description of the bug or enhancement
Depends on: #2791 
- Minimal reproducible example
   - Download project https://github.com/cuba-labs/websocket-sample.git
   - Add uber jar deployment and run the uber jar
- Expected behavior
   - Navigate to http://localhost:8080/cs/VAADIN/index.html, click on Connect Button, enter smth and click Send button.
   - See new message in a greetings list
- Actual behavior
The application isn't started. Error in the log:
```
19:53:42.622 WARN  o.eclipse.jetty.webapp.WebAppContext    - Failed startup of context o.e.j.w.WebAppContext@336e1bcf{/app,jar:file:/E:/projects/groupstp/dispatcher/smartdispatch/build
/distributions/uberJar/app.jar!/LIB-INF/app,UNAVAILABLE}
org.springframework.context.ApplicationContextException: Failed to start bean 'stompWebSocketHandlerMapping'; nested exception is java.lang.IllegalStateException: Unable to start Jetty
 WebSocketServerFactory
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185) ~[na:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[na:na]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[na:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[na:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[na:na]
        at org.springframework.context.support.AbstractRefreshableConfigApplicationContext.afterPropertiesSet(AbstractRefreshableConfigApplicationContext.java:154) ~[na:na]
        at com.haulmont.cuba.core.sys.CubaClassPathXmlApplicationContext.<init>(CubaClassPathXmlApplicationContext.java:39) ~[na:na]
        at com.haulmont.cuba.core.sys.AbstractAppContextLoader.createApplicationContext(AbstractAppContextLoader.java:97) ~[na:na]
        at com.haulmont.cuba.core.sys.AbstractAppContextLoader.initAppContext(AbstractAppContextLoader.java:65) ~[na:na]
        at com.haulmont.cuba.core.sys.AbstractWebAppContextLoader.contextInitialized(AbstractWebAppContextLoader.java:83) ~[na:na]
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:959) ~[app.jar:na]
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553) ~[app.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:924) ~[app.jar:na]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:365) ~[app.jar:na]
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497) ~[app.jar:na]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459) ~[app.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:854) ~[app.jar:na]
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278) ~[app.jar:na]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545) ~[app.jar:na]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[app.jar:na]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167) ~[app.jar:na]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119) ~[app.jar:na]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) ~[app.jar:na]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[app.jar:na]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167) ~[app.jar:na]
        at org.eclipse.jetty.server.Server.start(Server.java:418) ~[app.jar:na]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) ~[app.jar:na]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) ~[app.jar:na]
        at org.eclipse.jetty.server.Server.doStart(Server.java:382) ~[app.jar:na]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[app.jar:na]
        at com.haulmont.uberjar.CubaJettyServer.start(CubaJettyServer.java:127) ~[app.jar:na]
        at com.haulmont.uberjar.ServerRunner.execute(ServerRunner.java:249) ~[app.jar:na]
        at com.haulmont.uberjar.ServerRunner.main(ServerRunner.java:39) ~[app.jar:na]
Caused by: java.lang.IllegalStateException: Unable to start Jetty WebSocketServerFactory
        at org.springframework.web.socket.server.jetty.JettyRequestUpgradeStrategy.start(JettyRequestUpgradeStrategy.java:134) ~[na:na]
        at org.springframework.web.socket.server.support.AbstractHandshakeHandler.doStart(AbstractHandshakeHandler.java:210) ~[na:na]
        at org.springframework.web.socket.server.support.AbstractHandshakeHandler.start(AbstractHandshakeHandler.java:204) ~[na:na]
        at org.springframework.web.socket.sockjs.transport.handler.WebSocketTransportHandler.start(WebSocketTransportHandler.java:87) ~[na:na]
        at org.springframework.web.socket.sockjs.transport.TransportHandlingSockJsService.start(TransportHandlingSockJsService.java:169) ~[na:na]
        at org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler.start(SockJsHttpRequestHandler.java:105) ~[na:na]
        at org.springframework.web.socket.server.support.WebSocketHandlerMapping.start(WebSocketHandlerMapping.java:56) ~[na:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[na:na]
        ... 34 common frames omitted
Caused by: java.lang.NullPointerException: javax.servlet.ServletContext
        at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[na:na]
        at org.eclipse.jetty.websocket.server.WebSocketServerFactory.<init>(WebSocketServerFactory.java:137) ~[app.jar:na]
        at org.eclipse.jetty.websocket.server.WebSocketServerFactory.<init>(WebSocketServerFactory.java:132) ~[app.jar:na]
        at org.springframework.web.socket.server.jetty.JettyRequestUpgradeStrategy.start(JettyRequestUpgradeStrategy.java:122) ~[na:na]
        ... 41 common frames omitted
```

**Comment by andreysubbotin** [comment]
Fixed in #2791
