### ISSUE TITLE
Error on screen commit if the committed object graph contains entities with inheritance

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#2798]
### Environment

- Platform version: 7.2.2

### Description of the bug or enhancement

Open and run the attached project:
[testviews.zip](https://github.com/cuba-platform/cuba/files/4420057/testviews.zip)

- Create Order
- Click Create, fill attributes, save
- Click Create2, fill attributes, save
- Try to save the order.
- Exception is thrown:

```
java.lang.IllegalArgumentException: Property 'param2' not found in testviews_DetailType1
	at com.haulmont.chile.core.model.impl.MetaClassImpl.getPropertyNN(MetaClassImpl.java:107)
	at com.haulmont.cuba.core.sys.EntityFetcher.fetch(EntityFetcher.java:120)
	at com.haulmont.cuba.core.sys.EntityFetcher.fetch(EntityFetcher.java:132)
	at com.haulmont.cuba.core.sys.EntityFetcher.fetch(EntityFetcher.java:156)
	at com.haulmont.cuba.core.sys.EntityFetcher.fetch(EntityFetcher.java:89)
	at com.haulmont.cuba.core.app.RdbmsStore.commit(RdbmsStore.java:433)
...
```

Caused by https://github.com/cuba-platform/cuba/issues/2745

**Comment by knstvk** [comment]
Linked to 23e6f47301de55440be465b6bef41fc264f8d67f by mistake.
