### ISSUE TITLE
URL browser history and navigation

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#280]
We should provide first-class support for URLs and parameters that should replace `LinkHandler` completely and bring new functionality.

Please note that we should permit both authorized and non-authorized access to URLs, for instance public pages of web application, such as Terms of use, Help, Registration and so on.

See forum: 
- [CUBA Changes URL via HTML5 History API](https://www.cuba-platform.com/support/topic/cuba-changes-url-via-html5-history-api)
- [Anonymous access](https://www.cuba-platform.ru/support/topic/как-отдать-веб-страницу-неавторизованному-пользователю#comment-2952) 

### Issues to be addressed:

- [x] Screen links: `/login`, `/main`, `/help`, etc
- [x] Sub paths: `/main/users`, `/main/users/<base64_id>`, `/main/users/add` (the last one should be explicitly defined by user-developer)
- [x] `UrlParamsChangedEvent`
- [x] New API for URL changing (route, params)
- [x] Handle 404
- [x] Screen navigation access check

---
Original issue: https://youtrack.haulmont.com/issue/PL-8076

**Comment by knstvk** [comment]
Not sure if we have to fix it, but the following steps lead to the below error:
- Start an app and open a screen
- Restart the app server
- Click on "Communication problem" banner
- Login again
- The following message is shown:

![image](https://user-images.githubusercontent.com/5513878/48301158-9bb7a800-e502-11e8-8d3c-dae5d15a454b.png)

**Comment by jreznot** [comment]
It seems that if URL is incorrect UI is not initialized correctly:
```
Exception in handlers:
java.lang.NullPointerException
        at com.haulmont.cuba.web.exception.ExceptionDialog.<init>(ExceptionDialog.java:117)
        at com.haulmont.cuba.web.exception.ExceptionDialog.<init>(ExceptionDialog.java:86)
        at com.haulmont.cuba.web.exception.DefaultExceptionHandler.showDialog(DefaultExceptionHandler.java:88)
        at com.haulmont.cuba.web.exception.DefaultExceptionHandler.handle(DefaultExceptionHandler.java:74)
        at com.haulmont.cuba.web.exception.ExceptionHandlers.handle(ExceptionHandlers.java:120)
```

**Comment by jreznot** [comment]
> 20:14:35.777 INFO  c.h.c.web.navigation.WebUrlRouting      - There's no route for screen "ref_Car.edit". URL params will be ignored

Let's make it DEBUG, it is completely OK if a screen does not have route.

**Comment by dtsaryov** [comment]
Studio support issue: [YouTrack](https://youtrack.cuba-platform.com/issue/STUDIO-5178).

**Comment by jreznot** [comment]
We need inheritance of route by default for both legacy and new screens, essentially inherited screen must have the same route by default if not set explicitly.

**Comment by myatlevEvg** [comment]
Sporadically occured exceprion at the main window page after starting app server and opening localhost.
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/49c59250-47d5-486c-a7a8-c73687928901)

**Comment by dtsaryov** [comment]
@myatlevEvg this problem was fixed in the previous commit

**Comment by web-devel** [comment]
![image](https://user-images.githubusercontent.com/3295727/49224157-1edd6700-f3fa-11e8-9658-12fdb6f60e0f.png)
Unfortunately did not catch conditions when it happened

**Comment by natfirst** [comment]
1. Create browser and editor legacy screens
2. Set the route for both screens
3. For the editor screen set the routeParentPrefix different from the browser route
4. Run the app, open editor screen

**A.R.** The editor URL will not contain any parent prefix neither of the browser or the routeParentPrefix attribute

**Comment by natfirst** [comment]
There should be a notification in the log if two or more screens have the same route

**Comment by natfirst** [comment]
1. Open browser screen, open editor (in this tab). 
2. Click history forward button and see the notification (this is OK)
3. Click backwards and return to the browser
4. Click forward and then backwards, the screen does not return to the main, notification will appear
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/3eb4f68e-3a7b-40b2-82ad-bbede2a15f5e)

**Comment by natfirst** [comment]
1. Create browser and editor legacy screens
2. Set the route for both screens
3. Set openType="DIALOG" for the editor
4. Run the app, open editor
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931)
	at com.haulmont.cuba.web.navigation.WebUrlRouting.buildDialogRoute(WebUrlRouting.java:175)
	at com.haulmont.cuba.web.navigation.WebUrlRouting.buildNestedRoute(WebUrlRouting.java:153)
	at com.haulmont.cuba.web.navigation.WebUrlRouting.buildNavState(WebUrlRouting.java:136)
	at com.haulmont.cuba.web.navigation.WebUrlRouting.updateState(WebUrlRouting.java:97)
	at com.haulmont.cuba.web.navigation.WebUrlRouting.pushState(WebUrlRouting.java:75)
	at com.haulmont.cuba.web.navigation.UrlRouting.pushState(UrlRouting.java:42)
	at com.haulmont.cuba.web.sys.WebScreens.show(WebScreens.java:423)
	at com.haulmont.cuba.web.sys.WebScreens.openEditor(WebScreens.java:1082)
	at com.haulmont.cuba.gui.components.HasWindowManager.openEditor(HasWindowManager.java:150)
	at com.haulmont.cuba.gui.components.actions.CreateAction.internalOpenEditor(CreateAction.java:298)
	at com.haulmont.cuba.gui.components.actions.CreateAction.actionPerform(CreateAction.java:257)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:62)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by natfirst** [comment]
1. Create browser and editor screens (new version)
2. Add `@Route("foo")` annotation to the browser and `@Route(path = "bar", parentPrefix = "foo")` to the editor
3. Start the app, create an entity
4. Open this entity to the edit, copy URL
5. Open URL in the new tab

![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/3c6950d9-f587-437d-a251-52f2421d2613)

**Comment by natfirst** [comment]
URL params are not propagated in case of nested route isn't changed

**Comment by natfirst** [comment]
1. Create BaseStringIdEntity entity
2. Create a browser and editor
3. Set routes
4. Run the app. Try to create new instance
```
java.lang.IllegalArgumentException: Unable to serialize null id
	at com.haulmont.bali.util.Preconditions.checkNotNullArgument(Preconditions.java:102)
	at com.haulmont.cuba.web.sys.navigation.UrlTools.serializeId(UrlTools.java:52)
	at com.haulmont.cuba.web.navigation.WebUrlRouting.processParams(WebUrlRouting.java:254)
	at com.haulmont.cuba.web.navigation.WebUrlRouting.buildNavState(WebUrlRouting.java:137)
	at com.haulmont.cuba.web.navigation.WebUrlRouting.updateState(WebUrlRouting.java:97)
	at com.haulmont.cuba.web.navigation.WebUrlRouting.pushState(WebUrlRouting.java:75)
	at com.haulmont.cuba.web.navigation.UrlRouting.pushState(UrlRouting.java:42)
	at com.haulmont.cuba.web.sys.WebScreens.show(WebScreens.java:423)
	at com.haulmont.cuba.gui.screen.Screen.show(Screen.java:307)
	at com.haulmont.cuba.gui.actions.list.CreateAction.actionPerform(CreateAction.java:121)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:62)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by dtsaryov** [comment]
> A.R. The editor URL will not contain any parent prefix neither of the browser or the routeParentPrefix attribute

It's not a bug, because:

`routeParentprefix` enables to specify a substring of a child route that should be skipped when parent and child routes are combined:

```Java
@Route("bars")
public class BarBrowser { ... }

@Route("bars/edit", parentPrefix = "bars")
public class BarEditor { ... }
```

Let `BarEditor` is opened in the same tab where `BarBrowser` is opened. 
- Without `parentPrefix` property a route will be "bars" + "bars/edit" = "bars/bars/edit".
- When `parentPrefix` is specified as "bars" this part of child route will be skipped and a route will be "bars/edit".

**Comment by dtsaryov** [comment]
@natfirst 

Please check supported `UrlRouting` injection intro screen controllers.

**Comment by sukhova** [comment]
The URL does not change when the current route consists of two parts separated by a slash.

In the **Refapp**:

1) **Administration** -> **Users**
2) Create a new user, but don't save it
3) Open **Administration** -> **Roles**

**AR**:
The URL does not change

**Comment by sukhova** [comment]
1) Create browser and editor screens.
2) Set routes for both screens.
3) Run the app.
4) Open the browser, then click on the **Create** button.
5) For example, an address is:
```host:port/app/#main/6/customers/customers/edit?id=5m55ewvv8140e4a0nbj1snjp2m```
6) Erase the address from the end, like this: ```host:port/app/#main/6/customers/customers/```

**AR**:

```
java.lang.IllegalArgumentException: null source
	at java.util.EventObject.<init>(EventObject.java:56)
	at com.haulmont.cuba.gui.navigation.UrlParamsChangedEvent.<init>(UrlParamsChangedEvent.java:45)
	at com.haulmont.cuba.web.sys.navigation.UrlChangeHandler.handleParamsChange(UrlChangeHandler.java:449)
	at com.haulmont.cuba.web.sys.navigation.UrlChangeHandler.handleScreenNavigation(UrlChangeHandler.java:199)
	at com.haulmont.cuba.web.sys.navigation.UrlChangeHandler.__handleUrlChange(UrlChangeHandler.java:123)
	at com.haulmont.cuba.web.sys.navigation.UrlChangeHandler.handleUrlChange(UrlChangeHandler.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.Page.fireEvent(Page.java:699)
	at com.vaadin.server.Page.updateLocation(Page.java:1126)
	at com.vaadin.ui.UI$1.popstate(UI.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by sukhova** [comment]
1) Login into application
2) Let address is ```http://localhost:8080/app/#main/main``` or ```http://localhost:8080/app/#main/login```

**ER**:
![2.jpg](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/8d87d039-1e85-4665-861d-be6a4297f920)
