### ISSUE TITLE
Error on editing entity with many-to-many mappedBy property

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba#2811]
https://www.cuba-platform.ru/discuss/t/sozdanie-inversnogo-atributa-studiej/4146

### Environment

- Platform version: 7.2

### Description of the bug or enhancement
- Create entity with toMany property: 
```
@ManyToMany(mappedBy = "details")
protected List<NewEntity> newEntities;
```
- Try to open entity editor. Error occurs:
```
java.lang.ClassCastException: com.company.testviews.entity.InterMediate cannot be cast to java.util.List
	at com.haulmont.chile.core.model.utils.MethodsCache$SettersHolder.accept(MethodsCache.java:193)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:160)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:126)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:142)
	at com.haulmont.cuba.gui.builders.EditorBuilderProcessor.initializeNestedEntity(EditorBuilderProcessor.java:308)
	at com.haulmont.cuba.gui.builders.EditorBuilderProcessor.initEntity(EditorBuilderProcessor.java:224)
	at com.haulmont.cuba.gui.builders.EditorBuilderProcessor.buildEditor(EditorBuilderProcessor.java:80)
	at com.haulmont.cuba.gui.builders.EditorBuilder.show(EditorBuilder.java:366)
	at com.company.testviews.web.screens.order.OrderFragment.createDetailEntity(OrderFragment.java:37)
	at com.company.testviews.web.screens.order.OrderFragment.onOrderDetailsTableCreate(OrderFragment.java:26)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.actions.BaseAction.actionPerform(BaseAction.java:222)
	at com.haulmont.cuba.gui.actions.list.CreateAction.actionPerform(CreateAction.java:288)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:67)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by knstvk** [comment]
QA: how to reproduce - start the attached project, edit Product, click "New tag".
[m2m-mappedby.zip](https://github.com/cuba-platform/cuba/files/4728519/m2m-mappedby.zip)
