### ISSUE TITLE
Unfetched attribute exception in the Group Browser

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2912]
### Environment

- Platform version: 7.2.4

### Description of the bug or enhancement
- Open http://cubadev:9072/app/#login
- Menu -> Administration -> Access Groups
- Select Company group
- Press Edit
- Don't change anything in the editor
- Press OK
- Exception occurs:
java.lang.IllegalStateException: Cannot get unfetched attribute [parent] from detached object com.haulmont.cuba.security.entity.Group-0fa2b1a5-1d68-4d69-9fbd-dff348347f93 [detached].

<details>
 <summary>Click to expand</summary>
 
```java
java.lang.IllegalStateException: Cannot get unfetched attribute [parent] from detached object com.haulmont.cuba.security.entity.Group-0fa2b1a5-1d68-4d69-9fbd-dff348347f93 [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100)
	at com.haulmont.cuba.core.sys.persistence.CubaEntityFetchGroup.onUnfetchedAttribute(CubaEntityFetchGroup.java:74)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:2998)
	at com.haulmont.chile.core.model.impl.AbstractInstance._persistence_checkFetched(AbstractInstance.java)
	at com.haulmont.cuba.security.entity.Group._persistence_get_parent(Group.java)
	at com.haulmont.cuba.security.entity.Group.getParent(Group.java:82)
	at com.haulmont.chile.core.model.impl.AbstractInstance.getValue(AbstractInstance.java:108)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.getValue(BaseGenericIdEntity.java:146)
	at com.haulmont.cuba.gui.data.impl.HierarchicalDatasourceImpl.getRootItemIds(HierarchicalDatasourceImpl.java:86)
	at com.haulmont.cuba.gui.components.data.tree.DatasourceTreeItems.getChildren(DatasourceTreeItems.java:153)
	at com.haulmont.cuba.gui.components.data.tree.DatasourceTreeItems.getChildCount(DatasourceTreeItems.java:147)
	at com.haulmont.cuba.gui.components.data.tree.DatasourceTreeItems.getChildCount(DatasourceTreeItems.java:36)
	at com.haulmont.cuba.web.gui.components.tree.TreeDataProvider.getChildCount(TreeDataProvider.java:106)
	at com.vaadin.data.provider.HierarchyMapper.getDirectChildren(HierarchyMapper.java:494)
	at com.vaadin.data.provider.HierarchyMapper.getChildrenStream(HierarchyMapper.java:525)
	at com.vaadin.data.provider.HierarchyMapper.lambda$getHierarchy$1(HierarchyMapper.java:482)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:257)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:605)
	at com.vaadin.data.provider.HierarchyMapper.getTreeSize(HierarchyMapper.java:88)
	at com.vaadin.data.provider.HierarchicalDataCommunicator.getDataProviderSize(HierarchicalDataCommunicator.java:405)
	at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:363)
	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:343)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:118)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:115)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:84)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

**Comment by alexbudarov** [comment]
discoverer: https://www.cuba-platform.com/discuss/t/illegalstateexception-error/12483/7
