### ISSUE TITLE
IllegalArgumentException occurs after re-expanding the Search folders hierarchy tree

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/cuba#2919]
### Environment

- Platform version: 7.2.5
- Database: Oracle Database
- Demo project [aft.zip](https://github.com/cuba-platform/cuba/files/4786479/aft.zip)
- Forum issue: https://www.cuba-platform.ru/discuss/t/nekorrektnoe-povedenie-pri-zagruzke-usersetting-dlya-subd-oracle/4414/2

### Description of the bug or enhancement

1. Create a new project 
2. Select Oracle db as the main database
3. Extends the main screen 
4. Enabled the pane folders 
5. Run the project and login in the app
6. Create the first search folder (for example `root`)
7. Create the second search folder (for example `sub1`) selected the first folder as the parent
8. Create the third search folder (for example `sub2`) selected the first folder as the parent
9. Сollapse and expand the folder
10. Сollapse and expand the folder

- Actual behavior
IllegalArgumentException occurs after re-expanding the tree hierarchy
```
java.lang.IllegalArgumentException: Invalid UUID string:  
	at java.base/java.util.UUID.fromString(UUID.java:215)
	at com.haulmont.cuba.web.app.folders.CubaFoldersPane.strToIds(CubaFoldersPane.java:374)
	at com.haulmont.cuba.web.app.folders.CubaFoldersPane.removeIdInStr(CubaFoldersPane.java:363)
	at com.haulmont.cuba.web.app.folders.CubaFoldersPane.lambda$collapseItemInTree$60585b96$1(CubaFoldersPane.java:338)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041)
	at com.vaadin.ui.Tree.fireExpandEvent(Tree.java:403)
	at com.vaadin.ui.Tree.lambda$new$1c20fe91$1(Tree.java:289)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041)
	at com.vaadin.ui.TreeGrid.fireExpandEvent(TreeGrid.java:640)
	at com.vaadin.ui.TreeGrid.lambda$registerTreeGridRpc$275f28ba$1(TreeGrid.java:188)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
```

### QA
Check the above case

**Comment by maistrenkoIulia** [comment]
[npe.txt](https://github.com/cuba-platform/cuba/files/4959237/npe.txt)
reopened
AR: sometimes appeares NPE during collaps/expand folder

**Comment by GlebDurygin** [comment]
> Caused by: java.lang.NullPointerException: null
	at com.haulmont.cuba.web.app.folders.CubaFoldersPane.lambda$collapseItemInTree$60585b96$1(CubaFoldersPane.java:336) ~[cuba-web-7.3-SNAPSHOT.jar:7.3-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496) ~[vaadin-server-8.9.2-13-cuba.jar:8.9.2-13-cuba]
	... 58 common frames omitted

`com/vaadin/event/ExpandEvent#getExpandedItem()` and `com/vaadin/event/CollapseEvent#getCollapsedItem()` methods may return `null` in rare cases. Thus, we need to add a null check to prevent the NPE.
