### ISSUE TITLE
Entity Log does not track changes of entity attributes if dynamic attributes were added

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#2932]
### Environment

- Platform version: 6.10.16
- Forum link https://www.cuba-platform.com/discuss/t/entitylog-error-with-dynamic-attribute/12880
- Demo project [sample99.zip](https://github.com/cuba-platform/cuba/files/4868104/sample99.zip)

Reproduced only for 6.10 and 7.0 platform versions, for 7.1 and 7.2 works fine

### Description of the bug or enhancement

1. Open demo project
2. Create some dynamic attributes for the Person entity
3. Set up Entity Log, choose all attributes
4. Create an entity instance
5. Modify a property of the entity (name or lastname)

```
20:39:56.241 WARN  c.h.cuba.security.app.EntityLog         - Unable to log entity com.company.sample99.entity.Person-b6fb4777-7c03-8fc2-7f56-a4aaab6bd6a9 [managed], id=b6fb4777-7c03-8fc2-7f56-a4aaab6bd6a9
java.lang.IllegalArgumentException: Property path +extraFieldsagrupacion isn't exists for type sample99$Person
	at com.haulmont.bali.util.Preconditions.checkNotNullArgument(Preconditions.java:124) ~[cuba-global-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.security.app.EntityLog.internalRegisterModify(EntityLog.java:545) ~[cuba-core-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.security.app.EntityLog.registerModify(EntityLog.java:515) ~[cuba-core-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.core.sys.persistence.PersistenceImplSupport$OnCommitEntityVisitor.visit(PersistenceImplSupport.java:577) [cuba-core-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.core.sys.persistence.PersistenceImplSupport.beforeStore(PersistenceImplSupport.java:236) [cuba-core-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.core.sys.persistence.PersistenceImplSupport.traverseEntities(PersistenceImplSupport.java:222) [cuba-core-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.core.sys.persistence.PersistenceImplSupport$ContainerResourceSynchronization.beforeCommit(PersistenceImplSupport.java:408) [cuba-core-6.10.17.jar:6.10.17]
	at org.springframework.transaction.support.TransactionSynchronizationUtils.triggerBeforeCommit(TransactionSynchronizationUtils.java:95) [spring-tx-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerBeforeCommit(AbstractPlatformTransactionManager.java:936) [spring-tx-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:748) [spring-tx-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:734) [spring-tx-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at com.haulmont.cuba.core.sys.TransactionImpl.commit(TransactionImpl.java:104) [cuba-core-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.core.app.RdbmsStore.commit(RdbmsStore.java:476) [cuba-core-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.core.app.DataManagerBean.commit(DataManagerBean.java:161) [cuba-core-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.core.app.DataServiceBean.commit(DataServiceBean.java:41) [cuba-core-6.10.17.jar:6.10.17]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) [spring-aop-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:84) [spring-aop-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:116) [cuba-core-6.10.17.jar:6.10.17]
	at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627) [spring-aop-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616) [spring-aop-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) [spring-aop-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) [spring-aop-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at com.sun.proxy.$Proxy218.commit(Unknown Source) [na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94) [cuba-core-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154) [cuba-web-6.10.17.jar:6.10.17]
	at com.sun.proxy.$Proxy29.commit(Unknown Source) [na:na]
	at com.haulmont.cuba.client.sys.DataManagerClientImpl.commit(DataManagerClientImpl.java:100) [cuba-client-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.gui.data.impl.GenericDataSupplier.commit(GenericDataSupplier.java:105) [cuba-gui-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.gui.data.impl.DsContextImpl.commit(DsContextImpl.java:166) [cuba-gui-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.gui.components.EditorWindowDelegate.commit(EditorWindowDelegate.java:271) [cuba-gui-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.web.gui.WebWindow$Editor.commitAndClose(WebWindow.java:1773) [cuba-web-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.gui.components.AbstractEditor.commitAndClose(AbstractEditor.java:111) [cuba-gui-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.gui.components.EditorWindowDelegate.lambda$wrapBy$1(EditorWindowDelegate.java:94) [cuba-gui-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.gui.components.actions.BaseAction.actionPerform(BaseAction.java:228) ~[cuba-gui-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.web.gui.WebWindow$1.handleAction(WebWindow.java:152) ~[cuba-web-6.10.17.jar:6.10.17]
	at com.vaadin.event.ActionManager.handleAction(ActionManager.java:245) ~[vaadin-server-7.7.15.cuba.12.jar:7.7.15.cuba.12]
	at com.vaadin.event.ActionManager.handleActions(ActionManager.java:228) ~[vaadin-server-7.7.15.cuba.12.jar:7.7.15.cuba.12]
	at com.haulmont.cuba.web.toolkit.ui.CubaOrderedActionsLayout.changeVariables(CubaOrderedActionsLayout.java:83) ~[cuba-web-6.10.17.jar:6.10.17]
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:623) ~[vaadin-server-7.7.15.cuba.12.jar:7.7.15.cuba.12]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:470) ~[vaadin-server-7.7.15.cuba.12.jar:7.7.15.cuba.12]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:413) ~[vaadin-server-7.7.15.cuba.12.jar:7.7.15.cuba.12]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274) ~[vaadin-server-7.7.15.cuba.12.jar:7.7.15.cuba.12]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90) ~[vaadin-server-7.7.15.cuba.12.jar:7.7.15.cuba.12]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) ~[vaadin-server-7.7.15.cuba.12.jar:7.7.15.cuba.12]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435) ~[vaadin-server-7.7.15.cuba.12.jar:7.7.15.cuba.12]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:361) ~[vaadin-server-7.7.15.cuba.12.jar:7.7.15.cuba.12]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:324) ~[cuba-web-6.10.17.jar:6.10.17]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:210) ~[cuba-web-6.10.17.jar:6.10.17]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.33]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107) ~[spring-web-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73) ~[spring-web-4.3.23.RELEASE.jar:4.3.23.RELEASE]
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:107) ~[cuba-web-6.10.17.jar:6.10.17]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[catalina.jar:8.5.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[catalina.jar:8.5.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[catalina.jar:8.5.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) ~[catalina.jar:8.5.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[catalina.jar:8.5.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) ~[tomcat-coyote.jar:8.5.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) ~[tomcat-coyote.jar:8.5.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) ~[tomcat-coyote.jar:8.5.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.33]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```

**Comment by andreysubbotin** [comment]
Fixed in #1533
