### ISSUE TITLE
MasterDetailScreen refreshes lookup fields even if they have not enough parameters set

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2936]
### Environment

- Platform version:7.2.6

### Description of the bug or enhancement
See attached project.
[mydlc.zip](https://github.com/cuba-platform/cuba/files/4878076/mydlc.zip)

I have master-detail screen for entity with two association fields: Group and User.
Both fields are edited with lookupField.

Option containers for both fields are connected (we want to show users of selected group):
```
        <collection id="groupsDc" class="com.haulmont.cuba.security.entity.Group">
            <view extends="_local"/>
            <loader id="groupsDl">
                <query>
                    <![CDATA[select e from sec$Group e]]>
                </query>
            </loader>
        </collection>
        <collection id="usersDc" class="com.haulmont.cuba.security.entity.User">
            <view extends="_local"/>
            <loader id="usersDl">
                <query>
                    <![CDATA[select e from sec$User e where e.group = :container_groupsDc]]>
                </query>
            </loader>
        </collection>
```

Screen has dataLoadCoordinator defined, and @LoadDataBeforeShow is deleted.

But if you open the screen, don't select anything in left table and press "Create" - the exception about missing query parameter is thrown:
```
java.lang.IllegalStateException: Query argument container_groupsDc not found in the list of parameters provided during query execution.
	at org.eclipse.persistence.internal.jpa.QueryImpl.processParameters(QueryImpl.java:592)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:183)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:482)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultFromCache(QueryImpl.java:764)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultList(QueryImpl.java:412)
	at com.haulmont.cuba.core.app.RdbmsStore.executeQuery(RdbmsStore.java:889)
	at com.haulmont.cuba.core.app.RdbmsStore.getResultList(RdbmsStore.java:797)
	at com.haulmont.cuba.core.app.RdbmsStore.loadList(RdbmsStore.java:238)
...
com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:159)
	at com.sun.proxy.$Proxy237.loadList(Unknown Source)
	at com.haulmont.cuba.client.sys.DataManagerClientImpl.loadList(DataManagerClientImpl.java:57)
	at com.haulmont.cuba.gui.model.impl.CollectionLoaderImpl.load(CollectionLoaderImpl.java:107)
	at com.haulmont.cuba.gui.screen.MasterDetailScreen.refreshOptionsForLookupFields(MasterDetailScreen.java:319)
	at com.haulmont.cuba.gui.screen.MasterDetailScreen.lambda$initBrowseCreateAction$3(MasterDetailScreen.java:269)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.components.actions.BaseAction.actionPerform(BaseAction.java:222)
	at com.haulmont.cuba.gui.actions.list.CreateAction.actionPerform(CreateAction.java:288)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:67)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

Is it how it is supposed to work?
If we move query condition to the "c:where" section - we will get undesired effect: full list of users may be loaded to memory, which may be stressful for server.

**Comment by alexbudarov** [comment]
Also: if you rewrite master-detail screen to browser + editor - you won't get such exception. Editor works fine, and "user" option list is empty when group is not selected (click Create from browser).
[mydlc-with-editor.zip](https://github.com/cuba-platform/cuba/files/4883010/mydlc-with-editor.zip)

**Comment by knstvk** [comment]
https://github.com/cuba-platform/cuba/commit/eb879bb1bb3f369d5fe82ca591f46cf1652ff4d2
