### ISSUE TITLE
Problems with web anonymous session when deploying web/core separately

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2961]
### Environment
- Platform version: 7.2

### Description of the bug or enhancement
Current implementation of "anonymous session" in web client in CUBA 7 was developed without taking cluster and separate web/core deployment in mind.
It may cause bugs when web and core layers are deployed separately.

- anonymous session for web client is created and stored here: com.haulmont.cuba.security.auth.AnonymousSessionHolder
- these sessions are created with "system" flag, so they are normally not expired and not replicated to other cluster nodes
- so each core node has its own anonymous session with own ID
- web client's anonymous session holder: com.haulmont.cuba.web.security.WebAnonymousSessionHolder
- WebAnonymousSessionHolder takes anonymous session from core layer **only once** and remembers it forever, without ever trying to reinitialize it
- so if web layer takes session from core node C1, and then C1 goes down - then web client is left with invalid anonymous session without ability to renew it
- **partially** this problem is shadowed by the fact the com.haulmont.cuba.security.app.UserSessions#sendClusterState method transfers all sessions include anonymous session to other cluster nodes when they are starting after 1st server. So if web layer takes its anonymous session from core node #1 - that session later becomes transferred to other core nodes.

### Reproducing the bug
The problem can be reproduced reliably even without middleware cluster, just by deploying "web" and "core" separately.

1) Create two separate tomcats, one holding "app-core" and another holding "app".

2) Local configuration for "app-core" tomcat:
- change ports in server.xml to 8006, 8081, remove AJP connector

3) Local configuration in "app" tomcat:
- set properties in local.app.properties:
```
cuba.useLocalServiceInvocation = false
cuba.connectionUrlList = http://localhost:8081/app-core
```

4) Start "app-core" tomcat
5) Start "app" tomcat
6) Log in to the application in browser (http://localhost:8080/app)
7) Stop "app-core" tomcat
8) Start "app-core" tomcat (here anonymous session is re-created with another ID)

9) Try to re-login in the browser.

Expected: user needs to relogin like it is usually necessary when we loose user sessions.

Actual: unrecoverable error in web client. It happens because web client stubbornly tries to use old anonymous session which is no longer valid:
![image](https://user-images.githubusercontent.com/6158807/87314505-5ef04f80-c534-11ea-9127-117ea1ee73bb.png)

Error messages in "app-core":
```
2020-07-13 18:05:47.260 INFO  [http-nio-8081-exec-7/app-core] com.haulmont.cuba.core.sys.ServiceInterceptor - Exception in UserSettingService.loadSetting(..): com.haulmont.cuba.security.global.NoUserSessionException: User session not found: 87246d1b-4aab-420d-947e-9574e104dcd5
2020-07-13 18:05:47.400 INFO  [http-nio-8081-exec-9/app-core] com.haulmont.cuba.core.sys.ServiceInterceptor - Exception in UserSettingService.loadSetting(..): com.haulmont.cuba.security.global.NoUserSessionException: User session not found: 87246d1b-4aab-420d-947e-9574e104dcd5
```

Error messages in "app":
```
2020-07-13 18:11:03.023 ERROR [http-nio-8080-exec-8/app/anonymous] com.haulmont.cuba.web.AppUI - Unable to init ui
com.haulmont.cuba.security.global.NoUserSessionException: User session not found: 87246d1b-4aab-420d-947e-9574e104dcd5
        at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:85) ~[na:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
        at ...
        at com.sun.proxy.$Proxy91.loadSetting(Unknown Source) ~[na:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205) ~[spring-aop-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at com.sun.proxy.$Proxy201.loadSetting(Unknown Source) ~[na:na]
...
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at com.sun.proxy.$Proxy32.loadSetting(Unknown Source) ~[na:na]
        at com.haulmont.cuba.web.settings.WebSettingsClient.getSetting(WebSettingsClient.java:50) ~[cuba-web-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.gui.settings.SettingsImpl.checkLoaded(SettingsImpl.java:48) ~[cuba-gui-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.gui.settings.SettingsImpl.get(SettingsImpl.java:72) ~[cuba-gui-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.gui.screen.ScreenSettings.lambda$applyDataLoadingSettings$1(ScreenSettings.java:91) ~[cuba-gui-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.gui.ComponentsHelper.__walkComponents(ComponentsHelper.java:294) ~[cuba-gui-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.gui.ComponentsHelper.__walkComponents(ComponentsHelper.java:300) ~[cuba-gui-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.gui.ComponentsHelper.__walkComponents(ComponentsHelper.java:300) ~[cuba-gui-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.gui.ComponentsHelper.walkComponents(ComponentsHelper.java:277) ~[cuba-gui-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.gui.screen.ScreenSettings.applyDataLoadingSettings(ScreenSettings.java:84) ~[cuba-gui-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.gui.screen.Screen.applyDataLoadingSettings(Screen.java:456) ~[cuba-gui-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.gui.screen.UiControllerUtils.applyDataLoadingSettings(UiControllerUtils.java:114) ~[cuba-gui-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.web.sys.WebScreens.applyDataLoadingSettings(WebScreens.java:577) ~[cuba-web-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.web.sys.WebScreens.show(WebScreens.java:430) ~[cuba-web-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.web.App.createTopLevelWindow(App.java:306) ~[cuba-web-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.web.DefaultApp.initializeUi(DefaultApp.java:244) ~[cuba-web-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.web.DefaultApp.connectionStateChanged(DefaultApp.java:112) ~[cuba-web-7.2.6.jar:7.2.6]
        at com.haulmont.bali.events.EventHub.publish(EventHub.java:170) ~[cuba-global-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.web.security.ConnectionImpl.fireStateChangeListeners(ConnectionImpl.java:228) ~[cuba-web-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.web.security.ConnectionImpl.login(ConnectionImpl.java:106) ~[cuba-web-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.web.DefaultApp.loginOnStart(DefaultApp.java:312) ~[cuba-web-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.web.AppUI.setupUI(AppUI.java:522) ~[cuba-web-7.2.6.jar:7.2.6]
        at com.haulmont.cuba.web.AppUI.init(AppUI.java:346) ~[cuba-web-7.2.6.jar:7.2.6]
        at com.vaadin.ui.UI.doInit(UI.java:738) [vaadin-server-8.9.2-13-cuba.jar:8.9.2-13-cuba]
        at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:209) [vaadin-server-8.9.2-13-cuba.jar:8.9.2-13-cuba]
        at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:67) [vaadin-server-8.9.2-13-cuba.jar:8.9.2-13-cuba]
```

### The same bug with core node failover in cluster
Reproduced 1 of 2 times.
Deploy 3 tomcats: web, core1, core2.
- Start core2 (anon2 session is created)
- Start core1 (anon1 session is created, anon2 is taken from core2 with jgroups state transfer)
- Start web
- Login to web client. It should take anonymous session anon1 from core1 and cache it.
- Stop core1
- Try to relogin in web client. Login screen fails, because core2 doesn't have cached "anon1" session.

### Suggestions
Previous implementation of anonymous session holder in portal module - com.haulmont.cuba.portal.sys.security.AnonymousSessionHolder - works fine.

So ideally anonymous session would need to be re-worked like done there:
- anonymous sessions are not "system", they are replicated to cluster
- anonymous sessions are periodically ping-ed by web client
- attempt to re-create and obtain new anonymous session if it gets lost for some reason
- we can still re-use them in middleware if we want so, but we'll need to validate that cached session was not expired

Alternative, less radical fix:
- When anonymous screen (login screen) is about to be shown (after logout or when user opens the application) - validate anonymous session in WebAnonymousSessionHolder and re-obtain it from core module if necessary.
- This fix will not work with round-robin balancing between web and core.

**Comment by andreysubbotin** [comment]
Test project: [https://app.zenhub.com/files/54624511/5de0b470-8487-449b-aeb2-e552066e577c/download](https://app.zenhub.com/files/54624511/5de0b470-8487-449b-aeb2-e552066e577c/download)

Gradle commands:
