### ISSUE TITLE
PickerOpenComposition action returns NPE if it is a composition with entity with legacy screens

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#2980]
### Environment

- Platform version: 7.2.6
- Forum issue https://www.cuba-platform.com/discuss/t/one-to-one-composition-to-sec-user-pickerfield-null-exception-cuba-7-2-6/13087

### Description of the bug or enhancement

1. Create an entity
2. Create a ONE_TO_ONE composition attribute with the User, Role, Group or another entity with legacy screens
3. Generate standard browser and editor 
PickerField with open_composition action will be generated
```
<pickerField id="groupField" property="group">
                    <actions>
                        <action id="open_composition" type="picker_open_composition"/>
                        <action id="clear" type="picker_clear"/>
                    </actions>
                </pickerField>
```
4. Generate DB scripts and start the app
5. Create a new entity instance and click to open_composition action

*A.R.* NPE occures
```java.lang.NullPointerException
at com.haulmont.cuba.gui.builders.EditorBuilderProcessor.buildEditor(EditorBuilderProcessor.java:144)
at com.haulmont.cuba.gui.builders.EditorBuilder.build(EditorBuilder.java:359)
at com.haulmont.cuba.gui.actions.picker.OpenAction.execute(OpenAction.java:317)
at com.haulmont.cuba.gui.actions.picker.OpenAction.actionPerform(OpenAction.java:275)
at com.haulmont.cuba.web.gui.components.WebPickerField.lambda$setPickerButtonAction$0(WebPickerField.java:340)
at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
at com.vaadin.ui.Button$1.click(Button.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by knstvk** [comment]
Composition between normal and legacy screens is impossible.
Replaced NPE with a meaningful exception.

**Comment by Mihail063** [comment]
Platform version: 7.2 - SNAPSHOT

1. Create an entity
2. Create a ONE_TO_ONE composition attribute with the Role attribute type
3. Generate legacy browser and editor screens
4. Run the project
5. Start to create a new entity instance
6. Click on the lookup button
![изображение](https://user-images.githubusercontent.com/24281695/92235309-80cada80-eec4-11ea-9483-cbbc7dab1c6e.png)

AR: Roles browser screen was not shown.

**Comment by knstvk** [comment]
Look at my comment above: https://github.com/cuba-platform/cuba/issues/2980#issuecomment-685461849
All we can do is to show an exception with meaningful description instead of NPE.

**Comment by Mihail063** [comment]
But both screens (browser and editor) are legacy. Exception was not shown and nothing happened when clicking to the lookup button.
![BugInLookup](https://user-images.githubusercontent.com/24281695/92246664-225b2780-eed7-11ea-9c3d-2fadd9604c6c.gif)

**Comment by knstvk** [comment]
It's the same on 7.2.7, so it's not related to recent changes.
And we are not going to change anything in the legacy screens API except for critical issues.
