### ISSUE TITLE
IllegalArgumentException occurs after trying to set value for a filter with custom condition with param type entity

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/cuba#2987]
### Environment

- Platform version: 7.2.7
- Forum [topic]( https://www.cuba-platform.com/discuss/t/possible-bug-in-filters/13165)

### Description of the bug or enhancement

1. Create a new project
2. Create the first persistent entity with UUID Id type (for example A)
3. Create the second persistent entity with UUID Id type (for example B)
4. Create the third persistent entity with Integer Id type (for example C)
5. Open the first entity and create the association attribute from A to B with `one to many` cardinality
6. Open the second entity and create the association attribute from B to C with `many to one` cardinality
7. Open the third entity and create boolean attribute
8. Create new views, browser and editor screens for the created entities. and start the project.
9. Open the browser screen of the first entity 
10. Start to create a filter with a new condition
11. Enter the following parameters
![изображение.png](https://images.zenhubusercontent.com/5c8a500319be624db5ac018e/7af56c6f-b37e-4405-927d-170e0eaa0418)
12. Select the created item in the filter dropdown menu

AR: Filter was not applied and IllegalArgumentException occurs
```
java.lang.IllegalArgumentException: You have attempted to set a value of type class java.lang.Integer for parameter filter_qIbULHHckd23826 with expected type of class com.company.samplebug.entity.C from query string select e from samplebug_A e join e.b b where b.c = :filter_qIbULHHckd23826.
	at org.eclipse.persistence.internal.jpa.QueryImpl.setParameterInternal(QueryImpl.java:946)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setParameter(EJBQueryImpl.java:611)
	at com.haulmont.cuba.core.sys.QueryImpl$Param.apply(QueryImpl.java:816)
	at com.haulmont.cuba.core.sys.QueryImpl.getQuery(QueryImpl.java:163)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultList(QueryImpl.java:412)
	at com.haulmont.cuba.core.app.RdbmsStore.executeQuery(RdbmsStore.java:895)
	at com.haulmont.cuba.core.app.RdbmsStore.getResultList(RdbmsStore.java:803)
	at com.haulmont.cuba.core.app.RdbmsStore.loadList(RdbmsStore.java:242)
	at jdk.internal.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy321.loadList(Unknown Source)
	at com.haulmont.cuba.core.app.DataManagerBean.loadList(DataManagerBean.java:78)
	at com.haulmont.cuba.core.app.DataServiceBean.loadList(DataServiceBean.java:54)
	at jdk.internal.reflect.GeneratedMethodAccessor164.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:90)
	at jdk.internal.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by andreysubbotin** [comment]
Not a bug. Specify id column in a query, `b.c.id = ?`
