### ISSUE TITLE
IllegalStateException when register CubaApplicationServlet programmatically

### ISSUE THREAD

**Issue by WildChildCode** [cuba-platform/cuba#3029]
### Environment

- Platform version: 7.2-SNAPSHOT

### Description of the bug or enhancement

- Minimal reproducible example
Test project: [test.zip](https://github.com/cuba-platform/cuba/files/5186380/test.zip)

1. Create new project.
2. Remove descriptions of servlets (_app_servlet_, _dispatcher_) and filter (_cuba_filter_) from _web module's web.xml_.
3. Use initializer bean (with event listener that is subscribed to _ServletContextInitializedEvent_) to dynamically register same servlets and filter with absolutely same parameters. The `ServletInitializer` is used in test project
4. Start project

- Expected behavior
_app_servlet_, _dispatcher_ and _cuba_filter_ are **successfully registered** 
- Actual behavior
_dispatcher_ and _cuba_filter_ are successfully registered, but there is an **exception during _app_servlet_ initialization**
````
java.lang.IllegalStateException: Unable to configure jsr356 at that stage. No Servlet associated with app_servlet
	at org.atmosphere.util.IOUtils.guestRawServletPath(IOUtils.java:282) [atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.atmosphere.util.IOUtils.guestServletPath(IOUtils.java:255) [atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:65) [atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:42) [atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_162]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_162]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_162]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [na:1.8.0_162]
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:237) [atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:308) [atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:294) [atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2092) [atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914) [atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838) [atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:189) [vaadin-server-8.9.2-15-cuba.jar:8.9.2-15-cuba]
	at com.vaadin.server.communication.PushRequestHandler.<init>(PushRequestHandler.java:64) [vaadin-server-8.9.2-15-cuba.jar:8.9.2-15-cuba]
	at com.vaadin.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:68) [vaadin-server-8.9.2-15-cuba.jar:8.9.2-15-cuba]
	at com.haulmont.cuba.web.sys.CubaVaadinServletService.createRequestHandlers(CubaVaadinServletService.java:166) [cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.vaadin.server.VaadinService.init(VaadinService.java:195) [vaadin-server-8.9.2-15-cuba.jar:8.9.2-15-cuba]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.createServletService(CubaApplicationServlet.java:82) [cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:357) [vaadin-server-8.9.2-15-cuba.jar:8.9.2-15-cuba]
	at com.vaadin.server.VaadinServlet.init(VaadinServlet.java:187) [vaadin-server-8.9.2-15-cuba.jar:8.9.2-15-cuba]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.init(CubaApplicationServlet.java:98) [cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.company.sr.servlets.ServletInitializer.initMainServlet(ServletInitializer.java:34) [app-web-0.1-SNAPSHOT.jar:na]
	at com.company.sr.servlets.ServletInitializer.initServlets(ServletInitializer.java:22) [app-web-0.1-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360) [spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at com.haulmont.cuba.core.sys.EventsImpl.publish(EventsImpl.java:33) [cuba-global-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.web.sys.WebEvents.publish(WebEvents.java:36) [cuba-web-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
	at com.haulmont.cuba.core.sys.AbstractWebAppContextLoader.contextInitialized(AbstractWebAppContextLoader.java:92) [cuba-global-7.2-SNAPSHOT.jar:7.2-SNAPSHOT]
```

**Comment by GlebDurygin** [comment]
Hello @WildChildCode,

In order to configure the JSR 356:
1) register the servlet to initialize the Atmosphere Framework:
```
ServletRegistration.Dynamic registration = servletCtx.addServlet(servletName, servlet);
registration.setAsyncSupported(true);
registration.addMapping("/*");
```
2) explicitly initialize the jsr356:
```
JSR356WebsocketInitializer.initAtmosphereForVaadinServlet(registration, servletCtx);
```
3) initialize the servlet:
```
try {
    servlet.init(new AbstractWebAppContextLoader.CubaServletConfig(servletName, servletCtx));
} catch (ServletException e) {
    throw new RuntimeException("An error while init app_servlet", e);
}
```

See **com/haulmont/cuba/web/sys/singleapp/SingleAppWebContextLoader** for more details.

Regards,
Gleb

**Comment by WildChildCode** [comment]
Hello @GlebDurygin,
thanks a lot, for the solution. It works well. 
There is nothing about "special" initialization logic of AppServlet in the corresponding sections of documentation ([here](https://doc.cuba-platform.com/manual-7.2/servlet_registration.html) and [here](https://doc.cuba-platform.com/manual-7.2/servlet_registration_sample.html)). Could you add some info about?

**Comment by GlebDurygin** [comment]
Hello @WildChildCode,

I have created an [issue](https://github.com/cuba-platform/documentation/issues/756) in Github.

Regards,
Gleb
