### ISSUE TITLE
NPE with in-memory read constraints in a cluster environment

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba#3075]
https://www.cuba-platform.ru/discuss/t/oshibka-pri-proverke-in-memory-constraints/5022

### Environment

- Platform version: 7.2

### Description of the bug or enhancement
- Minimal reproducible example
  - Create a design time group with an in-memory constraint for some entity.
  - Run application in a cluster with user session replication.
  - Try to open entity browser.
- Actual behavior
```
java.lang.NullPointerException
at com.haulmont.cuba.core.sys.PersistenceSecurityImpl.lambda$isNotPermittedInMemory$11(PersistenceSecurityImpl.java:418)
at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
at com.google.common.collect.CollectSpliterators$FlatMapSpliterator.tryAdvance(CollectSpliterators.java:337)
at com.google.common.collect.CollectSpliterators$FlatMapSpliterator.tryAdvance(CollectSpliterators.java:337)
at com.google.common.collect.CollectSpliterators$FlatMapSpliterator.tryAdvance(CollectSpliterators.java:337)
at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:533)
at com.haulmont.cuba.core.sys.PersistenceSecurityImpl.isNotPermittedInMemory(PersistenceSecurityImpl.java:418)
at com.haulmont.cuba.core.sys.PersistenceSecurityImpl.calculateFilteredData(PersistenceSecurityImpl.java:351)
at com.haulmont.cuba.core.sys.PersistenceSecurityImpl.calculateFilteredData(PersistenceSecurityImpl.java:376)
at com.haulmont.cuba.core.sys.PersistenceSecurityImpl.lambda$calculateFilteredData$2(PersistenceSecurityImpl.java:175)
at java.base/java.util.Vector.forEach(Vector.java:1388)
at com.haulmont.cuba.core.sys.PersistenceSecurityImpl.calculateFilteredData(PersistenceSecurityImpl.java:175)
at com.haulmont.cuba.core.app.RdbmsStore.loadList(RdbmsStore.java:248)
at jdk.internal.reflect.GeneratedMethodAccessor225.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
at com.sun.proxy.$Proxy288.loadList(Unknown Source)
at com.haulmont.cuba.core.app.DataManagerBean.loadList(DataManagerBean.java:78)
at com.haulmont.cuba.core.app.DataServiceBean.loadList(DataServiceBean.java:54)
at jdk.internal.reflect.GeneratedMethodAccessor184.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:90)
at jdk.internal.reflect.GeneratedMethodAccessor186.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
at com.sun.proxy.$Proxy152.loadList(Unknown Source)
at jdk.internal.reflect.GeneratedMethodAccessor184.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
at com.sun.proxy.$Proxy244.loadList(Unknown Source)
at jdk.internal.reflect.GeneratedMethodAccessor226.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.remoting.support.RemoteInvocation.invoke(RemoteInvocation.java:215)
at com.haulmont.cuba.core.sys.remoting.CubaRemoteInvocationExecutor.invoke(CubaRemoteInvocationExecutor.java:110)
at org.springframework.remoting.support.RemoteInvocationBasedExporter.invoke(RemoteInvocationBasedExporter.java:78)
at org.springframework.remoting.support.RemoteInvocationBasedExporter.invokeAndCreateResult(RemoteInvocationBasedExporter.java:114)
```

**Comment by andreysubbotin** [comment]
For QA: smoke test Access groups (runtime and design time) with in-memory constraints.
