### ISSUE TITLE
XmlInheritanceProcessor doesn't support inline views when extending screens (NPE)

### ISSUE THREAD

**Issue by jbwmcarter** [cuba-platform/cuba#3111]
### Environment

- Platform version: 7.2.10

### Description of the bug

XmlInheritanceProcessor has not yet been updated to support inline views. Therefore an NPE occurs on line 246 because the name attribute is NULL on an inline view tag, such as `<view extends="_local"/>`. The current code of ViewElementTargetLocator expects name, and either entity or class, attributes to be present on `<view/>` tags. According to the screen:data XSD, {name,entity,class} are not the correct attributes for the `<view/>` tag - http://schemas.haulmont.com/cuba/screen/data.xsd

- Minimal reproducible example

Objective: Use entity inheritance and create corresponding Edit screens using XML screen descriptor inheritance and screen controller inheritance, based on documentation, including:
 * https://doc.cuba-platform.com/manual-latest/gui_data_comp_decl.html
 * https://doc.cuba-platform.com/manual-latest/screen_extension.html
 * https://www.cuba-platform.com/guides/data-modelling-entity-inheritance (similar to this guide, but using inline views)

1. Create an entity "Pet" in the data model with some properties and create another entity "Cat" that extends it with string properties "breed" and "clawSharpness"
2. Use Studio to generate Browse and Edit screens for the base entity "Pet". Choose 'inline views' (as recommended)
3. Use Studio to extend the PetEdit screen to create a CatEdit screen - OR, generate Browse and Edit screens for 'Cat' then modify the CatEdit screen controller and screen definition XML to extend 'Pet' then trim the XML to remove duplicate elements
4. Modify the CatEdit screen XML ("cat-edit.xml") to look similar to this, i.e. reuse petDc and add some additional properties to the inline view (imagine these are association properties - in this simplified example, strings are used)
 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<window xmlns="http://schemas.haulmont.com/cuba/screen/window.xsd"
        caption="msg://catEdit.caption"
        messagesPack="com.example.petcliic.web.screens.cat"
        extends="com/example/petclinic/web/screens/pet/pet-edit.xml">
    <data>
        <instance id="petDc" class="com.example.petclinic.global.entity.Cat">
            <view extends="_local">
                <property name="breed" view="_minimal"/>
                <property name="clawSharpness" view="_minimal"/>
            </view>
            <loader/>
        </instance>
    </data>
    <dialogMode width="800" height="600"/>
    <layout>
        <scrollBox>
            <form id="catForm" dataContainer="petDc">
                <column width="350px">
                    <textField id="breedField" property="breed"/>
                    <textField id="clawSharpnessField" property="clawSharpness"/>
                </column>
            </form>
        </scrollBox>
    </layout>
</window>
```

5. Start the app. Create or edit a Cat, i.e. open the CatEdit screen.

- Expected behaviour

The 'Cat' editor opens and allows properties of 'Pet' and 'Cat' to be edited.

- Actual behaviour

NullPointerException in XmlInheritanceProcessor$ViewElementTargetLocator.locate():246
partial stack trace:

```
Caused by: java.lang.NullPointerException: null
	at com.haulmont.cuba.gui.xml.XmlInheritanceProcessor$ViewElementTargetLocator.locate(XmlInheritanceProcessor.java:246) ~[cuba-gui-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.gui.xml.XmlInheritanceProcessor.process(XmlInheritanceProcessor.java:164) ~[cuba-gui-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.gui.xml.XmlInheritanceProcessor.process(XmlInheritanceProcessor.java:167) ~[cuba-gui-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.gui.xml.XmlInheritanceProcessor.process(XmlInheritanceProcessor.java:175) ~[cuba-gui-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.gui.xml.XmlInheritanceProcessor.getResultRoot(XmlInheritanceProcessor.java:95) ~[cuba-gui-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.gui.xml.layout.ScreenXmlLoader.createDocument(ScreenXmlLoader.java:98) ~[cuba-gui-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.gui.xml.layout.ScreenXmlLoader.getDocument(ScreenXmlLoader.java:87) ~[cuba-gui-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.gui.xml.layout.ScreenXmlLoader.load(ScreenXmlLoader.java:66) ~[cuba-gui-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.web.sys.WebScreens.loadScreenXml(WebScreens.java:342) ~[cuba-web-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:196) ~[cuba-web-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:178) ~[cuba-web-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.gui.builders.EditorBuilderProcessor.createScreen(EditorBuilderProcessor.java:340) ~[cuba-gui-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.gui.builders.EditorBuilderProcessor.buildEditor(EditorBuilderProcessor.java:93) ~[cuba-gui-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.gui.builders.EditorBuilder.build(EditorBuilder.java:359) ~[cuba-gui-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.gui.actions.list.CreateAction.execute(CreateAction.java:331) ~[cuba-gui-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.gui.actions.list.CreateAction.actionPerform(CreateAction.java:287) ~[cuba-gui-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:67) ~[cuba-web-7.2.10.jar:7.2.10]
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76) ~[cuba-web-widgets-7.2.10.jar:na]
	at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-8.9.2-16-cuba.jar:8.9.2-16-cuba]
	... 43 common frames omitted
```

- Possible workarounds

1. Using views defined in views.xml instead of inline views, for the extended screen, might work
2. If you don't try to use `<view/>` tags on data in your extended screen definition, everything else about the extended screen works fine. However, this means you can't add fields to the view.

**Comment by andreysubbotin** [comment]
Sample project: [https://app.zenhub.com/files/54624511/ed43923a-65c5-4388-8114-57b56ce01ec9/download](https://app.zenhub.com/files/54624511/ed43923a-65c5-4388-8114-57b56ce01ec9/download)
