### ISSUE TITLE
TokenList gets ConcurrentModificationException while adding the third option using a dropdown list

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#3112]
### Environment
- Platform version: 6.10+
- Client type: Web;

### Description of the bug or enhancement
Support forum: [topic](https://www.cuba-platform.com/discuss/t/concurrentmodificationexception-when-using-tokenlist/14284);

- Minimal reproducible example
Download project: [demo.zip](https://github.com/cuba-platform/cuba/files/5659306/demo.zip)
1) Create three OrderLine entities;
2) Create Order and try to add three options using a dropdown list.

- Stacktrace:
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at com.haulmont.cuba.web.gui.components.WebTokenList.refreshValueIfNeeded(WebTokenList.java:537)
	at com.haulmont.cuba.web.gui.components.WebTokenList.handleSelection(WebTokenList.java:505)
	at com.haulmont.cuba.web.gui.components.WebTokenList.addValueFromLookupPickerField(WebTokenList.java:795)
	at com.haulmont.cuba.web.gui.components.WebTokenList.lambda$new$0(WebTokenList.java:99)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.web.gui.components.WebAbstractComponent.publish(WebAbstractComponent.java:100)
	at com.haulmont.cuba.web.gui.components.WebAbstractValueComponent.componentValueChanged(WebAbstractValueComponent.java:152)
	at com.haulmont.cuba.web.gui.components.WebLookupPickerField.componentValueChanged(WebLookupPickerField.java:468)
	at com.haulmont.cuba.web.gui.components.WebLookupPickerField.componentValueChanged(WebLookupPickerField.java:49)
	at com.haulmont.cuba.web.gui.components.WebV8AbstractField.lambda$attachValueChangeListener$ab1c93c8$1(WebV8AbstractField.java:144)
```

**Comment by maistrenkoIulia** [comment]
reopened
```
IllegalStateException: Cannot get unfetched attribute [order] from detached object com.company.token.entity.OrderLines-323da1c3-d9b9-9cdb-ae9e-e58c2110bb97 [detached].
```

see attached project
[token.zip](https://github.com/cuba-platform/cuba/files/5730909/token.zip)

**Comment by Flaurite** [comment]
@maistrenkoIulia please, check two cases:
1) optionsContainer's view does not load master-reference (Order) attribute, for instance:
```
<collection id="orderLinesDc"
            class="com.company.token.entity.OrderLines"
            view="_local">
    <loader id="orderLinesDl">
        <query><![CDATA[select e from token_OrderLines e]]></query>
    </loader>
</collection>
```
2) optionsContainer's view contains master-reference (Order) attribute, for instance:
```
<collection id="orderLinesDc"
            class="com.company.token.entity.OrderLines">
    <view extends="_local">
        <property name="order" view="_minimal"/>
    </view>
    <loader id="orderLinesDl">
        <query><![CDATA[select e from token_OrderLines e]]></query>
    </loader>
</collection>
```

**Comment by maistrenkoIulia** [comment]
[token.zip](https://github.com/cuba-platform/cuba/files/5734592/token.zip)
1.
 ```
<collection id="orderLinesDc"
                    class="com.company.token.entity.OrderLines">
            <view extends="_local">
                <property name="order" view="_minimal"/>
            </view>
            <loader id="orderLinesDl">
                <query><![CDATA[select e from token_OrderLines e]]></query>
            </loader>
        </collection>
```
 - OK
2.
```
<collection id="orderLinesDc"
                    class="com.company.token.entity.OrderLines"
                    view="_local">
            <loader id="orderLinesDl">
                <query><![CDATA[select e from token_OrderLines e]]></query>
            </loader>
        </collection>
```
- NOK
3.
```
 <collection id="orderLinesDc" class="com.company.token.entity.OrderLines" view="_local">
            <loader id="orderLinesDl">
                <query><![CDATA[select e from token_OrderLines e]]></query>
            </loader>
        </collection>
```
- NOK (generated automatically)

**Comment by maistrenkoIulia** [comment]
7.2-snapshot - ok
7.3-snapshot - ok
