### ISSUE TITLE
Unfetched attribute when trying to filter entity by hiererchical attribute

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#3120]
### Environment

- Platform version: 7.2.4, 7.2.10
- Forum issue https://www.cuba-platform.ru/discuss/t/unfetched-attribute-pri-poiske-po-ierarhicheskomu-svojstvu-v-filter/5206
- Demo project [untitled3.zip](https://github.com/cuba-platform/cuba/files/5689721/untitled3.zip)

### Description of the bug or enhancement

1. Create to entities Parent and Child
2. Child extends Parent
3. Parent entity has an association attribute with itself
```
public class TestEntity1 extends StandardEntity {
    private static final long serialVersionUID = -6311265788034455561L;

    @Column(name = "NAME")
    private String name;

    @Column(name = "TEST")
    private String test;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PARENT_ID")
    private TestEntity1 parent;

public class TestEntityExtends extends TestEntity1 {
    private static final long serialVersionUID = -5962358435637794446L;

    @Column(name = "TEST_ATTRIBUTE2")
    private String testAttribute2;
```
4. Create screens for both entities
5. Run the app, create instances for both entities
6. In Parent or Child screen try to add the filter condition with self-association attribute

*A.R.* Exception occurred. If you create only a Parent instance, everything works fine

```
java.lang.IllegalStateException: Cannot get unfetched attribute [name] from detached object com.company.untitled3.entity.TestEntityExtends-557a3061-e26c-d8ac-537c-bf4e3eef406f [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100)
	at com.haulmont.cuba.core.sys.persistence.CubaEntityFetchGroup.onUnfetchedAttribute(CubaEntityFetchGroup.java:74)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:2998)
	at com.haulmont.chile.core.model.impl.AbstractInstance._persistence_checkFetched(AbstractInstance.java)
	at com.company.untitled3.entity.TestEntity1._persistence_get_name(TestEntity1.java)
	at com.company.untitled3.entity.TestEntity1.getName(TestEntity1.java:42)
	at com.haulmont.chile.core.model.impl.AbstractInstance.getValue(AbstractInstance.java:108)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.getValue(BaseGenericIdEntity.java:146)
	at com.haulmont.cuba.core.global.MetadataTools.getInstanceName(MetadataTools.java:215)
	at com.haulmont.cuba.core.global.MetadataTools.format(MetadataTools.java:167)
	at com.haulmont.cuba.web.gui.components.WebLookupPickerField.generateDefaultItemCaption(WebLookupPickerField.java:131)
	at com.haulmont.cuba.web.gui.components.WebLookupPickerField.generateItemCaption(WebLookupPickerField.java:143)
	at com.vaadin.ui.ComboBox$3.generateData(ComboBox.java:319)
	at com.vaadin.data.provider.DataCommunicator.getDataObject(DataCommunicator.java:485)
	at com.vaadin.data.provider.DataCommunicator.pushData(DataCommunicator.java:465)
	at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:387)
	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:343)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:118)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:115)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:84)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by dtaimanov** [comment]
Unfortunately it is expected behaviour. 

Filter component loads all entities (including child entities) and uses `_minimal` view based on parent class (that used for field declaration):
```java
@NamePattern("%s|test")
//...
public class TestEntity1 extends StandardEntity {
    //...
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PARENT_ID")
    private TestEntity1 parent;
```
This view contains `test` because it appears in `@NamePattern` and doesn't contain `name`. CUBA Views based on the static entity model and cannot be changed during loading according to actually loaded entity metaclass. 

In order to display loaded entity `@NamePattern` should be resolved but it differs for child entity and requires field absent in parent `_minimal` view:
```java
@NamePattern("%s|name")
public class TestEntityExtends extends TestEntity1 {
```
That leads to exception.

Please, avoid usage of fields absent in parent `@NamePattern` for child `@NamePattern` if child entity need to be loaded by parent reference.

see also: [https://www.cuba-platform.com/discuss/t/polymorphic-views/7108/3](https://www.cuba-platform.com/discuss/t/polymorphic-views/7108/3)
