### ISSUE TITLE
IllegalStateException when trying open Entity log

### ISSUE THREAD

**Issue by skatova** [cuba-platform/cuba#3138]
### Environment

- Platform version: 7.2.11
- Forum issue: https://www.cuba-platform.com/discuss/t/entity-log-unfetched-attribute/14497

### Description of the bug or enhancement

- Minimal reproducible example
1. Create a new entity **Account** (extends User) with attribute included in instance name as in the example below 

```
@Entity(name = "extended_Account")
@NamePattern("%s %s|name,accountNumber")
public class Account extends User implements Categorized {
    private static final long serialVersionUID = 532060237095535135L;

    @Column(name = "ACCOUNT_NUMBER", unique = true, length = 25)
    private String accountNumber;
```
 2. Create standard screens for entity **Account**
 3. Run the application
 3. Сonfigure Entity log for entity **Account**
 4. Сreate an entry for entity **Account**
 5. Try to open **Entity log**

- Expected behavior

**Entity log** opened

- Actual behavior

IllegalStateException occurs

![image](https://user-images.githubusercontent.com/53561930/104444540-5b0bbb80-55b1-11eb-9648-462ff21893cf.png)
```
15:23:10.172 ERROR com.haulmont.cuba.web.log.AppLog        - Exception in com.haulmont.cuba.web.widgets.CubaComboBox: 
java.lang.IllegalStateException: Cannot get unfetched attribute [accountNumber] from detached object com.company.extended.entity.Account-308d0ab3-0cac-4f3d-cebc-218e542aaa77 [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100) ~[org.eclipse.persistence.core-2.7.3-14-cuba.jar:na]
	at com.haulmont.cuba.core.sys.persistence.CubaEntityFetchGroup.onUnfetchedAttribute(CubaEntityFetchGroup.java:74) ~[cuba-global-7.2.11.jar:7.2.11]
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:2998) ~[org.eclipse.persistence.jpa-2.7.3-14-cuba.jar:na]
	at com.haulmont.chile.core.model.impl.AbstractInstance._persistence_checkFetched(AbstractInstance.java) ~[cuba-global-7.2.11.jar:7.2.11]
	at com.company.extended.entity.Account._persistence_get_accountNumber(Account.java) ~[app-global-0.1-SNAPSHOT.jar:na]
	at com.company.extended.entity.Account.getAccountNumber(Account.java:20) ~[app-global-0.1-SNAPSHOT.jar:na]
	at com.haulmont.chile.core.model.impl.AbstractInstance.getValue(AbstractInstance.java:108) ~[cuba-global-7.2.11.jar:7.2.11]
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.getValue(BaseGenericIdEntity.java:146) ~[cuba-global-7.2.11.jar:7.2.11]
	at com.haulmont.cuba.core.global.MetadataTools.getInstanceName(MetadataTools.java:216) ~[cuba-global-7.2.11.jar:7.2.11]
	at com.haulmont.cuba.core.global.MetadataTools.format(MetadataTools.java:168) ~[cuba-global-7.2.11.jar:7.2.11]
	at com.haulmont.cuba.web.gui.components.WebLookupField.generateDefaultItemCaption(WebLookupField.java:125) ~[cuba-web-7.2.11.jar:7.2.11]
	at com.haulmont.cuba.web.gui.components.WebLookupField.generateItemCaption(WebLookupField.java:137) ~[cuba-web-7.2.11.jar:7.2.11]
	at com.vaadin.ui.ComboBox$3.generateData(ComboBox.java:319) ~[vaadin-server-8.9.2-17-cuba.jar:8.9.2-17-cuba]
	at com.vaadin.data.provider.DataCommunicator.getDataObject(DataCommunicator.java:485) ~[vaadin-server-8.9.2-17-cuba.jar:8.9.2-17-cuba]
	at com.vaadin.data.provider.DataCommunicator.pushData(DataCommunicator.java:465) ~[vaadin-server-8.9.2-17-cuba.jar:8.9.2-17-cuba]
	at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:387) ~[vaadin-server-8.9.2-17-cuba.jar:8.9.2-17-cuba]
	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:343) ~[vaadin-server-8.9.2-17-cuba.jar:8.9.2-17-cuba]
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:118) ~[vaadin-server-8.9.2-17-cuba.jar:8.9.2-17-cuba]
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:115) [vaadin-server-8.9.2-17-cuba.jar:8.9.2-17-cuba]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:84) [vaadin-server-8.9.2-17-cuba.jar:8.9.2-17-cuba]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) [vaadin-server-8.9.2-17-cuba.jar:8.9.2-17-cuba]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578) [vaadin-server-8.9.2-17-cuba.jar:8.9.2-17-cuba]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425) [vaadin-server-8.9.2-17-cuba.jar:8.9.2-17-cuba]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329) [cuba-web-7.2.11.jar:7.2.11]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215) [cuba-web-7.2.11.jar:7.2.11]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [servlet-api.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.38]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.38]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.38]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.38]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.38]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108) [spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74) [spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93) [cuba-web-7.2.11.jar:7.2.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.38]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.38]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.38]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:9.0.38]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.38]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [catalina.jar:9.0.38]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.38]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [catalina.jar:9.0.38]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:9.0.38]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.38]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-coyote.jar:9.0.38]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.38]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.38]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-coyote.jar:9.0.38]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.38]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.38]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]
```

**Comment by plakhov** [comment]
The root cause of your problem is described in [git hub issue](https://github.com/cuba-platform/cuba/issues/3120). Cut to the chase it is expected behaviour.

But if need wants to replace the User entity with an Account entity you should use Extends annotation.
For details see [documentation](https://doc.cuba-platform.com/manual-latest/entity_extension.html)
