### ISSUE TITLE
Dialog opened from Login screen cannot be closed

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#3145]
### Environment
- Platform version: 7.2.11
- Client type: Web

### Description of the bug or enhancement
Related to [cuba-platform/cuba#3109](https://github.com/cuba-platform/cuba/issues/3109)
Support forum: [topic](https://www.cuba-platform.com/discuss/t/tried-implementing-the-restore-password-but-getting-error/14595).
It also will broke the [sample-user-registration](https://github.com/cuba-platform/sample-user-registration) project, if we update it to 7.2.11.

- Minimal reproducible example
1. Download attached project: [test.zip](https://github.com/cuba-platform/cuba/files/5892268/test.zip)
2. Launch the app;
3. Click on "Reset password"
4. Try to close a dialog;
- Actual behavior
```
java.lang.IllegalStateException: RootWindow does not have any configured work area
	at com.haulmont.cuba.web.sys.WebScreens.getConfiguredWorkArea(WebScreens.java:966)
	at com.haulmont.cuba.web.sys.WebScreens.checkOpened(WebScreens.java:578)
	at com.haulmont.cuba.web.sys.WebScreens.remove(WebScreens.java:658)
	at com.haulmont.cuba.gui.screen.Screen.close(Screen.java:340)
	at com.company.test.web.screens.RestorePasswordScreen.onCancelBtnClick1(RestorePasswordScreen.java:101)
```

**Comment by glebfox** [comment]
Check `OpenType.ROOT` too.
