### ISSUE TITLE
DateField throws an exception if the user types a value that is out of the range

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#3248]
### Environment
- Platform version: 7.2
- Client type: Web

### Description of the bug or enhancement
The problem occurs after updating Vaadin: https://github.com/cuba-platform/cuba/issues/3245  (since v8.11).

#### Minimal reproducible example
1. Add daetField with range, e.g.:
```
<dateField id="dateField" rangeEnd="2021-12-03"/>
```
2. Type date that is out of the defined range: `06/12/2021`

- Expected behavior
Only notification will be shown

- Actual behavior
```
java.lang.IllegalArgumentException: value is not within acceptable range
	at com.vaadin.ui.AbstractDateField.setValue(AbstractDateField.java:732)
	at com.haulmont.cuba.web.gui.components.WebDateField.setValueToPresentation(WebDateField.java:401)
	at com.haulmont.cuba.web.gui.components.WebDateField.handleDateOutOfRange(WebDateField.java:294)
	at com.haulmont.cuba.web.gui.components.WebDateField.checkRange(WebDateField.java:274)
	at com.haulmont.cuba.web.gui.components.WebDateField.componentValueChanged(WebDateField.java:174)
```

**Comment by reznikova21** [comment]
7.2-SNAPSHOT - verified
