### ISSUE TITLE
Does anyone know how to fix this issue in IntelliJ and Cuba

### ISSUE THREAD

**Issue by gregcousin126** [cuba-platform/cuba#3255]
V15

### Environment

- Platform version: Latest

- Client type: Desktop
- Browser: Chrome
- Database:  PosgresSQL
- Operating system: Windows

### Description of the bug or enhancement
java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:218)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:227)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.<init>(TextEditorComponent.java:74)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:107)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.createEditorComponent(PsiAwareTextEditorImpl.java:85)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.<init>(TextEditorImpl.java:52)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.<init>(PsiAwareTextEditorImpl.java:36)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.createEditor(PsiAwareTextEditorProvider.java:31)
	at com.haulmont.studio.intellij.ui.dbupdate.tree.InitScriptNode.<init>(InitScriptNode.java:39)
	at com.haulmont.studio.intellij.ui.dbupdate.tree.DbScriptTree.createInitNodes(DbScriptTree.java:102)
	at com.haulmont.studio.intellij.ui.dbupdate.tree.DbScriptTree.buildModel(DbScriptTree.java:91)
	at com.haulmont.studio.intellij.ui.dbupdate.tree.DbScriptTree.init(DbScriptTree.java:63)
	at com.haulmont.studio.intellij.ui.dbupdate.DbUpdateDialog.createCenterPanel(DbUpdateDialog.java:136)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1309)
	at com.haulmont.studio.intellij.ui.dialog.CubaDialogWrapper.init(CubaDialogWrapper.java:56)
	at com.haulmont.studio.intellij.ui.dbupdate.DbUpdateDialog.<init>(DbUpdateDialog.java:75)
	at com.haulmont.studio.intellij.ui.dbupdate.DbUpdateDialog.createBeforeStartDbManager(DbUpdateDialog.java:92)
	at com.haulmont.studio.intellij.runconfiguration.InteractiveDbChecker.lambda$showDbDialogBeforeStart$9(InteractiveDbChecker.java:306)
	at com.haulmont.studio.intellij.runconfiguration.InteractiveDbChecker.lambda$getDialogResult$13(InteractiveDbChecker.java:352)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by knstvk** [comment]
Please use https://forum.cuba-platform.com for reporting issues in CUBA Studio.
