### ISSUE TITLE
Table aggregation values are not updated if the column is editable

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#370]
The sample project could be found here: https://www.cuba-platform.com/support/topic/editable-group-table-with-aggregation-doesnt-show-group-aggregations-in-edit-mode

1) ''Customer'' is a composition of ''Orders''
2) On the ''Customer'' edit-screen is a table with ''Orders''. (on the ''Order''  browse-screen will be the same)
3) Order has "orderDate", "amount", and "netAmount" attributes
4) Columns are as follows:
- ''netAmount'' is *editable* and *aggregatable*
- the table is grouped by ''orderDate''

```
<groupTable id="ordersTable"
            aggregatable="true"
            editable="true"
            height="100%"
            width="100%">
    ...
    <columns>
        <group>
            <column id="orderDate"/>
        </group>

        <column id="netAmount"
                editable="true">
            <aggregation type="SUM"/>
        </column>

        <column id="amount">
            <aggregation type="SUM"/>
        </column>
    </columns>
    ...
</groupTable>
```

5) Customer created and several instances of Order added

*AR:* SUM of netAmounts (the column is editable) is not displayed.

 !image.png!

---
Original issue: https://youtrack.haulmont.com/issue/PL-8725

**Comment by dtsaryov** [comment]
Fixed in #530.

**Comment by jreznot** [comment]
For QA: additionally check how it works with 15+ columns and 4000-5000 rows of data

**Comment by natfirst** [comment]
# Create a report
# Close the report screen and reopen it
```
java.lang.NullPointerException: Aggregation must be executed at least by one field
        at com.haulmont.cuba.gui.data.impl.AggregatableDelegate.aggregate(AggregatableDelegate.java:35) ~[cuba-gui-6.10-SNAPSHOT.jar:6.10-SNAPSHOT]
        at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.aggregate(CollectionDatasourceImpl.java:699) ~[cuba-gui-6.10-SNAPSHOT.jar:6.10-SNAPSHOT]
        at com.haulmont.cuba.web.gui.components.WebAbstractTable.__aggregate(WebAbstractTable.java:1949) ~[cuba-web-6.10-SNAPSHOT.jar:6.10-SNAPSHOT]
        at com.haulmont.cuba.web.gui.components.WebGroupTable$GroupTableDsWrapper.aggregate(WebGroupTable.java:725) ~[cuba-web-6.10-SNAPSHOT.jar:6.10-SNAPSHOT]
        at com.haulmont.cuba.web.toolkit.data.util.GroupTableContainerWrapper.aggregate(GroupTableContainerWrapper.java:220) ~[cuba-web-6.10-SNAPSHOT.jar:6.10-SNAPSHOT]
        at com.haulmont.cuba.web.toolkit.ui.CubaGroupTable.getAggregatedValuesForGroup(CubaGroupTable.java:208) ~[cuba-web-6.10-SNAPSHOT.jar:6.10-SNAPSHOT]
        at com.haulmont.cuba.web.toolkit.ui.CubaGroupTable.paintAdditionalData(CubaGroupTable.java:123) ~[cuba-web-6.10-SNAPSHOT.jar:6.10-SNAPSHOT]
        at com.vaadin.ui.Table.doPaintContent(Table.java:3338) ~[vaadin-server-7.7.14.cuba.2.jar:7.7.14.cuba.2]
        at com.vaadin.ui.Table.paintContent(Table.java:3310) ~[vaadin-server-7.7.14.cuba.2.jar:7.7.14.cuba.2]
        at com.haulmont.cuba.web.toolkit.ui.CubaTable.paintContent(CubaTable.java:828) ~[cuba-web-6.10-SNAPSHOT.jar:6.10-SNAPSHOT]
        at com.haulmont.cuba.web.toolkit.ui.CubaGroupTable.paintContent(CubaGroupTable.java:99) ~[cuba-web-6.10-SNAPSHOT.jar:6.10-SNAPSHOT]
        at com.vaadin.server.LegacyPaint.paint(LegacyPaint.java:65) ~[vaadin-server-7.7.14.cuba.2.jar:7.7.14.cuba.2]
        at com.vaadin.server.communication.LegacyUidlWriter.write(LegacyUidlWriter.java:82) ~[vaadin-server-7.7.14.cuba.2.jar:7.7.14.cuba.2]
        at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:131) ~[vaadin-server-7.7.14.cuba.2.jar:7.7.14.cuba.2]
        at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124) ~[vaadin-server-7.7.14.cuba.2.jar:7.7.14.cuba.2]
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92) ~[vaadin-server-7.7.14.cuba.2.jar:7.7.14.cuba.2]
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) ~[vaadin-server-7.7.14.cuba.2.jar:7.7.14.cuba.2]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435) ~[vaadin-server-7.7.14.cuba.2.jar:7.7.14.cuba.2]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:361) ~[vaadin-server-7.7.14.cuba.2.jar:7.7.14.cuba.2]
        at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:312) ~[cuba-web-6.10-SNAPSHOT.jar:6.10-SNAPSHOT]
        at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:203) ~[cuba-web-6.10-SNAPSHOT.jar:6.10-SNAPSHOT]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.33]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.33]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.33]
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:107) ~[cuba-web-6.10-SNAPSHOT.jar:6.10-SNAPSHOT]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.33]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[catalina.jar:8.5.33]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.33]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[catalina.jar:8.5.33]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[catalina.jar:8.5.33]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.33]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) ~[catalina.jar:8.5.33]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.33]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[catalina.jar:8.5.33]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) ~[tomcat-coyote.jar:8.5.33]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.33]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) ~[tomcat-coyote.jar:8.5.33]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) ~[tomcat-coyote.jar:8.5.33]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.33]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.33]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```
