### ISSUE TITLE
Ability to define DataGrid and Table without a datasource or dataContainer from XML

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#436]
Add the `metaClass` attribute which will be used to create `EmptyDataGridItems` / `EmptyTableItems` at XML load time.

---
Original issue: https://youtrack.haulmont.com/issue/PL-9135

**Comment by glebfox** [comment]
**For QA**

Check that the following components have the `metaClass` attribute:
* DataGrid
* TreeDataGrid
* Table
* GroupTable
* TreeTable

Pay attention that there is no java API for the `metaClass` attribute such as `setMetaClass` / `getMetaClass`. Defining the `metaClass` attribute in XML is equivalent to setting empty DataGrid/Table items:
* DataGrid - `new EmptyDataGridItems(metaClass)`
* TreeDataGrid - `new EmptyTreeDataGridItems(metaClass)`
* Table - `new EmptyTableItems(metaClass)`
* GroupTable - `new EmptyGroupTableItems(metaClass)`
* TreeTable - `new EmptyTreeTableItems(metaClass)`

Also, make sure that standard actions such as `ExcelAction` and `RefreshAction` properly work with empty items.

**Comment by BryanYin** [comment]
@glebfox So, after this feature applied, we should be able to create DataGrid and Table without DataContainer/Datasource in XML, then set DataContainer/DataSource in screen controller via programming method?

**Comment by glebfox** [comment]
Hi, @BryanYin!

As described above the `metaClass` attributed was added. This attribute must be used if neither `dataContainer` nor `datasource` attributes are defined. This is necessary because the DataGrid/Table must have a type to add columns.

**Comment by BryanYin** [comment]
Yes, that's reasonable. Thanks Gleb!

**Comment by natfirst** [comment]
Exception while trying to refresh empty items
```
 <buttonsPanel>
       <button action="table.excel"/>
       <button action="table.refresh"/>
 </buttonsPanel>
 <table id="table" metaClass="sec$User">
       <actions>
             <action id="excel" type="excel"/>
             <action id="refresh" type="refresh"/>
       </actions>
 </table>
```
```
java.lang.IllegalStateException: RefreshAction target is null or does not implement SupportsContainerBinding
	at com.haulmont.cuba.gui.actions.list.RefreshAction.actionPerform(RefreshAction.java:70)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:62)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```
