### ISSUE TITLE
Mysterious NPE in QueryTreeAnalyzer if passed collection is empty

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#496]
1. Run EntityManager.createQuery with jpql like "select t from validTable t where t.id in :ids"
1. Pass empty collection to q.setParameter("ids", ?);
AR.
```
java.lang.NullPointerException
	at com.haulmont.cuba.core.sys.jpql.QueryTreeAnalyzer.getChildrenByClass(QueryTreeAnalyzer.java:204)
	at com.haulmont.cuba.core.sys.jpql.QueryTreeAnalyzer.findConditionsForParameter(QueryTreeAnalyzer.java:185)
	at com.haulmont.cuba.core.sys.jpql.transform.QueryTreeTransformer.replaceInCondition(QueryTreeTransformer.java:230)
	at com.haulmont.cuba.core.sys.jpql.transform.QueryTransformerAstBased.replaceInCondition(QueryTransformerAstBased.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.haulmont.cuba.core.sys.PerformanceLogInterceptor.aroundInvoke(PerformanceLogInterceptor.java:29)
	at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy330.replaceInCondition(Unknown Source)
	at com.haulmont.cuba.core.sys.QueryImpl.replaceInCollectionParam(QueryImpl.java:283)
	at com.haulmont.cuba.core.sys.QueryImpl.replaceParams(QueryImpl.java:257)
	at com.haulmont.cuba.core.sys.QueryImpl.transformQueryString(QueryImpl.java:207)
	at com.haulmont.cuba.core.sys.QueryImpl.getQuery(QueryImpl.java:113)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultList(QueryImpl.java:312)
```
ER. Valid error message expected.

---
Also query: ```select pr, sum(p.amount) from commercialnetworks$Purchase p join p.storeProduct sp join sp.product prwhere p.store.id = :storeSelect group by pr```

Original issue: https://youtrack.haulmont.com/issue/PL-9428

**Comment by andreysubbotin** [comment]
For QA: test https://youtrack.haulmont.com/issue/PL-8018 and https://youtrack.haulmont.com/issue/PL-5610

**Comment by IskandarovRost** [comment]
could not check because #1264 occurs
