### ISSUE TITLE
Application can't start on operation system with Turkish locale

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#566]
https://www.cuba-platform.com/support/topic/unexpected-error-please-contact-system-administrator
#Setup Xubuntu with Turkish locale
#Setup CUBA studio
#Create sample project and try to start it
Error: 
```
com.haulmont.cuba.core.sys.AbstractWebAppContextLoader - Error initializing application
java.lang.IllegalArgumentException: An exception occurred while creating a query in EntityManager: 
Exception Description: Syntax error parsing [select u from sec$User u where u.loginLowerCase = ?1 and (u.active = true or u.active is null)]. 
[31, 93] The expression is not a valid conditional expression.
[93, 94] The query contains a malformed ending.
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createQuery(EntityManagerImpl.java:1620) ~[eclipselink-2.6.2.cuba18.jar:2.6.2.cuba18]
	at com.haulmont.cuba.core.sys.QueryImpl.getQuery(QueryImpl.java:122) ~[cuba-core-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
	at com.haulmont.cuba.core.sys.QueryImpl.getResultList(QueryImpl.java:314) ~[cuba-core-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
	at com.haulmont.cuba.security.auth.providers.AbstractAuthenticationProvider.loadUser(AbstractAuthenticationProvider.java:63) ~[cuba-core-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
	at com.haulmont.cuba.security.auth.providers.AnonymousAuthenticationProvider.authenticate(AnonymousAuthenticationProvider.java:61) ~[cuba-core-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
	at com.haulmont.cuba.security.auth.AuthenticationManagerBean.authenticateInternal(AuthenticationManagerBean.java:182) ~[cuba-core-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
	at com.haulmont.cuba.security.auth.AuthenticationManagerBean.login(AuthenticationManagerBean.java:73) ~[cuba-core-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
	at com.haulmont.cuba.security.auth.AnonymousSessionHolder.loginAnonymous(AnonymousSessionHolder.java:75) ~[cuba-core-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
	at com.haulmont.cuba.security.auth.AnonymousSessionHolder.initializeAnonymousSession(AnonymousSessionHolder.java:66) ~[cuba-core-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
	at com.haulmont.cuba.security.auth.AnonymousSessionHolder.applicationStarted(AnonymousSessionHolder.java:45) ~[cuba-core-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
	at com.haulmont.cuba.core.sys.AppContext.startContext(AppContext.java:234) ~[cuba-global-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
	at com.haulmont.cuba.core.sys.AppContext$Internals.startContext(AppContext.java:289) ~[cuba-global-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
	at com.haulmont.cuba.core.sys.AbstractWebAppContextLoader.contextInitialized(AbstractWebAppContextLoader.java:75) ~[cuba-global-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745) [catalina.jar:8.5.21]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207) [catalina.jar:8.5.21]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.5.21]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752) [catalina.jar:8.5.21]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728) [catalina.jar:8.5.21]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) [catalina.jar:8.5.21]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1144) [catalina.jar:8.5.21]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1878) [catalina.jar:8.5.21]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: org.eclipse.persistence.exceptions.JPQLException: 
Exception Description: Syntax error parsing [select u from sec$User u where u.loginLowerCase = ?1 and (u.active = true or u.active is null)]. 
[31, 93] The expression is not a valid conditional expression.
[93, 94] The query contains a malformed ending.
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildException(HermesParser.java:155) ~[eclipselink-2.6.2.cuba18.jar:2.6.2.cuba18]
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.validate(HermesParser.java:334) ~[eclipselink-2.6.2.cuba18.jar:2.6.2.cuba18]
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.populateQueryImp(HermesParser.java:278) ~[eclipselink-2.6.2.cuba18.jar:2.6.2.cuba18]
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildQuery(HermesParser.java:163) ~[eclipselink-2.6.2.cuba18.jar:2.6.2.cuba18]
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:143) ~[eclipselink-2.6.2.cuba18.jar:2.6.2.cuba18]
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:116) ~[eclipselink-2.6.2.cuba18.jar:2.6.2.cuba18]
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.<init>(EJBQueryImpl.java:102) ~[eclipselink-2.6.2.cuba18.jar:2.6.2.cuba18]
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.<init>(EJBQueryImpl.java:86) ~[eclipselink-2.6.2.cuba18.jar:2.6.2.cuba18]
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createQuery(EntityManagerImpl.java:1618) ~[eclipselink-2.6.2.cuba18.jar:2.6.2.cuba18]
	... 25 common frames omitted

```

---
Original issue: https://youtrack.haulmont.com/issue/PL-9785

**Comment by andreysubbotin** [comment]
EclipseLink issue: eclipse-ee4j/eclipselink#345
