### ISSUE TITLE
Extract REST API to separate app component

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#630]
Move REST v2 to app component.

### Updates

REST API is extracted as app component: [GitHub](http://github.com/cuba-platform/restapi/)

### QA

Check that new component:

- [ ] has all previous functionality
- [ ] has old URL mappings
- [ ] supports all deployment configurations (Standard, WAR, Single WAR, etc)

### DB migration check

REST API Entities are also moved to addon and their DB scripts are splitted:

- `init` scripts are moved to addon
- `update` scripts are in cuba

So DB updates while migration from 7.0 to 7.1 should be tested

#### Test project

[restv2_migration.zip](https://github.com/cuba-platform/cuba/files/3032498/restv2_migration.zip)

**Manual project migration manual**

- add app component with the following maven coordinates:
    `com.haulmont.addon.restapi:restapi-global:0.1-SNAPSHOT`

- remove `rest_api` servlet in `modules/web/web/WEB-INF/web.xml`
- remove `rest_api` servlet mapping in `modules/web/web/WEB-INF/web.xml`
- remove `restSpringSecurityFilterChain` filter in `modules/web/web/WEB-INF/web.xml`
- remove `restSpringSecurityFilterChain` filter mapping in `modules/web/web/WEB-INF/web.xml`

![image](https://user-images.githubusercontent.com/6183810/55379633-c0063680-552e-11e9-96f2-dde57a925710.png)

#### General test case

1. Run sample app (v7.0)
2. Enable [persistent REST API tokens storing](https://doc.cuba-platform.com/manual-7.0/rest_api_v2_persistent_token_store.html)
3. Obtain REST API token via [Postman](https://www.getpostman.com/):

    `http://localhost:8080/app/rest/v2/oauth/token?grant_type=password&username=admin&password=admin`

![image](https://user-images.githubusercontent.com/6183810/55380539-871b9100-5531-11e9-9b28-c91bd5d5e615.png)

4. Check that token is saved in DB:

![image](https://user-images.githubusercontent.com/6183810/55380655-e2e61a00-5531-11e9-86c8-a19e7c6b5008.png)

5. Migrate the project to v7.1
6. Update DB somehow (see for cases below)
7. Run an app

**E.R.:**

- REST API token is still in DB
- No errors found in logs

#### DB state while update is performing

Please also check cases when DB is re-created before update. It means that DB exists, but no tables created.

#### cuba.automaticDatabaseUpdate

We have a feature [Execution of Database Scripts by Server](https://doc.cuba-platform.com/manual-latest/db_update_in_prod_by_server.html) that enables to perform DB update via application itself.

In this case DB **is not updated** by Studio (by Gradle in fact - second case).

#### Gradle updateDb task

In this case DB **should be updated** by Studio (by Gradle `updateDb` task in fact).

**Comment by jreznot** [comment]
We will strip roughly 12 JARs from the Web Client if rest-api becomes optional.

**Comment by myatlevEvg** [comment]
Reopened.
UberJar doesn't work.
1) Create a project with Platform 7.1
2) Create DB
3) Create buildUberJar task
4) execute ```gradlew buildUberJar```
5) Try to start generated jar file

AR: Exception occurred
```
2019-04-12 14:01:11.283 WARN  [main] org.eclipse.jetty.servlet.BaseHolder -
java.lang.ClassNotFoundException: com.haulmont.restapi.sys.CubaRestApiServlet
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.eclipse.jetty.util.Loader.loadClass(Loader.java:86)
        at org.eclipse.jetty.servlet.BaseHolder.doStart(BaseHolder.java:95)
        at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:363)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:899)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1406)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1368)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:522)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:427)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:394)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com.haulmont.uberjar.CubaJettyServer.start(CubaJettyServer.java:121)
        at com.haulmont.uberjar.ServerRunner.execute(ServerRunner.java:249)
        at com.haulmont.uberjar.ServerRunner.main(ServerRunner.java:39)
```

**Comment by dtsaryov** [comment]
@myatlevEvg 

A project should be manually migrated while migration is [not supported in Studio](https://youtrack.haulmont.com/issue/STUDIO-5906) (see issue notes). Have you migrated a project?

[restapi-uberjar.zip](https://github.com/cuba-platform/cuba/files/3092941/restapi-uberjar.zip)

**Comment by Computerbabalulu** [comment]
> Reopened.
> UberJar doesn't work.
> 
> 1. Create a project with Platform 7.1
> 2. Create DB
> 3. Create buildUberJar task
> 4. execute `gradlew buildUberJar`
> 5. Try to start generated jar file
> 
> AR: Exception occurred
> 
> ```
> 2019-04-12 14:01:11.283 WARN  [main] org.eclipse.jetty.servlet.BaseHolder -
> java.lang.ClassNotFoundException: com.haulmont.restapi.sys.CubaRestApiServlet
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at org.eclipse.jetty.util.Loader.loadClass(Loader.java:86)
>         at org.eclipse.jetty.servlet.BaseHolder.doStart(BaseHolder.java:95)
>         at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:363)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:899)
>         at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
>         at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1406)
>         at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1368)
>         at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
>         at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
>         at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:522)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
>         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
>         at org.eclipse.jetty.server.Server.start(Server.java:427)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
>         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
>         at org.eclipse.jetty.server.Server.doStart(Server.java:394)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at com.haulmont.uberjar.CubaJettyServer.start(CubaJettyServer.java:121)
>         at com.haulmont.uberjar.ServerRunner.execute(ServerRunner.java:249)
>         at com.haulmont.uberjar.ServerRunner.main(ServerRunner.java:39)
> ```

I have the same Error on a new Projekt:

`C:\Develop\JAVA\JDK\jdk-11.0.2+9\bin>java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.2+9, mixed mode)

C:\Develop\JAVA\JDK\jdk-11.0.2+9\bin>java -jar C:\Develop\JAVA\Test\app.jar
Starting Jetty server on port: 8080 and contextPath: /app
01:15:57.604 INFO  org.eclipse.jetty.util.log              - Logging initialized @433ms
01:15:57.682 INFO  org.eclipse.jetty.server.Server         - jetty-9.3.z-SNAPSHOT, build timestamp: 2019-04-04T01:17:19+02:00, git hash: dae476e369ceca8b77926996dd9cd537472e5415
01:15:57.854 INFO  o.e.j.w.StandardDescriptorProcessor     - NO JSP Support for /app-core, did not find org.eclipse.jetty.jsp.JettyJspServlet
01:15:57.932 INFO  c.h.cuba.core.sys.AppComponents         - Using app components: [com.haulmont.cuba]
01:15:57.948 INFO  c.h.c.c.s.AbstractWebAppContextLoader   - Loading app properties from classpath:com/company/localapppropperties/app.properties
01:15:57.963 INFO  c.h.c.c.s.AbstractWebAppContextLoader   - Loading app properties from /WEB-INF/local.app.properties
01:15:58.010 INFO  c.h.cuba.core.sys.AppContextLoader      - DbmsType of the main database is set to hsql
01:15:58.104 INFO  c.h.c.c.s.p.PersistenceConfigProcessor  - Creating file C:\Develop\JAVA\JDK\jdk-11.0.2+9\bin\app-core\work\persistence.xml
01:16:02.059 INFO  c.h.c.c.s.CubaThreadPoolTaskScheduler   - Initializing ExecutorService 'scheduler'
01:16:02.152 INFO  c.h.cuba.core.sys.jmx.MBeanExporter     - Registering beans for JMX exposure: [app-core.cuba:type=PersistenceManager, app-core.cuba:type=ConfigStorage, app-core.cuba:type=UserSessions, app-core.cuba:type=UniqueNumbers, app-core.cuba:type=Emailer, app-core.cuba:type=EntityLog, app-core.cuba:type=FileStorage, app-core.cuba:type=LockManager, app-core.cuba:type=CachingFacade, app-core.cuba:type=ClusterManager, app-core.cuba:type=ScriptingManager, app-core.cuba:type=ServerInfo, app-core.cuba:type=Scheduling, app-core.cuba:type=PasswordEncryptionSupport, app-core.cuba:type=JmxNodeIdentifier, app-core.cuba:type=JmxLogControl, app-core.cuba:type=ClassLoaderManager, app-core.cuba:type=StatisticsCounter, app-core.cuba:type=BruteForceProtection, app-core.cuba:type=QueryCacheSupport]
01:16:02.309 INFO  c.h.cuba.core.sys.MetadataImpl          - Initializing metadata
01:16:02.449 INFO  c.h.cuba.core.sys.MetadataImpl          - Metadata initialized in 140 ms
01:16:02.777 INFO  c.h.c.c.sys.dbupdate.DbUpdaterEngine    - Updating database...
01:16:02.918 INFO  c.h.c.c.sys.dbupdate.DbUpdaterEngine    - Database is up-to-date
01:16:03.527 INFO  c.h.cuba.core.app.ConfigStorage         - Loading DB-stored app properties cache
01:16:03.761 INFO  c.h.c.c.s.DefaultPermissionValuesConfig - Initializing default permission values
01:16:03.824 INFO  c.h.c.s.a.AuthenticationManagerBean     - Logged in: fc88be44-6e95-acbc-50a5-84b31464b828 [anonymous]
01:16:03.824 INFO  c.h.c.c.s.AbstractWebAppContextLoader   - AppContext started
01:16:03.855 INFO  /app-core                               - Initializing Spring RemotingServlet 'remoting'
01:16:03.855 INFO  c.h.c.c.sys.remoting.RemotingServlet    - Initializing Servlet 'remoting'
01:16:03.886 INFO  c.h.c.c.s.r.RemoteServicesBeanCreator   - Configuring remote services
01:16:04.183 INFO  c.h.c.c.sys.remoting.RemotingServlet    - Completed initialization in 328 ms
01:16:04.183 INFO  o.e.j.server.handler.ContextHandler     - Started o.e.j.w.WebAppContext@7f2cfe3f{/app-core,jar:file:/C:/Develop/JAVA/Test/app.jar!/LIB-INF/app-core,AVAILABLE}
01:16:04.199 INFO  o.e.j.w.StandardDescriptorProcessor     - NO JSP Support for /app, did not find org.eclipse.jetty.jsp.JettyJspServlet
01:16:04.402 INFO  c.h.cuba.core.sys.AppComponents         - Using app components: [com.haulmont.cuba]
01:16:04.402 INFO  c.h.c.c.s.AbstractWebAppContextLoader   - Loading app properties from classpath:com/company/localapppropperties/web-app.properties
01:16:04.402 INFO  c.h.c.c.s.AbstractWebAppContextLoader   - Loading app properties from /WEB-INF/local.app.properties
01:16:06.073 INFO  c.h.c.c.s.r.d.StaticServerSelector      - Server URLs: [http://localhost:8080/app-core/remoting]
01:16:06.089 INFO  c.h.c.w.s.r.WebRemoteProxyBeanCreator   - Configuring proxy beans for local service invocations: [cuba_AuthenticationService, cuba_TrustedClientService, cuba_ServerInfoService, cuba_UserSettingService, cuba_UserManagementService, cuba_DataService, cuba_ConfigStorageService, cuba_PersistenceManagerService, cuba_LockService, cuba_UserSessionService, cuba_FoldersService, cuba_EmailService, cuba_FileStorageService, cuba_EntitySnapshotService, cuba_UniqueNumbersService, cuba_LocalizedMessageService, cuba_ResourceService, cuba_ScheduledTasksService, cuba_EntityLogService, cuba_TestingService, cuba_DomainDescriptionService, cuba_RelatedEntitiesService, cuba_EntitySqlGenerationService, cuba_NumberIdService, cuba_QueryResultsService, cuba_DynamicAttributesCacheService, cuba_EntityRestoreService, cuba_LocalFileExchangeService, cuba_EntityImportExportService, cuba_ConstraintLocalizationService, cuba_AttributeAccessService, cuba_ExceptionReportService, cuba_BulkEditorDataService]
01:16:06.667 INFO  c.h.c.c.s.CubaThreadPoolTaskScheduler   - Initializing ExecutorService 'scheduler'
01:16:06.823 INFO  c.h.cuba.core.sys.jmx.MBeanExporter     - Registering beans for JMX exposure: [app.cuba:type=ConfigStorage, app.cuba:type=CachingFacade, app.cuba:type=FileUploading, app.cuba:type=JmxNodeIdentifier, app.cuba:type=JmxLogControl, app.cuba:type=ClassLoaderManager, app.cuba:type=StatisticsCounter]
01:16:06.870 INFO  c.h.cuba.core.sys.MetadataImpl          - Initializing metadata
01:16:06.995 INFO  c.h.cuba.core.sys.MetadataImpl          - Metadata initialized in 125 ms
01:16:07.026 INFO  c.h.c.c.s.AbstractWebAppContextLoader   - AppContext started
01:16:07.026 INFO  /app                                    - Initializing Spring CubaDispatcherServlet 'dispatcher'
01:16:07.026 INFO  c.h.c.web.sys.CubaDispatcherServlet     - Initializing Servlet 'dispatcher'
01:16:07.386 INFO  c.h.c.web.sys.CubaDispatcherServlet     - Completed initialization in 360 ms
01:16:07.386 WARN  org.eclipse.jetty.servlet.BaseHolder    -
java.lang.ClassNotFoundException: com.haulmont.restapi.sys.CubaRestApiServlet
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
        at org.eclipse.jetty.util.Loader.loadClass(Loader.java:86) ~[app.jar:na]
        at org.eclipse.jetty.servlet.BaseHolder.doStart(BaseHolder.java:95) ~[app.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:363) ~[app.jar:na]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[app.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:899) ~[app.jar:na]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349) ~[app.jar:na]
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1406) ~[app.jar:na]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1368) ~[app.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778) ~[app.jar:na]
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262) ~[app.jar:na]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:522) ~[app.jar:na]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[app.jar:na]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) ~[app.jar:na]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113) ~[app.jar:na]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) ~[app.jar:na]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[app.jar:na]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) ~[app.jar:na]
        at org.eclipse.jetty.server.Server.start(Server.java:427) ~[app.jar:na]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105) ~[app.jar:na]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) ~[app.jar:na]
        at org.eclipse.jetty.server.Server.doStart(Server.java:394) ~[app.jar:na]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[app.jar:na]
        at com.haulmont.uberjar.CubaJettyServer.start(CubaJettyServer.java:121) ~[app.jar:na]
        at com.haulmont.uberjar.ServerRunner.execute(ServerRunner.java:249) ~[app.jar:na]
        at com.haulmont.uberjar.ServerRunner.main(ServerRunner.java:39) ~[app.jar:na]
01:16:07.401 WARN  /app`

**Comment by jreznot** [comment]
@Computerbabalulu Why do you use Platform 7.1? It is not released yet. 

For questions and problems please use https://www.cuba-platform.com/discuss/
