### ISSUE TITLE
Separate RadioButtonGroup and CheckBoxGroup components

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#719]
Deprecate OptionsGroup

---
Original issue: https://youtrack.haulmont.com/issue/PL-10524

**Comment by myatlevEvg** [comment]
Reopen.

Checkboxes in CheckBoxGroup are available to click even if the property "editable" set to "false"

![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/fb95a2c2-cabe-4bd3-adf8-07832d7a29c4)

**Comment by glebfox** [comment]
@myatlevEvg create a separate issue with a more detailed description. It's a default Vaadin component behavior, (see https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/check-box-group) and there is no need to fix it by ourselves right now.

**Comment by natfirst** [comment]
```
com.haulmont.cuba.gui.GuiDevelopmentException: Unknown component: radioButtonGroup, frameId=dabi$Customer.edit
	at com.haulmont.cuba.gui.xml.layout.LayoutLoader.getLoader(LayoutLoader.java:83)
	at com.haulmont.cuba.gui.xml.layout.LayoutLoader.createComponent(LayoutLoader.java:144)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.createSubComponents(ContainerLoader.java:70)
	at com.haulmont.cuba.gui.xml.layout.loaders.VBoxLayoutLoader.createComponent(VBoxLayoutLoader.java:26)
	at com.haulmont.cuba.gui.xml.layout.LayoutLoader.createComponent(LayoutLoader.java:146)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.createSubComponents(ContainerLoader.java:70)
	at com.haulmont.cuba.gui.xml.layout.loaders.WindowLoader.createContent(WindowLoader.java:66)
	at com.haulmont.cuba.gui.xml.layout.LayoutLoader.createWindowContent(LayoutLoader.java:172)
	at com.haulmont.cuba.web.sys.WebScreens.loadWindowFromXml(WebScreens.java:321)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:210)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:162)
	at com.haulmont.cuba.web.sys.WebScreens.openEditor(WebScreens.java:918)
	at com.haulmont.cuba.gui.screen.compatibility.LegacyFrame.openEditor(LegacyFrame.java:164)
	at com.haulmont.cuba.gui.components.actions.CreateAction.internalOpenEditor(CreateAction.java:298)
	at com.haulmont.cuba.gui.components.actions.CreateAction.actionPerform(CreateAction.java:257)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:60)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by glebfox** [comment]
Caused by: #575

**Comment by myatlevEvg** [comment]
New optionsContainer and dataContainer does not work with this components.
