### ISSUE TITLE
ORM uses inner join instead of outer join

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#734]
Attached patch for refapp 6.8.

There is an optional many-to-one relation: Car.colour -> Colour.
You reload entity two times. First loading uses batch fetch, second uses join fetch.

```
        View colourView = viewRepository.getView(Colour.class, View.MINIMAL);
        View view1 = new View(Car.class).addProperty("colour", colourView, FetchMode.BATCH);
        View view2 = new View(Car.class).addProperty("colour", colourView);
```

When first loading is performed, EclipseLink metadata somehow gets corrupted. And all subsequent join fetches issue inner join in SQL instead of left outer join.
```
#1
13:36:17.097 DEBUG com.haulmont.cuba.core.app.RdbmsStore - load: metaClass=ref$Car, id=4f25d8be-3b36-91cd-1b48-d01f7d74461b, view=com.haulmont.refapp.core.entity.Car/
13:36:17.111 DEBUG com.haulmont.cuba.core.sys.QueryImpl - select e from ref$Car e where e.id = :entityId
13:36:17.143 DEBUG com.haulmont.cuba.core.sys.FetchGroupManager - Fetch modes for com.haulmont.refapp.core.entity.Car/: e.colour=BATCH
13:36:17.147 DEBUG eclipselink.sql - <t 549913230, conn 187828388> SELECT ID,
       CREATE_TS,
       CREATED_BY,
       DELETE_TS,
       DELETED_BY,
       UPDATE_TS,
       UPDATED_BY,
       VERSION,
       COLOUR_ID
FROM REF_CAR
WHERE ((ID = ?)
       AND (DELETE_TS IS NULL))
	bind => [4f25d8be-3b36-91cd-1b48-d01f7d74461b]

#2
13:36:17.171 DEBUG com.haulmont.cuba.core.app.RdbmsStore - load: metaClass=ref$Car, id=4f25d8be-3b36-91cd-1b48-d01f7d74461b, view=com.haulmont.refapp.core.entity.Car/
13:36:17.183 DEBUG com.haulmont.cuba.core.sys.QueryImpl - select e from ref$Car e where e.id = :entityId
13:36:17.195 DEBUG com.haulmont.cuba.core.sys.FetchGroupManager - Fetch modes for com.haulmont.refapp.core.entity.Car/: e.colour=JOIN
13:36:17.203 DEBUG eclipselink.sql - <t 549913230, conn 1850004382> SELECT t1.ID,
       t1.CREATE_TS,
       t1.CREATED_BY,
       t1.DELETE_TS,
       t1.DELETED_BY,
       t1.UPDATE_TS,
       t1.UPDATED_BY,
       t1.VERSION,
       t1.COLOUR_ID,
       t0.ID,
       t0.DELETE_TS,
       t0.DELETED_BY,
       t0.NAME,
       t0.VERSION
FROM REF_COLOUR t0,
     REF_CAR t1
WHERE (((t1.ID = ?)
        AND (t1.DELETE_TS IS NULL))
       AND ((t0.ID = t1.COLOUR_ID)
            AND (t0.DELETE_TS IS NULL)))
	bind => [4f25d8be-3b36-91cd-1b48-d01f7d74461b]

java.lang.AssertionError
	at com.haulmont.refapp.core.WrongJoinTest.testInnerJoinInsteadOfLeftJoin(WrongJoinTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
```

If I comment first load() or remove fetch-batch hint from view1 - then error disappears.

---
Original issue: https://youtrack.haulmont.com/issue/PL-10597

**Comment by andreysubbotin** [comment]
RefApp unit test: https://git.haulmont.com/platform/refapp/commit/9b0aa0999ab45eeefc7186d4e105cc6192d54dba
