### ISSUE TITLE
Get rid of default implicit conversion of JPQL query parameters

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#744]
See https://www.cuba-platform.com/discuss/t/loading-record-in-onbeforeinsert/4320/9

---
Original issue: https://youtrack.haulmont.com/issue/PL-10658

**Comment by knstvk** [comment]
For legacy behavior use `cuba.implicitConversionOfJpqlParams = true`.

**Comment by knstvk** [comment]
Help - History:

```
IllegalArgumentException: You have attempted to set a value of type class com.haulmont.cuba.security.entity.User for parameter custom_userId with expected type of class java.util.UUID from query string 
                select h from sec$ScreenHistory h
                where ((h.user.id = :custom_userId and h.substitutedUser is null) or h.substitutedUser.id = :custom_userId)
                order by h.createTs desc
```

**Comment by knstvk** [comment]
Need regression testing of all CUBA functionality in 2 modes: default and with `cuba.implicitConversionOfJpqlParams = true`

**Comment by jreznot** [comment]
User editor -  Add substituted user:
```
IllegalArgumentException: You have attempted to set a value of type class com.haulmont.cuba.security.entity.User for parameter ds_subst_user with expected type of class java.util.UUID from query string 
                
                select u from sec$User u where u.id <> :ds_subst_user
                
            .
```

**Comment by jreznot** [comment]
Menu Help - History:

```
IllegalArgumentException: You have attempted to set a value of type class com.haulmont.cuba.security.entity.User for parameter custom_userId with expected type of class java.util.UUID from query string 
                select h from sec$ScreenHistory h
                where ((h.user.id = :custom_userId and h.substitutedUser is null) or h.substitutedUser.id = :custom_userId)
                order by h.createTs desc
            .
```

**Comment by natfirst** [comment]
User - Copy user setting to another user:
```
java.lang.IllegalArgumentException: You have attempted to set a value of type class com.haulmont.cuba.security.entity.User for parameter 1 with expected type of class java.util.UUID from query string delete from sec$Presentation p where p.user.id=?1.
	at org.eclipse.persistence.internal.jpa.QueryImpl.setParameterInternal(QueryImpl.java:944)
	at org.eclipse.persistence.internal.jpa.QueryImpl.setParameterInternal(QueryImpl.java:918)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setParameter(EJBQueryImpl.java:479)
	at com.haulmont.cuba.core.sys.QueryImpl$Param.apply(QueryImpl.java:756)
	at com.haulmont.cuba.core.sys.QueryImpl.getQuery(QueryImpl.java:153)
	at com.haulmont.cuba.core.sys.QueryImpl.executeUpdate(QueryImpl.java:437)
	at com.haulmont.cuba.security.app.UserSettingServiceBean.copyPresentations(UserSettingServiceBean.java:211)
	at com.haulmont.cuba.security.app.UserSettingServiceBean.copySettings(UserSettingServiceBean.java:111)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:117)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy246.copySettings(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154)
	at com.sun.proxy.$Proxy35.copySettings(Unknown Source)
```
