### ISSUE TITLE
Obtaining a next type safe value of a sequence

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#759]
TC:
1. create a sequence (in postgresql for instance) with name 'some_sequence'
2. call the follow code:
```
persistence.callInTransaction(em -> {
            return em.createNativeQuery("select nextval('some_sequence')", Long.class).getSingleResult();
});
```
AR:
```
java.lang.IllegalArgumentException: Non-entity result class for native query is not supported by EclipseLink: class java.lang.Long
        at com.haulmont.cuba.core.sys.QueryImpl.getQuery(QueryImpl.java:107) ~[cuba-core-6.8.1.jar:6.8.1]
        at com.haulmont.cuba.core.sys.QueryImpl.getSingleResult(QueryImpl.java:334) ~[cuba-core-6.8.1.jar:6.8.1]
        at ...
        at com.haulmont.cuba.core.sys.TransactionImpl.execute(TransactionImpl.java:76) ~[cuba-core-6.8.1.jar:6.8.1]
        at com.haulmont.cuba.core.sys.TransactionImpl.execute(TransactionImpl.java:70) ~[cuba-core-6.8.1.jar:6.8.1]
        at com.haulmont.cuba.core.sys.PersistenceImpl.callInTransaction(PersistenceImpl.java:108) ~[cuba-core-6.8.1.jar:6.8.1]
        at ...
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```
ER:
the query result is the next value of the sequence

P.S. but follow (type unsafe) code works
```
return ((Long) em.createNativeQuery("select nextval('kronos_rideshare_group_id_seq')").getSingleResult());
```

---
Original issue: https://youtrack.haulmont.com/issue/PL-10690

**Comment by knstvk** [comment]
Use new fluent API: #852
