### ISSUE TITLE
Support MySQL 8

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#817]
The issue was reported there: https://www.cuba-platform.com/discuss/t/dbinitializationexception/4785

### Environment

- Platform version: 6.8.7 
- Database: MySQL 

### Description of the bug or enhancement

See the new MySQL 8: https://dev.mysql.com/doc/relnotes/mysql/8.0/en/

- Minimal reproducible example
1) Download and install MySQL server
2) Download a new MySQL connector (mysql-connector-java-8.0.11 for instance)
3) Rename it and put to studio libs
4) Take some project and enable _cuba.automaticDatabaseUpdate = true_
5) Adjust connection to MySQL DBMS. Create there an empty database.
6) Assemble and deploy the project
7) Put the new connector to Tomcat libs (and remove the old one)
8) Start the project

- Expected behavior
THe database will be upgraded automatically

- Actual behavior
Not regarding the new driver was used. When the automatic DB updater tries to take a list of tables from metadata the following exception occurs

```
Caused by: com.haulmont.cuba.core.sys.DbInitializationException: Error connecting to database: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY TABLE_TYPE, TABLE_SCHEMA, TABLE_NAME' at line 1
	at com.haulmont.cuba.core.sys.dbupdate.DbUpdaterEngine.dbInitialized(DbUpdaterEngine.java:180) ~[cuba-core-6.8.7.jar:6.8.7]
	at com.haulmont.cuba.core.sys.dbupdate.DbUpdaterImpl.checkDatabaseOnStart(DbUpdaterImpl.java:98) ~[cuba-core-6.8.7.jar:6.8.7]
	... 29 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY TABLE_TYPE, TABLE_SCHEMA, TABLE_NAME' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118) ~[mysql-connector-java.jar:8.0.11]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95) ~[mysql-connector-java.jar:8.0.11]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java.jar:8.0.11]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:960) ~[mysql-connector-java.jar:8.0.11]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1019) ~[mysql-connector-java.jar:8.0.11]
	at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.executeMetadataQuery(DatabaseMetaDataUsingInfoSchema.java:62) ~[mysql-connector-java.jar:8.0.11]
	at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.getTables(DatabaseMetaDataUsingInfoSchema.java:835) ~[mysql-connector-java.jar:8.0.11]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingDatabaseMetaData.getTables(DelegatingDatabaseMetaData.java:645) ~[tomcat-dbcp.jar:8.5.23]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingDatabaseMetaData.getTables(DelegatingDatabaseMetaData.java:645) ~[tomcat-dbcp.jar:8.5.23]
	at com.haulmont.cuba.core.sys.dbupdate.DbUpdaterEngine.dbInitialized(DbUpdaterEngine.java:165) ~[cuba-core-6.8.7.jar:6.8.7]
```

**Comment by IskandarovRost** [comment]
See also the issue for Gradle plugin https://github.com/cuba-platform/cuba-gradle-plugin/issues/33

**Comment by gorbunkov** [comment]
The mysql-connector-java v8 doesn't work because of the bug https://bugs.mysql.com/bug.php?id=90887. The connector v5.1 should work with the database v8.
