### ISSUE TITLE
IllegalArgumentException occurs when opening screen with FileUploadField in app deployed in UberJAR

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#896]
- Platform version: 6.9-snapshot

1. Create a new project
2. Add the uberJar task
3. Deploy and start the Uber JAR
4. Open the project
5. Try to open the Roles or Groups screen

**A.R.** Exception will appear in the log

```
2018-05-29 13:55:44.167 ERROR [qtp787387795-16/app/admin] com.haulmont.cuba.web.log.AppLog - Exception:
java.lang.IllegalArgumentException: jquery-ui.min.js could not be found. Make sure you've added the corresponding WebJar and please check for typos.
        at org.webjars.WebJarAssetLocator.throwNotFoundException(WebJarAssetLocator.java:174) ~[shared/:na]
        at org.webjars.WebJarAssetLocator.getFullPath(WebJarAssetLocator.java:231) ~[shared/:na]
        at org.webjars.WebJarAssetLocator.getFullPath(WebJarAssetLocator.java:200) ~[shared/:na]
        at com.haulmont.cuba.web.sys.CubaUidlWriter.getWebJarResourcePath(CubaUidlWriter.java:129) ~[classes/:na]
        at com.haulmont.cuba.web.sys.CubaUidlWriter.getResourceActualPath(CubaUidlWriter.java:116) ~[classes/:na]
        at com.haulmont.cuba.web.sys.CubaUidlWriter.handleAdditionalDependencies(CubaUidlWriter.java:95) ~[classes/:na]
        at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:299) ~[shared/:na]
        at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124) ~[shared/:na]
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92) ~[shared/:na]
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) ~[shared/:na]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435) ~[shared/:na]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:361) ~[shared/:na]
        at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:312) ~[classes/:na]
        at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:203) ~[classes/:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[app.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812) ~[app.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) ~[app.jar:na]
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107) ~[shared/:na]
        at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73) ~[shared/:na]
        at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:107) ~[classes/:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[app.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) ~[app.jar:na]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[app.jar:na]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) ~[app.jar:na]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) ~[app.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) ~[app.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) ~[app.jar:na]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[app.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) ~[app.jar:na]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[app.jar:na]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) ~[app.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[app.jar:na]
        at org.eclipse.jetty.server.Server.handle(Server.java:499) ~[app.jar:na]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) ~[app.jar:na]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258) ~[app.jar:na]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544) ~[app.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) ~[app.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) ~[app.jar:na]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_172]
```

**Comment by IskandarovRost** [comment]
1) Enable BPM in the project
2) Build UberJar
3) Start the UberJar
4) Open the Application in browser
AR:
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/ec9a75f3-e8a1-4c17-9621-54f3c3c24b74)

**Comment by jreznot** [comment]
Please check Singe WAR packaging
