### ISSUE TITLE
SSO with LDAP Password Authentication: UnsupportedCredentialsException

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/cuba#899]
Platform version: 6.8.8, 6.9.SNAPSHOT

WTR: 

1. Create two apps: foo and bar and implement the [simplest SSO](https://doc.cuba-platform.com/manual-latest/sso_example.html)
2. Adjust basic LDAP:
* foo:
```
cuba.webContextName = foooo
cuba.restApiUrl = http://foooo:8082/foooo-portal/api
cuba.webPort = 8082
cuba.idp.serviceProviderUrls = http://foooo:8082/foooo/,http://barrr:8084/barrr/
cuba.idp.serviceProviderLogoutUrls = http://foooo:8082/foooo/dispatch/idpc/logout,http://barrr:8084/barrr/dispatch/idpc/logout
cuba.idp.trustedServicePassword = mdgh12SSX_pic2
cuba.webAppUrl = http://foooo:8082/foooo
cuba.web.idp.enabled = true
cuba.web.idp.baseUrl = http://foooo:8082/foooo/idp/
cuba.web.idp.trustedServicePassword = mdgh12SSX_pic2
cuba.web.requirePasswordForNewUsers = false
cuba.web.ldap.enabled = true
cuba.web.ldap.urls = ldap://192.168.1.1:10389
cuba.web.ldap.base = dc=example,dc=com
cuba.web.ldap.user = cn=pupkine,dc=example,dc=com
cuba.web.ldap.password = 1132Firefox
cuba.web.standardAuthenticationUsers = admin
cuba.web.ldap.userLoginField = cn
```
* bar:
```
cuba.webContextName = barrr
cuba.restApiUrl = http://barrr:8084/barrr-portal/api
cuba.webAppUrl = http://barrr:8084/barrr/
cuba.webPort = 8084
cuba.web.idp.enabled = true
cuba.web.idp.baseUrl = http://foooo:8082/foooo/idp/
cuba.web.idp.trustedServicePassword = mdgh12SSX_pic2
cuba.web.requirePasswordForNewUsers = false
cuba.web.ldap.enabled = true
cuba.web.ldap.urls = ldap://192.168.1.1:10389
cuba.web.ldap.base = dc=example,dc=com
cuba.web.ldap.user = cn=pupkine,dc=example,dc=com
cuba.web.ldap.password = 1132Firefox
cuba.web.standardAuthenticationUsers = admin
cuba.web.ldap.userLoginField = cn
```
3) Start foo and login as admin/admin

AR: UnsupportedCredentialsException
```
2018-05-29 17:30:22.458 DEBUG [http-nio-8082-exec-5] com.haulmont.cuba.web.App - Initializing application
2018-05-29 17:30:22.467 DEBUG [http-nio-8082-exec-5] com.haulmont.cuba.web.security.providers.ExternalUserLoginProvider - User {} is not allowed to use external login
2018-05-29 17:30:22.475 ERROR [http-nio-8082-exec-5] com.haulmont.cuba.web.AppUI - Unable to init ui
com.haulmont.cuba.security.global.UnsupportedCredentialsException: Unable to find login provider that supports credentials class com.haulmont.cuba.web.security.ExternalUserCredentials
	at com.haulmont.cuba.web.security.ConnectionImpl.loginInternal(ConnectionImpl.java:221) ~[cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.cuba.web.security.ConnectionImpl.login(ConnectionImpl.java:89) ~[cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.cuba.web.security.idp.IdpLoginLifecycleManager.onAppStarted(IdpLoginLifecycleManager.java:94) ~[cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:256) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:177) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:140) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at com.haulmont.cuba.core.sys.EventsImpl.publish(EventsImpl.java:33) ~[cuba-global-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.cuba.web.sys.WebEvents.publish(WebEvents.java:36) ~[cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.cuba.web.DefaultApp.publishAppStartedEvent(DefaultApp.java:225) ~[cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.cuba.web.DefaultApp.loginOnStart(DefaultApp.java:212) ~[cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.cuba.web.AppUI.setupUI(AppUI.java:297) ~[cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.cuba.web.AppUI.init(AppUI.java:221) ~[cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.vaadin.ui.UI.doInit(UI.java:693) [vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:222) [vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:74) [vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435) [vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:361) [vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:312) [cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:203) [cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.23]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.23]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107) [spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at com.haulmont.cuba.web.security.idp.BaseIdpSessionFilter.doFilter(BaseIdpSessionFilter.java:220) [cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112) [spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73) [spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:107) [cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.23]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:8.5.23]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.23]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [catalina.jar:8.5.23]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.23]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.23]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) [catalina.jar:8.5.23]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.23]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:8.5.23]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-coyote.jar:8.5.23]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.23]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:8.5.23]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-coyote.jar:8.5.23]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.23]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.23]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
```
[fullstacktrace.txt](https://github.com/cuba-platform/cuba/files/2048541/fullstacktrace.txt)
[foo.zip](https://github.com/cuba-platform/cuba/files/2048543/foo.zip)
[bar.zip](https://github.com/cuba-platform/cuba/files/2048544/bar.zip)

**Comment by jreznot** [comment]
Duplicates #829
