### ISSUE TITLE
UberJar does not serve WebJAR resources

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#944]
### Environment

- Platform version: 6.9.0
- Client type: Web
- Operating system: Linux (Cent OS)

### Description of the bug or enhancement

1. Build Uber Jar
1. Start application
1. Open web browser

```
    Jun 06, 2018 5:32:54 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE:
java.lang.IllegalArgumentException: jquery.min.js could not be found. Make sure you've added the corresponding WebJar and please check for typos.
        at com.haulmont.cuba.web.sys.WebJarResourceUtils.throwNotFoundException(WebJarResourceUtils.java:163)
        at com.haulmont.cuba.web.sys.WebJarResourceUtils.getFullPath(WebJarResourceUtils.java:123)
        at com.haulmont.cuba.web.sys.WebJarResourceUtils.getWebJarPath(WebJarResourceUtils.java:63)
        at com.haulmont.cuba.web.sys.CubaBootstrapListener.getWebJarResource(CubaBootstrapListener.java:69)
        at com.haulmont.cuba.web.sys.CubaBootstrapListener.modifyBootstrapPage(CubaBootstrapListener.java:51)
```

**Comment by jreznot** [comment]
Regression test of the main deployment scenarios required
