### ISSUE TITLE
Kryo serialization errors for cluster messages are almost lost

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#987]
### Environment
- Platform version: 6.8 snapshot
- Kryo serialization enabled
- Middleware cluster

### Description of the bug or enhancement
Send cluster message which inside of its graph contains class not implementing Serializable.

Expected: exception in app.log

Actual: no message in CUBA logs. Exception is written to stdout (catalina.out file for Tomcat):
```
Exception in thread "ClusterManagerMessageSender-274" com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Class is not registered: com.haulmont.xxxx.DirectionsBounds
Note: To register this class use: kryo.register("com.haulmont.xxxx.DirectionsBounds".class);
Serialization trace:
bounds (com.haulmont.xxxx.DirectionsRoute)
routes (com.haulmont.xxxx.DirectionsResult)
value (com.haulmont.xxxx.CacheClusterNotifier$CacheAddEntryEvent)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:101)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.haulmont.cuba.core.sys.serialization.KryoSerialization$CubaFieldSerializer.write(KryoSerialization.java:335)
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:100)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:40)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.haulmont.cuba.core.sys.serialization.KryoSerialization$CubaFieldSerializer.write(KryoSerialization.java:335)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.haulmont.cuba.core.sys.serialization.KryoSerialization$CubaFieldSerializer.write(KryoSerialization.java:335)
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651)
        at com.haulmont.cuba.core.sys.serialization.KryoSerialization.serialize(KryoSerialization.java:143)
        at com.haulmont.cuba.core.sys.serialization.KryoSerialization.serialize(KryoSerialization.java:157)
        at com.haulmont.cuba.core.sys.serialization.SerializationSupport.serialize(SerializationSupport.java:61)
        at com.haulmont.cuba.core.app.ClusterManager.internalSend(ClusterManager.java:141)
        at com.haulmont.cuba.core.app.ClusterManager$SendMessageRunnable.run(ClusterManager.java:518)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Class is not registered: com.haulmont.xxxx.DirectionsBounds
Note: To register this class use: kryo.register("com.haulmont.xxxx.DirectionsBounds".class);
        at com.haulmont.cuba.core.sys.serialization.KryoSerialization$CubaFieldSerializer.checkIncorrectObject(KryoSerialization.java:355)
        at com.haulmont.cuba.core.sys.serialization.KryoSerialization$CubaFieldSerializer.write(KryoSerialization.java:334)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        ... 22 more

```

**Comment by jreznot** [comment]
Hi,

There is another Major issue with Kryo: https://github.com/cuba-platform/cuba/issues/742 
Thus it is not recommended to use it.
